// 자료 원형용 장면(topic) 풀 — 이원표·산점도·선그래프가 공유한다. 장면 수가 독립 변형 수를 좌우한다(조사 문서 G7).

/** 이원표 장면: 두 집단(행) × 응답(열). 표 라벨(yLabel/nLabel)과 지문 표현(yv/yp)을 일부러 다른 낱말로 둔다 — 지문의 숫자 절이 표 라벨과 우연히 겹쳐 값 검사(lintDataAgainstText)를 오작동시키지 않게. */
export type TwTopic = { ent: string; rowHeader: string; r1: string; r2: string; yLabel: string; nLabel: string; title: string; yv: string; yp: string; where: string };
export const TW_TOPICS: TwTopic[] = [
  { ent: "students", rowHeader: "Grade", r1: "juniors", r2: "seniors", yLabel: "Joined", nLabel: "Did not join", title: "Robotics club membership", yv: "sign up for the robotics club", yp: "signed up for the robotics club", where: "at a high school" },
  { ent: "members", rowHeader: "Schedule", r1: "morning members", r2: "evening members", yLabel: "Uses pool", nLabel: "Does not use pool", title: "Pool use by membership type", yv: "swim in the pool", yp: "swam in the pool", where: "at a community center" },
  { ent: "voters", rowHeader: "Residence", r1: "urban residents", r2: "rural residents", yLabel: "Supports", nLabel: "Opposes", title: "Responses to a ballot measure", yv: "favor the ballot measure", yp: "favored the ballot measure", where: "in a county survey" },
  { ent: "customers", rowHeader: "Purchase type", r1: "online customers", r2: "in-store customers", yLabel: "Bought warranty", nLabel: "No warranty", title: "Warranty purchases", yv: "purchase an extended warranty", yp: "purchased an extended warranty", where: "at an electronics retailer" },
  { ent: "patients", rowHeader: "Age group", r1: "adult patients", r2: "child patients", yLabel: "Vaccinated", nLabel: "Not vaccinated", title: "Vaccination status at a clinic", yv: "receive the flu shot", yp: "received the flu shot", where: "at a health clinic" },
  { ent: "commuters", rowHeader: "Home location", r1: "city commuters", r2: "suburban commuters", yLabel: "Rides train", nLabel: "Drives", title: "Commute choice", yv: "ride the train to work", yp: "rode the train to work", where: "in a regional transit survey" },
  { ent: "employees", rowHeader: "Employment type", r1: "full-time employees", r2: "part-time employees", yLabel: "Participates", nLabel: "Does not participate", title: "Wellness program enrollment", yv: "enroll in the wellness program", yp: "enrolled in the wellness program", where: "at a mid-sized company" },
  { ent: "households", rowHeader: "Household type", r1: "households with children", r2: "households without children", yLabel: "Owns a pet", nLabel: "No pet", title: "Pet ownership", yv: "keep a pet", yp: "kept a pet", where: "in a neighborhood survey" },
  { ent: "residents", rowHeader: "Building type", r1: "apartment residents", r2: "house residents", yLabel: "Recycles", nLabel: "Does not recycle", title: "Recycling habits", yv: "separate their recycling", yp: "separated their recycling", where: "in a city survey" },
  { ent: "visitors", rowHeader: "Visit type", r1: "weekday visitors", r2: "weekend visitors", yLabel: "Bought a membership", nLabel: "Bought a day pass", title: "Museum ticket choice", yv: "buy an annual membership", yp: "bought an annual membership", where: "at a science museum" },
  { ent: "students", rowHeader: "Course level", r1: "beginner students", r2: "advanced students", yLabel: "Finished course", nLabel: "Did not finish", title: "Online course completion", yv: "complete the online course", yp: "completed the online course", where: "on a learning platform" },
  { ent: "readers", rowHeader: "Reader type", r1: "print readers", r2: "digital readers", yLabel: "Subscribes", nLabel: "Does not subscribe", title: "Newsletter subscriptions", yv: "subscribe to the newsletter", yp: "subscribed to the newsletter", where: "of a local newspaper" },
  { ent: "teenagers", rowHeader: "Age", r1: "younger teenagers", r2: "older teenagers", yLabel: "Volunteers", nLabel: "Does not volunteer", title: "Volunteering by age", yv: "volunteer on weekends", yp: "volunteered on weekends", where: "in a youth survey" },
  { ent: "cyclists", rowHeader: "Rider type", r1: "commuting cyclists", r2: "recreational cyclists", yLabel: "Wears helmet", nLabel: "No helmet", title: "Helmet use", yv: "wear a helmet", yp: "wore a helmet", where: "on a city trail" },
  { ent: "diners", rowHeader: "Meal", r1: "lunch diners", r2: "dinner diners", yLabel: "Ordered dessert", nLabel: "No dessert", title: "Dessert orders", yv: "have dessert", yp: "had dessert", where: "at a restaurant" },
  { ent: "athletes", rowHeader: "Division", r1: "varsity athletes", r2: "junior varsity athletes", yLabel: "Attends camp", nLabel: "Skips camp", title: "Summer camp attendance", yv: "attend the summer camp", yp: "attended the summer camp", where: "in a school district" },
  { ent: "tenants", rowHeader: "Lease length", r1: "short-term tenants", r2: "long-term tenants", yLabel: "Renews lease", nLabel: "Moves out", title: "Lease renewals", yv: "renew the lease", yp: "renewed the lease", where: "in an apartment complex" },
  { ent: "drivers", rowHeader: "Vehicle", r1: "electric-car drivers", r2: "gas-car drivers", yLabel: "Uses app", nLabel: "Does not use app", title: "Navigation app use", yv: "use a navigation app", yp: "used a navigation app", where: "in a transportation study" },
  { ent: "gardeners", rowHeader: "Plot size", r1: "small-plot gardeners", r2: "large-plot gardeners", yLabel: "Grows vegetables", nLabel: "Flowers only", title: "Garden crops", yv: "grow vegetables", yp: "grew vegetables", where: "in a community garden" },
  { ent: "parents", rowHeader: "School level", r1: "elementary parents", r2: "middle school parents", yLabel: "Came", nLabel: "Did not come", title: "Parent night attendance", yv: "attend parent night", yp: "attended parent night", where: "in a school district" },
  { ent: "students", rowHeader: "Class year", r1: "freshmen", r2: "sophomores", yLabel: "Attends tutoring", nLabel: "Skips tutoring", title: "Tutoring attendance", yv: "go to the tutoring center", yp: "went to the tutoring center", where: "at a university" },
  { ent: "shoppers", rowHeader: "Day", r1: "Saturday shoppers", r2: "Tuesday shoppers", yLabel: "Used coupon", nLabel: "No coupon", title: "Coupon use", yv: "redeem a paper coupon", yp: "redeemed a paper coupon", where: "at a grocery store" },
  { ent: "residents", rowHeader: "Neighborhood", r1: "north-side residents", r2: "south-side residents", yLabel: "Has solar panels", nLabel: "No solar panels", title: "Solar panel installation", yv: "install rooftop panels", yp: "installed rooftop panels", where: "in a town survey" },
  { ent: "runners", rowHeader: "Experience", r1: "first-time runners", r2: "veteran runners", yLabel: "Finished race", nLabel: "Dropped out", title: "Race completion", yv: "cross the finish line", yp: "crossed the finish line", where: "in a charity 10K" },
  { ent: "listeners", rowHeader: "Device", r1: "phone listeners", r2: "speaker listeners", yLabel: "Streams podcasts", nLabel: "Music only", title: "Podcast listening", yv: "stream a podcast weekly", yp: "streamed a podcast weekly", where: "in an audio survey" },
  { ent: "farmers", rowHeader: "Farm size", r1: "small-farm owners", r2: "large-farm owners", yLabel: "Uses drip lines", nLabel: "Uses sprinklers", title: "Irrigation method", yv: "water with drip lines", yp: "watered with drip lines", where: "in an agricultural survey" },
  { ent: "teachers", rowHeader: "Subject", r1: "science teachers", r2: "history teachers", yLabel: "Assigns projects", nLabel: "Assigns essays", title: "Assignment type", yv: "assign a team project", yp: "assigned a team project", where: "in a district survey" },
  { ent: "travelers", rowHeader: "Trip purpose", r1: "business travelers", r2: "leisure travelers", yLabel: "Books early", nLabel: "Books late", title: "Booking time", yv: "book a month ahead", yp: "booked a month ahead", where: "at an airline" },
  { ent: "players", rowHeader: "League", r1: "youth league players", r2: "adult league players", yLabel: "Wears mouthguard", nLabel: "No mouthguard", title: "Mouthguard use", yv: "wear a mouthguard", yp: "wore a mouthguard", where: "in a soccer association" },
  { ent: "patrons", rowHeader: "Branch", r1: "downtown patrons", r2: "uptown patrons", yLabel: "Borrowed e-books", nLabel: "Borrowed print", title: "Library borrowing", yv: "borrow an e-book", yp: "borrowed an e-book", where: "at a city library" },
  { ent: "homeowners", rowHeader: "Home age", r1: "older-home owners", r2: "newer-home owners", yLabel: "Replaced windows", nLabel: "Kept windows", title: "Window replacement", yv: "replace the windows", yp: "replaced the windows", where: "in a housing survey" },
  { ent: "employees", rowHeader: "Office", r1: "remote employees", r2: "on-site employees", yLabel: "Takes training", nLabel: "Skips training", title: "Training uptake", yv: "take the safety training", yp: "took the safety training", where: "at a software firm" },
  { ent: "campers", rowHeader: "Cabin", r1: "lakeside campers", r2: "hillside campers", yLabel: "Joined hike", nLabel: "Stayed in camp", title: "Hike participation", yv: "go on the morning hike", yp: "went on the morning hike", where: "at a summer camp" },
  { ent: "buyers", rowHeader: "Age band", r1: "younger buyers", r2: "older buyers", yLabel: "Chose hybrid", nLabel: "Chose gas", title: "Vehicle choice", yv: "choose a hybrid model", yp: "chose a hybrid model", where: "at a car dealership" },
  { ent: "viewers", rowHeader: "Screening", r1: "matinee viewers", r2: "evening viewers", yLabel: "Rated it high", nLabel: "Rated it low", title: "Film ratings", yv: "give the film a high rating", yp: "gave the film a high rating", where: "at a film festival" },
  { ent: "swimmers", rowHeader: "Lane group", r1: "morning swimmers", r2: "afternoon swimmers", yLabel: "Uses goggles", nLabel: "No goggles", title: "Goggle use", yv: "wear goggles", yp: "wore goggles", where: "at a recreation pool" },
  { ent: "bakers", rowHeader: "Shop type", r1: "home bakers", r2: "shop bakers", yLabel: "Uses sourdough", nLabel: "Uses yeast", title: "Leavening choice", yv: "bake with sourdough starter", yp: "baked with sourdough starter", where: "in a baking survey" },
  { ent: "hikers", rowHeader: "Trail", r1: "ridge trail hikers", r2: "valley trail hikers", yLabel: "Carries a map", nLabel: "Uses phone only", title: "Navigation habits", yv: "carry a paper map", yp: "carried a paper map", where: "in a park study" },
  { ent: "attendees", rowHeader: "Ticket", r1: "general attendees", r2: "VIP attendees", yLabel: "Visited booths", nLabel: "Skipped booths", title: "Expo booth visits", yv: "visit the vendor booths", yp: "visited the vendor booths", where: "at a trade expo" },
  { ent: "neighbors", rowHeader: "Neighbor type", r1: "corner-lot neighbors", r2: "mid-block neighbors", yLabel: "Has a garden", nLabel: "No garden", title: "Yard gardens", yv: "keep a garden", yp: "kept a garden", where: "in a block survey" },
  { ent: "interns", rowHeader: "Program", r1: "spring interns", r2: "fall interns", yLabel: "Offered a job", nLabel: "Not offered", title: "Job offers", yv: "receive a job offer", yp: "received a job offer", where: "at an engineering firm" },
  { ent: "skaters", rowHeader: "Rink", r1: "indoor skaters", r2: "outdoor skaters", yLabel: "Rents skates", nLabel: "Owns skates", title: "Skate rentals", yv: "rent skates", yp: "rented skates", where: "at a winter festival" },
  { ent: "renters", rowHeader: "Rental type", r1: "studio renters", r2: "two-bedroom renters", yLabel: "Has a roommate", nLabel: "Lives alone", title: "Living arrangements", yv: "share the apartment", yp: "shared the apartment", where: "in a housing study" },
  { ent: "learners", rowHeader: "Format", r1: "in-person learners", r2: "online learners", yLabel: "Passed exam", nLabel: "Did not pass", title: "Certification results", yv: "pass the certification exam", yp: "passed the certification exam", where: "in a training program" },
  { ent: "volunteers", rowHeader: "Shift", r1: "weekend volunteers", r2: "weekday volunteers", yLabel: "Comes back", nLabel: "Does not come back", title: "Volunteer retention", yv: "return the next season", yp: "returned the next season", where: "at an animal shelter" },
];

/** 산점도·선그래프 장면. x/y 는 명사구(문장 안), xa/ya 는 축 이름, conv 는 x 단위 환산(1 xu = per small). */
export type SeTopic = { x: string; y: string; xa: string; ya: string; xu: string; yu: string; conv?: { small: string; per: number } };
export const SE_TOPICS: SeTopic[] = [
  { x: "the number of hours a student studies", y: "that student's exam score", xa: "Hours studied", ya: "Exam score", xu: "hours", yu: "points", conv: { small: "minutes", per: 60 } },
  { x: "the age of a tree", y: "that tree's height", xa: "Age", ya: "Height", xu: "years", yu: "feet", conv: { small: "months", per: 12 } },
  { x: "the outdoor temperature", y: "the number of cold drinks sold", xa: "Temperature", ya: "Drinks sold", xu: "degrees", yu: "drinks" },
  { x: "the number of years since a town was founded", y: "the town's population", xa: "Years since founding", ya: "Population", xu: "years", yu: "hundreds of residents", conv: { small: "months", per: 12 } },
  { x: "the price of a ticket", y: "the number of tickets sold", xa: "Ticket price", ya: "Tickets sold", xu: "dollars", yu: "tickets", conv: { small: "cents", per: 100 } },
  { x: "the number of workers on a shift", y: "the number of items packed", xa: "Workers", ya: "Items packed", xu: "workers", yu: "items" },
  { x: "the weight of a package", y: "the package's shipping cost", xa: "Weight", ya: "Shipping cost", xu: "pounds", yu: "dollars", conv: { small: "ounces", per: 16 } },
  { x: "the number of weeks a plant has grown", y: "the plant's height", xa: "Weeks grown", ya: "Plant height", xu: "weeks", yu: "centimeters", conv: { small: "days", per: 7 } },
  { x: "the number of hours of sunlight a plant receives each day", y: "the plant's daily growth", xa: "Sunlight", ya: "Daily growth", xu: "hours", yu: "millimeters", conv: { small: "minutes", per: 60 } },
  { x: "the number of employees at a company", y: "the company's monthly revenue", xa: "Employees", ya: "Monthly revenue", xu: "employees", yu: "thousands of dollars" },
  { x: "the speed of a car", y: "the car's stopping distance", xa: "Speed", ya: "Stopping distance", xu: "miles per hour", yu: "feet" },
  { x: "the number of pages in a book", y: "the book's price", xa: "Pages", ya: "Price", xu: "pages", yu: "dollars" },
  { x: "the number of minutes a battery has been charging", y: "the battery's charge level", xa: "Charging time", ya: "Charge level", xu: "minutes", yu: "percent", conv: { small: "seconds", per: 60 } },
  { x: "the number of days since a candle was lit", y: "the candle's remaining height", xa: "Days burning", ya: "Candle height", xu: "days", yu: "centimeters", conv: { small: "hours", per: 24 } },
  { x: "the number of people attending a concert", y: "the amount of food sold", xa: "Attendance", ya: "Food sold", xu: "hundreds of people", yu: "kilograms" },
  { x: "the distance a delivery van travels", y: "the fuel the van uses", xa: "Distance", ya: "Fuel used", xu: "kilometers", yu: "liters" },
  { x: "the number of hours a phone is used each day", y: "the phone's battery life remaining", xa: "Daily use", ya: "Battery remaining", xu: "hours", yu: "percent", conv: { small: "minutes", per: 60 } },
  { x: "the number of seconds since a ball was dropped", y: "the ball's speed", xa: "Time", ya: "Speed", xu: "seconds", yu: "meters per second" },
  { x: "the number of rainy days in a month", y: "the umbrellas sold that month", xa: "Rainy days", ya: "Umbrellas sold", xu: "days", yu: "umbrellas" },
  { x: "the number of cups of flour used", y: "the number of muffins baked", xa: "Flour", ya: "Muffins baked", xu: "cups", yu: "muffins" },
  { x: "the number of songs on a playlist", y: "the playlist's total length", xa: "Songs", ya: "Total length", xu: "songs", yu: "minutes" },
  { x: "the number of lanes on a highway", y: "the highway's hourly traffic capacity", xa: "Lanes", ya: "Capacity", xu: "lanes", yu: "hundreds of cars" },
  { x: "the amount of fertilizer applied to a field", y: "the field's crop yield", xa: "Fertilizer", ya: "Crop yield", xu: "kilograms", yu: "bushels" },
  { x: "the number of apps installed on a tablet", y: "the tablet's free storage", xa: "Apps installed", ya: "Free storage", xu: "apps", yu: "gigabytes" },
  { x: "the time a pot of water has been heated", y: "the water's temperature", xa: "Heating time", ya: "Water temperature", xu: "minutes", yu: "degrees", conv: { small: "seconds", per: 60 } },
  { x: "the number of volunteers at a food drive", y: "the cans collected", xa: "Volunteers", ya: "Cans collected", xu: "volunteers", yu: "cans" },
  { x: "the height of a ramp", y: "the distance a toy car rolls", xa: "Ramp height", ya: "Distance rolled", xu: "centimeters", yu: "meters", conv: { small: "millimeters", per: 10 } },
  { x: "the number of lessons a student has attended", y: "that student's typing speed", xa: "Lessons attended", ya: "Typing speed", xu: "lessons", yu: "words per minute" },
  { x: "the number of hours a drone has flown", y: "the drone's remaining battery", xa: "Flight time", ya: "Battery remaining", xu: "hours", yu: "percent", conv: { small: "minutes", per: 60 } },
  { x: "the number of boxes loaded on a truck", y: "the truck's total weight", xa: "Boxes", ya: "Total weight", xu: "boxes", yu: "hundreds of pounds" },
  { x: "the number of tickets a game booth sells", y: "the booth's total earnings", xa: "Tickets sold", ya: "Earnings", xu: "tickets", yu: "dollars" },
  { x: "the number of months a gym membership has lasted", y: "the member's total fees paid", xa: "Months", ya: "Total fees", xu: "months", yu: "dollars" },
  { x: "the time a cake bakes", y: "the cake's internal temperature", xa: "Baking time", ya: "Temperature", xu: "minutes", yu: "degrees", conv: { small: "seconds", per: 60 } },
  { x: "the number of hours a pump runs", y: "the amount of water pumped", xa: "Run time", ya: "Water pumped", xu: "hours", yu: "gallons", conv: { small: "minutes", per: 60 } },
  { x: "the number of hours a player practices free throws", y: "the player's free-throw percentage", xa: "Practice time", ya: "Free-throw rate", xu: "hours", yu: "percent", conv: { small: "minutes", per: 60 } },
  { x: "the number of hours a freezer has been running", y: "the freezer's temperature", xa: "Running time", ya: "Freezer temperature", xu: "hours", yu: "degrees", conv: { small: "minutes", per: 60 } },
  { x: "the number of hours a machine operates", y: "the number of parts it produces", xa: "Operating time", ya: "Parts produced", xu: "hours", yu: "parts", conv: { small: "minutes", per: 60 } },
  { x: "the age of a car", y: "the car's resale value", xa: "Age", ya: "Resale value", xu: "years", yu: "hundreds of dollars", conv: { small: "months", per: 12 } },
  { x: "the age of a puppy", y: "the puppy's weight", xa: "Age", ya: "Weight", xu: "years", yu: "pounds", conv: { small: "months", per: 12 } },
  { x: "the number of years of experience", y: "an employee's salary", xa: "Experience", ya: "Salary", xu: "years", yu: "thousands of dollars", conv: { small: "months", per: 12 } },
  { x: "the age of a child", y: "the child's height", xa: "Age", ya: "Height", xu: "years", yu: "inches", conv: { small: "months", per: 12 } },
  { x: "the number of years a startup has operated", y: "the startup's number of employees", xa: "Years operating", ya: "Employees", xu: "years", yu: "employees", conv: { small: "months", per: 12 } },
  { x: "the number of weeks since a puppy was adopted", y: "the puppy's weight", xa: "Weeks since adoption", ya: "Weight", xu: "weeks", yu: "pounds", conv: { small: "days", per: 7 } },
  { x: "the number of weeks of training", y: "the distance a runner covers", xa: "Weeks of training", ya: "Distance run", xu: "weeks", yu: "miles", conv: { small: "days", per: 7 } },
  { x: "the number of weeks since an app launched", y: "the number of downloads", xa: "Weeks since launch", ya: "Downloads", xu: "weeks", yu: "thousands of downloads", conv: { small: "days", per: 7 } },
  { x: "the number of weeks in a savings plan", y: "the account balance", xa: "Weeks saving", ya: "Balance", xu: "weeks", yu: "dollars", conv: { small: "days", per: 7 } },
  { x: "the number of minutes a swimmer has been swimming", y: "the distance swum", xa: "Swim time", ya: "Distance", xu: "minutes", yu: "meters", conv: { small: "seconds", per: 60 } },
  { x: "the number of minutes a kettle heats", y: "the water temperature", xa: "Heating time", ya: "Water temperature", xu: "minutes", yu: "degrees", conv: { small: "seconds", per: 60 } },
  { x: "the number of minutes a video has been downloading", y: "the amount of data received", xa: "Download time", ya: "Data received", xu: "minutes", yu: "megabytes", conv: { small: "seconds", per: 60 } },
  { x: "the number of minutes a treadmill is used", y: "the calories burned", xa: "Treadmill time", ya: "Calories burned", xu: "minutes", yu: "calories", conv: { small: "seconds", per: 60 } },
  { x: "the number of days since a seed sprouted", y: "the seedling's height", xa: "Days since sprouting", ya: "Seedling height", xu: "days", yu: "millimeters", conv: { small: "hours", per: 24 } },
  { x: "the number of days a glacier was observed", y: "the glacier's measured thickness", xa: "Days observed", ya: "Ice thickness", xu: "days", yu: "meters", conv: { small: "hours", per: 24 } },
  { x: "the number of days since a loaf was baked", y: "the loaf's freshness score", xa: "Days since baking", ya: "Freshness score", xu: "days", yu: "points", conv: { small: "hours", per: 24 } },
  { x: "the price of a pen", y: "the number of pens sold", xa: "Price", ya: "Pens sold", xu: "dollars", yu: "pens", conv: { small: "cents", per: 100 } },
  { x: "the cost of a bike ride", y: "the number of riders", xa: "Ride cost", ya: "Riders", xu: "dollars", yu: "riders", conv: { small: "cents", per: 100 } },
  { x: "the price of a sandwich", y: "the number of sandwiches sold", xa: "Price", ya: "Sandwiches sold", xu: "dollars", yu: "sandwiches", conv: { small: "cents", per: 100 } },
  { x: "the weight of a backpack", y: "a hiker's walking speed", xa: "Backpack weight", ya: "Walking speed", xu: "pounds", yu: "miles per hour", conv: { small: "ounces", per: 16 } },
  { x: "the weight of a suitcase", y: "the airline's baggage fee", xa: "Suitcase weight", ya: "Baggage fee", xu: "pounds", yu: "dollars", conv: { small: "ounces", per: 16 } },
  { x: "the length of a board", y: "the board's cost", xa: "Board length", ya: "Cost", xu: "meters", yu: "dollars", conv: { small: "centimeters", per: 100 } },
  { x: "the height of a diving platform", y: "the splash radius", xa: "Platform height", ya: "Splash radius", xu: "meters", yu: "centimeters", conv: { small: "centimeters", per: 100 } },
  { x: "the length of a ramp", y: "the distance a ball rolls after it", xa: "Ramp length", ya: "Distance rolled", xu: "feet", yu: "feet", conv: { small: "inches", per: 12 } },
  { x: "the depth of a pool", y: "the amount of water it holds", xa: "Depth", ya: "Water volume", xu: "feet", yu: "hundreds of gallons", conv: { small: "inches", per: 12 } },
  { x: "the thickness of a book", y: "the book's weight", xa: "Thickness", ya: "Weight", xu: "centimeters", yu: "grams", conv: { small: "millimeters", per: 10 } },
];

export const CONV_TOPICS = SE_TOPICS.filter((t) => t.conv);
