// GENERATED by scripts/legal-docs/generate.mjs from docs/contracts/*.md — do not edit by hand.
// The English source files are the authoritative text; a drift test fails when they diverge.
import type { LegalDocumentData } from "../types";

export const GENERATED_LEGAL_DOCUMENTS: Record<"parentAgreement" | "teacherCalifornia" | "teacherNonUs" | "under13Notice", LegalDocumentData> = {
  "parentAgreement": {
    "title": "ALTON Education Services Agreement",
    "versionLine": "Agreement Version 0.3-EN-CA | October 6, 2026",
    "sections": [
      {
        "heading": "1. Parties and Student",
        "blocks": [
          {
            "t": "p",
            "text": "This Agreement is between **Alton Education LLC** (the “Company,” “ALTON,” “we,” or “us”) and the adult identified below (the “Customer”). For a Student under 18, the Customer must be a parent or legal guardian authorized to arrange services for that Student. An adult Student may sign as the Customer."
          },
          {
            "t": "ul",
            "items": [
              "Company notice address: [Company notice address]",
              "Contact: official@alton.education",
              "Customer legal name, email, and address: [Complete before signature]",
              "Customer capacity: [Parent / Legal guardian / Adult Student]",
              "Student legal name and date of birth: [Complete before signature]",
              "Agreement ID and version: [Automatically populated]"
            ]
          },
          {
            "t": "p",
            "text": "This Agreement covers one Student. The Customer confirms their authority to contract and must notify ALTON of a custody or authority restriction relevant to the services. Nothing here waives rights belonging to a minor under applicable law. ALTON may request proportionate evidence of authority."
          },
          {
            "t": "p",
            "text": "Students under 13 may enter a registration pathway; age alone does not automatically bar registration. Actual service availability is subject to operational review, appropriate parental verification, and legally required consent. Registration does not guarantee acceptance for tutoring or immediate access to every feature."
          }
        ]
      },
      {
        "heading": "2. Free Learning and Paid Services",
        "blocks": [
          {
            "t": "p",
            "text": "Free practice tests, learning tools, and approved study materials are governed by ALTON's website Terms at https://alton.education/terms and Privacy Notice at https://alton.education/privacy. Free registration, a parent invitation, or a consultation request does not create a paid tutoring purchase."
          },
          {
            "t": "p",
            "text": "This Agreement governs paid tutoring and educational consulting expressly offered to the Student. It does not apply retroactively to an initial consultation or trial lesson. A completed trial is not required for a direct-enrollment customer."
          },
          {
            "t": "p",
            "text": "A signed Agreement, required verification, payment, and applicable enrollment or scheduling conditions must be satisfied before paid lessons begin. Signature alone does not charge the Customer or grant lesson credits."
          },
          {
            "t": "p",
            "text": "The Student's existing account and learning history may continue through the transition to tutoring. Access to family records requires verified account relationships and appropriate permissions."
          }
        ]
      },
      {
        "heading": "3. Order Terms and Agreement Duration",
        "blocks": [
          {
            "t": "p",
            "text": "Each order identifies the product, subjects or services included, number and length of lessons, price, discount, currency, applicable taxes, total payment, credit validity, and refund-policy version. Those transaction-specific terms control the corresponding purchase. ALTON will retain the accepted version; later changes will not retroactively alter completed purchases."
          },
          {
            "t": "p",
            "text": "This Agreement has no fixed subscription term, automatic renewal, or obligation to make additional purchases. It remains applicable while services are used. Additional credits are separate voluntary purchases. A material change requires appropriate notice and acceptance before it applies."
          }
        ]
      },
      {
        "heading": "4. Services and Educational Outcomes",
        "blocks": [
          {
            "t": "p",
            "text": "Services may include individual instruction, educational guidance, assignments, materials, and lesson reviews. The current standard individual lesson is 120 minutes unless the order expressly states otherwise. Consulting deliverables, if any, must be identified in the service description or order; not every purchase includes every consulting service."
          },
          {
            "t": "p",
            "text": "Subjects, teachers, learning plans, materials, and available schedules may change for educational or operational reasons. ALTON does not guarantee an examination score, grade, admission, scholarship, or other academic outcome and is not affiliated with College Board unless expressly stated otherwise."
          }
        ]
      },
      {
        "heading": "5. Teacher Assignment and Changes",
        "blocks": [
          {
            "t": "p",
            "text": "Teachers are assigned by Student and subject. A particular teacher is not guaranteed indefinitely. The Customer may request a change, and ALTON may reassign a teacher based on fit, availability, quality, or operational needs."
          },
          {
            "t": "p",
            "text": "A change in one subject does not automatically end other services. Historical lessons and reviews remain attributed to the teacher who provided them. Necessary learning context may be shared with the replacement teacher. Future reservations do not automatically transfer; affected reservations and rescheduling instructions will be communicated."
          }
        ]
      },
      {
        "heading": "6. Lesson Credits",
        "blocks": [
          {
            "t": "p",
            "text": "A lesson credit entitles the Student to the lesson described in the order. The standard credit covers one 120-minute lesson. Booking holds the required credit; completion consumes it."
          },
          {
            "t": "p",
            "text": "Lesson credits have a 12-month validity period from purchase unless a different period is disclosed before purchase. The lesson must start within that validity period. ALTON generally uses the earliest-expiring credits first and sends reminders 30 and 7 days before expiry. Any expiry restriction is subject to applicable law. Any nonwaivable restriction on expiration prevails."
          }
        ]
      },
      {
        "heading": "7. Student Cancellation, Lateness, and Absence",
        "blocks": [
          {
            "t": "p",
            "text": "A cancellation at least 24 hours before the scheduled start releases the held credit without extending its original expiry. A cancellation less than 24 hours before the start consumes one credit."
          },
          {
            "t": "p",
            "text": "If the Student has not joined within 15 minutes after the start, the teacher may report a no-show. A credit is consumed only after the applicable confirmation process. Late cancellations and confirmed no-shows count as consumed lessons for the refund calculation."
          },
          {
            "t": "p",
            "text": "A late arrival does not extend the scheduled ending time. ALTON may consider documented illness or exceptional circumstances without promising an exception in every case. Decisions will be recorded."
          }
        ]
      },
      {
        "heading": "8. Company or Teacher Cancellation and Technical Failure",
        "blocks": [
          {
            "t": "p",
            "text": "If ALTON or the teacher cancels, the held credit is released. If its remaining validity is less than 30 days, the restored credit is extended to 30 days after cancellation, subject to applicable law."
          },
          {
            "t": "p",
            "text": "For teacher lateness of 10 minutes or more, undelivered time is recorded as make-up time. It may be provided that day by agreement and if scheduling permits, or attached to a later lesson with that teacher. Make-up time is not a separate credit."
          },
          {
            "t": "p",
            "text": "If ALTON's platform or designated meeting service prevents a lesson from starting, the credit is not consumed. If a lesson is interrupted, undelivered time is recorded for make-up. Contact ALTON promptly about access problems so the cause and appropriate remedy can be assessed."
          }
        ]
      },
      {
        "heading": "9. Payment and Price Changes",
        "blocks": [
          {
            "t": "p",
            "text": "There is no automatic renewal or automatic additional purchase under this Agreement. Prices are shown before checkout, ordinarily in USD. ALTON bears payment-processing fees; legally required taxes and the final total are disclosed before payment."
          },
          {
            "t": "p",
            "text": "Prices and package configurations are not fixed by this Agreement. The order must disclose the actual standalone lesson price used in any package refund calculation. A new price applies to new purchases only, with at least 30 days' advance notice under this Agreement. Existing purchases retain their recorded price and refund basis. Quotes remain valid for their stated period."
          }
        ]
      },
      {
        "heading": "10. Stopping Services and Refunds",
        "blocks": [
          {
            "t": "p",
            "text": "The Customer may stop purchasing or request that services in one or all subjects stop. No separate termination penalty applies. Future reservations must first be cancelled or resolved under Section 7."
          },
          {
            "t": "p",
            "text": "Refundable credits are paid, unused credits not held for an unresolved booking. Free or promotional credits have no cash refund value, without affecting statutory rights."
          },
          {
            "t": "p",
            "text": "If a refund is requested within seven days after purchase and no paid lesson has started and no credit from that purchase has been consumed, the actual amount paid is refunded in full."
          },
          {
            "t": "p",
            "text": "Otherwise the refund is calculated as follows:"
          },
          {
            "t": "p",
            "text": "**Refund = actual amount paid for that purchase − (consumed lessons × the actual undiscounted standalone lesson price disclosed at purchase).**"
          },
          {
            "t": "p",
            "text": "The result cannot be less than zero. No additional debt is created by a negative calculation. Late cancellations and confirmed no-shows count as consumed lessons. Remaining credits from a refunded purchase are retired."
          },
          {
            "t": "p",
            "text": "If ALTON ends a subject or service because it cannot provide it, unused paid credits are refunded at the actual per-credit purchase price without recapturing the package discount. Other termination circumstances are assessed under applicable law and the facts; this Agreement does not impose automatic forfeiture of all prepaid value."
          },
          {
            "t": "p",
            "text": "Approved refunds are submitted to the payment processor within five business days, in the original currency and ordinarily to the original payment method. Posting time depends on the processor. Mandatory refund rights prevail over this policy."
          }
        ]
      },
      {
        "heading": "11. Account Status and Records",
        "blocks": [
          {
            "t": "p",
            "text": "Stopping tutoring does not automatically delete the account or learning history. Free learning may remain available while the account is otherwise eligible. Past credits, expired credits, or ended teacher assignments do not automatically reactivate when the Student returns."
          },
          {
            "t": "p",
            "text": "Account closure and privacy requests are separate processes. A standard closure workflow may include a 30-day cancellation window, but that workflow does not postpone legally required privacy-request deadlines. Identity verification, lawful record retention, and applicable deletion exceptions may apply."
          }
        ]
      },
      {
        "heading": "12. Video Recording, Audio Recording, Transcription, and AI Lesson Notes",
        "blocks": [
          {
            "t": "p",
            "text": "Regular paid lessons include video recording, audio recording, conversion of speech into a text transcript, storage of recordings and transcripts, and AI-assisted preparation and storage of lesson notes and summaries. Recorded content may include participant images, voices, names, spoken questions and answers, shared lesson screens, instructional materials, and meeting metadata. These processes support instruction, review, preparation, quality and safety management, and teacher handover. They are required components of regular lessons; initial consultations and trial lessons are excluded."
          },
          {
            "t": "p",
            "text": "The signing participant expressly consents to these activities for authorized regular lessons. A parent or legal guardian authorizes processing of the named child's participation within their lawful authority. ALTON provides notice before recording and obtains consent from all participants as required by applicable law. Additional attendees must receive notice and give required consent before capture begins. A parent signature does not substitute for another participant's consent. Recording must not start until the applicable agreement, required parental verification, and participant consent are complete."
          },
          {
            "t": "p",
            "text": "ALTON uses designated Google Workspace, Meet, Drive, and Gemini services and authorized providers acting for the stated purposes. Recordings, transcripts, and AI notes are stored with restricted access. Authorized teachers and staff may access them for their duties. Students and verified guardians may view lesson artifacts made available to their accounts; this does not grant unrestricted download, redistribution, or access to another family's records or private student notes and whiteboards. No public posting, unrelated advertising, sale, or unrestricted model training is authorized by this consent."
          },
          {
            "t": "p",
            "text": "ALTON keeps these records only as reasonably necessary for the stated purposes, the student's service relationship, and applicable legal obligations or claims. Records no longer needed are securely deleted, subject to lawful preservation requirements. Parents and participants may request access, correction, deletion, or withdrawal of consent at official@alton.education. Withdrawal applies prospectively and does not make prior authorized processing unlawful. ALTON stops affected processing as required and resolves future lessons and unused paid credits under the applicable agreement without imposing a penalty for exercising statutory rights. Free learning access is not conditioned on agreeing to lesson recording."
          },
          {
            "t": "p",
            "text": "AI notes and transcripts may contain omissions, speaker errors, or inaccuracies. Corrections may be requested. AI output alone does not conclusively determine attendance, wages, fees, refunds, or disputes. Material changes receive updated notice and renewed consent when required."
          }
        ]
      },
      {
        "heading": "13. Children and Parental Verification",
        "blocks": [
          {
            "t": "p",
            "text": "Students under 13 are not automatically excluded from registration pathways, but services may be withheld pending operational review and legally required parental verification and consent. Age eligibility, operational approval, and consent completion are distinct."
          },
          {
            "t": "p",
            "text": "Where COPPA applies, ALTON must provide the required direct parent notice and obtain verifiable parental consent before covered collection, use, or disclosure, unless a lawful exception applies. ALTON will use a verification and consent method that meets applicable requirements. Account registration and this Agreement do not replace that process."
          },
          {
            "t": "p",
            "text": "The parent may request review or deletion of the child's information and cessation of further covered collection, subject to applicable law. Contact official@alton.education. Existing required consent must be obtained at the applicable collection stage; it cannot be delayed until a later tutoring purchase."
          }
        ]
      },
      {
        "heading": "14. Materials, Conduct, and Safety",
        "blocks": [
          {
            "t": "p",
            "text": "ALTON and relevant licensors retain rights in their materials, questions, explanations, software, and branding. Access is for authorized personal learning. Do not sell, publicly distribute, or unlawfully copy materials. The Student retains rights in their original work and allows ALTON to process it only as needed for the services and disclosed recordkeeping."
          },
          {
            "t": "p",
            "text": "Keep credentials secure. Harassment, discrimination, threats, inappropriate sexual conduct, unauthorized recording, infringement, and interference with service security are prohibited. ALTON may restrict access proportionately to investigate a safety or legal concern. Refund and record handling remain subject to applicable law."
          }
        ]
      },
      {
        "heading": "15. Electronic Signatures and Notices",
        "blocks": [
          {
            "t": "p",
            "text": "The parties intend to execute this Agreement electronically through DocuSign. ALTON must provide applicable electronic-record disclosures, access requirements, and a means to obtain a copy. A privacy authorization required at a different stage is not replaced merely by using DocuSign."
          },
          {
            "t": "p",
            "text": "This Agreement is signed by an authorized Company representative and sent to the Customer. The Agreement becomes effective when the required signatures are complete. Each amended version has its own execution record. Notices may be delivered through the registered email or account, subject to applicable delivery requirements."
          }
        ]
      },
      {
        "heading": "16. Responsibility and Events Beyond Control",
        "blocks": [
          {
            "t": "p",
            "text": "Nothing excludes nonwaivable rights or liability that cannot lawfully be excluded, including fraud, willful misconduct, or other non-excludable conduct. This Agreement does not impose a financial liability cap or waive class-action or jury rights."
          },
          {
            "t": "p",
            "text": "For an event reasonably beyond a party's control, the parties will communicate and reasonably mitigate disruption. This does not permit ALTON to retain payment for undelivered services contrary to applicable law or Section 10."
          }
        ]
      },
      {
        "heading": "17. California Law and Disputes",
        "blocks": [
          {
            "t": "p",
            "text": "California law governs this Agreement, together with applicable federal law. Mandatory protections of another applicable jurisdiction are preserved."
          },
          {
            "t": "p",
            "text": "A party may send a dispute notice and proposed remedy to the other party; ALTON's contact is official@alton.education. The parties will seek a good-faith resolution for up to 30 days. This process does not prevent timely filing, urgent relief, reporting to authorities, or exercising statutory rights."
          },
          {
            "t": "p",
            "text": "Subject to mandatory venue and jurisdiction rules, disputes may be brought in an eligible small-claims court or competent state or federal court in Santa Clara County, California. This Agreement does not require arbitration or waive class, representative, or jury rights."
          }
        ]
      },
      {
        "heading": "18. Entire Agreement and Changes",
        "blocks": [
          {
            "t": "p",
            "text": "This Agreement, its completed schedule, applicable orders, and expressly incorporated terms form the agreement for the paid services. Website terms cannot retroactively override recorded purchase conditions. The Privacy Notice describes processing and does not eliminate statutory rights."
          },
          {
            "t": "p",
            "text": "Material amendments require notice and acceptance where required. Ordinary subject, teacher, or scheduling changes do not automatically require a new Agreement. An unenforceable provision will be severed only to the extent lawful; the remaining terms continue where possible."
          }
        ]
      },
      {
        "heading": "Execution and Student Schedule",
        "blocks": [
          {
            "t": "p",
            "text": "The Customer confirms that they have read the Agreement, including payment, cancellation, refunds, and required regular-lesson AI processing; that they are an adult; and that they have authority to contract for the named Student where applicable."
          },
          {
            "t": "ul",
            "items": [
              "Customer legal name and capacity: [DocuSign field]",
              "Customer email and notice address: [DocuSign field]",
              "Student legal name and date of birth: [Secure field]",
              "Relationship to Student: [Parent / Legal guardian / Self]",
              "Customer signature and timestamp: [DocuSign]",
              "Company: Alton Education LLC",
              "Authorized representative name and title: [Authorized representative name and title]",
              "Company signature and timestamp: [DocuSign]"
            ]
          },
          {
            "t": "p",
            "text": "For a Student under 13, ALTON separately records the applicable direct-notice version, approved verification method, verified parent relationship, consent scope and timestamp, and any withdrawal. The required parental verification and consent process must be completed before covered collection begins."
          }
        ]
      }
    ]
  },
  "teacherCalifornia": {
    "title": "ALTON Teacher Employment Agreement — California",
    "versionLine": "Agreement Version 0.2-EN-CA | October 6, 2026",
    "sections": [
      {
        "heading": "1. Parties and Appointment",
        "blocks": [
          {
            "t": "p",
            "text": "Alton Education LLC (the “Company”) employs the undersigned teacher (the “Employee”) as a part-time, nonexempt teacher working in California. This Agreement takes effect on the start date in Schedule A. The Employee's supervisor, authorized work location, and notice information appear in that Schedule. Employment is subject to completion of legally required employment eligibility and payroll documentation."
          }
        ]
      },
      {
        "heading": "2. Employment Relationship",
        "blocks": [
          {
            "t": "p",
            "text": "Employment is at will: either party may end employment at any time, with or without cause or advance notice, subject to applicable law. Nothing permits unlawful discrimination, retaliation, or interference with protected rights. No minimum number of lessons, students, or hours is guaranteed. A change to at-will status requires a written agreement signed by an authorized Company representative and the Employee."
          }
        ]
      },
      {
        "heading": "3. Duties and Scheduling",
        "blocks": [
          {
            "t": "p",
            "text": "Duties include instruction, reasonable preparation, assignment review, lesson documentation, required meetings and training, and necessary communications. The Company communicates assignments and schedules through approved systems. The Employee must promptly report scheduling conflicts, safety concerns, and inability to provide assigned services. The Employee must not work outside an authorized location without notifying the Company and obtaining approval so payroll and legal requirements can be addressed."
          }
        ]
      },
      {
        "heading": "4. Compensation and Timekeeping",
        "blocks": [
          {
            "t": "p",
            "text": "The regular hourly rate is **USD $50.00 for all compensable time**. Compensable time includes teaching, required preparation and review, homework assessment, required meetings and training, required communications, and required setup or documentation. Lesson pricing and student credits do not determine wages owed."
          },
          {
            "t": "p",
            "text": "The Employee must accurately record all hours worked, including work outside scheduled lessons. No off-the-clock work is permitted. All hours worked will be paid, including overtime worked without advance approval; failure to follow scheduling instructions may be addressed separately. The Company pays applicable overtime, minimum wages, reporting-time pay, and other required compensation. No provision treats required preparation as unpaid or includes it without compensation in a teaching-only rate."
          },
          {
            "t": "p",
            "text": "The regular payroll period and designated paydays are stated in Schedule A and the required wage notice. Payroll deductions are limited to those permitted by law. Student refunds, cancellations, business losses, or disputed lesson credits do not authorize unlawful deductions from wages."
          }
        ]
      },
      {
        "heading": "5. Breaks, Leave, and Expenses",
        "blocks": [
          {
            "t": "p",
            "text": "The Company provides legally required meal and rest periods, premiums when required, paid sick leave, and other applicable leave. The Employee must promptly report missed or interrupted breaks and record compensable time accurately. Reporting a missed break will not result in retaliation."
          },
          {
            "t": "p",
            "text": "The Company reimburses necessary business expenses as required by law, including an appropriate business-use portion of required internet, telephone, equipment, or supplies. Expense procedures may require reasonable documentation but do not waive reimbursement rights. Workers' compensation coverage and legally required payroll protections apply."
          }
        ]
      },
      {
        "heading": "6. Student Safety and Professional Conduct",
        "blocks": [
          {
            "t": "p",
            "text": "Use approved communication and meeting channels. Maintain professional boundaries, protect student information, and promptly report suspected abuse, harassment, threats, inappropriate conduct, or security incidents. Comply with applicable mandatory reporting duties. Do not make unauthorized recordings, share credentials, solicit sensitive information unrelated to services, or move student communications to unauthorized private channels. Required screening and background-check notices and authorizations are provided separately when applicable."
          }
        ]
      },
      {
        "heading": "7. Video Recording, Audio Recording, Transcription, and AI Lesson Notes",
        "blocks": [
          {
            "t": "p",
            "text": "Regular paid lessons include video recording, audio recording, conversion of speech into a text transcript, storage of recordings and transcripts, and AI-assisted preparation and storage of lesson notes and summaries. Recorded content may include participant images, voices, names, spoken questions and answers, shared lesson screens, instructional materials, and meeting metadata. These processes support instruction, review, preparation, quality and safety management, and teacher handover. They are required components of regular lessons; initial consultations and trial lessons are excluded."
          },
          {
            "t": "p",
            "text": "The signing participant expressly consents to these activities for authorized regular lessons. A parent or legal guardian authorizes processing of the named child's participation within their lawful authority. ALTON provides notice before recording and obtains consent from all participants as required by applicable law. Additional attendees must receive notice and give required consent before capture begins. A parent signature does not substitute for another participant's consent. Recording must not start until the applicable agreement, required parental verification, and participant consent are complete."
          },
          {
            "t": "p",
            "text": "ALTON uses designated Google Workspace, Meet, Drive, and Gemini services and authorized providers acting for the stated purposes. Recordings, transcripts, and AI notes are stored with restricted access. Authorized teachers and staff may access them for their duties. Students and verified guardians may view lesson artifacts made available to their accounts; this does not grant unrestricted download, redistribution, or access to another family's records or private student notes and whiteboards. No public posting, unrelated advertising, sale, or unrestricted model training is authorized by this consent."
          },
          {
            "t": "p",
            "text": "ALTON keeps these records only as reasonably necessary for the stated purposes, the student's service relationship, and applicable legal obligations or claims. Records no longer needed are securely deleted, subject to lawful preservation requirements. Parents and participants may request access, correction, deletion, or withdrawal of consent at official@alton.education. Withdrawal applies prospectively and does not make prior authorized processing unlawful. ALTON stops affected processing as required and resolves future lessons and unused paid credits under the applicable agreement without imposing a penalty for exercising statutory rights. Free learning access is not conditioned on agreeing to lesson recording."
          },
          {
            "t": "p",
            "text": "AI notes and transcripts may contain omissions, speaker errors, or inaccuracies. Corrections may be requested. AI output alone does not conclusively determine attendance, wages, fees, refunds, or disputes. Material changes receive updated notice and renewed consent when required."
          },
          {
            "t": "p",
            "text": "Required review, correction, and documentation are compensable work under this Agreement."
          }
        ]
      },
      {
        "heading": "8. Confidentiality and Protected Rights",
        "blocks": [
          {
            "t": "p",
            "text": "Protect nonpublic student, family, employee, security, and business information. Use it only for authorized duties, restrict access, and return or securely remove Company information on request, subject to lawful retention and protected disclosures."
          },
          {
            "t": "p",
            "text": "Nothing restricts discussion of wages or working conditions, protected concerted activity, reporting suspected violations, cooperating with authorities, consulting counsel, or exercising other protected rights. No prior Company permission is required for legally protected reporting. Federal trade-secret law protects qualifying confidential disclosures to government officials or attorneys to report or investigate suspected violations and qualifying sealed court filings; this Agreement does not limit that protection."
          }
        ]
      },
      {
        "heading": "9. Work Product and Prior Materials",
        "blocks": [
          {
            "t": "p",
            "text": "To the extent permitted by law, work created within the scope of employment belongs to the Company as work made for hire. Where necessary and lawful, the Employee assigns rights in that work to the Company. Pre-existing materials listed in Schedule B remain the Employee's property. Any authorized incorporation of those materials includes a license sufficient for the agreed service use, as specified in Schedule B."
          },
          {
            "t": "p",
            "text": "This assignment excludes inventions protected by California Labor Code section 2870, including qualifying inventions developed entirely on the Employee's own time without Company equipment, supplies, facilities, or trade-secret information, except those relating to the Company's business or actual or demonstrably anticipated research or development, or resulting from work for the Company. This section provides notice of that exclusion and does not expand assignment beyond applicable law."
          }
        ]
      },
      {
        "heading": "10. Outside Work",
        "blocks": [
          {
            "t": "p",
            "text": "The Employee may engage in lawful outside work subject to avoiding actual conflicts, unauthorized use of Company resources or confidential information, and interference with scheduled duties. This Agreement creates no post-employment noncompetition restriction."
          }
        ]
      },
      {
        "heading": "11. Separation",
        "blocks": [
          {
            "t": "p",
            "text": "Upon separation, the Company pays final wages and accrued amounts within applicable statutory deadlines. The Employee must return Company property and cooperate with a reasonable handover; payment of earned wages is not conditioned on handover or a release. Student information must remain protected after separation. Any continuing obligations apply only to the extent lawful."
          }
        ]
      },
      {
        "heading": "12. Law, Disputes, and Entire Agreement",
        "blocks": [
          {
            "t": "p",
            "text": "California and applicable federal law govern, with mandatory protections preserved. The parties may seek a good-faith resolution of disputes, without restricting agency complaints, urgent relief, or filing deadlines. This Agreement does not require arbitration or waive jury, class, representative, or statutory enforcement rights."
          },
          {
            "t": "p",
            "text": "This Agreement and its completed schedules state the employment terms addressed here. Policies cannot reduce statutory rights or retroactively change earned compensation. Amendments require a written record and acceptance where required. An unenforceable provision is severed only to the extent lawful. The Employee receives a copy of the executed Agreement and applicable wage and employment notices."
          }
        ]
      },
      {
        "heading": "Schedule A — Employment and Payroll Details",
        "blocks": [
          {
            "t": "ul",
            "items": [
              "Employee legal name: ____________________",
              "Employee address and email: ____________________",
              "Company notice address: ____________________",
              "Company contact: official@alton.education",
              "Start date: ____________________",
              "California work location: ____________________",
              "Supervisor: ____________________",
              "Position: Part-time, nonexempt Teacher",
              "Regular hourly rate: USD $50.00",
              "Payroll period and designated paydays: ____________________",
              "Applicable overtime rates: As required by law and stated in the wage notice"
            ]
          }
        ]
      },
      {
        "heading": "Schedule B — Prior Materials",
        "blocks": [
          {
            "t": "p",
            "text": "List retained prior materials and any agreed license for their incorporation. If none, enter “None.”"
          },
          {
            "t": "p",
            "text": "____________________________________________________________________"
          }
        ]
      },
      {
        "heading": "Signatures",
        "blocks": [
          {
            "t": "p",
            "text": "Employee name and signature: ____________________  Date: __________"
          },
          {
            "t": "p",
            "text": "Alton Education LLC authorized representative name, title, and signature: ____________________  Date: __________"
          }
        ]
      }
    ]
  },
  "teacherNonUs": {
    "title": "ALTON Teacher Services Agreement — Services Outside the United States",
    "versionLine": "Agreement Version 0.2-EN | October 6, 2026",
    "sections": [
      {
        "heading": "1. Parties and Location",
        "blocks": [
          {
            "t": "p",
            "text": "This Agreement is between Alton Education LLC (the “Company”) and the teacher identified in Schedule A (the “Teacher”) for services performed entirely outside the United States. The Teacher must disclose their actual work country and notify the Company before changing it or performing services in the United States."
          },
          {
            "t": "p",
            "text": "The parties intend an independent service relationship where legally permissible. The title of this Agreement does not determine legal classification. Applicable mandatory employment, tax, social insurance, privacy, and other protections remain effective. If the proposed arrangement requires employment or another structure, the parties must establish that structure before continuing affected services."
          }
        ]
      },
      {
        "heading": "2. Accepted Services",
        "blocks": [
          {
            "t": "p",
            "text": "The Teacher may accept or decline offered assignments. An accepted assignment identifies subjects, lesson length, schedule, and agreed deliverables. No minimum assignments or income are guaranteed. Subject to agreed deliverables, student safety, privacy, and service standards, the Teacher controls their teaching methods and organization of work."
          },
          {
            "t": "p",
            "text": "The Teacher may not substitute another person or disclose student information to a substitute without written authorization and completion of required safeguards. Additional services beyond the accepted scope require an agreed written fee or applicable hourly basis before performance. No required work is presumed unpaid merely because it occurs outside a lesson."
          }
        ]
      },
      {
        "heading": "3. Fees and Recognized Lesson Time",
        "blocks": [
          {
            "t": "p",
            "text": "The lesson-service fee is **USD $50.00 per 60 minutes of recognized lesson time**, calculated by the minute. A recognized 120-minute lesson pays $100.00; a recognized 60-minute trial pays $50.00. The accepted rate is recorded for each assignment. A later rate change applies prospectively only after written agreement."
          },
          {
            "t": "p",
            "text": "Recognized lesson time is determined from the accepted booking and documented completion or cancellation decision, rather than meeting connection logs alone. Required nonlesson work, including preparation, review, documentation, meetings, or training, must have its scope and compensation recorded in Schedule A or an accepted written assignment. Mandatory payment rights under applicable law prevail."
          }
        ]
      },
      {
        "heading": "4. Cancellation and Attendance",
        "blocks": [
          {
            "t": "p",
            "text": "If the Teacher cancels a lesson, no lesson-service fee is earned for that cancelled lesson, without reducing payment for separate work already performed. If the Teacher is late by 10 minutes or more, undelivered time is documented and made up; the completed services are included in settlement without double payment for the same time."
          },
          {
            "t": "p",
            "text": "For an accepted regular 120-minute lesson, a student cancellation less than 24 hours before the scheduled start or a confirmed student no-show is recognized as 120 minutes when the Teacher was ready and available to provide the lesson. Student lateness does not shorten recognized time when the Teacher remains available for the scheduled period. A no-show requires the Company's documented confirmation process. Other cancellations and technical interruptions are settled according to the accepted assignment and actual services delivered, subject to applicable law."
          }
        ]
      },
      {
        "heading": "5. Statements and Payment",
        "blocks": [
          {
            "t": "p",
            "text": "Settlement covers each calendar month. The Company provides a statement within three business days after month end and pays amounts due within ten business days after month end. The Teacher should report a discrepancy within five business days after receiving the statement; missing that period does not forfeit a valid payment claim."
          },
          {
            "t": "p",
            "text": "The statement identifies assignments, recognized minutes, applicable rates, separately payable services, and lawful adjustments. Transfer method, currency conversion, and allocation of bank or intermediary fees are stated in Schedule A. No undisclosed fee or student refund is automatically deducted from earned compensation. Disputed amounts are identified and discussed promptly; undisputed amounts remain payable on schedule."
          }
        ]
      },
      {
        "heading": "6. Tax and Business Responsibilities",
        "blocks": [
          {
            "t": "p",
            "text": "The Teacher provides accurate tax-status documentation applicable to their circumstances, including Form W-8BEN when appropriate, and notifies the Company of changes. The Company makes any legally required withholding and reporting and provides supporting records. Neither an IRS form nor foreign citizenship alone determines worker classification."
          },
          {
            "t": "p",
            "text": "Subject to mandatory law and the agreed arrangement, the Teacher is responsible for their own business registrations, taxes, insurance, and ordinary equipment and connectivity costs. Any agreed reimbursable expense requires appropriate documentation. These terms do not transfer obligations that the Company must bear by law."
          }
        ]
      },
      {
        "heading": "7. Safety and Communications",
        "blocks": [
          {
            "t": "p",
            "text": "The Teacher uses approved student communication and meeting channels, maintains professional boundaries, and promptly reports safeguarding, privacy, or security concerns. Applicable reporting duties remain effective. Unauthorized recordings, credential sharing, inappropriate private contact, and disclosure of student information are prohibited. Qualification checks and any legally required screening authorizations are handled through the applicable onboarding process."
          }
        ]
      },
      {
        "heading": "8. Video Recording, Audio Recording, Transcription, and AI Lesson Notes",
        "blocks": [
          {
            "t": "p",
            "text": "Regular paid lessons include video recording, audio recording, conversion of speech into a text transcript, storage of recordings and transcripts, and AI-assisted preparation and storage of lesson notes and summaries. Recorded content may include participant images, voices, names, spoken questions and answers, shared lesson screens, instructional materials, and meeting metadata. These processes support instruction, review, preparation, quality and safety management, and teacher handover. They are required components of regular lessons; initial consultations and trial lessons are excluded."
          },
          {
            "t": "p",
            "text": "The signing participant expressly consents to these activities for authorized regular lessons. A parent or legal guardian authorizes processing of the named child's participation within their lawful authority. ALTON provides notice before recording and obtains consent from all participants as required by applicable law. Additional attendees must receive notice and give required consent before capture begins. A parent signature does not substitute for another participant's consent. Recording must not start until the applicable agreement, required parental verification, and participant consent are complete."
          },
          {
            "t": "p",
            "text": "ALTON uses designated Google Workspace, Meet, Drive, and Gemini services and authorized providers acting for the stated purposes. Recordings, transcripts, and AI notes are stored with restricted access. Authorized teachers and staff may access them for their duties. Students and verified guardians may view lesson artifacts made available to their accounts; this does not grant unrestricted download, redistribution, or access to another family's records or private student notes and whiteboards. No public posting, unrelated advertising, sale, or unrestricted model training is authorized by this consent."
          },
          {
            "t": "p",
            "text": "ALTON keeps these records only as reasonably necessary for the stated purposes, the student's service relationship, and applicable legal obligations or claims. Records no longer needed are securely deleted, subject to lawful preservation requirements. Parents and participants may request access, correction, deletion, or withdrawal of consent at official@alton.education. Withdrawal applies prospectively and does not make prior authorized processing unlawful. ALTON stops affected processing as required and resolves future lessons and unused paid credits under the applicable agreement without imposing a penalty for exercising statutory rights. Free learning access is not conditioned on agreeing to lesson recording."
          },
          {
            "t": "p",
            "text": "AI notes and transcripts may contain omissions, speaker errors, or inaccuracies. Corrections may be requested. AI output alone does not conclusively determine attendance, wages, fees, refunds, or disputes. Material changes receive updated notice and renewed consent when required."
          },
          {
            "t": "p",
            "text": "Required review, correction, and documentation must have expressly agreed compensation under Section 3; required work is not presumed unpaid."
          }
        ]
      },
      {
        "heading": "9. Confidentiality and Data Security",
        "blocks": [
          {
            "t": "p",
            "text": "Use nonpublic student, family, security, and business information only for accepted services. Apply reasonable security, restrict access, report incidents promptly, and return or securely remove information when access ends, subject to lawful retention. Follow applicable cross-border transfer and data-processing requirements. The Teacher may not use student data for unrelated marketing or solicitations."
          },
          {
            "t": "p",
            "text": "Nothing prohibits protected reporting, cooperation with authorities, legal advice, or other nonwaivable rights. Qualifying confidential trade-secret disclosures protected by applicable law remain protected."
          }
        ]
      },
      {
        "heading": "10. Materials and Intellectual Property",
        "blocks": [
          {
            "t": "p",
            "text": "The Teacher retains pre-existing materials identified in Schedule B. Upon payment, the Teacher assigns to the Company, to the extent legally transferable, rights in new materials expressly commissioned for Company ownership under an accepted assignment. Ordinary teaching does not transfer unrelated pre-existing works."
          },
          {
            "t": "p",
            "text": "For authorized incorporation of prior materials, Schedule B identifies the license required for the agreed service use. Third-party materials require lawful permission. Student work and personal information are not transferred as unrestricted Company property. Mandatory author rights and nonassignable rights remain protected."
          }
        ]
      },
      {
        "heading": "11. Other Clients and Conflicts",
        "blocks": [
          {
            "t": "p",
            "text": "The Teacher may serve other clients. The Teacher must not misuse confidential information, falsely represent Company authorization, divert an accepted Company engagement through unauthorized use of student contacts, or interfere with agreed services. This Agreement imposes no general post-termination noncompetition restriction."
          }
        ]
      },
      {
        "heading": "12. Duration and Termination",
        "blocks": [
          {
            "t": "p",
            "text": "This Agreement begins on the date in Schedule A. Either party may terminate on the written notice period completed in Schedule A. The parties may end an affected assignment promptly when necessary for safety, material breach, or a legal requirement, subject to applicable law and payment for earned services."
          },
          {
            "t": "p",
            "text": "Termination does not forfeit earned fees. The parties resolve outstanding statements, return property, and arrange a reasonable student handover. Continuing confidentiality and valid intellectual-property obligations survive only to the extent lawful."
          }
        ]
      },
      {
        "heading": "13. Responsibility and Law",
        "blocks": [
          {
            "t": "p",
            "text": "Each party is responsible for its own breaches and conduct under applicable law. Nothing excludes liability or rights that cannot lawfully be excluded. Events beyond reasonable control require prompt notice and reasonable mitigation; they do not automatically cancel payment for services already earned."
          },
          {
            "t": "p",
            "text": "California law and applicable federal law govern subject to mandatory protections in the Teacher's actual work jurisdiction. The parties seek good-faith resolution without preventing urgent relief, agency reporting, or timely claims. Disputes may be brought before a court with lawful jurisdiction, subject to mandatory venue rules. This Agreement does not require arbitration or waive nonwaivable rights."
          }
        ]
      },
      {
        "heading": "14. Entire Agreement and Execution",
        "blocks": [
          {
            "t": "p",
            "text": "This Agreement, completed schedules, and accepted written assignments govern the services. Material changes require written acceptance. Platform settings cannot retroactively alter accepted fees. An unenforceable term is severed only to the extent lawful. Both parties receive a copy of the executed Agreement. The parties may sign electronically in accordance with applicable law."
          }
        ]
      },
      {
        "heading": "Schedule A — Teacher and Commercial Details",
        "blocks": [
          {
            "t": "ul",
            "items": [
              "Teacher legal name, address, and email: ____________________",
              "Actual work country and location: ____________________",
              "Company notice address: ____________________",
              "Company contact: official@alton.education",
              "Effective date: ____________________",
              "Lesson fee: USD $50.00 per 60 recognized minutes",
              "Nonlesson services, scope, and compensation: ____________________",
              "Payment method and recipient details: ____________________",
              "Transfer, intermediary, and conversion fee allocation: ____________________",
              "Termination notice period: ____________________"
            ]
          }
        ]
      },
      {
        "heading": "Schedule B — Prior Materials and Licenses",
        "blocks": [
          {
            "t": "p",
            "text": "List retained materials and any license for agreed incorporation. If none, enter “None.”"
          },
          {
            "t": "p",
            "text": "____________________________________________________________________"
          }
        ]
      },
      {
        "heading": "Signatures",
        "blocks": [
          {
            "t": "p",
            "text": "Teacher name and signature: ____________________  Date: __________"
          },
          {
            "t": "p",
            "text": "Alton Education LLC authorized representative name, title, and signature: ____________________  Date: __________"
          }
        ]
      }
    ]
  },
  "under13Notice": {
    "title": "Parent Notice and Consent for a Child Under 13",
    "versionLine": "Alton Education LLC | Effective October 6, 2026",
    "sections": [
      {
        "heading": "Operator and Child",
        "blocks": [
          {
            "t": "p",
            "text": "ALTON provides practice tests, results and weakness analysis, a mistake notebook, vocabulary learning, approved study materials, and separately purchased tutoring. Contact official@alton.education for privacy questions and parent requests."
          },
          {
            "t": "p",
            "text": "Child legal name: ____________________"
          },
          {
            "t": "p",
            "text": "Child date of birth: ____________________"
          },
          {
            "t": "p",
            "text": "Parent or legal guardian name and contact: ____________________"
          }
        ]
      },
      {
        "heading": "Information and Purposes",
        "blocks": [
          {
            "t": "p",
            "text": "With verified parental consent, ALTON collects the child's name, account identifiers, email where used, date of birth, grade, optional school, practice attempts, answers, scores, saved questions, vocabulary progress, study notes and whiteboard work, service communications, and necessary usage and security data. These support account operation, instruction, grading, learning progress, safety, and service administration. Parent verification information is used to establish authority and consent and is not used for unrelated marketing."
          },
          {
            "t": "p",
            "text": "Registration does not guarantee operational acceptance or access before verification. ALTON obtains legally required verifiable parental consent before covered collection, use, or disclosure. Only information allowed for requesting consent or another lawful exception may be collected beforehand. Free registration does not create a tutoring contract, lesson credits, teacher assignment, or payment."
          }
        ]
      },
      {
        "heading": "Regular-Lesson Recording and AI Processing",
        "blocks": [
          {
            "t": "h3",
            "text": "Video Recording, Audio Recording, Transcription, and AI Lesson Notes"
          },
          {
            "t": "p",
            "text": "Regular paid lessons include video recording, audio recording, conversion of speech into a text transcript, storage of recordings and transcripts, and AI-assisted preparation and storage of lesson notes and summaries. Recorded content may include participant images, voices, names, spoken questions and answers, shared lesson screens, instructional materials, and meeting metadata. These processes support instruction, review, preparation, quality and safety management, and teacher handover. They are required components of regular lessons; initial consultations and trial lessons are excluded."
          },
          {
            "t": "p",
            "text": "The signing participant expressly consents to these activities for authorized regular lessons. A parent or legal guardian authorizes processing of the named child's participation within their lawful authority. ALTON provides notice before recording and obtains consent from all participants as required by applicable law. Additional attendees must receive notice and give required consent before capture begins. A parent signature does not substitute for another participant's consent. Recording must not start until the applicable agreement, required parental verification, and participant consent are complete."
          },
          {
            "t": "p",
            "text": "ALTON uses designated Google Workspace, Meet, Drive, and Gemini services and authorized providers acting for the stated purposes. Recordings, transcripts, and AI notes are stored with restricted access. Authorized teachers and staff may access them for their duties. Students and verified guardians may view lesson artifacts made available to their accounts; this does not grant unrestricted download, redistribution, or access to another family's records or private student notes and whiteboards. No public posting, unrelated advertising, sale, or unrestricted model training is authorized by this consent."
          },
          {
            "t": "p",
            "text": "ALTON keeps these records only as reasonably necessary for the stated purposes, the student's service relationship, and applicable legal obligations or claims. Records no longer needed are securely deleted, subject to lawful preservation requirements. Parents and participants may request access, correction, deletion, or withdrawal of consent at official@alton.education. Withdrawal applies prospectively and does not make prior authorized processing unlawful. ALTON stops affected processing as required and resolves future lessons and unused paid credits under the applicable agreement without imposing a penalty for exercising statutory rights. Free learning access is not conditioned on agreeing to lesson recording."
          },
          {
            "t": "p",
            "text": "AI notes and transcripts may contain omissions, speaker errors, or inaccuracies. Corrections may be requested. AI output alone does not conclusively determine attendance, wages, fees, refunds, or disputes. Material changes receive updated notice and renewed consent when required."
          }
        ]
      },
      {
        "heading": "Providers and Disclosure",
        "blocks": [
          {
            "t": "p",
            "text": "Necessary providers include Supabase for authentication and storage, Vercel for hosting, Google Workspace/Meet/Drive/Gemini for authorized lesson services, DocuSign for signatures, Stripe for payments, and the designated service-email provider. Authorized teachers and staff receive information needed for their duties. Verified linked guardians receive permitted learning results and lesson artifacts. Private personal notes and whiteboards are not generally exposed to guardians. Information is not sold or shared for targeted advertising. No disclosure unrelated to the service is authorized by this form. Information may be processed in the United States and provider processing locations, with applicable safeguards."
          }
        ]
      },
      {
        "heading": "Parent Rights and Retention",
        "blocks": [
          {
            "t": "p",
            "text": "You may review your child's information, request correction or deletion, and refuse further collection or withdraw consent by contacting official@alton.education. ALTON verifies authority and responds within applicable deadlines. Withdrawal may prevent delivery of features requiring that processing but does not authorize a forfeiture of statutory rights. A 30-day account-closure workflow does not postpone privacy-request deadlines. Child information is retained only for the disclosed purposes and as legally required, then securely deleted; it is not retained indefinitely for possible future use."
          }
        ]
      },
      {
        "heading": "Parent Authorization",
        "blocks": [
          {
            "t": "p",
            "text": "I am the named child's parent or legal guardian and have authority to consent. I have received this notice and the Privacy Policy. I authorize the collection, use, storage, and necessary service-provider disclosure described above. For regular paid lessons, I expressly authorize video recording, audio recording, speech-to-text transcription and storage, and AI meeting notes and summaries and their storage. This consent does not authorize recording initial consultations or trial lessons, public publication, sale, targeted advertising, or unrelated disclosures."
          },
          {
            "t": "p",
            "text": "Parent signature: ____________________  Date: __________"
          },
          {
            "t": "p",
            "text": "Child/account reference: ____________________"
          },
          {
            "t": "p",
            "text": "Consent version: U13-EN-2026-10-06"
          },
          {
            "t": "p",
            "text": "ALTON completes the applicable parental verification process before enabling covered collection. Signing this form alone does not bypass that process."
          }
        ]
      }
    ]
  }
};
