// AB 풀 세트 정확 선택(무료, DB 없음). npx tsx scripts/ap-generation/ab-select.ts [--exclude key1,key2] [--prev data/ap/stock/ab-full-set-selection.json] [--seed N] [--dry-run | --write-report <경로> | --write-published]
// 기본·--dry-run: 디스크 무변경(출력만). 보고서 저장은 --write-report <경로>(게시본 경로 불가). 게시본(docs/ap/ab-full-set-selection.md·data/ap/stock/ab-full-set-selection.json)은 --write-published 명시 때만 덮어쓴다.
// 사용 이력(겹침)은 선택 파일 data/ap/stock/published-usage.json [{stockKey, fullMock, practice}] 에서 읽는다(없으면 이력 미상 = 0으로 두고 보고서에 명시).
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { PUBLISHED_JSON, PUBLISHED_MD, planOutputs } from "../../lib/ap-exam/ab-select-output";
const plan = planOutputs(process.argv); if (plan.error) { console.error(plan.error); process.exit(2); }
import { gateCandidate } from "../../lib/ap-figures/gate";
import { selectFrq, selectMc, verify, type Cand, type Sel } from "../../lib/ap-exam/ab-select";
import { clusterLookAlikes } from "../../lib/ap-exam/look-alike";
import type { ApCurriculumFile } from "../../lib/ap-curriculum/types";
const SUBJECT = "ap_calculus_ab"; const arg = (n: string) => { const i = process.argv.indexOf(n); return i > 0 ? process.argv[i + 1] : ""; };
type It = { stockKey: string; apSubjectCode: string; kind: "mc" | "frq_bundle"; validation: string; keywordCode: string; calculator: string; itemFamilyId: string; payload: Record<string, unknown>; skillPrimary?: string; duplicateOf?: string | null };
const scan = new Set((JSON.parse(readFileSync("data/ap/stock/defect-scan.json", "utf-8")) as { key: string }[]).map((r) => r.key));
const all = ["items", "s1a-items", "v1ab-items", "v45ab-items"].flatMap((f) => { try { return JSON.parse(readFileSync(`data/ap/stock/${f}.json`, "utf-8")) as It[]; } catch { return [] as It[]; } }).filter((i) => i.apSubjectCode === SUBJECT && i.validation === "auto_passed" && !scan.has(i.stockKey) && !i.duplicateOf);
const ev = new Set(readdirSync("data/ap/screen-evidence").filter((f) => /^evidence-.*\.json$/.test(f)).flatMap((f) => (JSON.parse(readFileSync(`data/ap/screen-evidence/${f}`, "utf-8")) as { entries: { candidate_key: string }[] }).entries.map((e) => e.candidate_key)));
const usageFile = "data/ap/stock/published-usage.json"; const usage = new Map((existsSync(usageFile) ? (JSON.parse(readFileSync(usageFile, "utf-8")) as { stockKey: string; fullMock?: boolean | number; practice?: string[] | number }[]) : []).map((u) => [u.stockKey, u]));
const cur = JSON.parse(readFileSync(`data/ap/curriculum-2027/${SUBJECT}.json`, "utf-8")) as ApCurriculumFile; const unitName = new Map(cur.units.map((u) => [u.code, (u as unknown as { title: string }).title]));
const pool: Cand[] = all.map((i) => { const g = gateCandidate({ stockKey: i.stockKey, candidateKey: i.stockKey, apSubjectCode: i.apSubjectCode, kind: i.kind, payload: i.payload }); const u = usage.get(i.stockKey);
  return { key: i.stockKey, kind: (i.kind === "mc" ? "mc" : "frq") as Cand["kind"], unit: Number(i.keywordCode.split(".")[0]), skillCat: Number((i.skillPrimary ?? "0")[0]), calc: i.calculator as Cand["calc"], family: i.itemFamilyId, type: i.keywordCode, graphRequired: g.need === "required" && g.stimKind === "graph", screenVerified: ev.has(i.stockKey), renderOk: g.status !== "fail", fullMockUses: Number(u?.fullMock ? 1 : 0), practiceUses: Array.isArray(u?.practice) ? u.practice.length : Number(u?.practice ?? 0) }; }).filter((c) => c.renderOk);
// 구조적 look-alike(2026-10-09): 문항군 ID 가 달라도 같은 틀이면 같은 문항군으로 센다(풀 세트 문항군 상한 1).
{ const P = (i: It) => i.payload as { archetype?: string; topic?: string; stem?: string; stimulus?: { kind?: string }; blueprint?: { student_thinking?: string[] } };
  const byK = new Map(all.map((i) => [i.stockKey, i])); const cl = clusterLookAlikes(pool.filter((c) => c.kind === "mc").map((c) => { const i = byK.get(c.key)!; const p = P(i); return { key: c.key, family: c.family, archetype: p.archetype, topic: c.type, stimKind: p.stimulus?.kind ?? "none", stem: p.stem ?? "", thinking: p.blueprint?.student_thinking }; }));
  for (const c of pool) if (c.kind === "mc") c.family = cl.effectiveFamily.get(c.key) ?? c.family; }
const exclude = new Set((arg("--exclude") || "").split(",").filter(Boolean)); const prevSel = arg("--prev") && existsSync(arg("--prev")) ? (JSON.parse(readFileSync(arg("--prev"), "utf-8")) as { keys: Record<string, string[]> }).keys : null;
const byKey = new Map(pool.map((c) => [c.key, c])); const fromKeys = (k: string[] = []) => k.map((x) => byKey.get(x)).filter((c): c is Cand => !!c);
const seedArg = arg("--seed"); const seed = seedArg ? Number(seedArg) : undefined; if (seedArg && !Number.isInteger(seed)) { console.error("--seed 는 정수"); process.exit(2); }
const mc = selectMc(pool, { seed, exclude, prev: prevSel ? { mcA: fromKeys(prevSel.mcA), mcB: fromKeys(prevSel.mcB) } : undefined }); const fq = selectFrq(pool, exclude);
console.log(`재고 ${pool.length}(MC ${pool.filter((c) => c.kind === "mc").length}, FRQ ${pool.filter((c) => c.kind === "frq").length}), 그래프 필수 MC ${pool.filter((c) => c.kind === "mc" && c.graphRequired).length} / FRQ ${pool.filter((c) => c.kind === "frq" && c.graphRequired).length}, 화면 검증 ${pool.filter((c) => c.screenVerified).length}, 사용 이력 파일 ${usage.size ? "있음" : "없음(겹침 미상)"}`);
if (!mc || !fq) { console.log("해 없음", { mc: !!mc, frq: !!fq }); process.exit(3); }
const sel: Sel = { ...mc, frqA: fq.a, frqB: fq.b }; const cons = verify(sel); const ok = cons.every((c) => c.ok);
const sections: [string, Cand[]][] = [["MC Part A (계산기 불가, 62분)", sel.mcA], ["MC Part B (계산기 필수, 38분)", sel.mcB], ["FRQ Part A (계산기, 30분)", sel.frqA], ["FRQ Part B (계산기 불가, 60분)", sel.frqB]];
const setsOf = (k: string) => { const p = usage.get(k)?.practice; return Array.isArray(p) ? p : []; };
const perSet = new Map<string, number>(); for (const c of failedList0()) for (const n of setsOf(c.key)) perSet.set(n, (perSet.get(n) ?? 0) + 1);
function failedList0() { return [...sel.mcA, ...sel.mcB, ...sel.frqA, ...sel.frqB]; }
const reexp = failedList0().filter((c) => c.practiceUses > 0).length;
const st = (c: Cand) => (c.screenVerified ? "화면 검증 완료" : "검증 대기") + (c.practiceUses ? ` / 재노출: ${setsOf(c.key).join(", ")}` : " / 첫 노출");
const L = ["# AB 풀 모의고사 1세트 선택 결과 (자동 생성 — `ab-select.ts`)", "", `결과: **${ok ? "모든 제약 통과(검증기 재계산)" : "제약 실패 있음"}**. 방식은 고정 시드 탐색 + 독립 검증기이며, 못 찾은 경우가 불가능의 증명은 아니다. 사용 이력(겹침): ${usage.size ? "published-usage.json 반영" : "**미반영** — 비프로덕션 사용 이력을 `published-usage.json` 으로 주면 풀 모의고사 겹침 0 · 연습 세트 재노출을 계산한다"}.`, "", "## 제약 (official = 공식, internal = 내부 설계 조건; 서로 섞어 표기하지 않는다)", "| 구분 | 제약 | 결과 | 값 |", "|---|---|---|---|", ...cons.map((c) => `| ${c.label} | ${c.text} | ${c.ok ? "통과" : "실패"} | ${c.detail} |`), "", "## 연습 세트 겹침(정책: 풀 모의고사끼리 0, 연습 세트와는 허용하되 보고)", `- 게시된 풀 모의고사 없음 -> 풀 모의고사 겹침 0. 연습 세트 겹침 ${reexp}/48건(재노출), 첫 노출 ${48 - reexp}건.`, ...[...perSet].map(([n, v]) => `- ${n}: ${v}건`), "- 해당 연습 세트를 응시한 학생에게는 위 재노출 항목이 두 번째 노출이고, 나머지는 첫 노출이다.", "", "## 단원 구성 (코드 = CED 단원 번호, 이름 = 커리큘럼 파일의 CED 이름)", "> 주의: 아래 단원·스킬 문항 수는 **이 세트의 배분**이다. 공식 자료(CED)는 단원·스킬 범주별 **비중 범위(%)** 만 정하며(MC 42문항 기준 단원별 허용 개수는 `OFFICIAL.unitBounds`), 모든 세트에 적용되는 고정 개수가 아니다. 범위 안이면 세트마다 달라도 된다.", "", "| 단원 | 이름 | MC A | MC B | 합계 |", "|---|---|---|---|---|", ...[1, 2, 3, 4, 5, 6, 7, 8].map((u) => { const a = sel.mcA.filter((c) => c.unit === u).length, b = sel.mcB.filter((c) => c.unit === u).length; return `| ${u} | ${unitName.get(String(u))} | ${a} | ${b} | ${a + b} |`; }), "", "학생 화면의 `Covers Units …` 문구는 단원 번호(코드)만 쓴다(`lib/ap-exam/layouts.ts`); 이름을 쓰는 화면은 위 CED 이름과 일치해야 한다.", "", `## 48건 목록 (검증 에이전트 입력) — 화면 검증 완료 ${failedList(sel).filter((c) => c.screenVerified).length} / 검증 대기 ${failedList(sel).filter((c) => !c.screenVerified).length}`, "| 구역 | # | 키 | 단원.키워드 | 스킬 | 문항군 | 그래프 필수 | 상태 |", "|---|---|---|---|---|---|---|---|"];
function failedList(s: Sel) { return [...s.mcA, ...s.mcB, ...s.frqA, ...s.frqB]; }
for (const [n, xs] of sections) xs.forEach((c, i) => L.push(`| ${n} | ${i + 1} | ${c.key} | ${c.type} | ${c.skillCat || "-"} | ${c.family} | ${c.graphRequired ? "예" : ""} | ${st(c)} |`));
L.push("", "## 실패 시 교체 절차(재고 우선, 생성 없음)", "1. 검증 에이전트가 탈락 키를 모은다.", "2. `npx tsx scripts/ap-generation/ab-select.ts --prev data/ap/stock/ab-full-set-selection.json --exclude <키1,키2>` — 탈락 슬롯만 재고에서 교체하고 **세트 전체 제약을 다시 검증**한다(같은 구역 교체 우선, 실패하면 전체 재탐색).", "3. 해가 없으면(종료 코드 3) 부족한 구조(단원·계산기·그래프 필수·FRQ 유형)와 최소 생성 비용을 적어 별도 승인을 요청한다(예비 생성은 이번에 미승인).", "", "## 비프로덕션 조립 명령 (dry-run — 실행하지 않음)", "```", "npx tsx scripts/ap-generation/ab-select.ts --dry-run    # 선택 + 검증만(디스크 무변경, 무료)", "npx tsx scripts/ap-generation/ab-select.ts --write-report <경로>   # 별도 경로에 보고서 저장", "npx tsx scripts/ap-generation/ab-select.ts --write-published   # 게시본 덮어쓰기(명시 시에만)", "npx tsx scripts/ap-generation/ab-select.ts --exclude <키들> --prev data/ap/stock/ab-full-set-selection.json   # 탈락 교체", "# 조립·게시는 오너/배포 담당: 위 48건의 problem_version 으로 ap_mock_exam 풀 세트 행을 비프로덕션에 만드는 단계(기존 연습 세트 게시 스크립트와 동일 경로). 이 문서는 조립을 실행하지 않는다.", "```");
const json = JSON.stringify({ ok, constraints: cons, keys: { mcA: sel.mcA.map((c) => c.key), mcB: sel.mcB.map((c) => c.key), frqA: sel.frqA.map((c) => c.key), frqB: sel.frqB.map((c) => c.key) } }, null, 1);
if (plan.writeReport) { writeFileSync(plan.writeReport, L.join("\n") + "\n"); writeFileSync(plan.writeReport.replace(/(\.md)?$/, ".json"), json); console.log(`보고서 저장: ${plan.writeReport}`); }
if (plan.writePublished) { writeFileSync(PUBLISHED_MD, L.join("\n") + "\n"); writeFileSync(PUBLISHED_JSON, json); console.log("게시본 덮어씀(--write-published)"); }
if (!plan.writeReport && !plan.writePublished) console.log("(저장 없음: --write-report <경로> 또는 --write-published)");
console.log(cons.map((c) => `${c.ok ? "OK " : "NO "}[${c.label}] ${c.text} ${c.detail}`).join("\n")); process.exit(ok ? 0 : 1);
