// 복합 도형(CM) 계열 자료 원형 공용 키트 — 조합 파일(items/<조합ID>.ts)이 함께 쓴다.
// 규칙: 치수는 그림 라벨에만 있고 지문은 "the figure shown" 으로 가리킨다. 바깥 도형과 안쪽 도형의 크기 관계가 렌더러에서 고정인 장면(정사각형에 내접한 원, 원에 내접한 정사각형, 직사각형 위 반원)은 그림이 참값대로 그려지고, 그 외는 notToScale 이다.
import { fmtNum } from "../../text";
import type { Rng } from "../../rng";
import { NUM_JS } from "./geo-kit";

export type CmFig = { type: "composite"; outer: { kind: "square" | "rectangle" | "circle"; width?: string; height?: string; side?: string; radius?: string; diameter?: string }; inner: { kind: "circle" | "square" | "rectangle" | "semicircle" | "triangle"; side?: string; width?: string; height?: string; radius?: string; diameter?: string; placement?: "center" | "on_base" | "corner" }; shaded: "outer_minus_inner" | "inner" | "none"; notToScale?: boolean };
/** FIGURE(composite) 라벨을 숫자로 읽는 JS: O(바깥)·I(안쪽) 의 각 라벨은 숫자 또는 NaN. */
export const CM_JS = `${NUM_JS}const O=FIGURE.outer, I=FIGURE.inner; const on=(k)=>O[k]===undefined?NaN:num(O[k]); const inn=(k)=>I[k]===undefined?NaN:num(I[k]);\n`;
export const CM_LEAD = ["", "", "A designer draws the shape shown. ", "An architect sketches the plan below. ", "A student studies the figure shown. ", "A craftsperson cuts the piece shown from a sheet. ", "A landscaper plans the area shown. ", "A sign maker lays out the design below. ", "A tile installer marks the surface shown. ", "A museum curator plans the display shown. ", "A baker cuts the shape shown from a sheet of dough. ", "A teacher shows the class the diagram below. "];
export const CM_CTX = ["", "", "All lengths are in the same unit. ", "Lengths are in centimeters. ", "Lengths are given in meters. ", "Use the labels in the figure. ", "Read each label before computing. ", "Think about which pieces to add and which to subtract. ", "Break the shape into simpler pieces first. ", "A calculator is not necessary. ", "Check each label against the part of the figure it describes. ", "The figure is not meant to be measured; use the labels. ", "Look at how the pieces fit together before computing. ", "Work carefully with the units given. "];
/** a + bπ 형식 식 문자열(KaTeX): b<0 이면 빼기. a=0 이면 bπ 만. */
export function exprPi(a: number, b: number): string {
  const pb = Math.abs(b) === 1 ? "\\pi" : `${fmtNum(Math.abs(b))}\\pi`;
  if (a === 0) return b < 0 ? `$-${pb}$` : `$${pb}$`;
  if (b === 0) return `$${fmtNum(a)}$`;
  return `$${fmtNum(a)} ${b < 0 ? "-" : "+"} ${pb}$`;
}
export const SPR_NO_CM = "정답이 π 를 포함한 식(a ± bπ)이라 순수한 수 하나로 낼 수 없다";
export const pickOne = <T,>(rng: Rng, xs: T[]): T => rng.pick(xs);
/** 지문 도입: 장식 + 맥락 + 장면 설명(여러 문장 중 하나) + 추가 문장. */
export const cmIntro = (rng: Rng, scenes: string[], extra = "") => `${rng.pick(CM_LEAD)}${rng.pick(CM_CTX)}${rng.pick(scenes)}${extra}`.replace(/ {2,}/g, " ").trim();
export const SQ_CIRCLE = ["The figure shows a circle drawn inside a square; the circle touches all four sides of the square.", "A circle is inscribed in a square in the figure shown, touching each side of the square.", "In the figure shown, a circle fits snugly inside a square so that it touches all four sides.", "The circle in the figure is tangent to every side of the square that surrounds it.", "A round plate sits exactly inside a square tray in the figure, touching all four sides of the square.", "The figure shows a square with the largest possible circle drawn inside it."];
export const RECT_SEMI = ["The figure shows a rectangle with a semicircle attached along its top side; the diameter of the semicircle is the top side of the rectangle.", "A semicircle sits on top of a rectangle in the figure shown, and its diameter is the rectangle's top side.", "In the figure shown, a semicircular cap is placed on a rectangle, with the semicircle's diameter matching the rectangle's top side.", "A window shaped like a rectangle topped by a semicircle is shown; the straight side of the semicircle is the top of the rectangle.", "The figure shows a rectangle whose top side is the diameter of a semicircle drawn above it."];
export const CIRC_SQ = ["The figure shows a square drawn inside a circle; all four vertices of the square lie on the circle.", "A square is inscribed in a circle in the figure shown, with each vertex of the square on the circle.", "In the figure shown, the corners of a square touch the circle that surrounds it.", "The square in the figure is inscribed in the circle: every vertex of the square is on the circle.", "A square tile is cut from a circular piece of wood so that its four corners touch the edge, as shown in the figure."];

// 장면 문장을 더 다양하게(독립 변형 확보) — 같은 기하 관계를 서로 다른 말로 설명한다.
SQ_CIRCLE.push("A coin-shaped disk is pressed into a square frame so that it just fits, touching the frame on every side, as in the figure.", "Inside the square in the figure there is a circle with the greatest size that still fits; it meets all four sides of the square.", "The figure shows a circular stamp inside a square label, with the circle's edge meeting the middle of each side of the label.", "In the figure shown, the circle and the square are arranged so that the circle's diameter spans the full width of the square.");
RECT_SEMI.push("A tunnel entrance is modeled by a rectangle with a half-circle on top, as shown; the flat edge of the half-circle is the top of the rectangle.", "The figure shows a doorway: a rectangular opening capped by a semicircular arch whose width equals the width of the rectangle.", "A semicircular roof covers a rectangular room in the figure shown, and the roof's straight edge runs along the top of the room.", "In the figure, half of a circle is attached to the upper edge of a rectangle, and the two shapes share that edge.", "The cross section of a barn is shown: a rectangle supports a semicircular roof that is as wide as the rectangle.");
CIRC_SQ.push("A square is cut from a round pizza so that each corner of the square lies on the crust, as shown in the figure.", "The figure shows a circle with a square drawn inside it; the corners of the square are on the circle and the diagonal of the square passes through the center.", "A square frame fits inside a round window so that its four corners touch the glass edge, as shown.");
export const Q_AREA = (rng: Rng, what: string) => rng.pick([`What is the ${what}?`, `Find the ${what}.`, `How large is the ${what}?`, `Determine the ${what}.`, `Calculate the ${what}.`, `The ${what} equals what value?`]);
export const Q_PI = (rng: Rng, what: string) => rng.pick([`What is the ${what}, in terms of $\\pi$?`, `Find the ${what} in terms of $\\pi$.`, `The ${what} is how many units, in terms of $\\pi$?`, `Express the ${what} in terms of $\\pi$.`, `Which value gives the ${what}, written in terms of $\\pi$?`, `Determine the ${what}, leaving $\\pi$ in your answer.`]);
