// 포물선 그래프 선택지형(FN.C) 원형 팩토리(math-A 소유) — 꼭짓점·영점·통과 점·계수·평행이동 조건 두 개를 서술로 주고 포물선 그래프 4개 중 하나를 고른다.
import { GenFail, type OperatorId } from "../../types";
import type { Rng } from "../../rng";
import { defineItem } from "./item-kit";
import { C_LEADS, QSTAT, R_SET, SPR_NO_PLANE_CHOICE, cInst, oneCond, parabolaOk, parabolaPool, poolChoices, twoCond } from "./cplane-kit";

type Q = { A: number; H: number; K: number; R: number };
type B = { clause: string; P: Record<string, number>; A: string; Bj: string; rules: [string, string, string]; ok: Q; trace: [string, string][]; tag: string };
const sg = (n: number) => (n < 0 ? `-${-n}` : `${n}`);
const UP = (a: number) => (a > 0 ? "upward" : "downward");
const R3: [string, string, string] = ["first_off", "second_off", "both_off"];
function base(rng: Rng, o: { aPool?: number[] } = {}): Q { for (let t = 0; t < 400; t++) { const R = rng.pick(R_SET), A = rng.pick(o.aPool ?? [-2, -1, 1, 2]), H = rng.int(-3, 3), K = rng.int(-(R - 3), R - 3); try { parabolaOk(R, A, H, K); } catch { continue; } if (K === 0 && rng.chance(0.7)) continue; return { A, H, K, R }; } throw new GenFail("포물선 표집 실패"); }
const coef = (q: Q) => ({ a: q.A, b: -2 * q.A * q.H, c: q.A * q.H * q.H + q.K });

export const QBUILD: Record<string, (rng: Rng) => B> = {
  vertex(rng) { const q = base(rng); return { tag: "vertex", clause: rng.pick([`has its vertex at the point with $x$-coordinate ${q.H} and $y$-coordinate ${q.K}`, `has a vertex where $x = ${q.H}$ and $y = ${q.K}$`, `turns around at the point with $x$-coordinate ${q.H} and $y$-coordinate ${q.K}`]), P: { h: q.H, k: q.K }, A: "s.H === P.h", Bj: "s.K === P.k", rules: ["vertex_x_off", "vertex_y_off", "both_off"], ok: q, trace: [[`꼭짓점은 (${q.H}, ${q.K}) 이다.`, "The vertex is given."]] }; },
  vertexOpen(rng) { const q = base(rng); return { tag: "vertex_x_open", clause: rng.pick([`has its vertex at $x = ${q.H}$ and opens ${UP(q.A)}`, `opens ${UP(q.A)} and has an axis of symmetry at $x = ${q.H}$`, `has the vertical line $x = ${q.H}$ as its axis of symmetry and opens ${UP(q.A)}`]), P: { h: q.H, up: q.A > 0 ? 1 : 0 }, A: "s.H === P.h", Bj: "(s.A > 0 ? 1 : 0) === P.up", rules: ["axis_off", "opening_off", "both_off"], ok: q, trace: [[`대칭축 x = ${q.H}, ${UP(q.A) === "upward" ? "위" : "아래"}로 열린다.`, "Axis and opening direction."]] }; },
  vertexKOpen(rng) { const q = base(rng); return { tag: "vertex_y_open", clause: rng.pick([`has its ${q.A > 0 ? "lowest" : "highest"} point at $y = ${q.K}$ and opens ${UP(q.A)}`, `opens ${UP(q.A)} with a ${q.A > 0 ? "minimum" : "maximum"} value of ${q.K}`]), P: { k: q.K, up: q.A > 0 ? 1 : 0 }, A: "s.K === P.k", Bj: "(s.A > 0 ? 1 : 0) === P.up", rules: ["vertex_y_off", "opening_off", "both_off"], ok: q, trace: [[`${q.A > 0 ? "최솟값" : "최댓값"} ${q.K} 이므로 꼭짓점의 y 좌표는 ${q.K}, ${UP(q.A) === "upward" ? "위" : "아래"}로 열린다.`, "Extreme value and opening direction."]] }; },
  zeros(rng) { for (let t = 0; t < 400; t++) { const q = base(rng); const d2 = -q.K / q.A; const d = Math.sqrt(d2); if (!Number.isInteger(d) || d < 1) continue; const p = q.H - d, r = q.H + d; if (Math.abs(p) > q.R - 1 || Math.abs(r) > q.R - 1) continue;
      return { tag: "zeros", clause: rng.pick([`crosses the $x$-axis at $x = ${p}$ and at $x = ${r}$`, `has $x$-intercepts at ${p} and ${r}`, `has zeros at $x = ${p}$ and $x = ${r}$`]), P: { p, r }, A: "Math.abs(s.A * P.p * P.p + s.B * P.p + s.C) < 1e-9", Bj: "Math.abs(s.A * P.r * P.r + s.B * P.r + s.C) < 1e-9", rules: ["first_zero_off", "second_zero_off", "both_off"], ok: q, trace: [[`영점 ${p}, ${r} 이므로 대칭축은 x = ${q.H} 이다.`, "The axis lies midway between the zeros."]] }; } throw new GenFail("영점"); },
  pointOpen(rng) { const q = base(rng); const c = coef(q); const xs: number[] = []; for (let x = -q.R + 1; x <= q.R - 1; x++) { const y = c.a * x * x + c.b * x + c.c; if (x !== 0 && Math.abs(y) <= q.R - 1) xs.push(x); } if (!xs.length) throw new GenFail("점"); const x = rng.pick(xs); const y = c.a * x * x + c.b * x + c.c;
    return { tag: "point_open", clause: rng.pick([`passes through the point with $x$-coordinate ${x} and $y$-coordinate ${y} and opens ${UP(q.A)}`, `opens ${UP(q.A)} and contains the point where $x = ${x}$ and $y = ${y}$`]), P: { p: x, q: y, up: q.A > 0 ? 1 : 0 }, A: "Math.abs(s.A * P.p * P.p + s.B * P.p + s.C - P.q) < 1e-9", Bj: "(s.A > 0 ? 1 : 0) === P.up", rules: ["point_off", "opening_off", "both_off"], ok: q, trace: [[`점 (${x}, ${y}) 를 지나고 ${UP(q.A) === "upward" ? "위" : "아래"}로 열린다.`, "Point and opening direction."]] }; },
  aValue(rng) { const q = base(rng); const c = coef(q); return { tag: "a_and_c", clause: rng.pick([`is the graph of $y = ax² + bx + c$ where $a = ${sg(c.a)}$ and $c = ${sg(c.c)}$`, `represents $y = ax² + bx + c$ with $a = ${sg(c.a)}$ and $c = ${sg(c.c)}$`]), P: { a: c.a, c: c.c }, A: "s.A === P.a", Bj: "s.C === P.c", rules: ["a_off", "c_off", "both_off"], ok: q, trace: [[`a = ${c.a} 이므로 ${c.a > 0 ? "위" : "아래"}로 열리고, c = ${c.c} 는 y 절편이다.`, "a gives the opening; c is the y-intercept."]] }; },
  bValue(rng) { const q = base(rng); const c = coef(q); return { tag: "a_and_b", clause: rng.pick([`is the graph of $y = ax² + bx + c$ where $a = ${sg(c.a)}$ and $b = ${sg(c.b)}$`, `represents $y = ax² + bx + c$ with $a = ${sg(c.a)}$ and $b = ${sg(c.b)}$`]), P: { a: c.a, b: c.b }, A: "s.A === P.a", Bj: "s.B === P.b", rules: ["a_off", "b_off", "both_off"], ok: q, trace: [[`a = ${c.a}, b = ${c.b} 이므로 대칭축은 x = -b/(2a) = ${q.H} 이다.`, "The axis is x = -b / (2a)."]] }; },
  shifted(rng) { const q = base(rng); const s = rng.nz(-3, 3), t = rng.nz(-3, 3); const mode = rng.pick(["h", "v", "hv"]); const dx = mode === "v" ? 0 : s, dy = mode === "h" ? 0 : t; const ok: Q = { ...q, H: q.H + dx, K: q.K + dy }; try { parabolaOk(ok.R, ok.A, ok.H, ok.K); } catch { throw new GenFail("범위"); } const mv = (v: number, pos: string, neg: string) => (v > 0 ? `${v} units ${pos}` : `${-v} units ${neg}`); const parts = [dx ? mv(dx, "to the right", "to the left") : "", dy ? mv(dy, "up", "down") : ""].filter(Boolean).join(" and ");
    return { tag: `shift_${mode}`, clause: rng.pick([`is the graph obtained by shifting a parabola with vertex at the point with $x$-coordinate ${q.H} and $y$-coordinate ${q.K}, opening ${UP(q.A)} with the same shape, ${parts}`, `is the image of a ${UP(q.A)}-opening parabola with vertex where $x = ${q.H}$ and $y = ${q.K}$ after it moves ${parts}`, `results from moving ${parts} a ${UP(q.A)}-opening parabola whose vertex has $x$-coordinate ${q.H} and $y$-coordinate ${q.K}`]), P: { h: q.H, k: q.K, ...(dx ? { dx } : {}), ...(dy ? { dy } : {}), up: q.A > 0 ? 1 : 0 }, A: `(s.A > 0 ? 1 : 0) === P.up && s.H === P.h${dx ? " + P.dx" : ""}`, Bj: `s.K === P.k${dy ? " + P.dy" : ""}`, rules: ["horizontal_off", "vertical_off", "both_off"], ok, trace: [[`꼭짓점 (${q.H}, ${q.K}) 를 ${parts} 옮기면 (${ok.H}, ${ok.K}) 이다.`, "Shift the vertex."]] }; },
  twoSol(rng) { const q = base(rng); const c = q.A > 0 ? q.K + rng.int(1, 4) : q.K - rng.int(1, 4); if (Math.abs(c) > q.R - 1 || c === 0) throw new GenFail("c"); return { tag: "two_solutions", clause: rng.pick([`meets the horizontal line $y = ${c}$ at exactly two points and opens ${UP(q.A)}`, `opens ${UP(q.A)} and crosses the line $y = ${c}$ twice`]), P: { c, up: q.A > 0 ? 1 : 0 }, A: "(P.c - s.K) / s.A > 1e-9", Bj: "(s.A > 0 ? 1 : 0) === P.up", rules: ["intersections_off", "opening_off", "both_off"], ok: q, trace: [[`${UP(q.A) === "upward" ? "위" : "아래"}로 열리고 꼭짓점 높이 ${q.K} 보다 ${q.A > 0 ? "위" : "아래"}인 y = ${c} 와 두 점에서 만난다.`, "Two intersections happen when the line is past the vertex."]] }; },
  oneSol(rng) { const q = base(rng); return { tag: "one_solution", clause: rng.pick([`touches the horizontal line $y = ${q.K}$ at exactly one point and opens ${UP(q.A)}`, `opens ${UP(q.A)} and is tangent to the line $y = ${q.K}$`]), P: { k: q.K, up: q.A > 0 ? 1 : 0 }, A: "s.K === P.k", Bj: "(s.A > 0 ? 1 : 0) === P.up", rules: ["tangent_off", "opening_off", "both_off"], ok: q, trace: [[`한 점에서만 만나려면 y = ${q.K} 가 꼭짓점의 높이여야 한다.`, "A single intersection occurs at the vertex height."]] }; },
};

const OPS: OperatorId[] = ["repr_shift", "chain2", "compose_kind", "inverse"];
const STEMS = ["Four graphs of parabolas are shown in the $xy$-plane, all with the same axes.", "The four graphs shown are parabolas drawn on identical $xy$-plane axes.", "Each of the four graphs shown is a parabola in the same $xy$-plane.", "Four candidate parabolas are shown, graphed on one set of axes.", "The choices shown are four parabola graphs that share the same axes.", "Four quadratic graphs share one grid and are shown as choices."];
const QS = (c: string) => [`Which of the four graphs shown is a parabola that ${c}?`, `Which graph shown is the graph of a parabola that ${c}?`, `Exactly one of the four parabolas shown ${c}. Which one is it?`, `Of the graphs shown, which parabola ${c}?`, `Which parabola among the choices shown ${c}?`];
type Spec = { itemId: string; prefix: string; menu: [string, string, string, string]; easy: string; med: string; what: string; concepts: string[] };

function make(rng: Rng, key: string) { const b = QBUILD[key](rng); const c = twoCond(QSTAT, b.A, b.Bj, b.rules); const ok = parabolaOk(b.ok.R, b.ok.A, b.ok.H, b.ok.K); const ch = poolChoices(rng, { ok, pool: parabolaPool(b.ok.R), P: b.P, ...c }); return { ch, b, c }; }
export function quadCItem(spec: Spec) {
  const hard = spec.menu.map((key, i) => ({ op: OPS[i], sprNo: SPR_NO_PLANE_CHOICE, structure: `포물선 조건(${key}) 두 개를 서술로 주고 두 조건을 모두 만족하는 포물선 그래프를 4개 중에서 고름`, extra: "두 조건을 각각 따져 네 그래프를 대조해야 함(조건 하나만 맞는 그래프가 함정) — medium 은 직접 대조", concepts: spec.concepts,
    gen(rng: Rng) { const { ch, b, c } = make(rng, key); return cInst(rng, ch, { stimulus: `${rng.pick(C_LEADS)}${rng.pick(STEMS)}`, question: rng.pick(QS(b.clause)), P: b.P, ...c, variant: `${spec.what}_${b.tag}`, trace: [...b.trace, ["각 그래프에서 꼭짓점·열린 방향·지나는 점을 읽는다.", "Read the vertex, opening direction, and points of each graph."], ["첫째 조건을 어긴 그래프를 지운다.", "Eliminate the graphs that fail the first condition."], ["둘째 조건을 어긴 그래프를 지운다.", "Eliminate the graphs that fail the second condition."], ["남은 그래프가 정답이다.", "The remaining graph is the answer."]] }, ["다른 그래프는 조건 하나 이상이 어긋난다.", "Each other graph violates at least one condition."]); } }));
  const em = [{ lv: "easy" as const, key: spec.easy }, { lv: "medium" as const, key: spec.med }].map(({ lv, key }) => ({ lv, name: `${lv}_${key}`, sprNo: SPR_NO_PLANE_CHOICE, structure: `포물선 조건(${key})으로 그래프 4개 중 고름`, extra: lv === "easy" ? "easy: 한 조건" : "medium: 두 조건", concepts: spec.concepts,
    gen(rng: Rng) { if (lv === "easy") { const q = base(rng); const P = { h: q.H }; const c = oneCond(QSTAT, "s.H", "P.h", "2"); const ch = poolChoices(rng, { ok: parabolaOk(q.R, q.A, q.H, q.K), pool: parabolaPool(q.R), P, ...c }); return cInst(rng, ch, { stimulus: `${rng.pick(C_LEADS)}${rng.pick(STEMS)}`, question: rng.pick([`Which of the four graphs shown is a parabola whose vertex has $x$-coordinate ${q.H}?`, `Which parabola shown has its axis of symmetry at $x = ${q.H}$?`, `Of the graphs shown, which parabola has its vertex directly over or under $x = ${q.H}$?`, `Exactly one of the four parabolas shown has its vertex at $x = ${q.H}$. Which one is it?`, `Which parabola among the choices shown is symmetric about the line $x = ${q.H}$?`, `The vertex of one of the four parabolas shown has $x$-coordinate ${q.H}. Which graph is it?`, `Which of the following parabolas shown has $x = ${q.H}$ as its axis of symmetry?`, `Which choice shown is a parabola that turns around at $x = ${q.H}$?`]), P, ...c, variant: `${spec.what}_axis_only`, trace: [[`꼭짓점의 x 좌표가 ${q.H} 인 포물선을 찾는다.`, "Find the parabola whose vertex has the given x-coordinate."], ["나머지 그래프는 대칭축이 달라 지운다.", "Eliminate the other axes."]] }, ["대칭축이 다른 그래프는 정답이 아니다.", "Other axes are wrong."]); }
      const { ch, b, c } = make(rng, key); return cInst(rng, ch, { stimulus: `${rng.pick(C_LEADS)}${rng.pick(STEMS)}`, question: rng.pick([...QS(b.clause), `Which graph shown matches a parabola that ${b.clause}?`, `Select the parabola shown that ${b.clause}.`, `One of the four parabolas shown ${b.clause}. Which graph is it?`]), P: b.P, ...c, variant: `${spec.what}_${b.tag}_med`, trace: [...b.trace, ["조건을 어긴 그래프를 지운다.", "Eliminate the graphs that fail a condition."], ["남은 그래프가 정답이다.", "The remaining graph is the answer."]] }, ["다른 그래프는 조건 하나 이상이 어긋난다.", "Each other graph violates at least one condition."]); } }));
  return defineItem({ prefix: spec.prefix, itemId: spec.itemId, hard, em });
}
