// 도수다각형·누적도수곡선(FO) 공용 장면 키트 — one_variable_data.{mean,median,grouped_median_interval,quartile_percentile_from_plot,relative_cumulative_frequency}.FO.P.
// 규칙(자료 계열 공통): 수치를 먼저 뽑고 → figure(freq_chart)를 만들고 → 지문은 값을 되풀이하지 않고 "the graph shown" 으로 가리킨다. 정보는 자료에만 있다.
// 모든 도수는 u(= N/10 = 2·4·5) 의 배수라서 점이 세로 눈금선 위에 놓이고(정확히 읽힌다) 누적 상대도수는 10% 단위로 떨어진다.
import { GenFail, type Instance } from "../../types";
import type { Rng } from "../../rng";
import { fmtNum } from "../../text";
import { W } from "../d-kit";
import { figJs } from "../../figure-kit";
import { defineItem } from "./item-kit";
import { gInst } from "./graph-kit";
import { renderFreqChart, type FreqChartSpec } from "@/lib/problem-figures/templates/freq-chart";

const f = fmtNum;
export type FoTopic = { what: string; ent: string; where: string; unit: string; xName: string; lo0: number[]; w: number[] };
export const FO_TOPICS: FoTopic[] = [
  { what: "scores on a math test", ent: "students", where: "in a class", unit: "points", xName: "Test score", lo0: [20, 30, 40, 50], w: [10] },
  { what: "times to finish a race", ent: "runners", where: "in a city race", unit: "minutes", xName: "Finish time", lo0: [20, 30, 40], w: [5, 10] },
  { what: "weights of packages", ent: "packages", where: "at a shipping center", unit: "pounds", xName: "Package weight", lo0: [0, 10, 20], w: [5, 10] },
  { what: "daily numbers of visitors", ent: "days", where: "at a museum", unit: "visitors", xName: "Daily visitors", lo0: [100, 200, 300], w: [50, 100] },
  { what: "heights of plants", ent: "plants", where: "in a greenhouse", unit: "centimeters", xName: "Plant height", lo0: [10, 20, 30], w: [5, 10] },
  { what: "lengths of phone calls", ent: "calls", where: "at a help desk", unit: "minutes", xName: "Call length", lo0: [0, 5, 10], w: [5, 10] },
  { what: "waiting times for appointments", ent: "patients", where: "at a clinic", unit: "minutes", xName: "Waiting time", lo0: [0, 10, 20], w: [10, 20] },
  { what: "distances jumped in a contest", ent: "athletes", where: "in a school meet", unit: "inches", xName: "Jump distance", lo0: [60, 80, 100], w: [10, 20] },
  { what: "battery lives", ent: "phones", where: "in a product test", unit: "hours", xName: "Battery life", lo0: [10, 20, 30], w: [5, 10] },
  { what: "monthly electricity bills", ent: "households", where: "in a neighborhood", unit: "dollars", xName: "Monthly bill", lo0: [40, 60, 80], w: [20] },
];
export type FoScene = { t: FoTopic; bins: { from: number; to: number; count: number }[]; N: number; u: number; w: number; cum: number[]; mids: number[]; fig: FreqChartSpec; kind: "polygon" | "ogive"; percent: boolean };
const partitions = (rng: Rng, k: number): number[] => { for (let t = 0; t < 200; t++) { const c = Array.from({ length: k }, () => 1); let left = 10 - k; while (left > 0) { c[rng.int(0, k - 1)]++; left--; } if (Math.max(...c) <= 5) return c; } throw new GenFail("분할"); };
export type FoOpts = { kind: "polygon" | "ogive"; percent?: boolean; k?: number; distinctMax?: boolean };
export function makeFO(rng: Rng, o: FoOpts): FoScene {
  const t = rng.pick(FO_TOPICS); const w = rng.pick(t.w); const k = o.k ?? rng.int(5, 6); const lo = rng.pick(t.lo0); const u = rng.pick([2, 4, 5]);
  const parts = partitions(rng, k); if (o.distinctMax && parts.filter((c) => c === Math.max(...parts)).length > 1) throw new GenFail("최빈 계급 중복");
  const bins = parts.map((c, i) => ({ from: lo + i * w, to: lo + (i + 1) * w, count: c * u })); const N = 10 * u; let acc = 0; const cum = bins.map((b) => (acc += b.count)); const mids = bins.map((b) => (b.from + b.to) / 2);
  const percent = !!o.percent; const xTitle = `${t.xName} (${t.unit})`; const base = { type: "freq_chart" as const, kind: o.kind, bins, xTitle };
  const fig: FreqChartSpec = o.kind === "polygon" ? { ...base, yTitle: `Frequency (${t.ent})`, yStep: u, yMax: (Math.max(...parts) + 1) * u } : percent ? { ...base, percent: true, yTitle: "Cumulative percent (%)", yStep: 10, yMax: 100 } : { ...base, yTitle: `Cumulative frequency (${t.ent})`, yStep: u, yMax: N };
  if (renderFreqChart(fig).issues.length) throw new GenFail("도수다각형 배치");
  return { t, bins, N, u, w, cum, mids, fig, kind: o.kind, percent };
}
export const FO_JS = "const B=FIGURE.bins; const N=B.reduce((a,b)=>a+b.count,0); const w=B[0].to-B[0].from; const mids=B.map(b=>(b.from+b.to)/2); let ac=0; const cum=B.map(b=>(ac+=b.count)); const rel=cum.map(c=>c*100/N); const r6=(x)=>Math.round(x*1e6)/1e6; const cnt=B.map(b=>b.count); const medIdx=(extra,pos)=>{ const n=N+(extra||0); const p=pos===undefined?(n+1)/2:pos; for(let i=0;i<B.length;i++){ if(p<=cum[i]+(extra||0)) return i; } return B.length-1; };\n";
export const LEADS = [
  "Use the information in the graph to answer the question.", "Refer to the graph when answering the question that follows.", "Answer the question using only the data in the graph.", "Study the graph carefully before answering.",
  "The graph contains all of the data needed for this question.", "Consider the data displayed in the graph.", "Examine the graph and then answer the question below.", "Base your answer on the data the graph displays.",
  "Every value in the data set belongs to exactly one class.", "The classes are all the same width.", "Read the labels on both axes before you begin.", "Note which quantity each axis shows.",
];
const KIND_NAME = { polygon: "frequency polygon", ogive: "cumulative frequency graph" } as const;
export const foIntro = (rng: Rng, s: FoScene) => { const g = s.kind === "ogive" && s.percent ? "cumulative percent graph" : KIND_NAME[s.kind]; return rng.pick([
  `The ${g} shown summarizes the ${s.t.what} for ${s.t.ent} ${s.t.where}. The data are grouped into classes of width ${s.w}.`,
  `A ${g} is shown for the ${s.t.what} of ${s.t.ent} ${s.t.where}, with every class ${s.w} ${s.t.unit} wide.`,
  `The ${s.t.what} for a group of ${s.t.ent} ${s.t.where} are grouped into classes ${s.w} ${s.t.unit} wide and displayed in the ${g} shown.`,
  `In the ${g} shown, the ${s.t.what} for ${s.t.ent} ${s.t.where} are organized into equal classes of width ${s.w}.`,
]); };
export const foRead = (s: FoScene): [string, string] => [s.kind === "polygon" ? `도수다각형에서 계급별 도수를 읽는다: ${s.bins.map((b) => `${b.from}~${b.to}: ${b.count}`).join(", ")} — 전체 ${s.N}.` : s.percent ? `누적 상대도수 그래프에서 각 경계의 누적 %를 읽는다: ${s.bins.map((b, i) => `${b.to}: ${s.cum[i] * 10 / s.u}%`).join(", ")}.` : `누적도수 그래프에서 각 경계의 누적 도수를 읽는다: ${s.bins.map((b, i) => `${b.to}: ${s.cum[i]}`).join(", ")}.`, "Read the values from the graph."];
const pos = (ws: ReturnType<typeof W>[]) => ws.filter((w) => w.v >= 0);
type D = { stim?: string; question: string | string[]; correct: number; wrongs: ReturnType<typeof W>[]; js: string; P?: Record<string, number | string>; trace: [string, string][]; variant: string; min?: number };
const tr5 = (t: [string, string][], ans: string, min: number): [string, string][] => { const o: [string, string][] = [...t, [`따라서 답은 ${ans} 이다.`, "That is the requested value."]]; while (o.length < min) o.splice(o.length - 1, 0, ["결과를 그래프와 다시 대조해 확인한다.", "Check the result against the graph."]); return o; };
export const FD = (rng: Rng, s: FoScene, d: D): Instance => gInst(rng, { stimulus: `${foIntro(rng, s)}${d.stim ? ` ${d.stim}` : ""} ${rng.pick(LEADS)}`, question: Array.isArray(d.question) ? rng.pick(d.question) : d.question, correct: d.correct, wrongs: pos(d.wrongs).filter((w) => Math.abs(w.v - d.correct) > 1e-9), verificationJs: figJs(d.P ?? {}, s.fig, `${FO_JS}${d.js}`), trace: tr5(d.trace, f(d.correct), d.min ?? 5), variant: d.variant }, s.fig);
const medI = (s: FoScene, extraLow = 0) => { const n = s.N + extraLow; const p = (n + 1) / 2; const cum = s.cum.map((c) => c + extraLow); for (let i = 0; i < cum.length; i++) if (p <= cum[i]) return i; return cum.length - 1; };
const cntOf = (s: FoScene, i: number) => s.bins[i].count;
const meanEst = (s: FoScene) => s.bins.reduce((a, b, i) => a + s.mids[i] * b.count, 0) / s.N;
const midOf = (s: FoScene, i: number) => s.mids[i];

// ───────────────────────── mean.FO.P (도수다각형) ─────────────────────────
export const meanItem = () => defineItem({
  prefix: "ovd", itemId: "one_variable_data.mean.FO.P",
  hard: [
    { op: "chain2", structure: "도수다각형에서 위쪽 세 계급만의 평균을 계급값(가운데 값)으로 추정", extra: "계급값 → 가중 합 → 부분 개수로 나누기의 연쇄 — medium 은 전체 평균", concepts: ["도수다각형", "계급값", "집단 자료의 평균"],
      gen(rng) { for (let tr = 0; tr < 80; tr++) { const s = makeFO(rng, { kind: "polygon" }); const top = s.bins.slice(-3); const n = top.reduce((a, b) => a + b.count, 0); const m = top.reduce((a, b, i) => a + s.mids[s.bins.length - 3 + i] * b.count, 0) / n; if (!Number.isInteger(Math.round(m * 100) / 10)) continue;
        return FD(rng, s, { question: [`Using the midpoint of each class, what is the estimated mean of the ${s.t.what} for the three highest classes combined?`, `Estimate the mean of the values in the three highest classes, using class midpoints.`], correct: m, wrongs: [W(meanEst(s), "scope", "전체 평균을 답했다."), W(top.reduce((a, b, i) => a + s.mids[s.bins.length - 3 + i], 0) / 3, "formula_misuse", "도수를 무시하고 계급값만 평균 냈다."), W(top.reduce((a, b, i) => a + s.mids[s.bins.length - 3 + i] * b.count, 0), "step_missing", "합을 개수로 나누지 않았다."), W(top.reduce((a, b) => a + b.to * b.count, 0) / n, "axis_misread", "상한을 계급값으로 썼다."), W(m + s.w / 2, "other", "계산 중 어긋났다.")], js: `const k=B.length; let S=0,n=0; for(let i=k-3;i<k;i++){ S+=mids[i]*cnt[i]; n+=cnt[i]; } return r6(S/n);`, trace: [foRead(s), [`위쪽 세 계급: ${top.map((b, i) => `${s.mids[s.bins.length - 3 + i]}(도수 ${b.count})`).join(", ")} 이다.`, "Take the three highest classes."], [`가중 합 = ${top.reduce((a, b, i) => a + s.mids[s.bins.length - 3 + i] * b.count, 0)} 이다.`, "Weight each midpoint by its frequency."], [`개수 = ${n} 이다.`, "Count them."], [`평균 = ${f(m)} 이다.`, "Divide."]], variant: "mean_of_top_classes" }); } throw new GenFail("top mean"); } },
    { op: "inverse", structure: "m 개의 값이 같은 계급에 더해져 추정 평균이 M 이 될 때 그 계급의 계급값을 역으로 구함", extra: "가중 합을 구하고 새 평균 조건에서 계급값을 거꾸로 풀어야 함 — medium 은 추정 평균", concepts: ["도수다각형", "계급값", "평균의 역산"],
      gen(rng) { for (let t = 0; t < 120; t++) { const s = makeFO(rng, { kind: "polygon" }); const j = rng.int(0, s.bins.length - 1); const m = rng.pick([s.u, 2 * s.u, 3 * s.u]); const S = s.bins.reduce((a, b, i) => a + s.mids[i] * b.count, 0); const M = (S + m * s.mids[j]) / (s.N + m); if (!Number.isInteger(M * 2) || M === s.mids[j]) continue;
        return FD(rng, s, { stim: `${m} more values are added, and all of them fall in a single class. Using class midpoints, the estimated mean of all the values is then ${f(M)} ${s.t.unit}.`, question: [`What is the midpoint, in ${s.t.unit}, of the class that received the new values?`, `Which class midpoint, in ${s.t.unit}, do the ${m} new values have?`], correct: s.mids[j], wrongs: [W(M, "step_missing", "새 평균을 답했다."), W(Math.round(meanEst(s)), "step_missing", "원래 평균을 답했다."), W(s.mids[j] + s.w, "other", "한 계급 어긋났다."), W(s.mids[j] - s.w, "other", "한 계급 어긋났다."), W(M * (s.N + m) - S, "formula_misuse", "새 합의 차를 m 으로 나누지 않았다.")], P: { m, M }, js: `let S=0; for(let i=0;i<B.length;i++) S+=mids[i]*cnt[i]; const x=(P.M*(N+P.m)-S)/P.m; if(!mids.includes(x)) throw new Error('계급값이 아님'); return x;`, trace: [foRead(s), [`계급값 × 도수의 합 = ${S} 이다.`, "Weighted sum of midpoints."], [`새 개수 = ${s.N} + ${m} = ${s.N + m}, 새 합 = ${f(M)} × ${s.N + m} = ${f(M * (s.N + m))} 이다.`, "New total and count."], [`더해진 합 = ${f(M * (s.N + m))} - ${S} = ${f(m * s.mids[j])} 이다.`, "Sum added."], [`계급값 = ${f(m * s.mids[j])} ÷ ${m} = ${s.mids[j]} 이다.`, "Divide by the number of new values."]], variant: "added_class_midpoint" }); } throw new GenFail("inverse"); } },
    { op: "compare_scenarios", structure: "가장 낮은 계급의 값이 모두 가장 높은 계급으로 옮겨질 때 추정 평균이 얼마나 늘어나는지 구함", extra: "이동한 개수 × 계급값의 차 ÷ 전체로 변화량을 직접 구해야 함 — medium 은 추정 평균", concepts: ["도수다각형", "계급값", "평균의 변화"],
      gen(rng) { const s = makeFO(rng, { kind: "polygon" }); const k = s.bins.length; const c = (cntOf(s, 0) * (midOf(s, k - 1) - midOf(s, 0))) / s.N;
        return FD(rng, s, { stim: "Suppose every value in the lowest class is moved to the highest class.", question: ["By how much does the estimated mean (using class midpoints) increase?", `By how many ${s.t.unit} does the estimated mean increase?`], correct: c, wrongs: [W(midOf(s, k - 1) - midOf(s, 0), "step_missing", "계급값의 차를 답했다."), W(cntOf(s, 0) * (midOf(s, k - 1) - midOf(s, 0)), "step_missing", "전체로 나누지 않았다."), W((cntOf(s, 0) * (midOf(s, k - 1) - midOf(s, 0))) / (s.N - cntOf(s, 0)), "formula_misuse", "옮긴 뒤가 아닌 다른 개수로 나눴다."), W(c + s.w / 2, "other", "계산 중 어긋났다."), W(meanEst(s), "scope", "추정 평균을 답했다.")], js: `return r6(cnt[0]*(mids[B.length-1]-mids[0])/N);`, trace: [foRead(s), [`가장 낮은 계급의 도수 = ${cntOf(s, 0)} 이다.`, "Frequency of the lowest class."], [`계급값의 차 = ${midOf(s, k - 1)} - ${midOf(s, 0)} = ${midOf(s, k - 1) - midOf(s, 0)} 이다.`, "Distance each value moves."], [`합의 증가 = ${cntOf(s, 0)} × ${midOf(s, k - 1) - midOf(s, 0)} 이다.`, "Increase of the sum."], [`평균의 증가 = ÷ ${s.N} = ${f(c)} 이다.`, "Divide by the number of values."]], variant: "mean_change_after_moving_class" }); } },
    { op: "param_condition", structure: "가장 높은 계급에 값을 더해 추정 평균이 M 이상이 되도록 하는 최소 개수를 구함", extra: "목표 평균 조건을 부등식으로 세우고 정수로 올림해야 함 — medium 은 추정 평균", concepts: ["도수다각형", "계급값", "부등식과 정수"],
      gen(rng) { for (let t = 0; t < 120; t++) { const s = makeFO(rng, { kind: "polygon" }); const k = s.bins.length; const S = s.bins.reduce((a, b, i) => a + s.mids[i] * b.count, 0); const x = midOf(s, k - 1); const M0 = Math.ceil(meanEst(s)); const M = M0 + rng.int(1, Math.max(1, Math.floor(s.w / 2))); if (M >= x) continue; const need = (M * s.N - S) / (x - M); if (need <= 0 || Number.isInteger(need)) continue; const ans = Math.ceil(need); if (ans > 99) continue;
        return FD(rng, s, { stim: "More values are added, all in the highest class.", question: [`What is the least number of new values needed so that the estimated mean (using class midpoints) is at least ${M} ${s.t.unit}?`, `At least how many values must be added to the highest class for the estimated mean to reach ${M} ${s.t.unit}?`], correct: ans, wrongs: [W(ans - 1, "condition_ignored", "올림 대신 내림했다."), W(Math.round((M * s.N - S) / x), "formula_misuse", "새 값의 합이 아니라 목표 합으로 나눴다."), W(Math.ceil((M * s.N - S) / (x - M + 1)), "formula_misuse", "계산 중 어긋났다."), W(ans + 1, "other", "하나 더 올렸다."), W(Math.round(need), "condition_ignored", "반올림했다.")], P: { M }, js: `let S=0; for(let i=0;i<B.length;i++) S+=mids[i]*cnt[i]; const x=mids[B.length-1]; return Math.ceil((P.M*N-S)/(x-P.M));`, trace: [foRead(s), [`가중 합 = ${S}, 전체 = ${s.N} 이고 가장 높은 계급값은 ${x} 이다.`, "Weighted sum, count, and the highest midpoint."], [`(${S} + ${x}n) ÷ (${s.N} + n) ≥ ${M} 로 둔다.`, "Set up the inequality."], [`${x - M}n ≥ ${M * s.N - S} 이므로 n ≥ ${f(Math.round(need * 100) / 100)} 이다.`, "Solve for n."], [`가장 작은 정수는 ${ans} 이다.`, "Round up."]], variant: "values_needed_for_target_mean" }); } throw new GenFail("param"); } },
  ],
  em: [
    { lv: "easy", name: "total_count", structure: "도수다각형의 모든 도수를 더해 전체 개수를 구함", extra: "easy: 도수 합", concepts: ["도수다각형", "전체 개수"],
      gen(rng) { const s = makeFO(rng, { kind: "polygon" }); return FD(rng, s, { question: `How many ${s.t.ent} are represented in the graph?`, correct: s.N, wrongs: [W(s.bins.length, "axis_misread", "계급의 수를 답했다."), W(Math.max(...s.bins.map((b) => b.count)), "step_missing", "가장 높은 점만 읽었다."), W(s.N - s.bins[0].count, "step_missing", "첫 계급을 빠뜨렸다."), W(s.N + s.u, "other", "계산 중 어긋났다.")], js: `return N;`, trace: [foRead(s), [`${s.bins.map((b) => b.count).join(" + ")} = ${s.N} 이다.`, "Add the frequencies."]], variant: "total_from_polygon", min: 2 }); } },
    { lv: "medium", name: "estimated_mean", structure: "계급값과 도수로 평균을 추정", extra: "medium: 가중 평균", concepts: ["도수다각형", "계급값", "추정 평균"],
      gen(rng) { const s = makeFO(rng, { kind: "polygon" }); const m = meanEst(s); return FD(rng, s, { question: ["Using the midpoint of each class, what is the estimated mean?", `What is the estimated mean of the ${s.t.what}, using class midpoints?`], correct: m, wrongs: [W(s.mids.reduce((a, b) => a + b, 0) / s.mids.length, "formula_misuse", "도수를 무시하고 계급값만 평균 냈다."), W(s.bins.reduce((a, b, i) => a + s.mids[i] * b.count, 0), "step_missing", "합을 개수로 나누지 않았다."), W(s.bins.reduce((a, b) => a + b.from * b.count, 0) / s.N, "axis_misread", "하한을 계급값으로 썼다."), W(m + s.w / 2, "other", "계산 중 어긋났다.")], js: `let S=0; for(let i=0;i<B.length;i++) S+=mids[i]*cnt[i]; return r6(S/N);`, trace: [foRead(s), [`계급값 = ${s.mids.join(", ")} 이다.`, "Midpoints."], [`가중 합 = ${s.bins.reduce((a, b, i) => a + s.mids[i] * b.count, 0)} 이다.`, "Weighted sum."], [`평균 = ÷ ${s.N} = ${f(m)} 이다.`, "Divide."]], variant: "estimated_mean_polygon", min: 3 }); } },
  ],
});

// ───────────────────────── median.FO.P (누적도수곡선) ─────────────────────────
export const medianItem = () => defineItem({
  prefix: "ovd", itemId: "one_variable_data.median.FO.P",
  hard: [
    { op: "chain2", structure: "누적도수곡선에서 중앙값이 속한 계급을 찾고 그 계급의 도수를 구함", extra: "누적 도수의 차로 계급 도수를 구하는 2 단계 — medium 은 중앙값 계급의 하한", concepts: ["누적도수곡선", "중앙값이 속한 계급", "계급 도수"],
      gen(rng) { const s = makeFO(rng, { kind: "ogive" }); const j = medI(s); const c = cntOf(s, j);
        return FD(rng, s, { question: ["How many of the values are in the class that contains the median?", "How many values lie in the median class?"], correct: c, wrongs: [W(s.cum[j], "step_missing", "누적 도수를 답했다."), W(s.N / 2, "step_missing", "전체의 절반을 답했다."), W(cntOf(s, Math.min(j + 1, s.bins.length - 1)) === c ? c + s.u : cntOf(s, Math.min(j + 1, s.bins.length - 1)), "axis_misread", "다음 계급의 도수를 답했다."), W(j > 0 ? s.cum[j - 1] : s.u, "axis_misread", "앞 계급까지의 누적을 답했다."), W(c + s.u, "other", "계산 중 어긋났다.")], js: `const j=medIdx(0); return j===0?cum[0]:cum[j]-cum[j-1];`, trace: [foRead(s), [`전체 ${s.N} 개이므로 중앙값은 ${(s.N + 1) / 2} 번째 값 근처이다.`, "Locate the middle position."], [`누적 도수가 처음 ${(s.N + 1) / 2} 이상이 되는 계급은 ${s.bins[j].from}~${s.bins[j].to} 이다.`, "Find the first class whose cumulative frequency reaches the middle."], [`그 계급의 도수 = ${s.cum[j]}${j > 0 ? ` - ${s.cum[j - 1]}` : ""} = ${c} 이다.`, "Difference of cumulative frequencies."]], variant: "median_class_frequency" }); } },
    { op: "compare_scenarios", structure: "두 계급의 도수(누적도수의 차)를 각각 구해 그 차를 구함", extra: "곡선의 두 구간에서 각각 증가량을 읽어 비교 — medium 은 한 계급", concepts: ["누적도수곡선", "계급 도수", "두 계급 비교"],
      gen(rng) { const s = makeFO(rng, { kind: "ogive" }); const [i, j] = rng.shuffle([...s.bins.keys()]).slice(0, 2); const d = Math.abs(cntOf(s, i) - cntOf(s, j)); if (d === 0) throw new GenFail("eq"); const hi = cntOf(s, i) > cntOf(s, j) ? i : j, lo = hi === i ? j : i;
        return FD(rng, s, { question: `How many more values are in the class ${s.bins[hi].from}–${s.bins[hi].to} than in the class ${s.bins[lo].from}–${s.bins[lo].to}?`, correct: d, wrongs: [W(cntOf(s, hi), "step_missing", "한 계급의 도수만 답했다."), W(Math.abs(s.cum[hi] - s.cum[lo]), "axis_misread", "누적 도수의 차를 답했다."), W(cntOf(s, hi) + cntOf(s, lo), "sign_error", "합을 구했다."), W(d + s.u, "other", "계산 중 어긋났다."), W(Math.abs(hi - lo) * s.u, "other", "계급 수의 차를 썼다.")], P: { a: s.bins[hi].from, b: s.bins[lo].from }, js: `const ia=B.findIndex(x=>x.from===P.a), ib=B.findIndex(x=>x.from===P.b); const c=(i)=>i===0?cum[0]:cum[i]-cum[i-1]; return Math.abs(c(ia)-c(ib));`, trace: [foRead(s), [`${s.bins[hi].from}~${s.bins[hi].to}: ${s.cum[hi]}${hi > 0 ? ` - ${s.cum[hi - 1]}` : ""} = ${cntOf(s, hi)} 이다.`, "Frequency of the first class."], [`${s.bins[lo].from}~${s.bins[lo].to}: ${s.cum[lo]}${lo > 0 ? ` - ${s.cum[lo - 1]}` : ""} = ${cntOf(s, lo)} 이다.`, "Frequency of the second class."], [`차 = ${d} 이다.`, "Positive difference."]], variant: "class_frequency_difference" }); } },
    { op: "param_condition", structure: "가장 낮은 계급에 값을 더해도 중앙값이 같은 계급에 남도록 하는 최대 개수를 구함", extra: "중앙값 위치와 누적 도수의 부등식을 세워 정수 최댓값을 구함 — medium 은 중앙값 계급", concepts: ["누적도수곡선", "중앙값 위치", "부등식과 정수"],
      gen(rng) { for (let t = 0; t < 80; t++) { const s = makeFO(rng, { kind: "ogive" }); const j = medI(s); if (j === 0) continue; const ans = s.N - 2 * s.cum[j - 1]; if (ans < 1 || ans > 40) continue;
        return FD(rng, s, { stim: "More values are added to the lowest class only.", question: ["What is the greatest number of values that can be added so that the median is still in the same class as before?", "At most how many values can be added to the lowest class without moving the median out of its current class?"], correct: ans, wrongs: [W(ans + 1, "condition_ignored", "경계를 포함했다."), W(ans - 1, "other", "1 어긋났다."), W(s.N - s.cum[j - 1], "formula_misuse", "새 값이 전체도 늘리는 것을 무시했다."), W(s.cum[j] - s.cum[j - 1], "scope", "중앙값 계급의 도수를 답했다."), W(Math.floor(ans / 2), "formula_misuse", "절반으로 나눴다.")], js: `const j=medIdx(0); if(j===0) throw new Error('첫 계급'); let t=0; while(medIdx(t+1,(N+t+1+1)/2)===j && t<500) t++; return t;`, trace: [foRead(s), [`중앙값 계급은 ${s.bins[j].from}~${s.bins[j].to} 이고 그 앞 계급까지의 누적은 ${s.cum[j - 1]} 이다.`, "The median class and the cumulative count before it."], [`t 개를 더하면 중앙값 위치는 (${s.N} + t + 1) ÷ 2 이고 앞 누적은 ${s.cum[j - 1]} + t 이다.`, "Both the position and the count below grow."], [`같은 계급에 남으려면 ${s.cum[j - 1]} + t < (${s.N} + t + 1) ÷ 2 이어야 한다.`, "The median position must stay above the count below the class."], [`t ≤ ${s.N} - 2 × ${s.cum[j - 1]} = ${ans} 이다.`, "Solve for t."]], variant: "values_addable_median_stays" }); } throw new GenFail("param"); } },
    { op: "compose_kind", structure: "중앙값이 속한 계급을 찾아 그 계급의 계급값(가운데 값)을 구함", extra: "누적도수로 계급을 찾은 뒤 하한과 상한의 평균을 구함 — medium 은 하한", concepts: ["누적도수곡선", "중앙값이 속한 계급", "계급값"],
      gen(rng) { const s = makeFO(rng, { kind: "ogive" }); const j = medI(s); const mdv = midOf(s, j);
        return FD(rng, s, { question: ["What is the midpoint of the class that contains the median?", `What is the midpoint, in ${s.t.unit}, of the median class?`], correct: mdv, wrongs: [W(s.bins[j].from, "axis_misread", "하한을 답했다."), W(s.bins[j].to, "axis_misread", "상한을 답했다."), W(midOf(s, Math.min(j + 1, s.bins.length - 1)) === mdv ? mdv + s.w : midOf(s, Math.min(j + 1, s.bins.length - 1)), "other", "다음 계급을 골랐다."), W(j > 0 ? midOf(s, j - 1) : mdv - s.w, "other", "앞 계급을 골랐다."), W(Math.round(meanEst(s)), "scope", "평균을 답했다.")], js: `const j=medIdx(0); return mids[j];`, trace: [foRead(s), [`중앙값은 ${(s.N + 1) / 2} 번째 값 근처이다.`, "Middle position."], [`누적 도수가 처음 그 이상이 되는 계급은 ${s.bins[j].from}~${s.bins[j].to} 이다.`, "Find the median class."], [`계급값 = (${s.bins[j].from} + ${s.bins[j].to}) ÷ 2 = ${mdv} 이다.`, "Midpoint."]], variant: "median_class_midpoint" }); } },
  ],
  em: [
    { lv: "easy", name: "total", structure: "누적도수곡선의 마지막 점에서 전체 개수를 읽음", extra: "easy: 마지막 누적 도수", concepts: ["누적도수곡선", "전체 개수"],
      gen(rng) { const s = makeFO(rng, { kind: "ogive" }); return FD(rng, s, { question: `How many ${s.t.ent} are represented in the graph?`, correct: s.N, wrongs: [W(s.cum[0], "axis_misread", "첫 점을 읽었다."), W(s.bins.length, "axis_misread", "계급의 수를 답했다."), W(s.N - s.u, "other", "하나 아래 눈금을 읽었다."), W(s.N + s.u, "other", "하나 위 눈금을 읽었다.")], js: `return N;`, trace: [foRead(s), [`마지막 점의 누적 도수가 전체 ${s.N} 이다.`, "The last point is the total."]], variant: "total_from_ogive", min: 2 }); } },
    { lv: "medium", name: "median_class_lower", structure: "누적도수곡선에서 중앙값이 속한 계급의 하한을 구함", extra: "medium: 중앙값 위치 → 계급", concepts: ["누적도수곡선", "중앙값이 속한 계급"],
      gen(rng) { const s = makeFO(rng, { kind: "ogive" }); const j = medI(s); return FD(rng, s, { question: "What is the lower limit of the class that contains the median?", correct: s.bins[j].from, wrongs: [W(s.bins[j].to, "axis_misread", "상한을 답했다."), W(s.bins[Math.max(0, j - 1)].from === s.bins[j].from ? s.bins[j].from + s.w : s.bins[Math.max(0, j - 1)].from, "other", "앞 계급을 골랐다."), W(s.bins[Math.min(s.bins.length - 1, j + 1)].from === s.bins[j].from ? s.bins[j].from - s.w : s.bins[Math.min(s.bins.length - 1, j + 1)].from, "other", "다음 계급을 골랐다."), W(Math.round(s.N / 2), "scope", "위치를 답했다.")], js: `return B[medIdx(0)].from;`, trace: [foRead(s), [`중앙값 위치는 ${(s.N + 1) / 2} 번째 부근이다.`, "Middle position."], [`누적 도수가 처음 그 이상인 계급: ${s.bins[j].from}~${s.bins[j].to} 이다.`, "Find the class."]], variant: "median_class_lower_limit", min: 3 }); } },
  ],
});

// ───────────────────────── grouped_median_interval.FO.P (도수다각형) ─────────────────────────
export const groupedMedianItem = () => defineItem({
  prefix: "ovd", itemId: "one_variable_data.grouped_median_interval.FO.P",
  hard: [
    { op: "chain2", structure: "도수다각형의 도수를 누적해 중앙값이 속한 계급의 하한을 구함", extra: "도수를 차례로 누적하고 중앙값 위치와 비교 — medium 은 위치가 주어진 경우", concepts: ["도수다각형", "누적 도수", "중앙값이 속한 계급"],
      gen(rng) { const s = makeFO(rng, { kind: "polygon" }); const j = medI(s);
        return FD(rng, s, { question: ["What is the lower limit of the class that contains the median?", `In which class does the median lie? Give the lower limit of that class, in ${s.t.unit}.`], correct: s.bins[j].from, wrongs: [W(s.bins[j].to, "axis_misread", "상한을 답했다."), W(s.bins[Math.min(s.bins.length - 1, medI({ ...s, N: s.N } as FoScene) + 1)].from === s.bins[j].from ? s.bins[j].from - s.w : s.bins[Math.min(s.bins.length - 1, j + 1)].from, "other", "다음 계급을 골랐다."), W(s.bins[Math.max(0, j - 1)].from === s.bins[j].from ? s.bins[j].from + s.w : s.bins[Math.max(0, j - 1)].from, "other", "앞 계급을 골랐다."), W(s.bins[s.bins.map((b) => b.count).indexOf(Math.max(...s.bins.map((b) => b.count)))].from === s.bins[j].from ? s.bins[j].from + 2 * s.w : s.bins[s.bins.map((b) => b.count).indexOf(Math.max(...s.bins.map((b) => b.count)))].from, "scope", "가장 높은 점의 계급을 골랐다.")], js: `return B[medIdx(0)].from;`, trace: [foRead(s), [`누적 도수: ${s.cum.join(", ")} 이다.`, "Accumulate the frequencies."], [`전체 ${s.N} 개이므로 중앙값 위치는 ${(s.N + 1) / 2} 번째이다.`, "Middle position."], [`누적이 처음 그 이상인 계급은 ${s.bins[j].from}~${s.bins[j].to} 이다.`, "The median class."]], variant: "median_class_from_polygon" }); } },
    { op: "compare_scenarios", structure: "가장 높은 계급에 값을 더했을 때 중앙값 계급의 하한이 얼마나 변하는지 비교", extra: "더하기 전과 후의 중앙값 위치를 각각 구해 비교 — medium 은 한 상황", concepts: ["도수다각형", "누적 도수", "두 상황 비교"],
      gen(rng) { for (let t = 0; t < 80; t++) { const s = makeFO(rng, { kind: "polygon" }); const add = rng.pick([s.u * 2, s.u * 3, s.u * 5]); const extra = s.bins.map((b, i) => (i === s.bins.length - 1 ? b.count + add : b.count)); const N2 = s.N + add; let acc = 0; const cum2 = extra.map((c) => (acc += c)); const p2 = (N2 + 1) / 2; const j2 = cum2.findIndex((c) => p2 <= c); const j = medI(s); if (j2 === j) continue; const d = s.bins[j2].from - s.bins[j].from;
        return FD(rng, s, { stim: `${add} more values are added, all in the highest class.`, question: "By how much does the lower limit of the median class change?", correct: Math.abs(d), wrongs: [W(Math.abs(d) + s.w, "other", "한 계급 더 이동했다."), W(0, "condition_ignored", "중앙값 계급이 바뀌지 않는다고 보았다."), W(s.bins[j2].from, "scope", "새 하한을 답했다."), W(s.bins[j].from, "scope", "원래 하한을 답했다."), W(add, "scope", "더한 개수를 답했다.")], P: { add }, js: `const j=medIdx(0); const n2=N+P.add; let a=0; const c2=B.map((b,i)=>(a+=b.count+(i===B.length-1?P.add:0))); const p2=(n2+1)/2; const j2=c2.findIndex(c=>p2<=c); return Math.abs(B[j2].from-B[j].from);`, trace: [foRead(s), [`처음 중앙값 계급의 하한은 ${s.bins[j].from} 이다.`, "Original median class."], [`${add} 개를 더하면 전체 ${N2}, 중앙값 위치 ${(N2 + 1) / 2} 이다.`, "New total and position."], [`새 누적 도수: ${cum2.join(", ")} 이다.`, "New cumulative counts."], [`새 중앙값 계급의 하한은 ${s.bins[j2].from} 이므로 변화는 ${Math.abs(d)} 이다.`, "Difference."]], variant: "median_class_shift_adding_top" }); } throw new GenFail("cmp"); } },
    { op: "inverse", structure: "가장 낮은 계급에 값을 더해 중앙값이 바로 아래 계급으로 내려오게 하는 최소 개수를 구함", extra: "새 중앙값 위치가 아래 계급의 누적 안에 들어오는 조건을 거꾸로 세움 — medium 은 중앙값 계급", concepts: ["도수다각형", "누적 도수", "부등식과 정수"],
      gen(rng) { for (let t = 0; t < 120; t++) { const s = makeFO(rng, { kind: "polygon" }); const j = medI(s); if (j < 2) continue; const need = Math.max(1, s.N + 1 - 2 * s.cum[j - 1]); const ans = need % 1 === 0 ? need : Math.ceil(need); if (ans > 60) continue;
        return FD(rng, s, { stim: "More values are added to the lowest class only.", question: ["What is the least number of values that must be added so that the median moves into the class just below its current class?", "How many values must be added to the lowest class, at a minimum, for the median to fall in the next lower class?"], correct: ans, wrongs: [W(ans - 1, "condition_ignored", "경계를 포함하지 않았다."), W(ans + 1, "other", "하나 더 올렸다."), W(s.N - s.cum[j - 1], "formula_misuse", "새 값이 전체도 늘리는 것을 무시했다."), W(s.cum[j - 1], "scope", "앞 누적을 답했다."), W(Math.ceil(ans / 2), "formula_misuse", "절반으로 나눴다.")], js: `const j=medIdx(0); let t=0; while(medIdx(t,(N+t+1)/2)>=j && t<500) t++; return t;`, trace: [foRead(s), [`처음 중앙값 계급은 ${s.bins[j].from}~${s.bins[j].to} 이고 그 앞 누적은 ${s.cum[j - 1]} 이다.`, "The median class."], [`아래 계급으로 내려오려면 (${s.N} + t + 1) ÷ 2 ≤ ${s.cum[j - 1]} + t 이어야 한다.`, "The new position must be within the lower class."], [`t ≥ ${s.N + 1} - 2 × ${s.cum[j - 1]} = ${f(s.N + 1 - 2 * s.cum[j - 1])} 이다.`, "Solve for t."], [`가장 작은 정수는 ${ans} 이다.`, "Round up."]], variant: "values_to_move_median_down" }); } throw new GenFail("inverse"); } },
    { op: "constraint_select", structure: "가장 낮은 계급부터 계급을 합쳐 합친 도수가 처음 전체의 절반을 넘기 위한 계급의 개수를 구함", extra: "누적 도수가 N/2 를 처음 초과하는 위치를 경계(같으면 제외)까지 따져 찾아야 함 — medium 은 누적 도수 읽기", concepts: ["도수다각형", "누적 도수", "조건 선택"],
      gen(rng) { const s = makeFO(rng, { kind: "polygon" }); const half = s.N / 2; const j = s.cum.findIndex((c) => c > half); const ge = s.cum.findIndex((c) => c >= half); if (j < 0) throw new GenFail("j");
        return FD(rng, s, { question: ["Starting from the lowest class, how many classes must be combined so that their total frequency is greater than half of all the values?", "What is the fewest number of classes, starting from the lowest, whose combined frequency exceeds half of the values?"], correct: j + 1, wrongs: [W(ge + 1 === j + 1 ? j + 2 : ge + 1, "condition_ignored", "'이상' 으로 읽었다."), W(j, "other", "하나 모자라게 셌다."), W(j + 2, "other", "하나 더 셌다."), W(s.bins.length - j, "opposite", "위쪽에서부터 셌다."), W(s.bins.length, "scope", "전체를 답했다.")].filter((w) => w.v > 0), js: `const h=N/2; return cum.findIndex(c=>c>h)+1;`, trace: [foRead(s), [`누적 도수: ${s.cum.join(", ")} 이다.`, "Accumulate."], [`전체의 절반은 ${half} 이다.`, "Half of the values."], [`누적이 ${half} 를 처음 넘는 것은 ${j + 1} 번째 계급까지이다.`, "First class where the cumulative frequency exceeds half."]], variant: "classes_to_exceed_half" }); } },
  ],
  em: [
    { lv: "easy", name: "tallest_class", structure: "도수다각형에서 도수가 가장 큰 계급의 하한을 읽음", extra: "easy: 가장 높은 점", concepts: ["도수다각형", "최빈 계급"],
      gen(rng) { const s = makeFO(rng, { kind: "polygon", distinctMax: true }); const j = s.bins.map((b) => b.count).indexOf(Math.max(...s.bins.map((b) => b.count))); return FD(rng, s, { question: "What is the lower limit of the class with the greatest frequency?", correct: s.bins[j].from, wrongs: [W(s.bins[j].to, "axis_misread", "상한을 답했다."), W(s.mids[j], "axis_misread", "계급값을 답했다."), W(s.bins[Math.min(j + 1, s.bins.length - 1)].from === s.bins[j].from ? s.bins[j].from - s.w : s.bins[Math.min(j + 1, s.bins.length - 1)].from, "other", "다음 계급을 골랐다."), W(Math.max(...s.bins.map((b) => b.count)), "scope", "도수를 답했다.")], js: `const m=Math.max(...cnt); return B[cnt.indexOf(m)].from;`, trace: [foRead(s), [`가장 높은 점은 ${s.bins[j].from}~${s.bins[j].to} 계급이다.`, "Tallest point."]], variant: "tallest_class_lower_limit", min: 2 }); } },
    { lv: "medium", name: "class_of_kth_value", structure: "누적 도수로 k 번째로 작은 값이 속한 계급의 하한을 구함", extra: "medium: 누적 도수와 위치 비교", concepts: ["도수다각형", "누적 도수"],
      gen(rng) { const s = makeFO(rng, { kind: "polygon" }); const kth = rng.int(2, s.N - 1); const j = s.cum.findIndex((c) => kth <= c); return FD(rng, s, { question: `The values are listed from least to greatest. In which class is the ${kth}th value? Give the lower limit of that class.`, correct: s.bins[j].from, wrongs: [W(s.bins[j].to, "axis_misread", "상한을 답했다."), W(s.bins[Math.min(j + 1, s.bins.length - 1)].from === s.bins[j].from ? s.bins[j].from - s.w : s.bins[Math.min(j + 1, s.bins.length - 1)].from, "other", "다음 계급을 골랐다."), W(s.bins[Math.max(0, j - 1)].from === s.bins[j].from ? s.bins[j].from + s.w : s.bins[Math.max(0, j - 1)].from, "other", "앞 계급을 골랐다."), W(kth, "scope", "위치를 답했다."), W(s.bins[j].from + 2 * s.w, "other", "두 계급 어긋났다."), W(s.bins[j].from - 2 * s.w, "other", "두 계급 어긋났다.")], P: { kth }, js: `return B[cum.findIndex(c=>P.kth<=c)].from;`, trace: [foRead(s), [`누적 도수: ${s.cum.join(", ")} 이다.`, "Accumulate."], [`${kth} 번째 값이 처음 포함되는 계급은 ${s.bins[j].from}~${s.bins[j].to} 이다.`, "Find the class."]], variant: "class_of_kth_value", min: 3 }); } },
  ],
});

// ───────────────────────── quartile_percentile_from_plot.FO.P · relative_cumulative_frequency.FO.P (누적 상대도수 %) ─────────────────────────
const pctAt = (s: FoScene, i: number) => (s.cum[i] * 100) / s.N;
const bnd = (s: FoScene, i: number) => s.bins[i].to;
export const quartileItem = () => defineItem({
  prefix: "ovd", itemId: "one_variable_data.quartile_percentile_from_plot.FO.P",
  hard: [
    { op: "chain2", structure: "누적 상대도수 그래프에서 제3사분위수(75%)가 처음 도달되는 계급의 상한을 구함", extra: "75% 에 처음 도달하는 경계를 눈금으로 찾아야 함 — medium 은 50%", concepts: ["누적 상대도수", "사분위수", "백분위수"],
      gen(rng) { const s = makeFO(rng, { kind: "ogive", percent: true }); const j = s.cum.findIndex((c) => (c * 100) / s.N >= 75);
        return FD(rng, s, { question: ["What is the least class upper limit such that at least 75% of the values are less than or equal to it?", `At which class boundary, in ${s.t.unit}, does the cumulative percent first reach at least 75%?`], correct: bnd(s, j), wrongs: [W(bnd(s, Math.max(0, j - 1)), "condition_ignored", "75% 에 못 미치는 경계를 골랐다."), W(bnd(s, Math.min(s.bins.length - 1, j + 1)), "other", "한 경계 더 갔다."), W(s.bins[j].from, "axis_misread", "하한을 답했다."), W(75, "unit_error", "퍼센트를 답했다."), W(bnd(s, s.cum.findIndex((c) => (c * 100) / s.N >= 50)), "scope", "50% 의 경계를 답했다.")], js: `return B[rel.findIndex(r=>r>=75)].to;`, trace: [foRead(s), [`제3사분위수는 누적 75% 가 처음 도달되는 지점이다.`, "Third quartile corresponds to the 75th percentile."], [`누적 %: ${s.cum.map((_, i) => `${bnd(s, i)}→${pctAt(s, i)}%`).join(", ")} 이다.`, "Cumulative percents at each boundary."], [`처음 75% 이상이 되는 경계는 ${bnd(s, j)} 이다.`, "First boundary reaching 75%."]], variant: "third_quartile_boundary" }); } },
    { op: "compare_scenarios", structure: "제1사분위수와 제3사분위수의 경계를 각각 찾아 그 차를 구함", extra: "25% 와 75% 의 경계를 모두 찾아 사분위 범위(근사)를 구함 — medium 은 한 경계", concepts: ["누적 상대도수", "사분위수", "사분위 범위"],
      gen(rng) { const s = makeFO(rng, { kind: "ogive", percent: true }); const a = s.cum.findIndex((c) => (c * 100) / s.N >= 25), b = s.cum.findIndex((c) => (c * 100) / s.N >= 75); const d = bnd(s, b) - bnd(s, a); if (d <= 0) throw new GenFail("d");
        return FD(rng, s, { question: ["What is the difference between the class upper limit where the cumulative percent first reaches 75% and the one where it first reaches 25%?", "By how much do the boundaries at which the cumulative percent first reaches 75% and 25% differ?"], correct: d, wrongs: [W(bnd(s, b), "step_missing", "75% 경계만 답했다."), W(bnd(s, a), "step_missing", "25% 경계만 답했다."), W(d + s.w, "other", "한 계급 더 셌다."), W(d - s.w, "other", "한 계급 덜 셌다."), W(50, "unit_error", "퍼센트 차를 답했다.")].filter((w) => w.v > 0), js: `return B[rel.findIndex(r=>r>=75)].to - B[rel.findIndex(r=>r>=25)].to;`, trace: [foRead(s), [`25% 에 처음 도달하는 경계는 ${bnd(s, a)} 이다.`, "First boundary reaching 25%."], [`75% 에 처음 도달하는 경계는 ${bnd(s, b)} 이다.`, "First boundary reaching 75%."], [`차 = ${bnd(s, b)} - ${bnd(s, a)} = ${d} 이다.`, "Subtract."]], variant: "iqr_boundaries" }); } },
    { op: "inverse", structure: "한 경계 이하의 개수가 주어질 때 누적 상대도수로 전체 개수를 구함", extra: "개수 = 누적 % × 전체 를 거꾸로 써서 전체를 구함 — medium 은 개수 읽기", concepts: ["누적 상대도수", "백분위수", "역산"],
      gen(rng) { const s = makeFO(rng, { kind: "ogive", percent: true }); const j = rng.int(0, s.bins.length - 2); const C = s.cum[j];
        return FD(rng, s, { stim: `Exactly ${C} of the values are less than or equal to ${bnd(s, j)} ${s.t.unit}.`, question: ["How many values are in the data set altogether?", `What is the total number of ${s.t.ent} represented?`], correct: s.N, wrongs: [W(C, "scope", "주어진 개수를 답했다."), W(Math.round(pctAt(s, j)), "unit_error", "퍼센트를 답했다."), W(Math.round((C * pctAt(s, j)) / 100), "formula_misuse", "곱해 버렸다."), W(s.N + s.u, "other", "계산 중 어긋났다."), W(s.N - s.u, "other", "계산 중 어긋났다.")], P: { C, b: bnd(s, j) }, js: `const i=B.findIndex(x=>x.to===P.b); const N2=P.C*100/rel[i]; return r6(N2);`, trace: [foRead(s), [`${bnd(s, j)} 이하의 누적 %는 ${pctAt(s, j)}% 이다.`, "Read the cumulative percent."], [`${C} 는 전체의 ${pctAt(s, j)}% 이다.`, "The given count is that percent of the total."], [`전체 = ${C} ÷ ${pctAt(s, j) / 100} = ${s.N} 이다.`, "Divide."]], variant: "total_from_cumulative_percent" }); } },
    { op: "constraint_select", structure: "누적 상대도수가 50% 이상인 경계의 개수를 센다", extra: "각 경계의 누적 %를 읽어 같은 경우를 포함해 세야 함 — medium 은 한 경계", concepts: ["누적 상대도수", "중앙값", "조건 개수"],
      gen(rng) { const s = makeFO(rng, { kind: "ogive", percent: true }); const n50 = s.cum.filter((c) => (c * 100) / s.N >= 50).length; const gt = s.cum.filter((c) => (c * 100) / s.N > 50).length; if (n50 === gt) throw new GenFail("same");
        return FD(rng, s, { question: ["At how many of the class boundaries shown is the cumulative percent at least 50%?", "For how many of the plotted class boundaries is the cumulative percent 50% or more?"], correct: n50, wrongs: [W(gt, "condition_ignored", "50% 인 경계를 제외했다."), W(s.bins.length - n50, "opposite", "50% 미만을 셌다."), W(n50 + 1, "other", "첫 점(0%)까지 셌다."), W(s.bins.length, "scope", "전체를 답했다.")].filter((w) => w.v > 0), js: `return rel.filter(r=>r>=50).length;`, trace: [foRead(s), [`누적 %: ${s.cum.map((_, i) => pctAt(s, i)).join(", ")} 이다.`, "Cumulative percents."], [`50% 이상(같은 것 포함)을 센다.`, "Count those at least 50%."], [`개수는 ${n50} 이다.`, "Count."]], variant: "boundaries_at_least_half" }); } },
  ],
  em: [
    { lv: "easy", name: "percent_at_boundary", structure: "한 경계 이하의 누적 상대도수(%)를 읽음", extra: "easy: 점 높이 읽기", concepts: ["누적 상대도수", "백분위수"],
      gen(rng) { const s = makeFO(rng, { kind: "ogive", percent: true }); const j = rng.int(0, s.bins.length - 2); return FD(rng, s, { question: `What percent of the values are less than or equal to ${bnd(s, j)} ${s.t.unit}?`, correct: pctAt(s, j), wrongs: [W(pctAt(s, Math.min(j + 1, s.bins.length - 1)) === pctAt(s, j) ? pctAt(s, j) + 10 : pctAt(s, Math.min(j + 1, s.bins.length - 1)), "axis_misread", "다음 경계를 읽었다."), W(Math.max(0, pctAt(s, j) - 10), "axis_misread", "한 눈금 아래를 읽었다."), W(bnd(s, j), "unit_error", "경계 값을 답했다."), W(100 - pctAt(s, j), "opposite", "초과하는 %를 답했다.")], P: { b: bnd(s, j) }, js: `return rel[B.findIndex(x=>x.to===P.b)];`, trace: [foRead(s), [`${bnd(s, j)} 에서 곡선의 높이는 ${pctAt(s, j)}% 이다.`, "Read the height."]], variant: "percent_at_boundary", min: 2 }); } },
    { lv: "medium", name: "count_below_boundary", structure: "전체 개수와 누적 %로 한 경계 이하의 개수를 구함", extra: "medium: % × 전체", concepts: ["누적 상대도수", "개수 환산"],
      gen(rng) { const s = makeFO(rng, { kind: "ogive", percent: true }); const j = rng.int(0, s.bins.length - 2); return FD(rng, s, { stim: `There are ${s.N} values in all.`, question: `How many of the values are less than or equal to ${bnd(s, j)} ${s.t.unit}?`, correct: s.cum[j], wrongs: [W(pctAt(s, j), "unit_error", "퍼센트를 답했다."), W(s.N - s.cum[j], "opposite", "초과하는 개수를 답했다."), W(s.cum[Math.min(j + 1, s.bins.length - 1)] === s.cum[j] ? s.cum[j] + s.u : s.cum[Math.min(j + 1, s.bins.length - 1)], "axis_misread", "다음 경계를 읽었다."), W(s.cum[j] + s.u, "other", "계산 중 어긋났다.")], P: { N2: s.N, b: bnd(s, j) }, js: `return r6(rel[B.findIndex(x=>x.to===P.b)]*P.N2/100);`, trace: [foRead(s), [`${bnd(s, j)} 이하는 ${pctAt(s, j)}% 이다.`, "Read the percent."], [`${s.N} × ${pctAt(s, j) / 100} = ${s.cum[j]} 이다.`, "Convert to a count."]], variant: "count_below_boundary", min: 3 }); } },
  ],
});
export const relCumItem = () => defineItem({
  prefix: "ovd", itemId: "one_variable_data.relative_cumulative_frequency.FO.P",
  hard: [
    { op: "chain2", structure: "누적 상대도수 그래프에서 두 경계 사이에 속하는 값의 퍼센트를 구함", extra: "두 경계의 누적 %를 읽어 차를 구함 — medium 은 한 경계", concepts: ["누적 상대도수", "계급의 상대도수"],
      gen(rng) { const s = makeFO(rng, { kind: "ogive", percent: true }); const [i, j] = rng.shuffle([...s.bins.keys()]).slice(0, 2).sort((a, b) => a - b); if (i === j) throw new GenFail("same"); const d = pctAt(s, j) - pctAt(s, i); if (d <= 0) throw new GenFail("d");
        return FD(rng, s, { question: `What percent of the values are greater than ${bnd(s, i)} ${s.t.unit} and less than or equal to ${bnd(s, j)} ${s.t.unit}?`, correct: d, wrongs: [W(pctAt(s, j), "step_missing", "윗 경계의 %만 답했다."), W(pctAt(s, i), "step_missing", "아랫 경계의 %만 답했다."), W(pctAt(s, i) + pctAt(s, j), "sign_error", "합을 구했다."), W(100 - d, "opposite", "그 구간 밖의 %를 답했다."), W(d + 10, "other", "한 눈금 어긋났다.")], P: { a: bnd(s, i), b: bnd(s, j) }, js: `return rel[B.findIndex(x=>x.to===P.b)] - rel[B.findIndex(x=>x.to===P.a)];`, trace: [foRead(s), [`${bnd(s, j)} 이하: ${pctAt(s, j)}% 이다.`, "Percent up to the upper boundary."], [`${bnd(s, i)} 이하: ${pctAt(s, i)}% 이다.`, "Percent up to the lower boundary."], [`차 = ${d}% 이다.`, "Subtract."]], variant: "percent_between_boundaries" }); } },
    { op: "compare_scenarios", structure: "한 경계 이하의 % 와 다른 경계 초과의 % 를 비교해 차를 구함", extra: "'이하' 와 '초과' 의 방향이 다른 두 %를 각각 구해 비교 — medium 은 한 %", concepts: ["누적 상대도수", "여사건", "두 경우 비교"],
      gen(rng) { const s = makeFO(rng, { kind: "ogive", percent: true }); const [i, j] = rng.shuffle([...s.bins.keys()].slice(0, s.bins.length - 1)).slice(0, 2); if (i === j) throw new GenFail("same"); const a = pctAt(s, i), b = 100 - pctAt(s, j); if (a === b) throw new GenFail("eq"); const d = Math.abs(a - b);
        return FD(rng, s, { question: `What is the positive difference between the percent of values that are at most ${bnd(s, i)} ${s.t.unit} and the percent that are greater than ${bnd(s, j)} ${s.t.unit}?`, correct: d, wrongs: [W(a, "step_missing", "하나의 %만 답했다."), W(b, "step_missing", "다른 %만 답했다."), W(Math.abs(a - pctAt(s, j)), "opposite", "초과를 이하로 읽었다."), W(a + b, "sign_error", "합을 구했다."), W(d + 10, "other", "한 눈금 어긋났다.")], P: { a: bnd(s, i), b: bnd(s, j) }, js: `return Math.abs(rel[B.findIndex(x=>x.to===P.a)] - (100 - rel[B.findIndex(x=>x.to===P.b)]));`, trace: [foRead(s), [`${bnd(s, i)} 이하: ${a}% 이다.`, "At most the first boundary."], [`${bnd(s, j)} 초과: 100 - ${pctAt(s, j)} = ${b}% 이다.`, "Greater than the second boundary."], [`차 = ${d} 이다.`, "Positive difference."]], variant: "at_most_vs_greater_than" }); } },
    { op: "inverse", structure: "한 구간에 속하는 개수가 주어질 때 누적 상대도수로 전체 개수를 구함", extra: "구간의 % 를 구해 개수 = % × 전체 를 거꾸로 씀 — medium 은 개수 환산", concepts: ["누적 상대도수", "역산"],
      gen(rng) { const s = makeFO(rng, { kind: "ogive", percent: true }); const j = rng.int(1, s.bins.length - 1); const c = cntOf(s, j);
        return FD(rng, s, { stim: `There are ${c} values in the class ${s.bins[j].from}–${s.bins[j].to}.`, question: ["How many values are in the data set altogether?", `What is the total number of ${s.t.ent} represented in the graph?`], correct: s.N, wrongs: [W(c, "scope", "주어진 개수를 답했다."), W(Math.round((c * 100) / pctAt(s, j)), "formula_misuse", "누적 %로 나눴다."), W(Math.round(100 / ((c * 100) / s.N)), "formula_misuse", "계산 중 어긋났다."), W(s.N + s.u, "other", "계산 중 어긋났다."), W(s.N - s.u, "other", "계산 중 어긋났다.")], P: { c, b: bnd(s, j) }, js: `const i=B.findIndex(x=>x.to===P.b); const pct=rel[i]-(i===0?0:rel[i-1]); return r6(P.c*100/pct);`, trace: [foRead(s), [`${bnd(s, j)} 까지 ${pctAt(s, j)}%, 그 앞 경계까지 ${j > 0 ? pctAt(s, j - 1) : 0}% 이다.`, "Read both cumulative percents."], [`그 계급의 % = ${pctAt(s, j) - (j > 0 ? pctAt(s, j - 1) : 0)}% 이다.`, "Percent in the class."], [`전체 = ${c} ÷ ${(pctAt(s, j) - (j > 0 ? pctAt(s, j - 1) : 0)) / 100} = ${s.N} 이다.`, "Divide."]], variant: "total_from_class_count" }); } },
    { op: "unit_ratio", structure: "전체 개수가 주어질 때 두 경계 사이에 속하는 값의 개수를 구함", extra: "두 경계의 누적 %의 차를 개수로 환산 — medium 은 한 경계 이하의 개수", concepts: ["누적 상대도수", "개수 환산"],
      gen(rng) { const s = makeFO(rng, { kind: "ogive", percent: true }); const [i, j] = rng.shuffle([...s.bins.keys()]).slice(0, 2).sort((a, b) => a - b); if (i === j) throw new GenFail("same"); const c = s.cum[j] - s.cum[i];
        return FD(rng, s, { stim: `There are ${s.N} values in all.`, question: `How many of the values are greater than ${bnd(s, i)} ${s.t.unit} and at most ${bnd(s, j)} ${s.t.unit}?`, correct: c, wrongs: [W(pctAt(s, j) - pctAt(s, i), "unit_error", "퍼센트 차를 답했다."), W(s.cum[j], "step_missing", "윗 경계 이하의 개수만 답했다."), W(s.cum[i], "step_missing", "아랫 경계 이하의 개수만 답했다."), W(s.N - c, "opposite", "구간 밖의 개수를 답했다."), W(c + s.u, "other", "계산 중 어긋났다.")], P: { N2: s.N, a: bnd(s, i), b: bnd(s, j) }, js: `return r6((rel[B.findIndex(x=>x.to===P.b)]-rel[B.findIndex(x=>x.to===P.a)])*P.N2/100);`, trace: [foRead(s), [`${bnd(s, j)} 이하 ${pctAt(s, j)}%, ${bnd(s, i)} 이하 ${pctAt(s, i)}% 이다.`, "Read both cumulative percents."], [`차 = ${pctAt(s, j) - pctAt(s, i)}% 이다.`, "Percent in between."], [`${s.N} × ${(pctAt(s, j) - pctAt(s, i)) / 100} = ${c} 이다.`, "Convert to a count."]], variant: "count_between_boundaries" }); } },
  ],
  em: [
    { lv: "easy", name: "percent_at_most", structure: "한 경계 이하의 누적 상대도수(%)를 읽음", extra: "easy: 점 높이 읽기", concepts: ["누적 상대도수"],
      gen(rng) { const s = makeFO(rng, { kind: "ogive", percent: true }); const j = rng.int(0, s.bins.length - 2); return FD(rng, s, { question: `What percent of the values are at most ${bnd(s, j)} ${s.t.unit}?`, correct: pctAt(s, j), wrongs: [W(100 - pctAt(s, j), "opposite", "초과하는 %를 답했다."), W(Math.max(0, pctAt(s, j) - 10), "axis_misread", "한 눈금 아래를 읽었다."), W(pctAt(s, Math.min(j + 1, s.bins.length - 1)) === pctAt(s, j) ? pctAt(s, j) + 10 : pctAt(s, Math.min(j + 1, s.bins.length - 1)), "axis_misread", "다음 경계를 읽었다.")], P: { b: bnd(s, j) }, js: `return rel[B.findIndex(x=>x.to===P.b)];`, trace: [foRead(s), [`${bnd(s, j)} 에서 곡선의 높이는 ${pctAt(s, j)}% 이다.`, "Read the height."]], variant: "percent_at_most", min: 2 }); } },
    { lv: "medium", name: "percent_above", structure: "한 경계를 초과하는 값의 퍼센트를 구함", extra: "medium: 100% - 누적 %", concepts: ["누적 상대도수", "여사건"],
      gen(rng) { const s = makeFO(rng, { kind: "ogive", percent: true }); const j = rng.int(0, s.bins.length - 2); return FD(rng, s, { question: `What percent of the values are greater than ${bnd(s, j)} ${s.t.unit}?`, correct: 100 - pctAt(s, j), wrongs: [W(pctAt(s, j), "opposite", "이하의 %를 답했다."), W(Math.max(0, 100 - pctAt(s, j) - 10), "other", "한 눈금 어긋났다."), W(100 - pctAt(s, j) + 10, "other", "한 눈금 어긋났다.")], P: { b: bnd(s, j) }, js: `return 100 - rel[B.findIndex(x=>x.to===P.b)];`, trace: [foRead(s), [`${bnd(s, j)} 이하는 ${pctAt(s, j)}% 이다.`, "Percent at most the boundary."], [`초과 = 100 - ${pctAt(s, j)} = ${100 - pctAt(s, j)}% 이다.`, "Complement."]], variant: "percent_above_boundary", min: 3 }); } },
  ],
});
