// 원그래프(PI) 공용 장면 키트 — percentages.{percent_of,find_whole,find_percent}·ratios_rates_units.proportion·probability.{simple,sequential_without_replacement,spinner_expected_value}·circles.sector_area 의 .PI.P 조합이 함께 쓴다.
// 규칙(자료 계열 공통): 수치를 먼저 뽑고 → figure(pie)를 만들고 → 지문은 값을 되풀이하지 않고 "the pie chart shown" 으로 가리킨다. 정보는 자료에만 있다.
// 퍼센트는 5 의 배수·부채꼴 하나는 10% 이상(라벨이 겹치지 않게), 전체 N 은 20 의 배수(모든 부채꼴의 수가 정수).
import { GenFail, type Instance } from "../../types";
import type { Rng } from "../../rng";
import { fmtNum, frac, spin } from "../../text";
import type { DistractorKind } from "../../../review";
import { W } from "../d-kit";
import { figJs } from "../../figure-kit";
import { defineItem } from "./item-kit";
import { gInst } from "./graph-kit";
import { renderPie, type PieSpec } from "@/lib/problem-figures/templates/pie";

export type PieTopic = { desc: string; ent: string; ent1: string; cats: string[]; verb: string; title: string };
export const PIE_TOPICS: PieTopic[] = [
  { desc: "the favorite sport of the students surveyed at a school", ent: "students", ent1: "student", verb: "chose", title: "Favorite sport", cats: ["Soccer", "Tennis", "Swimming", "Baseball", "Track", "Volleyball"] },
  { desc: "how the members of a book club voted for their next genre", ent: "members", ent1: "member", verb: "voted for", title: "Genre votes", cats: ["Mystery", "Fantasy", "History", "Poetry", "Science", "Romance"] },
  { desc: "the main way the employees of a company travel to work", ent: "employees", ent1: "employee", verb: "use", title: "Commute method", cats: ["Car", "Bus", "Train", "Bicycle", "Walking", "Carpool"] },
  { desc: "the favorite lunch choice of the students in a cafeteria survey", ent: "students", ent1: "student", verb: "picked", title: "Lunch choice", cats: ["Pizza", "Salad", "Pasta", "Burgers", "Soup", "Tacos"] },
  { desc: "the language studied by the students in a school's language program", ent: "students", ent1: "student", verb: "study", title: "Language studied", cats: ["Spanish", "French", "German", "Chinese", "Latin", "Korean"] },
  { desc: "the type of pet owned by the households in a neighborhood survey", ent: "households", ent1: "household", verb: "own", title: "Pet owned", cats: ["Dogs", "Cats", "Birds", "Fish", "Rabbits", "Hamsters"] },
  { desc: "the favorite activity chosen by the visitors to a park", ent: "visitors", ent1: "visitor", verb: "chose", title: "Favorite activity", cats: ["Hiking", "Picnics", "Biking", "Fishing", "Camping", "Kayaking"] },
  { desc: "the topic of the books checked out at a library in one week", ent: "books", ent1: "book", verb: "were about", title: "Book topics", cats: ["Travel", "Cooking", "Biography", "Art", "Sports", "Gardening"] },
  { desc: "the instrument chosen by the students in a school music program", ent: "students", ent1: "student", verb: "play", title: "Instrument", cats: ["Piano", "Guitar", "Violin", "Drums", "Flute", "Trumpet"] },
  { desc: "the after-school activity chosen by the students at a middle school", ent: "students", ent1: "student", verb: "joined", title: "Activity chosen", cats: ["Chess", "Drama", "Robotics", "Choir", "Art club", "Debate"] },
];
export const N_CHOICES = [100, 120, 140, 160, 180, 200, 240, 280, 300, 360, 400, 480, 500, 600, 800];

export type PieScene = { t: PieTopic; names: string[]; pct: number[]; N: number; fig: PieSpec; k: number };
/** 퍼센트 부분집합(5 의 배수, 각 10% 이상, 합 100). distinct 면 서로 다름. */
export function pctSet(rng: Rng, k: number, distinct = true): number[] {
  for (let t = 0; t < 200; t++) {
    const units = Array.from({ length: k }, () => 2); let left = 20 - 2 * k;
    while (left > 0) { units[rng.int(0, k - 1)]++; left--; }
    if (distinct && new Set(units).size !== k) continue;
    return units.map((u) => u * 5);
  }
  throw new GenFail("퍼센트 분할");
}
export type PieOpts = { k?: number; N?: number; distinct?: boolean; mode?: "percent" | "degrees" | "amount"; unit?: string };
export function makePie(rng: Rng, o: PieOpts = {}): PieScene {
  const t = rng.pick(PIE_TOPICS); const k = o.k ?? rng.int(4, 5); const names = rng.shuffle(t.cats).slice(0, k); const pct = pctSet(rng, k, o.distinct ?? true); const N = o.N ?? rng.pick(N_CHOICES);
  const mode = o.mode ?? "percent";
  const slices = names.map((label, i) => ({ label, amount: mode === "percent" ? pct[i] : mode === "degrees" ? pct[i] * 3.6 : (pct[i] * N) / 100 }));
  const fig: PieSpec = { type: "pie", format: mode, title: t.title, slices };
  if (renderPie(fig).issues.length) throw new GenFail("원그래프 라벨 배치");
  return { t, names, pct, N, fig, k };
}
export const PIE_JS = "const sl=FIGURE.slices, fmt=FIGURE.format; const nm=sl.map(s=>s.label); const T=sl.reduce((a,s)=>a+s.amount,0); const pcs=sl.map(s=>s.amount*100/T); const pc=(k)=>{ const i=nm.indexOf(k); if(i<0) throw new Error('부채꼴 없음'); return pcs[i]; }; const am=(k)=>{ const i=nm.indexOf(k); if(i<0) throw new Error('부채꼴 없음'); return sl[i].amount; }; const r6=(x)=>Math.round(x*1e6)/1e6;\n";
export const pieShown = (s: PieScene, mode = "") => (s.fig.format === "percent" ? "percent" : s.fig.format === "degrees" ? "central angle" : "number") + mode;
/** 문장 변주(독립 변형 수를 늘리는 중립 문장) — 정보를 더하지 않고 말투만 바꾼다. */
export const PLEADS = [
  "Use the information in the pie chart to answer the question.", "Refer to the pie chart when answering the question that follows.", "Answer the question using only the data in the pie chart.", "Study the pie chart carefully before answering.",
  "The pie chart contains the data needed for this question.", "Consider the data displayed in the pie chart.", "Examine the pie chart and then answer the question below.", "Base your answer on what the pie chart shows.",
  "Notice how the whole circle is divided among the categories.", "Each section of the pie chart is a separate category.", "Read the label on each section before you begin.", "The sections of the pie chart together make up the whole.",
];
export const pieIntro = (rng: Rng, s: PieScene, withTotal = false) => {
  const base = rng.pick([
    `The pie chart shown gives ${s.t.desc}.`, `A pie chart is shown for ${s.t.desc}.`, `The pie chart shown summarizes ${s.t.desc}. Each section is one category.`, `In the pie chart shown, each section represents one category of ${s.t.desc}.`]);
  const share = s.fig.format === "percent" ? "The size of each section is labeled as a percent of the whole." : s.fig.format === "degrees" ? "The size of each section is labeled as its central angle in degrees." : `The size of each section is labeled with the number of ${s.t.ent} it represents.`;
  return `${base}${withTotal ? ` A total of ${s.N} ${s.t.ent} are represented.` : ""}${share ? ` ${share}` : ""}`;
};
export const pieRead = (s: PieScene): [string, string] => [`원그래프에서 각 부채꼴의 값을 읽는다: ${s.names.map((n, i) => `${n} ${s.fig.format === "percent" ? s.pct[i] + "%" : s.fig.format === "degrees" ? s.fig.slices[i].amount + "°" : s.fig.slices[i].amount}`).join(", ")}.`, "Read each section's label from the pie chart."];
export const FW = (n: number, d: number, kind: DistractorKind, reason: string) => ({ text: frac(n, d), kind, reason });
const pos = (ws: ReturnType<typeof W>[]) => ws.filter((w) => w.v >= 0);
const f = fmtNum;

type D = { stim?: string; question: string; correct: number; wrongs: ReturnType<typeof W>[]; js: string; P?: Record<string, number | string>; trace: [string, string][]; variant: string; withTotal?: boolean; fmt?: (v: number) => string };
/** 숫자 정답 문항 조립 — 풀이가 4 단계 이상이면 마지막에 답 문장을 붙인다(hard 는 5 단계 이상이어야 한다). */
export const E = (rng: Rng, s: PieScene, d: D): Instance =>
  gInst(rng, { stimulus: `${pieIntro(rng, s, d.withTotal)}${d.stim ? ` ${d.stim}` : ""} ${rng.pick(PLEADS)}`, question: d.question, correct: d.correct, fmt: d.fmt, wrongs: pos(d.wrongs).filter((w) => Math.abs(w.v - d.correct) > 1e-9), verificationJs: figJs(d.P ?? {}, s.fig, `${PIE_JS}${d.js}`), trace: d.trace.length >= 4 ? [...d.trace, [`따라서 답은 ${f(d.correct)} 이다.`, "That is the requested value."]] : d.trace, variant: d.variant }, s.fig);
/** 분수 정답 문항 조립. */
type DF = { stim?: string; question: string; num: number; den: number; wrongs: { text: string; kind: DistractorKind; reason: string }[]; js: string; P?: Record<string, number | string>; trace: [string, string][]; variant: string; withTotal?: boolean };
export const EF = (rng: Rng, s: PieScene, d: DF): Instance =>
  gInst(rng, { stimulus: `${pieIntro(rng, s, d.withTotal)}${d.stim ? ` ${d.stim}` : ""} ${rng.pick(PLEADS)}`, question: d.question, correctText: frac(d.num, d.den), range: [0, 1], wrongTexts: d.wrongs.filter((w) => w.text !== frac(d.num, d.den)), verificationJs: figJs(d.P ?? {}, s.fig, `${PIE_JS}${d.js}`), trace: d.trace.length >= 4 ? [...d.trace, [`따라서 답은 ${frac(d.num, d.den)} 이다.`, "That is the probability."]] : d.trace, variant: d.variant }, s.fig);
export const nm2 = (rng: Rng, s: PieScene): [number, number] => { const [i, j] = rng.shuffle([...s.names.keys()]).slice(0, 2); return [i, j]; };

// ───────────────────────── percentages.percent_of.PI.P ─────────────────────────
export const percentOfItem = () => defineItem({
  prefix: "pct", itemId: "percentages.percent_of.PI.P",
  hard: [
    { op: "chain2", structure: "원그래프에서 두 부채꼴의 퍼센트를 더한 뒤 전체 N 의 그 퍼센트를 구함", extra: "퍼센트 합 → 전체에 대한 퍼센트의 연쇄 — medium 은 한 부채꼴의 퍼센트", concepts: ["원그래프", "퍼센트", "합"],
      gen(rng) { const s = makePie(rng); const [i, j] = nm2(rng, s); const a = s.names[i], b = s.names[j]; const c = ((s.pct[i] + s.pct[j]) * s.N) / 100;
        return E(rng, s, { withTotal: true, question: spin(rng, `[[How many of the ${s.t.ent} ${s.t.verb} ${a} or ${b}?|What is the total number of ${s.t.ent} who ${s.t.verb} either ${a} or ${b}?]]`), correct: c, wrongs: [W((s.pct[i] * s.N) / 100, "step_missing", "한 부채꼴만 셌다."), W((s.pct[j] * s.N) / 100, "step_missing", "다른 부채꼴만 셌다."), W(s.N - c, "opposite", "나머지를 구했다."), W(s.pct[i] + s.pct[j], "unit_error", "퍼센트를 그대로 답했다."), W((s.pct[i] * s.pct[j] * s.N) / 10000, "formula_misuse", "퍼센트를 곱했다.")], P: { N: s.N, a, b }, js: `return (pc(P.a) + pc(P.b)) * P.N / 100;`, trace: [pieRead(s), [`${a} 는 ${s.pct[i]}%, ${b} 는 ${s.pct[j]}% 이다.`, "Read the two percents."], [`합 = ${s.pct[i] + s.pct[j]}% = ${(s.pct[i] + s.pct[j]) / 100} 이다.`, "Add the percents."], [`${s.N} × ${(s.pct[i] + s.pct[j]) / 100} = ${f(c)} 이다.`, "Multiply by the total."]], variant: "two_sections_count" }); } },
    { op: "compare_scenarios", structure: "두 부채꼴의 수를 각각 구해 그 차를 구함", extra: "각 부채꼴에 퍼센트를 적용한 뒤 비교(퍼센트 차에만 곱해도 되지만 전체를 곱해야 함) — medium 은 한 부채꼴", concepts: ["원그래프", "퍼센트", "두 경우 비교"],
      gen(rng) { const s = makePie(rng); const [i, j] = nm2(rng, s); const a = s.names[i], b = s.names[j]; const A = (s.pct[i] * s.N) / 100, B = (s.pct[j] * s.N) / 100; const c = Math.abs(A - B);
        return E(rng, s, { withTotal: true, question: `How many more ${s.t.ent} ${s.t.verb} ${A > B ? a : b} than ${A > B ? b : a}?`, correct: c, wrongs: [W(Math.abs(s.pct[i] - s.pct[j]), "unit_error", "퍼센트 차를 그대로 답했다."), W(A, "step_missing", "한 부채꼴만 답했다."), W(B, "step_missing", "다른 부채꼴만 답했다."), W(A + B, "sign_error", "합을 구했다."), W(c / 2, "formula_misuse", "차를 둘로 나눴다.")], P: { N: s.N, a, b }, js: `return Math.abs(pc(P.a) - pc(P.b)) * P.N / 100;`, trace: [pieRead(s), [`${a}: ${s.N} × ${s.pct[i] / 100} = ${A} 이다.`, "First section."], [`${b}: ${s.N} × ${s.pct[j] / 100} = ${B} 이다.`, "Second section."], [`차 = |${A} - ${B}| = ${c} 이다.`, "Positive difference."]], variant: "two_sections_difference" }); } },
    { op: "inverse", structure: "한 부채꼴의 수가 주어질 때 다른 부채꼴의 수를 퍼센트의 비로 구함", extra: "전체를 주지 않고 한 부채꼴의 수에서 거꾸로 비례해 다른 부채꼴을 구해야 함 — medium 은 p% 계산", concepts: ["원그래프", "퍼센트", "역산·비례"],
      gen(rng) { const s = makePie(rng); const [i, j] = nm2(rng, s); const a = s.names[i], b = s.names[j]; const C = (s.pct[i] * s.N) / 100; const x = (s.pct[j] * s.N) / 100;
        return E(rng, s, { stim: `${C} of the ${s.t.ent} ${s.t.verb} ${a}.`, question: `How many of the ${s.t.ent} ${s.t.verb} ${b}?`, correct: x, wrongs: [W(C, "scope", "주어진 수를 답했다."), W((s.pct[j] * C) / 100, "formula_misuse", "주어진 수에 퍼센트를 곱했다."), W(C + s.pct[j] - s.pct[i], "formula_misuse", "퍼센트 차를 더했다."), W((C * s.pct[i]) / s.pct[j], "opposite", "비를 뒤집었다."), W(x + 10, "other", "계산 중 어긋났다.")], P: { C, a, b }, js: `return P.C / pc(P.a) * pc(P.b);`, trace: [pieRead(s), [`${a} 는 ${s.pct[i]}% 이고 ${C} 명이다.`, "Match the count to its percent."], [`전체 = ${C} ÷ ${s.pct[i] / 100} = ${s.N} 이다.`, "Find the total."], [`${b} 는 ${s.pct[j]}% 이다.`, "Read the other percent."], [`${s.N} × ${s.pct[j] / 100} = ${x} 이다.`, "Apply it."]], variant: "other_section_from_count" }); } },
    { op: "constraint_select", structure: "각 부채꼴에 퍼센트를 적용해 기준 T 보다 큰 수를 가진 부채꼴의 개수를 셈", extra: "모든 부채꼴을 계산해 경계(같은 경우 제외)를 따져 세야 함 — medium 은 한 부채꼴", concepts: ["원그래프", "퍼센트", "조건 개수"],
      gen(rng) { const s = makePie(rng); const cs = s.pct.map((p) => (p * s.N) / 100); const T = rng.pick(cs) + rng.pick([0, 0, 1, 5]); const cnt = cs.filter((c) => c > T).length; const ge = cs.filter((c) => c >= T).length; if (cnt < 1 || cnt >= s.k) throw new GenFail("cnt");
        return E(rng, s, { withTotal: true, question: `For how many of the categories are there more than ${T} ${s.t.ent}?`, correct: cnt, wrongs: [W(ge === cnt ? cnt + 1 : ge, "condition_ignored", "같은 경우까지 셌다."), W(s.k - cnt, "opposite", "기준 이하인 개수를 셌다."), W(cnt - 1 < 1 ? cnt + 2 : cnt - 1, "other", "하나를 빠뜨렸다."), W(s.pct.filter((p) => p > T).length === cnt ? cnt + 2 : s.pct.filter((p) => p > T).length, "step_missing", "퍼센트를 수로 바꾸지 않고 비교했다."), W(s.k, "condition_ignored", "전체를 답했다.")], P: { N: s.N, T }, js: `return pcs.filter(p => p * P.N / 100 > P.T).length;`, trace: [pieRead(s), [`각 부채꼴의 수: ${s.names.map((n, i) => `${n} ${cs[i]}`).join(", ")} 이다.`, "Apply each percent to the total."], [`기준은 ${T} 보다 큰 것(같은 것은 제외)이다.`, "Strictly greater."], [`${T} 보다 큰 부채꼴: ${cnt} 개이다.`, "Select."]], variant: "count_sections_above" }); } },
  ],
  em: [
    { lv: "easy", name: "one_section", structure: "원그래프의 한 부채꼴 퍼센트로 수를 구함", extra: "easy: p% × N", concepts: ["원그래프", "퍼센트"],
      gen(rng) { const s = makePie(rng); const i = rng.int(0, s.k - 1); const a = s.names[i]; const c = (s.pct[i] * s.N) / 100; return E(rng, s, { withTotal: true, question: `How many of the ${s.t.ent} ${s.t.verb} ${a}?`, correct: c, wrongs: [W(s.pct[i], "unit_error", "퍼센트를 그대로 답했다."), W(s.N - c, "opposite", "나머지를 구했다."), W(c / 10, "unit_error", "자리를 잘못 옮겼다."), W(c + s.N / 20, "other", "계산 중 어긋났다.")], P: { N: s.N, a }, js: `return pc(P.a) * P.N / 100;`, trace: [pieRead(s), [`${s.N} × ${s.pct[i] / 100} = ${f(c)} 이다.`, "Multiply the total by the percent."]], variant: "one_section_count" }); } },
    { lv: "medium", name: "not_in_section", structure: "한 부채꼴에 속하지 않는 수를 (100 - p)% 로 구함", extra: "medium: 나머지 비율", concepts: ["원그래프", "퍼센트", "여사건"],
      gen(rng) { const s = makePie(rng); const i = rng.int(0, s.k - 1); const a = s.names[i]; const c = ((100 - s.pct[i]) * s.N) / 100; return E(rng, s, { withTotal: true, question: `How many of the ${s.t.ent} did not belong to the category "${a}"?`, correct: c, wrongs: [W((s.pct[i] * s.N) / 100, "opposite", "그 부채꼴을 답했다."), W(100 - s.pct[i], "unit_error", "퍼센트를 답했다."), W(s.N - 100 + s.pct[i], "formula_misuse", "단위를 섞었다."), W(c - s.N / 20, "other", "계산 중 어긋났다.")], P: { N: s.N, a }, js: `return (100 - pc(P.a)) * P.N / 100;`, trace: [pieRead(s), [`나머지 비율 = 100 - ${s.pct[i]} = ${100 - s.pct[i]}% 이다.`, "Complement percent."], [`${s.N} × ${(100 - s.pct[i]) / 100} = ${f(c)} 이다.`, "Apply it."]], variant: "complement_count" }); } },
  ],
});

// ───────────────────────── percentages.find_whole.PI.P ─────────────────────────
export const findWholeItem = () => defineItem({
  prefix: "pct", itemId: "percentages.find_whole.PI.P",
  hard: [
    { op: "inverse", structure: "한 부채꼴의 수와 퍼센트에서 전체를 거꾸로 구하고, 두 부채꼴을 합한 수를 구함", extra: "전체를 먼저 역산한 뒤 다른 부채꼴 둘을 합해야 함 — medium 은 전체만", concepts: ["원그래프", "전체 구하기", "퍼센트 합"],
      gen(rng) { const s = makePie(rng); const idx = rng.shuffle([...s.names.keys()]); const [a, b, c] = idx; const C = (s.pct[a] * s.N) / 100; const ans = ((s.pct[b] + s.pct[c]) * s.N) / 100;
        return E(rng, s, { stim: `${C} of the ${s.t.ent} are in the category "${s.names[a]}".`, question: `How many of the ${s.t.ent} are in the categories "${s.names[b]}" and "${s.names[c]}" combined?`, correct: ans, wrongs: [W(s.N, "step_missing", "전체를 답했다."), W(((s.pct[b] + s.pct[c]) * C) / 100, "formula_misuse", "주어진 수에 퍼센트를 곱했다."), W(C + s.pct[b] + s.pct[c], "formula_misuse", "수에 퍼센트를 더했다."), W(s.N - ans, "opposite", "나머지를 구했다."), W(ans + s.N / 20, "other", "계산 중 어긋났다.")], P: { C, a: s.names[a], b: s.names[b], c: s.names[c] }, js: `return P.C / pc(P.a) * (pc(P.b) + pc(P.c));`, trace: [pieRead(s), [`${s.names[a]} 는 ${s.pct[a]}% 이고 ${C} 이다.`, "Match the count to its percent."], [`전체 = ${C} ÷ ${s.pct[a] / 100} = ${s.N} 이다.`, "Find the whole."], [`${s.names[b]} + ${s.names[c]} = ${s.pct[b] + s.pct[c]}% 이다.`, "Add the two percents."], [`${s.N} × ${(s.pct[b] + s.pct[c]) / 100} = ${f(ans)} 이다.`, "Apply it."]], variant: "whole_then_two_sections" }); } },
    { op: "chain2", structure: "한 부채꼴의 수에서 전체를 구한 뒤, 그 부채꼴에 속하지 않은 수를 구함", extra: "전체 → 나머지의 연쇄 — medium 은 전체만", concepts: ["원그래프", "전체 구하기", "여사건"],
      gen(rng) { const s = makePie(rng); const a = rng.int(0, s.k - 1); const C = (s.pct[a] * s.N) / 100; const ans = s.N - C;
        return E(rng, s, { stim: `${C} of the ${s.t.ent} are in the category "${s.names[a]}".`, question: `How many of the ${s.t.ent} are not in the category "${s.names[a]}"?`, correct: ans, wrongs: [W(s.N, "step_missing", "전체를 답했다."), W(C, "opposite", "주어진 수를 답했다."), W(100 - s.pct[a], "unit_error", "퍼센트를 답했다."), W(C * (100 - s.pct[a]) / 100, "formula_misuse", "주어진 수에 나머지 퍼센트를 곱했다."), W(ans + s.N / 20, "other", "계산 중 어긋났다.")], P: { C, a: s.names[a] }, js: `return P.C / pc(P.a) * 100 - P.C;`, trace: [pieRead(s), [`${s.names[a]} 는 ${s.pct[a]}% 이고 ${C} 이다.`, "Match the count to its percent."], [`전체 = ${C} ÷ ${s.pct[a] / 100} = ${s.N} 이다.`, "Find the whole."], [`나머지 = ${s.N} - ${C} = ${ans} 이다.`, "Subtract."]], variant: "whole_then_rest" }); } },
    { op: "compare_scenarios", structure: "같은 분포를 가진 두 집단에서 서로 다른 부채꼴의 수로 각 집단의 전체를 구해 차를 구함", extra: "두 번의 역산을 하고 비교해야 함 — medium 은 전체 하나", concepts: ["원그래프", "전체 구하기", "두 집단 비교"],
      gen(rng) { const s = makePie(rng); const [i, j] = nm2(rng, s); const N1 = s.N, N2 = rng.pick(N_CHOICES.filter((n) => n !== s.N)); const C1 = (s.pct[i] * N1) / 100, C2 = (s.pct[j] * N2) / 100; const c = Math.abs(N1 - N2);
        return E(rng, s, { stim: `The same percents describe two groups of ${s.t.ent}. In Group 1, ${C1} ${s.t.ent} are in the category "${s.names[i]}". In Group 2, ${C2} ${s.t.ent} are in the category "${s.names[j]}".`, question: "What is the positive difference between the total numbers of " + s.t.ent + " in the two groups?", correct: c, wrongs: [W(Math.abs(C1 - C2), "step_missing", "주어진 수의 차를 답했다."), W(N1 + N2, "sign_error", "합을 구했다."), W(N1, "step_missing", "한 집단의 전체만 답했다."), W(N2, "step_missing", "다른 집단의 전체만 답했다."), W(c + 20, "other", "계산 중 어긋났다.")], P: { C1, C2, a: s.names[i], b: s.names[j] }, js: `return Math.abs(P.C1 / pc(P.a) * 100 - P.C2 / pc(P.b) * 100);`, trace: [pieRead(s), [`Group 1: ${C1} ÷ ${s.pct[i] / 100} = ${N1} 이다.`, "Whole of group 1."], [`Group 2: ${C2} ÷ ${s.pct[j] / 100} = ${N2} 이다.`, "Whole of group 2."], [`차 = |${N1} - ${N2}| = ${c} 이다.`, "Positive difference."]], variant: "two_wholes_difference" }); } },
    { op: "constraint_select", structure: "한 부채꼴의 수에서 전체를 구하고 기준 T 보다 큰 수를 가진 부채꼴의 개수를 셈", extra: "전체를 역산한 뒤 모든 부채꼴에 적용해 경계를 따져야 함 — medium 은 전체만", concepts: ["원그래프", "전체 구하기", "조건 개수"],
      gen(rng) { const s = makePie(rng); const a = rng.int(0, s.k - 1); const C = (s.pct[a] * s.N) / 100; const cs = s.pct.map((p) => (p * s.N) / 100); const T = rng.pick(cs) + rng.pick([0, 0, 1, 5]); const cnt = cs.filter((c) => c > T).length; if (cnt < 1 || cnt >= s.k) throw new GenFail("cnt");
        return E(rng, s, { stim: `${C} of the ${s.t.ent} are in the category "${s.names[a]}".`, question: `For how many of the categories are there more than ${T} ${s.t.ent}?`, correct: cnt, wrongs: [W(cs.filter((c) => c >= T).length === cnt ? cnt + 1 : cs.filter((c) => c >= T).length, "condition_ignored", "같은 경우까지 셌다."), W(s.k - cnt, "opposite", "기준 이하인 개수를 셌다."), W(s.pct.filter((p) => p > T).length === cnt ? cnt + 2 : s.pct.filter((p) => p > T).length, "step_missing", "퍼센트와 기준을 바로 비교했다."), W(cnt + 1, "other", "경계를 잘못 잡았다."), W(s.k, "condition_ignored", "전체를 답했다.")], P: { C, a: s.names[a], T }, js: `const N = P.C / pc(P.a) * 100; return pcs.filter(p => p * N / 100 > P.T).length;`, trace: [pieRead(s), [`전체 = ${C} ÷ ${s.pct[a] / 100} = ${s.N} 이다.`, "Find the whole."], [`각 부채꼴의 수: ${s.names.map((n, i) => `${n} ${cs[i]}`).join(", ")} 이다.`, "Apply each percent."], [`${T} 보다 큰 것(같은 것은 제외)을 고른다.`, "Strictly greater."], [`개수는 ${cnt} 이다.`, "Count."]], variant: "whole_then_count_above" }); } },
  ],
  em: [
    { lv: "easy", name: "whole_from_one", structure: "한 부채꼴의 수와 퍼센트로 전체를 구함", extra: "easy: 수 ÷ p%", concepts: ["원그래프", "전체 구하기"],
      gen(rng) { const s = makePie(rng); const a = rng.int(0, s.k - 1); const C = (s.pct[a] * s.N) / 100; return E(rng, s, { stim: `${C} of the ${s.t.ent} are in the category "${s.names[a]}".`, question: `How many ${s.t.ent} are represented in the pie chart in all?`, correct: s.N, wrongs: [W(C * s.pct[a], "formula_misuse", "수에 퍼센트를 곱했다."), W(C + s.pct[a], "formula_misuse", "수에 퍼센트를 더했다."), W((C * 100) / (100 - s.pct[a]), "opposite", "나머지 퍼센트로 나눴다."), W(C, "scope", "주어진 수를 답했다.")], P: { C, a: s.names[a] }, js: `return P.C / pc(P.a) * 100;`, trace: [pieRead(s), [`${C} ÷ ${s.pct[a] / 100} = ${s.N} 이다.`, "Divide by the decimal."]], variant: "whole_from_one_section" }); } },
    { lv: "medium", name: "whole_from_two", structure: "두 부채꼴을 합한 수와 퍼센트 합으로 전체를 구함", extra: "medium: 퍼센트를 먼저 합하기", concepts: ["원그래프", "전체 구하기", "퍼센트 합"],
      gen(rng) { const s = makePie(rng); const [i, j] = nm2(rng, s); const C = ((s.pct[i] + s.pct[j]) * s.N) / 100; return E(rng, s, { stim: `${C} of the ${s.t.ent} are in the categories "${s.names[i]}" and "${s.names[j]}" combined.`, question: `How many ${s.t.ent} are represented in the pie chart in all?`, correct: s.N, wrongs: [W((C * 100) / s.pct[i], "step_missing", "한 부채꼴의 퍼센트만 썼다."), W((C * 100) / s.pct[j], "step_missing", "다른 부채꼴의 퍼센트만 썼다."), W(C * (s.pct[i] + s.pct[j]), "formula_misuse", "수에 퍼센트를 곱했다."), W(C, "scope", "주어진 수를 답했다.")], P: { C, a: s.names[i], b: s.names[j] }, js: `return P.C / (pc(P.a) + pc(P.b)) * 100;`, trace: [pieRead(s), [`두 부채꼴의 퍼센트 합 = ${s.pct[i]} + ${s.pct[j]} = ${s.pct[i] + s.pct[j]}% 이다.`, "Add the percents."], [`${C} ÷ ${(s.pct[i] + s.pct[j]) / 100} = ${s.N} 이다.`, "Divide."]], variant: "whole_from_two_sections" }); } },
  ],
});

// ───────────────────────── percentages.find_percent.PI.P ─────────────────────────
export const findPercentItem = () => defineItem({
  prefix: "pct", itemId: "percentages.find_percent.PI.P",
  hard: [
    { op: "chain2", structure: "원그래프에 쓰인 수들의 합(전체)을 구한 뒤 두 부채꼴의 수를 합해 전체에 대한 퍼센트를 구함", extra: "전체 합산 → 부분 합 → 퍼센트의 연쇄 — medium 은 한 부채꼴의 퍼센트", concepts: ["원그래프", "퍼센트 구하기", "합"],
      gen(rng) { const s = makePie(rng, { mode: "amount" }); const [i, j] = nm2(rng, s); const A = s.fig.slices[i].amount, B = s.fig.slices[j].amount; const p = s.pct[i] + s.pct[j];
        return E(rng, s, { question: `What percent of the ${s.t.ent} ${s.t.verb} ${s.names[i]} or ${s.names[j]}?`, correct: p, wrongs: [W(s.pct[i], "step_missing", "한 부채꼴만 구했다."), W(s.pct[j], "step_missing", "다른 부채꼴만 구했다."), W(100 - p, "opposite", "나머지를 구했다."), W(((A + B) * 100) / (s.N - A), "formula_misuse", "전체에서 하나를 빼고 나눴다."), W(A + B, "unit_error", "수를 그대로 답했다.")], P: { a: s.names[i], b: s.names[j] }, js: `return (am(P.a) + am(P.b)) / T * 100;`, trace: [pieRead(s), [`전체 = ${s.fig.slices.map((x) => x.amount).join(" + ")} = ${s.N} 이다.`, "Add all the sections."], [`두 부채꼴의 합 = ${A} + ${B} = ${A + B} 이다.`, "Add the two sections."], [`${A + B} ÷ ${s.N} = ${p / 100} 이다.`, "Divide by the whole."], [`퍼센트 = ${p}% 이다.`, "Convert to a percent."]], variant: "percent_of_two_sections" }); } },
    { op: "compare_scenarios", structure: "두 부채꼴의 퍼센트를 각각 구해 퍼센트포인트 차를 구함", extra: "각각 전체에 대한 퍼센트로 바꾼 뒤 비교해야 함(수의 차를 그대로 쓰면 틀림) — medium 은 한 부채꼴", concepts: ["원그래프", "퍼센트 구하기", "퍼센트포인트"],
      gen(rng) { const s = makePie(rng, { mode: "amount" }); const [i, j] = nm2(rng, s); const A = s.fig.slices[i].amount, B = s.fig.slices[j].amount; const c = Math.abs(s.pct[i] - s.pct[j]);
        return E(rng, s, { question: `The percent of the ${s.t.ent} in the category "${s.names[i]}" is how many percentage points ${s.pct[i] > s.pct[j] ? "greater" : "less"} than the percent in the category "${s.names[j]}"?`, correct: c, wrongs: [W(Math.abs(A - B), "unit_error", "수의 차를 답했다."), W(s.pct[i], "step_missing", "한 부채꼴의 퍼센트만 답했다."), W(s.pct[j], "step_missing", "다른 부채꼴의 퍼센트만 답했다."), W(s.pct[i] + s.pct[j], "sign_error", "합을 구했다."), W(Math.round((Math.abs(A - B) / Math.min(A, B)) * 100), "formula_misuse", "퍼센트 변화율로 계산했다.")], P: { a: s.names[i], b: s.names[j] }, js: `return Math.abs(am(P.a) - am(P.b)) / T * 100;`, trace: [pieRead(s), [`전체 = ${s.N} 이다.`, "Add all the sections."], [`${s.names[i]} = ${A} ÷ ${s.N} = ${s.pct[i]}% 이다.`, "First percent."], [`${s.names[j]} = ${B} ÷ ${s.N} = ${s.pct[j]}% 이다.`, "Second percent."], [`차 = ${c} 퍼센트포인트이다.`, "Subtract."]], variant: "percentage_point_difference" }); } },
    { op: "inverse", structure: "한 부채꼴에 x 개를 더해 그 부채꼴이 전체의 P% 가 되도록 하는 x 를 구함", extra: "더한 뒤 전체도 함께 커진다는 점을 방정식 (a + x) / (N + x) = P% 로 세워 풀어야 함 — medium 은 퍼센트 계산", concepts: ["원그래프", "퍼센트 구하기", "방정식 역산"],
      gen(rng) { for (let t = 0; t < 120; t++) { const s = makePie(rng, { mode: "amount" }); const i = rng.int(0, s.k - 1); const a = s.fig.slices[i].amount; const Pt = rng.pick([20, 25, 30, 40, 50, 60]); if (Pt <= s.pct[i]) continue; const x = (Pt * s.N - 100 * a) / (100 - Pt); if (!Number.isInteger(x) || x <= 0 || x > 999) continue;
        return E(rng, s, { stim: `More ${s.t.ent} are added to the category "${s.names[i]}" only.`, question: `How many ${s.t.ent} must be added to that category so that it makes up exactly ${Pt}% of all the ${s.t.ent}?`, correct: x, wrongs: [W((Pt * s.N) / 100 - a, "formula_misuse", "전체가 커지는 것을 무시했다."), W((Pt * s.N) / 100, "step_missing", "목표 수를 답했다."), W((x * (100 - Pt)) / 100, "formula_misuse", "계산 중 어긋났다."), W(x + 1, "other", "1 어긋났다."), W(x - 1, "other", "1 어긋났다.")], P: { Pt, a: s.names[i] }, js: `return (P.Pt * T - 100 * am(P.a)) / (100 - P.Pt);`, trace: [pieRead(s), [`전체 = ${s.N}, ${s.names[i]} = ${a} 이다.`, "Total and the section."], [`(${a} + x) ÷ (${s.N} + x) = ${Pt / 100} 로 둔다.`, "The whole also grows."], [`${100 - Pt}x = ${Pt * s.N - 100 * a} 로 정리한다.`, "Clear denominators."], [`x = ${x} 이다.`, "Solve."]], variant: "added_to_reach_percent" }); } throw new GenFail("inverse"); } },
    { op: "compose_kind", structure: "한 부채꼴이 다른 부채꼴보다 몇 퍼센트 더 큰지(변화율 형태)를 구함", extra: "전체 대비 퍼센트가 아니라 두 부채꼴 사이의 증가율을 구해야 함 — medium 은 전체 대비 퍼센트", concepts: ["원그래프", "퍼센트 구하기", "퍼센트 증가"],
      gen(rng) { for (let t = 0; t < 120; t++) { const s = makePie(rng, { mode: "amount" }); const [i, j] = nm2(rng, s); if (s.pct[i] <= s.pct[j]) continue; const r = ((s.pct[i] - s.pct[j]) * 100) / s.pct[j]; if (!Number.isInteger(r)) continue;
        return E(rng, s, { question: `The number of ${s.t.ent} in the category "${s.names[i]}" is what percent greater than the number in the category "${s.names[j]}"?`, correct: r, wrongs: [W(s.pct[i] - s.pct[j], "step_missing", "전체 대비 퍼센트포인트 차를 답했다."), W(((s.pct[i] - s.pct[j]) * 100) / s.pct[i], "opposite", "기준을 큰 쪽으로 잡았다."), W((s.pct[i] * 100) / s.pct[j], "formula_misuse", "비율을 그대로 답했다."), W(r + 10, "other", "계산 중 어긋났다."), W(s.pct[i], "scope", "한 부채꼴의 퍼센트를 답했다.")], P: { a: s.names[i], b: s.names[j] }, js: `return (am(P.a) - am(P.b)) / am(P.b) * 100;`, trace: [pieRead(s), [`${s.names[i]} = ${s.fig.slices[i].amount}, ${s.names[j]} = ${s.fig.slices[j].amount} 이다.`, "Read the two counts."], [`차 = ${s.fig.slices[i].amount - s.fig.slices[j].amount} 이다.`, "Difference."], [`기준은 ${s.names[j]} 이므로 ${s.fig.slices[i].amount - s.fig.slices[j].amount} ÷ ${s.fig.slices[j].amount} 이다.`, "Divide by the base."], [`= ${r}% 이다.`, "Convert."]], variant: "percent_greater_than_other" }); } throw new GenFail("compose"); } },
  ],
  em: [
    { lv: "easy", name: "percent_one", structure: "한 부채꼴의 수를 전체로 나눠 퍼센트를 구함", extra: "easy: 수 ÷ 전체", concepts: ["원그래프", "퍼센트"],
      gen(rng) { const s = makePie(rng, { mode: "amount" }); const i = rng.int(0, s.k - 1); return E(rng, s, { question: `What percent of the ${s.t.ent} ${s.t.verb} ${s.names[i]}?`, correct: s.pct[i], wrongs: [W(s.fig.slices[i].amount, "unit_error", "수를 답했다."), W(100 - s.pct[i], "opposite", "나머지를 구했다."), W(s.pct[i] / 10, "unit_error", "자리를 잘못 옮겼다."), W(Math.round((s.fig.slices[i].amount * 100) / (s.N - s.fig.slices[i].amount)), "formula_misuse", "다른 것들로 나눴다.")], P: { a: s.names[i] }, js: `return am(P.a) / T * 100;`, trace: [pieRead(s), [`전체 = ${s.N} 이다.`, "Add all the sections."], [`${s.fig.slices[i].amount} ÷ ${s.N} = ${s.pct[i] / 100} = ${s.pct[i]}% 이다.`, "Divide."]], variant: "percent_one_section" }); } },
    { lv: "medium", name: "percent_not", structure: "한 부채꼴을 제외한 나머지의 퍼센트를 구함", extra: "medium: 100% - p%", concepts: ["원그래프", "퍼센트", "여사건"],
      gen(rng) { const s = makePie(rng, { mode: "amount" }); const i = rng.int(0, s.k - 1); return E(rng, s, { question: `What percent of the ${s.t.ent} are not in the category "${s.names[i]}"?`, correct: 100 - s.pct[i], wrongs: [W(s.pct[i], "opposite", "그 부채꼴을 답했다."), W(s.N - s.fig.slices[i].amount, "unit_error", "수를 답했다."), W(100 - s.pct[i] - 5, "other", "계산 중 어긋났다."), W(100 - s.pct[i] + 5, "other", "계산 중 어긋났다.")], P: { a: s.names[i] }, js: `return (T - am(P.a)) / T * 100;`, trace: [pieRead(s), [`전체 = ${s.N} 이다.`, "Total."], [`나머지 = ${s.N - s.fig.slices[i].amount} ÷ ${s.N} = ${(100 - s.pct[i]) / 100} = ${100 - s.pct[i]}% 이다.`, "Divide the rest by the whole."]], variant: "percent_not_section" }); } },
  ],
});
export { pos as _pos, f as _f };

// ───────────────────────── ratios_rates_units.proportion.PI.P ─────────────────────────
const sameDist = (s: PieScene) => `The same distribution describes a second, larger group of ${s.t.ent}.`;
export const proportionItem = () => defineItem({
  prefix: "rru", itemId: "ratios_rates_units.proportion.PI.P",
  hard: [
    { op: "inverse", structure: "둘째 집단에서 한 부채꼴의 수가 주어질 때 같은 비율로 다른 부채꼴의 수를 구함", extra: "전체를 모르는 채로 두 부채꼴의 퍼센트 비로 비례식을 세워야 함 — medium 은 같은 집단에서의 비례", concepts: ["원그래프", "비례", "비율"],
      gen(rng) { for (let t = 0; t < 80; t++) { const s = makePie(rng); const [i, j] = nm2(rng, s); const M = rng.pick(N_CHOICES.filter((n) => n !== s.N)); const C = (s.pct[i] * M) / 100; const x = (s.pct[j] * M) / 100;
        return E(rng, s, { stim: `${sameDist(s)} In that group, ${C} ${s.t.ent} ${s.t.verb} ${s.names[i]}.`, question: `How many ${s.t.ent} in the second group ${s.t.verb} ${s.names[j]}?`, correct: x, wrongs: [W(C, "scope", "주어진 수를 답했다."), W((C * s.pct[i]) / s.pct[j], "opposite", "비를 뒤집었다."), W(C + s.pct[j] - s.pct[i], "formula_misuse", "퍼센트 차를 더했다."), W((C * s.pct[j]) / 100, "formula_misuse", "주어진 수에 퍼센트를 곱했다."), W(x + 10, "other", "계산 중 어긋났다.")], P: { C, a: s.names[i], b: s.names[j] }, js: `return P.C * pc(P.b) / pc(P.a);`, trace: [pieRead(s), [`${s.names[i]} : ${s.names[j]} = ${s.pct[i]} : ${s.pct[j]} 이다.`, "Set up the ratio."], [`${C} : x = ${s.pct[i]} : ${s.pct[j]} 로 비례식을 세운다.`, "Write the proportion."], [`x = ${C} × ${s.pct[j]} ÷ ${s.pct[i]} 이다.`, "Cross-multiply."]], variant: "proportion_second_group" }); } throw new GenFail("inverse"); } },
    { op: "unit_ratio", structure: "한 부채꼴이 다른 부채꼴 10 개당 몇 개인지 비율로 구함", extra: "두 퍼센트의 비를 '10 당' 단위비로 바꿔야 함 — medium 은 몇 배인지", concepts: ["원그래프", "단위비", "비율"],
      gen(rng) { for (let t = 0; t < 120; t++) { const s = makePie(rng); const [i, j] = nm2(rng, s); const per = rng.pick([10, 20, 40]); const x = (s.pct[i] * per) / s.pct[j]; if (!Number.isInteger(x)) continue;
        return E(rng, s, { question: `For every ${per} ${s.t.ent} who ${s.t.verb} ${s.names[j]}, how many ${s.t.ent} ${s.t.verb} ${s.names[i]}?`, correct: x, wrongs: [W((s.pct[j] * per) / s.pct[i], "opposite", "비를 뒤집었다."), W(s.pct[i] - s.pct[j] + per, "formula_misuse", "차를 더했다."), W(s.pct[i], "unit_error", "퍼센트를 답했다."), W(x + per / 10, "other", "계산 중 어긋났다."), W((s.pct[i] * per) / 100, "formula_misuse", "퍼센트에 곱하기만 했다.")], P: { per, a: s.names[i], b: s.names[j] }, js: `return P.per * pc(P.a) / pc(P.b);`, trace: [pieRead(s), [`${s.names[i]} 는 ${s.pct[i]}%, ${s.names[j]} 는 ${s.pct[j]}% 이다.`, "Read the two percents."], [`비 = ${s.pct[i]} : ${s.pct[j]} 이다.`, "Form the ratio."], [`${per} 에 맞추면 x = ${per} × ${s.pct[i]} ÷ ${s.pct[j]} 이다.`, "Scale the ratio."]], variant: "per_ten_unit_ratio" }); } throw new GenFail("unit_ratio"); } },
    { op: "chain2", structure: "둘째 집단에서 한 부채꼴의 수로 전체를 구한 뒤 두 부채꼴 어느 쪽도 아닌 수를 구함", extra: "전체 역산 → 여러 부채꼴의 합 → 나머지의 연쇄 — medium 은 한 부채꼴", concepts: ["원그래프", "비례", "합과 나머지"],
      gen(rng) { const s = makePie(rng, { k: 5 }); const idx = rng.shuffle([...s.names.keys()]); const [a, b, c] = idx; const M = rng.pick(N_CHOICES.filter((n) => n !== s.N)); const C = (s.pct[a] * M) / 100; const ans = ((100 - s.pct[b] - s.pct[c]) * M) / 100;
        return E(rng, s, { stim: `${sameDist(s)} In that group, ${C} ${s.t.ent} ${s.t.verb} ${s.names[a]}.`, question: `How many ${s.t.ent} in the second group ${s.t.verb} neither ${s.names[b]} nor ${s.names[c]}?`, correct: ans, wrongs: [W(((s.pct[b] + s.pct[c]) * M) / 100, "opposite", "두 부채꼴의 합을 답했다."), W(M, "step_missing", "전체를 답했다."), W(C, "scope", "주어진 수를 답했다."), W(ans + M / 20, "other", "계산 중 어긋났다."), W(((100 - s.pct[b] - s.pct[c]) * C) / 100, "formula_misuse", "주어진 수에 퍼센트를 곱했다.")], P: { C, a: s.names[a], b: s.names[b], c: s.names[c] }, js: `const M = P.C / pc(P.a) * 100; return M - (pc(P.b) + pc(P.c)) * M / 100;`, trace: [pieRead(s), [`${s.names[a]} = ${s.pct[a]}% 이고 ${C} 이므로 전체 = ${C} ÷ ${s.pct[a] / 100} = ${M} 이다.`, "Find the total of the second group."], [`${s.names[b]} + ${s.names[c]} = ${s.pct[b] + s.pct[c]}% 이다.`, "Add the two percents."], [`나머지 = ${100 - s.pct[b] - s.pct[c]}% 이다.`, "Complement."], [`${M} × ${(100 - s.pct[b] - s.pct[c]) / 100} = ${f(ans)} 이다.`, "Apply it."]], variant: "neither_of_two_sections" }); } },
    { op: "compare_scenarios", structure: "같은 분포를 가진 두 집단(전체가 다름)에서 한 부채꼴의 수의 차를 구함", extra: "각 집단에 같은 비율을 적용한 뒤 비교해야 함 — medium 은 한 집단", concepts: ["원그래프", "비례", "두 집단 비교"],
      gen(rng) { const s = makePie(rng); const i = rng.int(0, s.k - 1); const M = rng.pick(N_CHOICES.filter((n) => n !== s.N)); const A1 = (s.pct[i] * s.N) / 100, A2 = (s.pct[i] * M) / 100; const c = Math.abs(A1 - A2);
        return E(rng, s, { withTotal: true, stim: `${sameDist(s)} The second group has ${M} ${s.t.ent} in all.`, question: `How many more ${s.t.ent} ${s.t.verb} ${s.names[i]} in the ${s.N > M ? "first" : "second"} group than in the ${s.N > M ? "second" : "first"} group?`, correct: c, wrongs: [W(Math.abs(s.N - M), "step_missing", "전체의 차를 답했다."), W(A1, "step_missing", "한 집단의 수만 답했다."), W(A2, "step_missing", "다른 집단의 수만 답했다."), W(A1 + A2, "sign_error", "합을 구했다."), W(c + 10, "other", "계산 중 어긋났다.")], P: { N1: s.N, N2: M, a: s.names[i] }, js: `return Math.abs(P.N1 - P.N2) * pc(P.a) / 100;`, trace: [pieRead(s), [`첫째 집단: ${s.N} × ${s.pct[i] / 100} = ${A1} 이다.`, "First group."], [`둘째 집단: ${M} × ${s.pct[i] / 100} = ${A2} 이다.`, "Second group."], [`차 = |${A1} - ${A2}| = ${c} 이다.`, "Positive difference."]], variant: "same_share_two_groups" }); } },
  ],
  em: [
    { lv: "easy", name: "times_as_many", structure: "한 부채꼴이 다른 부채꼴의 몇 배인지 퍼센트의 비로 구함", extra: "easy: 퍼센트의 비", concepts: ["원그래프", "비율"],
      gen(rng) { for (let t = 0; t < 120; t++) { const s = makePie(rng); const [i, j] = nm2(rng, s); if (s.pct[i] % s.pct[j] !== 0 || s.pct[i] === s.pct[j]) continue; const x = s.pct[i] / s.pct[j];
        return E(rng, s, { question: `The number of ${s.t.ent} who ${s.t.verb} ${s.names[i]} is how many times the number who ${s.t.verb} ${s.names[j]}?`, correct: x, wrongs: [W(s.pct[i] - s.pct[j], "formula_misuse", "차를 답했다."), W(s.pct[i], "unit_error", "퍼센트를 답했다."), W(x + 1, "other", "1 어긋났다."), W(Math.max(1, x - 1), "other", "1 어긋났다.")], P: { a: s.names[i], b: s.names[j] }, js: `return pc(P.a) / pc(P.b);`, trace: [pieRead(s), [`${s.pct[i]} ÷ ${s.pct[j]} = ${x} 이다.`, "Divide the percents."]], variant: "times_as_many" }); } throw new GenFail("times"); } },
    { lv: "medium", name: "same_group_count", structure: "같은 집단에서 한 부채꼴의 수로 다른 부채꼴의 수를 비례로 구함", extra: "medium: 비례식", concepts: ["원그래프", "비례"],
      gen(rng) { const s = makePie(rng); const [i, j] = nm2(rng, s); const C = (s.pct[i] * s.N) / 100; const x = (s.pct[j] * s.N) / 100; return E(rng, s, { stim: `${C} ${s.t.ent} ${s.t.verb} ${s.names[i]}.`, question: `How many ${s.t.ent} ${s.t.verb} ${s.names[j]}?`, correct: x, wrongs: [W(C, "scope", "주어진 수를 답했다."), W((C * s.pct[i]) / s.pct[j], "opposite", "비를 뒤집었다."), W(C + s.pct[j] - s.pct[i], "formula_misuse", "퍼센트 차를 더했다."), W(x + 10, "other", "계산 중 어긋났다.")], P: { C, a: s.names[i], b: s.names[j] }, js: `return P.C * pc(P.b) / pc(P.a);`, trace: [pieRead(s), [`${C} : x = ${s.pct[i]} : ${s.pct[j]} 이다.`, "Set up the proportion."], [`x = ${f(x)} 이다.`, "Solve."]], variant: "same_group_proportion" }); } },
  ],
});

// ───────────────────────── probability.simple.PI.P ─────────────────────────
const pickOne = (rng: Rng, s: PieScene) => rng.pick([`One ${s.t.ent1} is chosen at random from the group.`, `A single ${s.t.ent1} is selected at random.`, `Suppose one of the ${s.t.ent} is picked at random.`, `Each ${s.t.ent1} is equally likely to be chosen, and one is chosen.`]);
export const probSimpleItem = () => defineItem({
  prefix: "pr", itemId: "probability.simple.PI.P",
  hard: [
    { op: "chain2", structure: "한 부채꼴에 속하지 않는 개체 중에서 다른 부채꼴에 속할 조건부 확률을 구함", extra: "표본 공간이 '그 부채꼴이 아닌 것' 으로 줄어든다는 점을 반영해야 함 — medium 은 한 부채꼴의 확률", concepts: ["원그래프", "조건부 확률"],
      gen(rng) { const s = makePie(rng); const [i, j] = nm2(rng, s);
        return EF(rng, s, { stim: `${pickOne(rng, s)} It is known that the chosen ${s.t.ent1} did not ${s.t.verb === "were about" ? "match" : "belong to"} the category "${s.names[i]}".`, question: `What is the probability that the chosen ${s.t.ent1} is in the category "${s.names[j]}"?`, num: s.pct[j], den: 100 - s.pct[i], wrongs: [FW(s.pct[j], 100, "condition_ignored", "조건을 쓰지 않았다."), FW(s.pct[j], s.pct[i], "scope", "제외한 부채꼴로 나눴다."), FW(100 - s.pct[i], 100, "opposite", "제외한 부채꼴의 여사건을 답했다."), FW(s.pct[i], 100 - s.pct[j], "axis_misread", "두 부채꼴을 바꿨다."), FW(s.pct[j] - 5, 100 - s.pct[i], "other", "분자가 어긋났다.")], P: { a: s.names[i], b: s.names[j] }, js: `return pc(P.b) / (100 - pc(P.a));`, trace: [pieRead(s), [`${s.names[i]} 가 아닌 것은 ${100 - s.pct[i]}% 이다.`, "The sample space shrinks."], [`${s.names[j]} 는 ${s.pct[j]}% 이다.`, "The favorable share."], [`확률 = ${s.pct[j]} ÷ ${100 - s.pct[i]} 이다.`, "Divide."]], variant: "conditional_not_in_section" }); } },
    { op: "compare_scenarios", structure: "두 부채꼴을 합한 확률과 다른 한 부채꼴의 확률의 차를 구함", extra: "합의 확률과 한 부채꼴의 확률을 모두 구해 비교 — medium 은 합의 확률", concepts: ["원그래프", "확률", "두 사건 비교"],
      gen(rng) { const s = makePie(rng, { k: 5 }); const [a, b, c] = rng.shuffle([...s.names.keys()]); const u = s.pct[a] + s.pct[b], v = s.pct[c]; if (u === v) throw new GenFail("eq"); const d = Math.abs(u - v);
        return EF(rng, s, { stim: pickOne(rng, s), question: `How much greater is the probability that the chosen ${s.t.ent1} is in the category "${u > v ? `${s.names[a]}" or "${s.names[b]}` : s.names[c]}" than the probability that the chosen ${s.t.ent1} is in the category "${u > v ? s.names[c] : `${s.names[a]}" or "${s.names[b]}`}"?`, num: d, den: 100, wrongs: [FW(u, 100, "step_missing", "합의 확률만 답했다."), FW(v, 100, "step_missing", "한 부채꼴의 확률만 답했다."), FW(u + v, 100, "sign_error", "합을 구했다."), FW(d + 5, 100, "other", "분자가 어긋났다."), FW(d, 50, "formula_misuse", "분모를 잘못 잡았다.")], P: { a: s.names[a], b: s.names[b], c: s.names[c] }, js: `return Math.abs(pc(P.a) + pc(P.b) - pc(P.c)) / 100;`, trace: [pieRead(s), [`P(${s.names[a]} 또는 ${s.names[b]}) = ${u}/100 이다.`, "Add the two sections."], [`P(${s.names[c]}) = ${v}/100 이다.`, "The other section."], [`차 = ${d}/100 이다.`, "Subtract."]], variant: "union_vs_single_probability" }); } },
    { op: "compose_kind", structure: "복원추출로 두 번 뽑을 때 둘 다 같은 부채꼴일 확률(독립 사건의 곱)을 구함", extra: "확률을 곱으로 합성하고 분수를 약분해야 함 — medium 은 한 부채꼴의 확률", concepts: ["원그래프", "확률", "독립 사건"],
      gen(rng) { const s = makePie(rng); const i = rng.int(0, s.k - 1);
        return EF(rng, s, { stim: `One ${s.t.ent1} is chosen at random, recorded, and put back. Then a second ${s.t.ent1} is chosen at random.`, question: `What is the probability that both chosen ${s.t.ent} are in the category "${s.names[i]}"?`, num: s.pct[i] * s.pct[i], den: 10000, wrongs: [FW(s.pct[i], 100, "step_missing", "한 번의 확률만 답했다."), FW(2 * s.pct[i], 100, "formula_misuse", "곱 대신 합을 구했다."), FW(s.pct[i] * (s.pct[i] - 5), 100 * 95, "formula_misuse", "비복원으로 계산했다."), FW(s.pct[i] * s.pct[i], 1000, "unit_error", "분모를 잘못 잡았다."), FW(s.pct[i] * 2, 10000, "other", "제곱 대신 곱하기 2 를 했다.")], P: { a: s.names[i] }, js: `return (pc(P.a) / 100) ** 2;`, trace: [pieRead(s), [`한 번 뽑을 때 ${s.names[i]} 일 확률은 ${s.pct[i]}/100 이다.`, "Single draw."], [`뽑은 것을 되돌려 놓으므로 두 번은 독립이다.`, "Draws are independent."], [`곱 = (${s.pct[i]}/100) × (${s.pct[i]}/100) 이다.`, "Multiply."]], variant: "two_draws_with_replacement" }); } },
    { op: "constraint_select", structure: "기준 T% 보다 큰 비율을 가진 부채꼴 전체에 속할 확률을 구함", extra: "조건에 맞는 부채꼴을 가려 퍼센트를 합해야 함(같은 경우 제외) — medium 은 두 부채꼴", concepts: ["원그래프", "확률", "조건 선택"],
      gen(rng) { const s = makePie(rng); const T = rng.pick(s.pct); const sel = s.pct.filter((p) => p > T); if (!sel.length) throw new GenFail("none"); const sm = sel.reduce((a, b) => a + b, 0); if (sm === 100) throw new GenFail("all");
        return EF(rng, s, { stim: pickOne(rng, s), question: `What is the probability that the chosen ${s.t.ent1} is in a category that makes up more than ${T}% of the whole?`, num: sm, den: 100, wrongs: [FW(sm + T, 100, "condition_ignored", "경계 값까지 더했다."), FW(sm, 100 - T, "formula_misuse", "분모를 잘못 잡았다."), FW(100 - sm, 100, "opposite", "기준 이하를 답했다."), FW(sel.length, s.k, "step_missing", "부채꼴의 개수 비로 답했다."), FW(Math.max(sm - 5, 5), 100, "other", "분자가 어긋났다.")], P: { T }, js: `return pcs.filter(p => p > P.T).reduce((a, b) => a + b, 0) / 100;`, trace: [pieRead(s), [`기준은 ${T}% 보다 큰 것(같은 것은 제외)이다.`, "Strictly greater."], [`해당 부채꼴: ${s.pct.filter((p) => p > T).join("%, ")}% 이다.`, "Select the sections."], [`합 = ${sm}% 이므로 확률은 ${sm}/100 이다.`, "Add them."]], variant: "sections_above_threshold" }); } },
  ],
  em: [
    { lv: "easy", name: "one_section", structure: "한 부채꼴에 속할 확률을 퍼센트로 구함", extra: "easy: p/100", concepts: ["원그래프", "확률"],
      gen(rng) { const s = makePie(rng); const i = rng.int(0, s.k - 1); return EF(rng, s, { stim: pickOne(rng, s), question: `What is the probability that the chosen ${s.t.ent1} is in the category "${s.names[i]}"?`, num: s.pct[i], den: 100, wrongs: [FW(s.pct[i], 100 - s.pct[i], "formula_misuse", "비(odds)를 구했다."), FW(100 - s.pct[i], 100, "opposite", "여사건을 답했다."), FW(1, s.k, "axis_misread", "부채꼴 개수로 나눴다."), FW(s.pct[i] + 5, 100, "other", "분자가 어긋났다.")], P: { a: s.names[i] }, js: `return pc(P.a) / 100;`, trace: [pieRead(s), [`${s.names[i]} 는 ${s.pct[i]}% 이므로 확률은 ${s.pct[i]}/100 이다.`, "Percent to probability."]], variant: "one_section_probability" }); } },
    { lv: "medium", name: "two_sections", structure: "두 부채꼴 중 하나에 속할 확률을 퍼센트 합으로 구함", extra: "medium: 퍼센트 합", concepts: ["원그래프", "확률", "합"],
      gen(rng) { const s = makePie(rng); const [i, j] = nm2(rng, s); return EF(rng, s, { stim: pickOne(rng, s), question: `What is the probability that the chosen ${s.t.ent1} is in the category "${s.names[i]}" or "${s.names[j]}"?`, num: s.pct[i] + s.pct[j], den: 100, wrongs: [FW(s.pct[i], 100, "step_missing", "한 부채꼴만 답했다."), FW(s.pct[j], 100, "step_missing", "다른 부채꼴만 답했다."), FW(s.pct[i] * s.pct[j], 10000, "formula_misuse", "곱을 구했다."), FW(100 - s.pct[i] - s.pct[j], 100, "opposite", "나머지를 답했다.")], P: { a: s.names[i], b: s.names[j] }, js: `return (pc(P.a) + pc(P.b)) / 100;`, trace: [pieRead(s), [`${s.names[i]} 는 ${s.pct[i]}%, ${s.names[j]} 는 ${s.pct[j]}% 이다.`, "Read the two percents."], [`${s.pct[i]} + ${s.pct[j]} = ${s.pct[i] + s.pct[j]}% 이다.`, "Add."]], variant: "two_sections_probability" }); } },
  ],
});

// ───────────────────────── probability.sequential_without_replacement.PI.P ─────────────────────────
const SEQ_N = [20, 40, 60, 80, 100];
const seqIntro = (s: PieScene) => `Two ${s.t.ent} are chosen at random, one after the other, without replacement.`;
export const sequentialItem = () => defineItem({
  prefix: "pr", itemId: "probability.sequential_without_replacement.PI.P",
  hard: [
    { op: "chain2", structure: "비복원으로 두 번 뽑을 때 둘 다 같은 부채꼴일 확률(조건부 곱)을 구함", extra: "두 번째 뽑기의 분모·분자가 하나씩 줄어드는 곱을 세워야 함 — medium 은 첫 번째 확률", concepts: ["원그래프", "비복원 확률", "곱의 법칙"],
      gen(rng) { const s = makePie(rng, { N: rng.pick(SEQ_N) }); const i = rng.int(0, s.k - 1); const c = (s.pct[i] * s.N) / 100; if (c < 2) throw new GenFail("c");
        return EF(rng, s, { withTotal: true, stim: seqIntro(s), question: `What is the probability that both ${s.t.ent} are in the category "${s.names[i]}"?`, num: c * (c - 1), den: s.N * (s.N - 1), wrongs: [FW(c * c, s.N * s.N, "formula_misuse", "복원으로 계산했다."), FW(c * (c - 1), s.N * s.N, "formula_misuse", "분모를 줄이지 않았다."), FW(c, s.N, "step_missing", "첫 번째 확률만 답했다."), FW(c * c, s.N * (s.N - 1), "formula_misuse", "분자를 줄이지 않았다."), FW(c * (c - 1) * 2, s.N * (s.N - 1), "other", "순서를 두 번 센 것으로 보았다.")], P: { N: s.N, a: s.names[i] }, js: `const c = pc(P.a) * P.N / 100; return c * (c - 1) / (P.N * (P.N - 1));`, trace: [pieRead(s), [`${s.names[i]} 는 ${s.N} × ${s.pct[i] / 100} = ${c} 이다.`, "Count of the category."], [`첫 번째가 ${s.names[i]} 일 확률 = ${c}/${s.N} 이다.`, "First draw."], [`두 번째는 ${c - 1}/${s.N - 1} 이다.`, "Second draw, one fewer of each."], [`곱 = ${c}/${s.N} × ${c - 1}/${s.N - 1} 이다.`, "Multiply."]], variant: "both_same_section" }); } },
    { op: "compare_scenarios", structure: "두 부채꼴에 대해 각각 '둘 다 그 부채꼴'일 확률을 구해 차를 구함", extra: "같은 분모에서 서로 다른 분자를 비교 — medium 은 한 부채꼴", concepts: ["원그래프", "비복원 확률", "두 사건 비교"],
      gen(rng) { const s = makePie(rng, { N: rng.pick(SEQ_N) }); const [i, j] = nm2(rng, s); const ci = (s.pct[i] * s.N) / 100, cj = (s.pct[j] * s.N) / 100; if (ci < 2 || cj < 2) throw new GenFail("c"); const a = ci * (ci - 1), b = cj * (cj - 1); if (a === b) throw new GenFail("eq"); const hi = a > b ? i : j, lo = a > b ? j : i; const d = Math.abs(a - b), D = s.N * (s.N - 1);
        return EF(rng, s, { withTotal: true, stim: seqIntro(s), question: `How much greater is the probability that both are in the category "${s.names[hi]}" than the probability that both are in the category "${s.names[lo]}"?`, num: d, den: D, wrongs: [FW(Math.max(a, b), D, "step_missing", "한 확률만 답했다."), FW(a + b, D, "sign_error", "합을 구했다."), FW(Math.abs(ci * ci - cj * cj), s.N * s.N, "formula_misuse", "복원으로 계산했다."), FW(Math.abs(ci - cj), s.N, "scope", "첫 번째 확률의 차를 답했다."), FW(d, s.N * s.N, "formula_misuse", "분모를 줄이지 않았다.")], P: { N: s.N, a: s.names[hi], b: s.names[lo] }, js: `const ca = pc(P.a) * P.N / 100, cb = pc(P.b) * P.N / 100; return (ca * (ca - 1) - cb * (cb - 1)) / (P.N * (P.N - 1));`, trace: [pieRead(s), [`${s.names[hi]} = ${hi === i ? ci : cj}, ${s.names[lo]} = ${lo === i ? ci : cj} 이다.`, "Counts."], [`P(둘 다 ${s.names[hi]}) = ${a > b ? a : b}/${D} 이다.`, "First probability."], [`P(둘 다 ${s.names[lo]}) = ${a > b ? b : a}/${D} 이다.`, "Second probability."], [`차 = ${d}/${D} 이다.`, "Subtract."]], variant: "both_same_two_sections" }); } },
    { op: "constraint_select", structure: "비복원으로 두 번 뽑을 때 적어도 하나가 어떤 부채꼴일 확률(여사건)을 구함", extra: "'둘 다 아님' 의 확률을 구해 1 에서 빼야 함 — medium 은 첫 번째 확률", concepts: ["원그래프", "비복원 확률", "여사건"],
      gen(rng) { const s = makePie(rng, { N: rng.pick(SEQ_N) }); const i = rng.int(0, s.k - 1); const c = (s.pct[i] * s.N) / 100; const m = s.N - c; const D = s.N * (s.N - 1);
        return EF(rng, s, { withTotal: true, stim: seqIntro(s), question: `What is the probability that at least one of the two is in the category "${s.names[i]}"?`, num: D - m * (m - 1), den: D, wrongs: [FW(m * (m - 1), D, "opposite", "둘 다 아닐 확률을 답했다."), FW(D - m * m, s.N * s.N, "formula_misuse", "복원으로 계산했다."), FW(2 * c, s.N, "formula_misuse", "합으로 계산했다."), FW(c, s.N, "step_missing", "첫 번째 확률만 답했다."), FW(D - m * (m - 1) - c, D, "other", "분자가 어긋났다.")], P: { N: s.N, a: s.names[i] }, js: `const c = pc(P.a) * P.N / 100, m = P.N - c; return 1 - m * (m - 1) / (P.N * (P.N - 1));`, trace: [pieRead(s), [`${s.names[i]} 는 ${c}, 아닌 것은 ${m} 이다.`, "Counts."], [`둘 다 아닐 확률 = ${m}/${s.N} × ${m - 1}/${s.N - 1} = ${m * (m - 1)}/${D} 이다.`, "Neither."], [`적어도 하나 = 1 - ${m * (m - 1)}/${D} 이다.`, "Complement."], [`= ${D - m * (m - 1)}/${D} 이다.`, "Simplify."]], variant: "at_least_one_in_section" }); } },
    { op: "compose_kind", structure: "비복원으로 두 번 뽑을 때 첫 번째가 한 부채꼴, 두 번째가 다른 부채꼴일 확률을 구함", extra: "서로 다른 두 범주를 순서대로 뽑는 곱(두 번째 분모만 줄어듦)을 세워야 함 — medium 은 두 번째의 조건부 확률", concepts: ["원그래프", "비복원 확률", "순서 있는 사건"],
      gen(rng) { const s = makePie(rng, { N: rng.pick(SEQ_N) }); const [i, j] = nm2(rng, s); const ci = (s.pct[i] * s.N) / 100, cj = (s.pct[j] * s.N) / 100; const D = s.N * (s.N - 1);
        return EF(rng, s, { withTotal: true, stim: seqIntro(s), question: `What is the probability that the first is in the category "${s.names[i]}" and the second is in the category "${s.names[j]}"?`, num: ci * cj, den: D, wrongs: [FW(ci * cj, s.N * s.N, "formula_misuse", "복원으로 계산했다."), FW(2 * ci * cj, D, "formula_misuse", "순서를 두 가지로 셌다."), FW(ci * (cj - 1), D, "other", "두 번째 개수를 줄였다."), FW(ci + cj, s.N, "formula_misuse", "합으로 계산했다."), FW(cj * (cj - 1), D, "axis_misread", "같은 부채꼴로 보았다.")], P: { N: s.N, a: s.names[i], b: s.names[j] }, js: `const ca = pc(P.a) * P.N / 100, cb = pc(P.b) * P.N / 100; return ca * cb / (P.N * (P.N - 1));`, trace: [pieRead(s), [`${s.names[i]} = ${ci}, ${s.names[j]} = ${cj} 이다.`, "Counts."], [`첫 번째가 ${s.names[i]} 일 확률 = ${ci}/${s.N} 이다.`, "First draw."], [`두 번째가 ${s.names[j]} 일 확률 = ${cj}/${s.N - 1} 이다.`, "Second draw."], [`곱 = ${ci * cj}/${D} 이다.`, "Multiply."]], variant: "first_a_then_b" }); } },
  ],
  em: [
    { lv: "easy", name: "first_draw", structure: "첫 번째로 뽑은 것이 한 부채꼴에 속할 확률을 구함", extra: "easy: 수 ÷ 전체", concepts: ["원그래프", "확률"],
      gen(rng) { const s = makePie(rng, { N: rng.pick(SEQ_N) }); const i = rng.int(0, s.k - 1); const c = (s.pct[i] * s.N) / 100; return EF(rng, s, { withTotal: true, stim: seqIntro(s), question: `What is the probability that the first one chosen is in the category "${s.names[i]}"?`, num: c, den: s.N, wrongs: [FW(c, s.N - 1, "scope", "분모를 줄였다."), FW(c - 1, s.N - 1, "scope", "두 번째 뽑기로 계산했다."), FW(s.N - c, s.N, "opposite", "여사건을 답했다."), FW(c + 1, s.N, "other", "분자가 어긋났다.")], P: { N: s.N, a: s.names[i] }, js: `return pc(P.a) * P.N / 100 / P.N;`, trace: [pieRead(s), [`${s.names[i]} = ${c}, 전체 = ${s.N} 이므로 ${c}/${s.N} 이다.`, "Count over total."]], variant: "first_draw_probability" }); } },
    { lv: "medium", name: "second_given_first", structure: "첫 번째가 한 부채꼴이었을 때 두 번째가 다른 부채꼴일 조건부 확률을 구함", extra: "medium: 분모가 하나 줄어듦", concepts: ["원그래프", "비복원 확률", "조건부 확률"],
      gen(rng) { const s = makePie(rng, { N: rng.pick(SEQ_N) }); const [i, j] = nm2(rng, s); const cj = (s.pct[j] * s.N) / 100; return EF(rng, s, { withTotal: true, stim: `${seqIntro(s)} The first one chosen is in the category "${s.names[i]}".`, question: `What is the probability that the second one is in the category "${s.names[j]}"?`, num: cj, den: s.N - 1, wrongs: [FW(cj, s.N, "scope", "분모를 줄이지 않았다."), FW(cj - 1, s.N - 1, "scope", "분자를 줄였다."), FW(cj, s.N - 2, "other", "분모를 두 번 줄였다."), FW(s.N - cj, s.N - 1, "opposite", "나머지를 답했다.")], P: { N: s.N, b: s.names[j] }, js: `return pc(P.b) * P.N / 100 / (P.N - 1);`, trace: [pieRead(s), [`${s.names[j]} = ${cj} 이다.`, "Count."], [`한 명이 빠졌으므로 전체는 ${s.N - 1} 이다.`, "One fewer remains."], [`확률 = ${cj}/${s.N - 1} 이다.`, "Divide."]], variant: "second_given_first_probability" }); } },
  ],
});

// ───────────────────────── circles.sector_area.PI.P ─────────────────────────
const UNITS = ["centimeters", "inches", "meters", "feet"];
const R_CHOICES = [10, 20, 30, 40, 50];
const circIntro = (rng: Rng, s: PieScene, r: number, u: string) => `${pieIntro(rng, s)} The pie chart is drawn as a circle with a radius of ${r} ${u}.`;
const sqU = (u: string) => `square ${u}`;
export const sectorAreaItem = () => defineItem({
  prefix: "ci", itemId: "circles.sector_area.PI.P",
  hard: [
    { op: "chain2", structure: "두 부채꼴의 중심각(퍼센트)을 합해 원 전체 넓이에 대한 비율로 두 부채꼴을 합한 넓이를 구함", extra: "각 부채꼴의 비율을 합한 뒤 πr² 에 곱하는 연쇄 — medium 은 한 부채꼴의 넓이", concepts: ["원그래프", "부채꼴 넓이", "비율의 합"],
      gen(rng) { const s = makePie(rng, { mode: rng.pick(["percent", "degrees"] as const) }); const [i, j] = nm2(rng, s); const r = rng.pick(R_CHOICES), u = rng.pick(UNITS); const k = ((s.pct[i] + s.pct[j]) * r * r) / 100;
        return E(rng, s, { stim: `The pie chart is drawn as a circle with a radius of ${r} ${u}. The combined area of the sections "${s.names[i]}" and "${s.names[j]}" is $k\\pi$ ${sqU(u)}.`, question: "What is the value of $k$?", correct: k, wrongs: [W((s.pct[i] * r * r) / 100, "step_missing", "한 부채꼴만 구했다."), W((s.pct[j] * r * r) / 100, "step_missing", "다른 부채꼴만 구했다."), W(r * r, "step_missing", "원 전체의 넓이를 답했다."), W(((s.pct[i] + s.pct[j]) * 2 * r) / 100, "formula_misuse", "원주 공식으로 계산했다."), W(s.pct[i] + s.pct[j], "unit_error", "퍼센트를 답했다.")], P: { r, a: s.names[i], b: s.names[j] }, js: `return (pc(P.a) + pc(P.b)) / 100 * P.r * P.r;`, trace: [pieRead(s), [`두 부채꼴의 비율 = ${s.pct[i]}% + ${s.pct[j]}% = ${s.pct[i] + s.pct[j]}% 이다.`, "Add the fractions of the circle."], [`원 전체의 넓이 = π × ${r}² = ${r * r}π 이다.`, "Area of the whole circle."], [`${r * r}π × ${(s.pct[i] + s.pct[j]) / 100} = ${f(k)}π 이다.`, "Multiply."]], variant: "two_sector_areas" }); } },
    { op: "compare_scenarios", structure: "두 부채꼴의 넓이를 각각 구해 그 차를 구함", extra: "각 부채꼴의 비율을 πr² 에 곱한 뒤 비교 — medium 은 한 부채꼴", concepts: ["원그래프", "부채꼴 넓이", "두 경우 비교"],
      gen(rng) { const s = makePie(rng, { mode: rng.pick(["percent", "degrees"] as const) }); const [i, j] = nm2(rng, s); const r = rng.pick(R_CHOICES), u = rng.pick(UNITS); const A = (s.pct[i] * r * r) / 100, B = (s.pct[j] * r * r) / 100; const k = Math.abs(A - B);
        return E(rng, s, { stim: `The pie chart is drawn as a circle with a radius of ${r} ${u}. The area of the section "${A > B ? s.names[i] : s.names[j]}" is $k\\pi$ ${sqU(u)} greater than the area of the section "${A > B ? s.names[j] : s.names[i]}".`, question: "What is the value of $k$?", correct: k, wrongs: [W(A, "step_missing", "한 부채꼴만 답했다."), W(B, "step_missing", "다른 부채꼴만 답했다."), W(A + B, "sign_error", "합을 구했다."), W(Math.abs(s.pct[i] - s.pct[j]), "unit_error", "퍼센트 차를 답했다."), W(Math.round((k * 2) / r), "formula_misuse", "계산 중 어긋났다.")], P: { r, a: s.names[i], b: s.names[j] }, js: `return Math.abs(pc(P.a) - pc(P.b)) / 100 * P.r * P.r;`, trace: [pieRead(s), [`${s.names[i]}: ${s.pct[i]}% × ${r * r}π = ${f(A)}π 이다.`, "First sector."], [`${s.names[j]}: ${s.pct[j]}% × ${r * r}π = ${f(B)}π 이다.`, "Second sector."], [`차 = ${f(k)}π 이다.`, "Subtract."]], variant: "sector_area_difference" }); } },
    { op: "inverse", structure: "한 부채꼴의 넓이 kπ 와 그 비율로 원의 반지름을 역으로 구함", extra: "넓이 = 비율 × πr² 을 거꾸로 써서 r² 을 구하고 제곱근을 취해야 함 — medium 은 넓이 계산", concepts: ["원그래프", "부채꼴 넓이", "반지름 역산"],
      gen(rng) { for (let t = 0; t < 40; t++) { const s = makePie(rng, { mode: rng.pick(["percent", "degrees"] as const) }); const i = rng.int(0, s.k - 1); const r = rng.pick(R_CHOICES), u = rng.pick(UNITS); const k = (s.pct[i] * r * r) / 100; if (k >= 1000) continue;
        return E(rng, s, { stim: `The pie chart is drawn as a circle. The area of the section "${s.names[i]}" is ${f(k)}$\\pi$ ${sqU(u)}.`, question: `What is the radius of the circle, in ${u}?`, correct: r, wrongs: [W(r * r, "step_missing", "제곱근을 취하지 않았다."), W(k, "scope", "넓이 계수를 답했다."), W(Math.round(Math.sqrt(k)), "step_missing", "비율을 반영하지 않았다."), W((k * 100) / s.pct[i] / 2, "formula_misuse", "원주 공식으로 계산했다."), W(r + 10, "other", "계산 중 어긋났다.")], P: { k, a: s.names[i] }, js: `const r2 = P.k * 100 / pc(P.a); const r = Math.round(Math.sqrt(r2)); if (r * r !== Math.round(r2)) throw new Error('반지름이 정수가 아님'); return r;`, trace: [pieRead(s), [`부채꼴의 비율은 ${s.pct[i]}% 이다.`, "Fraction of the circle."], [`π r² × ${s.pct[i] / 100} = ${f(k)}π 이다.`, "Set up the area equation."], [`r² = ${f(k)} ÷ ${s.pct[i] / 100} = ${r * r} 이다.`, "Solve for r squared."], [`r = ${r} 이다.`, "Take the square root."]], variant: "radius_from_sector_area" }); } throw new GenFail("r"); } },
    { op: "compose_kind", structure: "부채꼴의 넓이 대신 호의 길이를 구하는 문제로 합성(둘레 공식과 비율)", extra: "넓이 공식이 아닌 원둘레 2πr 에 비율을 곱해야 함 — medium 은 넓이", concepts: ["원그래프", "호의 길이", "비율"],
      gen(rng) { for (let t = 0; t < 120; t++) { const s = makePie(rng, { mode: rng.pick(["percent", "degrees"] as const) }); const i = rng.int(0, s.k - 1); const r = rng.pick(R_CHOICES), u = rng.pick(UNITS); const k = (s.pct[i] * 2 * r) / 100; if (!Number.isInteger(k)) continue;
        return E(rng, s, { stim: `The pie chart is drawn as a circle with a radius of ${r} ${u}. The length of the arc along the edge of the section "${s.names[i]}" is $k\\pi$ ${u}.`, question: "What is the value of $k$?", correct: k, wrongs: [W((s.pct[i] * r * r) / 100, "formula_misuse", "넓이로 계산했다."), W(2 * r, "step_missing", "원둘레 계수를 답했다."), W(k / 2, "formula_misuse", "지름 대신 반지름을 썼다."), W(k * 2, "formula_misuse", "비율을 두 번 반영했다."), W(s.pct[i], "unit_error", "퍼센트를 답했다.")], P: { r, a: s.names[i] }, js: `return pc(P.a) / 100 * 2 * P.r;`, trace: [pieRead(s), [`부채꼴의 비율은 ${s.pct[i]}% 이다.`, "Fraction of the circle."], [`원둘레 = 2π × ${r} = ${2 * r}π 이다.`, "Circumference."], [`호의 길이 = ${2 * r}π × ${s.pct[i] / 100} = ${f(k)}π 이다.`, "Multiply."]], variant: "arc_length_from_section" }); } throw new GenFail("arc"); } },
  ],
  em: [
    { lv: "easy", name: "one_sector_area", structure: "한 부채꼴의 비율에 원 전체 넓이를 곱해 부채꼴의 넓이를 구함", extra: "easy: 비율 × πr²", concepts: ["원그래프", "부채꼴 넓이"],
      gen(rng) { const s = makePie(rng, { mode: rng.pick(["percent", "degrees"] as const) }); const i = rng.int(0, s.k - 1); const r = rng.pick(R_CHOICES), u = rng.pick(UNITS); const k = (s.pct[i] * r * r) / 100; return E(rng, s, { stim: `The pie chart is drawn as a circle with a radius of ${r} ${u}. The area of the section "${s.names[i]}" is $k\\pi$ ${sqU(u)}.`, question: "What is the value of $k$?", correct: k, wrongs: [W(r * r, "step_missing", "원 전체의 넓이를 답했다."), W(s.pct[i], "unit_error", "퍼센트를 답했다."), W((s.pct[i] * 2 * r) / 100, "formula_misuse", "원주 공식으로 계산했다."), W(k + r, "other", "계산 중 어긋났다.")], P: { r, a: s.names[i] }, js: `return pc(P.a) / 100 * P.r * P.r;`, trace: [pieRead(s), [`원 전체의 넓이 = ${r * r}π, 비율 = ${s.pct[i]}% 이다.`, "Whole circle and fraction."], [`${r * r} × ${s.pct[i] / 100} = ${f(k)} 이다.`, "Multiply."]], variant: "one_sector_area" }); } },
    { lv: "medium", name: "rest_of_circle", structure: "한 부채꼴을 제외한 나머지 부분의 넓이를 구함", extra: "medium: 나머지 비율", concepts: ["원그래프", "부채꼴 넓이", "나머지"],
      gen(rng) { const s = makePie(rng, { mode: rng.pick(["percent", "degrees"] as const) }); const i = rng.int(0, s.k - 1); const r = rng.pick(R_CHOICES), u = rng.pick(UNITS); const k = ((100 - s.pct[i]) * r * r) / 100; return E(rng, s, { stim: `The pie chart is drawn as a circle with a radius of ${r} ${u}. The total area of all the sections other than "${s.names[i]}" is $k\\pi$ ${sqU(u)}.`, question: "What is the value of $k$?", correct: k, wrongs: [W((s.pct[i] * r * r) / 100, "opposite", "그 부채꼴의 넓이를 답했다."), W(r * r, "step_missing", "원 전체의 넓이를 답했다."), W(100 - s.pct[i], "unit_error", "퍼센트를 답했다."), W(k + r, "other", "계산 중 어긋났다.")], P: { r, a: s.names[i] }, js: `return (100 - pc(P.a)) / 100 * P.r * P.r;`, trace: [pieRead(s), [`나머지 비율 = ${100 - s.pct[i]}% 이다.`, "Complement."], [`${r * r} × ${(100 - s.pct[i]) / 100} = ${f(k)} 이다.`, "Multiply."]], variant: "rest_sector_area" }); } },
  ],
});

// ───────────────────────── probability.spinner_expected_value.PI.P ─────────────────────────
const PRIZES = [0, 1, 2, 3, 5, 8, 10, 15, 20, 25, 50];
const SP_TOPICS = [
  { game: "a prize game", where: "at a school carnival", title: "Carnival spinner" }, { game: "a points game", where: "in a game room", title: "Arcade spinner" }, { game: "a reward game", where: "in a math class", title: "Reward spinner" },
  { game: "a prize game", where: "at a charity event", title: "Fundraiser spinner" }, { game: "a points game", where: "on family game night", title: "Board game spinner" }, { game: "a reward game", where: "on a school radio show", title: "Quiz show spinner" },
  { game: "a prize game", where: "at a county fair", title: "Fair spinner" }, { game: "a points game", where: "during a reading week", title: "Reading spinner" }, { game: "a reward game", where: "at a science museum", title: "Museum spinner" },
  { game: "a prize game", where: "in a puzzle app", title: "Bonus wheel" }, { game: "a points game", where: "at a pep rally", title: "Rally spinner" }, { game: "a reward game", where: "at a bake sale", title: "Bake sale spinner" },
];
type SpScene = { t: (typeof SP_TOPICS)[number]; names: string[]; pct: number[]; vals: number[]; k: number; fig: PieSpec; ev: number };
function makeSpinner(rng: Rng): SpScene {
  const k = rng.int(4, 5); const vals = rng.shuffle(PRIZES).slice(0, k); const pct = pctSet(rng, k, true); const names = vals.map((v) => `${v}`);
  const t = rng.pick(SP_TOPICS); const fig: PieSpec = { type: "pie", format: "percent", title: t.title, slices: names.map((label, i) => ({ label, amount: pct[i] })) };
  if (renderPie(fig).issues.length) throw new GenFail("스피너 라벨 배치");
  const ev = Math.round(vals.reduce((a, v, i) => a + (v * pct[i]) / 100, 0) * 100) / 100;
  return { t, names, pct, vals, k, fig, ev };
}
const spIntro = (rng: Rng, s: SpScene) => rng.pick([`In ${s.t.game} ${s.t.where}, a player spins the spinner shown in the pie chart once. Each section is labeled with the number of points it awards, and its size is its percent of the whole spinner.`, `The pie chart shown is the spinner for ${s.t.game} ${s.t.where}. The label on a section is the number of points awarded, and the percent is the chance of landing on that section.`, "A game uses the spinner shown in the pie chart. Each section is labeled with the number of points it awards, and the size of each section is its percent of the whole spinner.", "In the game described by the pie chart shown, a player spins the spinner once. The label on each section is the number of points awarded, and each section's size is given as a percent.", "The pie chart shown is a spinner for a prize game. The label on a section is the number of points awarded, and the percent is the chance of landing on that section."]);
const SP_JS = "const sl=FIGURE.slices; const T=sl.reduce((a,s)=>a+s.amount,0); const val=sl.map(s=>Number(s.label)); const p=sl.map(s=>s.amount/T); const ev=val.reduce((a,v,i)=>a+v*p[i],0); const r6=(x)=>Math.round(x*1e6)/1e6;\n";
const SD = (rng: Rng, s: SpScene, d: { stim?: string; question: string; correct: number; wrongs: ReturnType<typeof W>[]; js: string; P?: Record<string, number | string>; trace: [string, string][]; variant: string; text?: { num: number; den: number; wt: { text: string; kind: DistractorKind; reason: string }[] } }): Instance =>
  gInst(rng, { stimulus: `${spIntro(rng, s)}${d.stim ? ` ${d.stim}` : ""} ${rng.pick(PLEADS)}`, question: d.question, ...(d.text ? { correctText: frac(d.text.num, d.text.den), range: [0, 1] as [number, number], wrongTexts: d.text.wt.filter((w) => w.text !== frac(d.text!.num, d.text!.den)) } : { correct: d.correct, wrongs: pos(d.wrongs).filter((w) => Math.abs(w.v - d.correct) > 1e-9) }), verificationJs: figJs(d.P ?? {}, s.fig, `${SP_JS}${d.js}`), trace: d.trace.length >= 4 ? [...d.trace, [`따라서 답은 ${d.text ? frac(d.text.num, d.text.den) : f(d.correct)} 이다.`, "That is the requested value."]] : d.trace, variant: d.variant }, s.fig);
const evStep = (s: SpScene): [string, string] => [`기댓값 = ${s.vals.map((v, i) => `${v}×${s.pct[i] / 100}`).join(" + ")} = ${f(s.ev)} 이다.`, "Multiply each prize by its probability and add."];
const spRead = (s: SpScene): [string, string] => [`스피너에서 점수와 확률을 읽는다: ${s.names.map((n, i) => `${n} (${s.pct[i]}%)`).join(", ")}.`, "Read each prize and its percent."];
export const spinnerItem = () => defineItem({
  prefix: "pr", itemId: "probability.spinner_expected_value.PI.P",
  hard: [
    { op: "chain2", structure: "스피너의 기댓값을 구한 뒤 한 번 돌리는 데 드는 비용을 빼 순기댓값을 구함", extra: "상금×확률의 합 → 비용 차감의 연쇄 — medium 은 기댓값", concepts: ["원그래프", "기댓값", "순이익"],
      gen(rng) { const s = makeSpinner(rng); if (s.ev < 2) throw new GenFail('ev'); const c = rng.int(1, Math.min(8, Math.floor(s.ev) - 0 || 1)); if (c >= s.ev) throw new GenFail('c'); const net = Math.round((s.ev - c) * 100) / 100;
        return SD(rng, s, { stim: `It costs ${c} points to play the game once.`, question: rng.pick(["What is the expected net gain, in points, for one play of the game?", "On average, how many points does a player gain per play after paying the cost?", "What is the expected number of points a player nets from one play?"]), correct: net, wrongs: [W(s.ev, "step_missing", "비용을 빼지 않았다."), W(Math.round((s.ev + c) * 100) / 100, "sign_error", "비용을 더했다."), W(c, "scope", "비용을 답했다."), W(Math.round((s.vals.reduce((a, b) => a + b, 0) / s.k - c) * 100) / 100, "formula_misuse", "확률을 무시하고 평균 상금을 썼다."), W(Math.round((net + 1) * 100) / 100, "other", "1 어긋났다.")].filter((w) => true), P: { c }, js: `return r6(ev - P.c);`, trace: [spRead(s), evStep(s), [`한 번에 드는 비용은 ${c} 이다.`, "Cost of one play."], [`순기댓값 = ${f(s.ev)} - ${c} = ${f(net)} 이다.`, "Subtract the cost."]], variant: "net_expected_gain" }); } },
    { op: "compare_scenarios", structure: "스피너의 기댓값과 고정 상금 F 를 받는 경우의 차를 구함", extra: "기댓값을 구해 확정 금액과 비교(부호 포함 절댓값) — medium 은 기댓값", concepts: ["원그래프", "기댓값", "두 선택 비교"],
      gen(rng) { const s = makeSpinner(rng); const F = rng.int(1, 12); if (Math.abs(s.ev - F) < 0.01) throw new GenFail("eq"); const d = Math.round(Math.abs(s.ev - F) * 100) / 100;
        return SD(rng, s, { stim: `Instead of spinning, a player may take a sure ${F} points.`, question: rng.pick([`By how many points does the expected award from one spin ${s.ev > F ? "exceed" : "fall short of"} the sure prize?`, `How far is the expected number of points from one spin ${s.ev > F ? "above" : "below"} the sure ${F} points?`, `What is the positive difference between the expected number of points from one spin and the sure ${F} points?`]), correct: d, wrongs: [W(s.ev, "step_missing", "기댓값만 답했다."), W(F, "scope", "확정 상금을 답했다."), W(Math.round((s.ev + F) * 100) / 100, "sign_error", "합을 구했다."), W(Math.abs(Math.round((s.vals.reduce((a, b) => a + b, 0) / s.k - F) * 100) / 100), "formula_misuse", "확률을 무시했다."), W(Math.round((d + 1) * 100) / 100, "other", "1 어긋났다.")], P: { F }, js: `return r6(Math.abs(ev - P.F));`, trace: [spRead(s), evStep(s), [`확정 상금은 ${F} 이다.`, "The sure prize."], [`차 = |${f(s.ev)} - ${F}| = ${f(d)} 이다.`, "Positive difference."]], variant: "expected_vs_sure_prize" }); } },
    { op: "inverse", structure: "한 구역의 상금을 새 금액 x 로 바꿔 기댓값이 T 가 되도록 하는 x 를 구함", extra: "기댓값 식에서 한 항을 거꾸로 풀어야 함 — medium 은 기댓값 계산", concepts: ["원그래프", "기댓값", "역산"],
      gen(rng) { for (let t = 0; t < 120; t++) { const s = makeSpinner(rng); const i = rng.int(0, s.k - 1); const x = rng.int(0, 60); if (x === s.vals[i]) continue; const T = Math.round((s.ev + ((x - s.vals[i]) * s.pct[i]) / 100) * 100) / 100; if (!Number.isInteger(Math.round(T * 10 * 1000) / 1000)) continue;
        return SD(rng, s, { stim: rng.pick([`The award on the section labeled "${s.names[i]}" is changed to a new number of points, and the expected award from one spin becomes ${f(T)} points.`, `Organizers revise only the section labeled "${s.names[i]}" so that it awards a different number of points; afterward, the expected number of points per spin is ${f(T)}.`, `Only the section labeled "${s.names[i]}" is relabeled with a new point value, and the new expected number of points for one spin is ${f(T)}.`]), question: rng.pick(["What is the new number of points for that section?", "How many points must that section award after the change?", "After the change, how many points does that section award?"]), correct: x, wrongs: [W(Math.round(T * 100) / 100, "step_missing", "새 기댓값을 답했다."), W(s.vals[i], "scope", "원래 상금을 답했다."), W(Math.round((T - s.ev) * 100) / 100, "formula_misuse", "기댓값의 차를 답했다."), W(Math.round(((T - s.ev) * 100) / s.pct[i] * 100) / 100 + 1, "other", "1 어긋났다."), W(x + 5, "other", "계산 중 어긋났다.")], P: { T, nm: s.names[i] }, js: `const i = sl.findIndex(x => x.label === P.nm); const others = ev - val[i] * p[i]; return r6((P.T - others) / p[i]);`, trace: [spRead(s), [`바꾸는 구역의 확률은 ${s.pct[i]}% 이다.`, "Probability of the changed section."], [`나머지 구역의 기여분 = ${f(s.ev)} - ${s.vals[i]}×${s.pct[i] / 100} = ${f(Math.round((s.ev - (s.vals[i] * s.pct[i]) / 100) * 100) / 100)} 이다.`, "Contribution of the other sections."], [`${f(T)} = (나머지) + x×${s.pct[i] / 100} 로 둔다.`, "Set up the equation."], [`x = ${x} 이다.`, "Solve."]], variant: "new_prize_for_target_ev" }); } throw new GenFail("inverse"); } },
    { op: "unit_ratio", structure: "n 번 돌렸을 때의 기대 총 상금(기댓값 × 횟수)을 구함", extra: "한 번의 기댓값을 횟수로 확장하는 단위 환산 — medium 은 한 번의 기댓값", concepts: ["원그래프", "기댓값", "횟수 환산"],
      gen(rng) { for (let t = 0; t < 120; t++) { const s = makeSpinner(rng); const n = rng.pick([10, 20, 40, 50, 100]); const tot = Math.round(s.ev * n * 100) / 100; if (!Number.isInteger(tot * 4)) continue;
        return SD(rng, s, { stim: `A player spins ${n} times.`, question: rng.pick([`Based on the expected prize per spin, what is the expected total of the points over the ${n} spins?`, `About how many points in total should the player expect over the ${n} spins?`, `What is the expected total number of points after ${n} spins?`]), correct: tot, wrongs: [W(s.ev, "step_missing", "한 번의 기댓값만 답했다."), W(Math.round((s.vals.reduce((a, b) => a + b, 0) / s.k) * n * 100) / 100, "formula_misuse", "확률을 무시했다."), W(Math.max(...s.vals) * n, "scope", "최대 상금으로 계산했다."), W(Math.round((tot + n) * 100) / 100, "other", "계산 중 어긋났다."), W(Math.round((s.ev + n) * 100) / 100, "formula_misuse", "곱 대신 합을 구했다.")], P: { n }, js: `return r6(ev * P.n);`, trace: [spRead(s), evStep(s), [`${n} 번 돌린다.`, "Number of spins."], [`기대 총 상금 = ${f(s.ev)} × ${n} = ${f(tot)} 이다.`, "Multiply."]], variant: "expected_total_over_spins" }); } throw new GenFail("unit"); } },
  ],
  em: [
    { lv: "easy", name: "probability_at_least", structure: "상금이 T 이상인 구역에 멈출 확률을 퍼센트 합으로 구함", extra: "easy: 퍼센트 합", concepts: ["원그래프", "확률"],
      gen(rng) { const s = makeSpinner(rng); const T = rng.pick(s.vals.filter((v) => v > 0)); const sel = s.pct.filter((_, i) => s.vals[i] >= T).reduce((a, b) => a + b, 0); if (sel === 100) throw new GenFail("all"); return SD(rng, s, { question: rng.pick([`What is the probability that the number of points from one spin is at least ${T}?`, `A player spins once. What is the probability of getting ${T} or more points?`, `What is the chance that one spin awards at least ${T} points?`, `If the spinner is spun once, what is the probability that the points awarded are ${T} or greater?`]), correct: 0, text: { num: sel, den: 100, wt: [FW(sel, 100 - sel, "formula_misuse", "비(odds)를 구했다."), FW(100 - sel, 100, "opposite", "여사건을 답했다."), FW(s.vals.filter((v) => v >= T).length, s.k, "step_missing", "구역의 개수 비로 답했다."), FW(sel + 5, 100, "other", "분자가 어긋났다.")] }, wrongs: [], P: { T }, js: `return val.reduce((a, v, i) => a + (v >= P.T ? p[i] : 0), 0);`, trace: [spRead(s), [`상금이 ${T} 이상인 구역의 퍼센트 합 = ${sel}% 이다.`, "Add the sections."]], variant: "probability_prize_at_least" }); } },
    { lv: "medium", name: "expected_value", structure: "스피너의 기댓값(상금×확률의 합)을 구함", extra: "medium: 가중 합", concepts: ["원그래프", "기댓값"],
      gen(rng) { const s = makeSpinner(rng); return SD(rng, s, { question: rng.pick(["What is the expected number of points for one spin?", "On average, how many points does one spin award?", "What is the mean number of points a player gets per spin in the long run?", "What is the expected value, in points, of a single spin?"]), correct: s.ev, wrongs: [W(Math.round((s.vals.reduce((a, b) => a + b, 0) / s.k) * 100) / 100, "formula_misuse", "확률을 무시하고 평균을 냈다."), W(Math.max(...s.vals), "scope", "최대 상금을 답했다."), W(s.vals.reduce((a, b) => a + b, 0), "step_missing", "상금의 합을 답했다."), W(Math.round((s.ev + 1) * 100) / 100, "other", "1 어긋났다.")], js: `return r6(ev);`, trace: [spRead(s), [`각 점수에 그 확률을 곱한다: ${s.vals.map((v, i) => `${v}×${s.pct[i] / 100}`).join(", ")}.`, "Multiply each value by its probability."], evStep(s)], variant: "expected_value" }); } },
  ],
});
