// 누적(쌓은) 막대그래프(SB) 공용 장면 키트 — two_variable_data.{cell,row_total,conditional_share}.SB.P · percentages.percent_change.SB.P.
// 규칙(자료 계열 공통): 수치를 먼저 뽑고 → figure(stacked_bar)를 만들고 → 지문은 값을 되풀이하지 않고 "the stacked bar graph shown" 으로 가리킨다. 정보는 자료에만 있다.
// 모든 값은 눈금 간격 U 의 배수이고 한 막대의 높이는 8U 이하라서 조각 안 값 라벨이 들어가고 눈금으로도 읽힌다.
import { GenFail, type Instance } from "../../types";
import type { Rng } from "../../rng";
import { fmtNum, frac } from "../../text";
import type { DistractorKind } from "../../../review";
import { W } from "../d-kit";
import { figJs } from "../../figure-kit";
import { defineItem } from "./item-kit";
import { gInst } from "./graph-kit";
import { renderStackedBar, type StackedBarSpec } from "@/lib/problem-figures/templates/stacked-bar";

const f = fmtNum;
export type SbTopic = { ent: string; what: string; where: string; rowHead: string; rowNoun: string; axisUnit: string; rows: string[]; cols: string[]; yUnit: string };
export const SB_TOPICS: SbTopic[] = [
  { ent: "students", what: "how students travel to school", where: "at a high school", rowHead: "Grade", axisUnit: "grade level", rowNoun: "grade level", rows: ["Grade 9", "Grade 10", "Grade 11", "Grade 12"], cols: ["Bus", "Walk", "Car", "Bike"], yUnit: "students" },
  { ent: "customers", what: "how customers paid", where: "at a store", rowHead: "Day", axisUnit: "day", rowNoun: "day of week", rows: ["Friday", "Saturday", "Sunday"], cols: ["Cash", "Card", "Phone"], yUnit: "customers" },
  { ent: "residents", what: "the type of home residents live in", where: "in a town", rowHead: "District", axisUnit: "area", rowNoun: "district", rows: ["North", "South", "East", "West"], cols: ["House", "Apartment", "Condo"], yUnit: "residents" },
  { ent: "members", what: "which activity members chose", where: "at a community center", rowHead: "Age group", axisUnit: "years", rowNoun: "age group", rows: ["Under 20", "20 to 39", "40 to 59", "60 and over"], cols: ["Fitness", "Art", "Music"], yUnit: "members" },
  { ent: "voters", what: "how voters answered a survey question", where: "in a county", rowHead: "Town", axisUnit: "name", rowNoun: "town", rows: ["Ashford", "Brook", "Cedar"], cols: ["Yes", "No", "Undecided"], yUnit: "voters" },
  { ent: "readers", what: "the format of the books readers borrowed", where: "from a library", rowHead: "Month", axisUnit: "name", rowNoun: "month", rows: ["March", "April", "May"], cols: ["Print", "Audio", "E-book"], yUnit: "readers" },
  { ent: "visitors", what: "which exhibit visitors saw first", where: "at a museum", rowHead: "Season", axisUnit: "name", rowNoun: "season", rows: ["Spring", "Summer", "Fall", "Winter"], cols: ["Space", "Ocean", "Dinosaurs"], yUnit: "visitors" },
  { ent: "employees", what: "how employees commute", where: "at a company", rowHead: "Office", axisUnit: "name", rowNoun: "office", rows: ["Main", "Harbor", "Hillside"], cols: ["Train", "Drive", "Bike", "Walk"], yUnit: "employees" },
  { ent: "patients", what: "which clinic service patients used", where: "at a health clinic", rowHead: "Clinic", axisUnit: "name", rowNoun: "clinic", rows: ["Downtown", "Lakeside", "Westgate"], cols: ["Checkup", "Vaccine", "Lab test"], yUnit: "patients" },
  { ent: "players", what: "which position players play", where: "in a youth league", rowHead: "Team", axisUnit: "name", rowNoun: "team", rows: ["Hawks", "Wolves", "Bears", "Eagles"], cols: ["Forward", "Midfield", "Defense"], yUnit: "players" },
];
export type SbScene = { t: SbTopic; rows: string[]; cols: string[]; U: number; units: number[][]; fig: StackedBarSpec; v: (r: number, c: number) => number; tot: (r: number) => number };
const U_CHOICES = [5, 10, 20, 25, 50];
export function makeSB(rng: Rng, o: { nr?: number; nc?: number; distinct?: boolean } = {}): SbScene {
  for (let tr = 0; tr < 60; tr++) {
    const t = rng.pick(SB_TOPICS); const nr = o.nr ?? rng.int(2, Math.min(3, t.rows.length)); const nc = o.nc ?? rng.int(2, Math.min(3, t.cols.length)); const U = rng.pick(U_CHOICES);
    const rows = rng.shuffle(t.rows).slice(0, nr).sort((a, b) => t.rows.indexOf(a) - t.rows.indexOf(b)); const cols = rng.shuffle(t.cols).slice(0, nc).sort((a, b) => t.cols.indexOf(a) - t.cols.indexOf(b));
    const units = rows.map(() => cols.map(() => rng.int(1, 3))); if (units.some((r) => r.reduce((a, b) => a + b, 0) > 8)) continue;
    if (o.distinct) { const flat = units.flat(); if (new Set(flat).size < Math.min(flat.length, 3)) continue; }
    const maxTot = Math.max(...units.map((r) => r.reduce((a, b) => a + b, 0)));
    const fig: StackedBarSpec = { type: "stacked_bar", title: t.what.charAt(0).toUpperCase() + t.what.slice(1), categories: rows, series: cols.map((name, j) => ({ name, values: units.map((r) => r[j] * U) })), xTitle: `${t.rowHead} (${t.axisUnit})`, yTitle: `${t.yUnit.charAt(0).toUpperCase() + t.yUnit.slice(1)} (count)`, yStep: U, yMax: (maxTot + 1) * U, showValues: true };
    if (fig.title!.length > 60) fig.title = fig.title!.slice(0, 60);
    if (renderStackedBar(fig).issues.length) continue;
    return { t, rows, cols, U, units, fig, v: (r, c) => units[r][c] * U, tot: (r) => units[r].reduce((a, b) => a + b, 0) * U };
  }
  throw new GenFail("누적 막대 장면");
}
export const SB_JS = "const C=FIGURE.categories, S=FIGURE.series; const ci=(c)=>{ const i=C.indexOf(c); if(i<0) throw new Error('범주 없음'); return i; }; const si=(s)=>{ const j=S.findIndex(x=>x.name===s); if(j<0) throw new Error('계열 없음'); return j; }; const v=(c,s)=>S[si(s)].values[ci(c)]; const tot=(c)=>S.reduce((a,x)=>a+x.values[ci(c)],0); const grand=C.reduce((a,c)=>a+tot(c),0); const sTot=(s)=>C.reduce((a,c)=>a+v(c,s),0); const r6=(x)=>Math.round(x*1e6)/1e6;\n";
export const SLEADS = [
  "Use the information in the graph to answer the question.", "Refer to the graph when answering the question that follows.", "Answer the question using only the data in the graph.", "Study the graph carefully before answering.",
  "The graph contains all of the data needed for this question.", "Consider the data displayed in the graph.", "Examine the graph and then answer the question below.", "Base your answer on the data the graph displays.",
  "Each segment of a bar is labeled with its value.", "The legend tells which shade stands for which category.", "Read the labels on both axes before you begin.", "Each bar is split into segments, one for each answer.",
];
export const sbIntro = (rng: Rng, s: SbScene) => rng.pick([
  `The stacked bar graph shown gives ${s.t.what} ${s.t.where}. Each bar is one ${s.t.rowNoun}.`,
  `A stacked bar graph is shown for ${s.t.what} ${s.t.where}; the segments of each bar show the number of ${s.t.ent} in each category.`,
  `The stacked bar graph shown displays ${s.t.what} ${s.t.where}, with one bar for each ${s.t.rowNoun}.`,
  `In the stacked bar graph shown, each bar represents one ${s.t.rowNoun}, and its segments show ${s.t.what} ${s.t.where}.`,
]);
export const sbRead = (s: SbScene): [string, string] => [`그래프의 조각 값을 읽는다: ${s.rows.map((r, i) => `${r}(${s.cols.map((c, j) => `${c} ${s.v(i, j)}`).join(", ")})`).join("; ")}.`, "Read the value of every segment."];
const pos = (ws: ReturnType<typeof W>[]) => ws.filter((w) => w.v >= 0);
const tr5 = (t: [string, string][], ans: string, min: number): [string, string][] => { const o: [string, string][] = [...t, [`따라서 답은 ${ans} 이다.`, "That is the requested value."]]; while (o.length < min) o.splice(o.length - 1, 0, ["결과를 그래프와 다시 대조해 확인한다.", "Check the result against the graph."]); return o; };
type D = { stim?: string; question: string | string[]; correct: number; wrongs: ReturnType<typeof W>[]; js: string; P?: Record<string, number | string>; trace: [string, string][]; variant: string; min?: number };
export const SD = (rng: Rng, s: SbScene, d: D): Instance => gInst(rng, { stimulus: `${sbIntro(rng, s)}${d.stim ? ` ${d.stim}` : ""} ${rng.pick(SLEADS)}`, question: Array.isArray(d.question) ? rng.pick(d.question) : d.question, correct: d.correct, wrongs: pos(d.wrongs).filter((w) => Math.abs(w.v - d.correct) > 1e-9), verificationJs: figJs(d.P ?? {}, s.fig, `${SB_JS}${d.js}`), trace: tr5(d.trace, f(d.correct), d.min ?? 5), variant: d.variant }, s.fig);
const FW = (n: number, d: number, kind: DistractorKind, reason: string) => ({ text: frac(n, d), kind, reason });
type DF = { stim?: string; question: string | string[]; num: number; den: number; wrongs: { text: string; kind: DistractorKind; reason: string }[]; js: string; P?: Record<string, number | string>; trace: [string, string][]; variant: string; min?: number };
export const SF = (rng: Rng, s: SbScene, d: DF): Instance => gInst(rng, { stimulus: `${sbIntro(rng, s)}${d.stim ? ` ${d.stim}` : ""} ${rng.pick(SLEADS)}`, question: Array.isArray(d.question) ? rng.pick(d.question) : d.question, correctText: frac(d.num, d.den), range: [0, 1], wrongTexts: d.wrongs.filter((w) => w.text !== frac(d.num, d.den)), verificationJs: figJs(d.P ?? {}, s.fig, `${SB_JS}${d.js}`), trace: tr5(d.trace, frac(d.num, d.den), d.min ?? 5), variant: d.variant }, s.fig);
const two = (rng: Rng, n: number): [number, number] => { const [a, b] = rng.shuffle([...Array(n).keys()]); return [a, b]; };

// ───────────────────────── two_variable_data.cell.SB.P ─────────────────────────
export const cellItem = () => defineItem({
  prefix: "tvd", itemId: "two_variable_data.cell.SB.P",
  hard: [
    { op: "chain2", structure: "누적 막대에서 한 막대의 두 조각 값을 읽어 더함", extra: "조각 하나가 아니라 두 조각을 읽어 합해야 함 — medium 은 한 조각", concepts: ["누적 막대그래프", "조각 읽기", "합"],
      gen(rng) { const s = makeSB(rng, { nc: 3 }); const r = rng.int(0, s.rows.length - 1); const [a, b] = two(rng, 3); const ans = s.v(r, a) + s.v(r, b);
        return SD(rng, s, { question: [`How many ${s.t.ent} in ${s.rows[r]} are in the categories "${s.cols[a]}" or "${s.cols[b]}"?`, `What is the combined number of ${s.t.ent} in ${s.rows[r]} in the "${s.cols[a]}" and "${s.cols[b]}" categories?`], correct: ans, wrongs: [W(s.v(r, a), "step_missing", "한 조각만 답했다."), W(s.v(r, b), "step_missing", "다른 조각만 답했다."), W(s.tot(r), "scope", "막대 전체를 답했다."), W(s.tot(r) - ans, "opposite", "나머지 조각을 답했다."), W(s.v(r, a) + s.v(r, b) + s.U, "other", "한 눈금 어긋났다.")], P: { r: s.rows[r], a: s.cols[a], b: s.cols[b] }, js: `return v(P.r, P.a) + v(P.r, P.b);`, trace: [sbRead(s), [`${s.rows[r]} 의 ${s.cols[a]} = ${s.v(r, a)} 이다.`, "First segment."], [`${s.rows[r]} 의 ${s.cols[b]} = ${s.v(r, b)} 이다.`, "Second segment."], [`합 = ${ans} 이다.`, "Add."]], variant: "two_segments_in_one_bar" }); } },
    { op: "compare_scenarios", structure: "두 막대에서 같은 범주의 조각 값을 읽어 그 차를 구함", extra: "두 막대의 조각을 각각 읽고 비교 — medium 은 한 조각", concepts: ["누적 막대그래프", "조각 읽기", "두 막대 비교"],
      gen(rng) { const s = makeSB(rng); const [r1, r2] = two(rng, s.rows.length); const c = rng.int(0, s.cols.length - 1); if (s.v(r1, c) === s.v(r2, c)) throw new GenFail("eq"); const hi = s.v(r1, c) > s.v(r2, c) ? r1 : r2, lo = hi === r1 ? r2 : r1; const d = s.v(hi, c) - s.v(lo, c);
        return SD(rng, s, { question: [`How many more ${s.t.ent} in the "${s.cols[c]}" category are there in ${s.rows[hi]} than in ${s.rows[lo]}?`, `By how many does the "${s.cols[c]}" segment of ${s.rows[hi]} exceed the "${s.cols[c]}" segment of ${s.rows[lo]}?`], correct: d, wrongs: [W(s.v(hi, c), "step_missing", "한 조각만 답했다."), W(s.v(lo, c), "step_missing", "다른 조각만 답했다."), W(s.v(hi, c) + s.v(lo, c), "sign_error", "합을 구했다."), W(Math.abs(s.tot(hi) - s.tot(lo)), "scope", "막대 전체의 차를 답했다."), W(d + s.U, "other", "한 눈금 어긋났다.")], P: { a: s.rows[hi], b: s.rows[lo], c: s.cols[c] }, js: `return v(P.a, P.c) - v(P.b, P.c);`, trace: [sbRead(s), [`${s.rows[hi]} 의 ${s.cols[c]} = ${s.v(hi, c)} 이다.`, "First bar."], [`${s.rows[lo]} 의 ${s.cols[c]} = ${s.v(lo, c)} 이다.`, "Second bar."], [`차 = ${d} 이다.`, "Subtract."]], variant: "same_category_two_bars" }); } },
    { op: "inverse", structure: "분포가 같은 다른 막대의 전체 수가 주어질 때, 그림의 비율로 한 범주의 수를 구함", extra: "조각 ÷ 막대 전체의 비율을 구해 새 전체에 적용 — medium 은 조각 읽기", concepts: ["누적 막대그래프", "비율", "비례"],
      gen(rng) { for (let t = 0; t < 80; t++) { const s = makeSB(rng); const r = rng.int(0, s.rows.length - 1); const c = rng.int(0, s.cols.length - 1); const T = rng.pick([100, 120, 150, 200, 240, 300, 400, 500]); const ans = (s.v(r, c) * T) / s.tot(r); if (!Number.isInteger(ans)) continue;
        return SD(rng, s, { stim: `Another group of ${s.t.ent} has the same distribution as ${s.rows[r]}, but there are ${T} ${s.t.ent} in all.`, question: [`How many ${s.t.ent} in the other group are in the "${s.cols[c]}" category?`, `Based on the same distribution, how many of the ${T} ${s.t.ent} are in the "${s.cols[c]}" category?`], correct: ans, wrongs: [W(s.v(r, c), "scope", "그림의 값을 그대로 답했다."), W((s.tot(r) * T) / s.v(r, c), "opposite", "비율을 뒤집었다."), W(T - ans, "opposite", "나머지를 구했다."), W(Math.round((s.v(r, c) / s.tot(r)) * 100), "unit_error", "퍼센트를 답했다."), W(ans + T / 20, "other", "계산 중 어긋났다.")], P: { r: s.rows[r], c: s.cols[c], T }, js: `return r6(v(P.r, P.c) * P.T / tot(P.r));`, trace: [sbRead(s), [`${s.rows[r]} 의 ${s.cols[c]} = ${s.v(r, c)}, 막대 전체 = ${s.tot(r)} 이다.`, "Segment and bar total."], [`비율 = ${s.v(r, c)} ÷ ${s.tot(r)} 이다.`, "Share of the bar."], [`${T} × ${s.v(r, c)} ÷ ${s.tot(r)} = ${f(ans)} 이다.`, "Apply the share."]], variant: "scale_distribution_to_new_total" }); } throw new GenFail("inverse"); } },
    { op: "constraint_select", structure: "한 범주의 조각이 다른 범주의 조각보다 큰 막대의 개수를 셈", extra: "막대마다 두 조각을 비교하고 같은 경우를 제외해 세야 함 — medium 은 한 막대", concepts: ["누적 막대그래프", "조각 비교", "조건 개수"],
      gen(rng) { for (let t = 0; t < 80; t++) { const s = makeSB(rng, { nr: 3 }); const [a, b] = two(rng, s.cols.length); const cnt = s.rows.filter((_, r) => s.v(r, a) > s.v(r, b)).length; const ge = s.rows.filter((_, r) => s.v(r, a) >= s.v(r, b)).length; if (cnt < 1 || cnt > 2 || ge === cnt) continue;
        return SD(rng, s, { question: [`In how many of the bars is the "${s.cols[a]}" segment greater than the "${s.cols[b]}" segment?`, `For how many of the bars is the number of ${s.t.ent} in "${s.cols[a]}" greater than the number in "${s.cols[b]}"?`], correct: cnt, wrongs: [W(ge, "condition_ignored", "같은 경우까지 셌다."), W(s.rows.length - cnt, "opposite", "반대 경우를 셌다."), W(s.rows.length, "condition_ignored", "전체를 답했다."), W(cnt + 2, "other", "개수가 어긋났다."), W(0, "condition_ignored", "해당하는 막대가 없다고 보았다.")], P: { a: s.cols[a], b: s.cols[b] }, js: `return C.filter((c) => v(c, P.a) > v(c, P.b)).length;`, trace: [sbRead(s), [`막대별 ${s.cols[a]} / ${s.cols[b]}: ${s.rows.map((r, i) => `${s.v(i, a)}/${s.v(i, b)}`).join(", ")} 이다.`, "Compare the two segments in each bar."], [`${s.cols[a]} 가 더 큰 막대(같은 것 제외)를 센다.`, "Strictly greater."], [`개수는 ${cnt} 이다.`, "Count."]], variant: "count_bars_a_greater_than_b" }); } throw new GenFail("select"); } },
  ],
  em: [
    { lv: "easy", name: "read_segment", structure: "누적 막대에서 한 조각의 값을 읽음", extra: "easy: 조각 읽기", concepts: ["누적 막대그래프", "조각 읽기"],
      gen(rng) { const s = makeSB(rng); const r = rng.int(0, s.rows.length - 1), c = rng.int(0, s.cols.length - 1); return SD(rng, s, { question: `How many ${s.t.ent} in ${s.rows[r]} are in the "${s.cols[c]}" category?`, correct: s.v(r, c), wrongs: [W(s.tot(r), "scope", "막대 전체를 답했다."), W(s.v(r, (c + 1) % s.cols.length), "axis_misread", "다른 조각을 읽었다."), W(s.v((r + 1) % s.rows.length, c), "axis_misread", "다른 막대를 읽었다."), W(s.v(r, c) + s.U, "other", "한 눈금 어긋났다.")], P: { r: s.rows[r], c: s.cols[c] }, js: `return v(P.r, P.c);`, trace: [sbRead(s), [`${s.rows[r]} 의 ${s.cols[c]} = ${s.v(r, c)} 이다.`, "Read the segment."]], variant: "read_one_segment", min: 2 }); } },
    { lv: "medium", name: "category_across_bars", structure: "모든 막대에서 한 범주의 조각을 더함", extra: "medium: 막대마다 한 조각씩 합", concepts: ["누적 막대그래프", "조각 읽기", "합"],
      gen(rng) { const s = makeSB(rng); const c = rng.int(0, s.cols.length - 1); const ans = s.rows.reduce((a, _, i) => a + s.v(i, c), 0); return SD(rng, s, { question: `How many ${s.t.ent} in all are in the "${s.cols[c]}" category?`, correct: ans, wrongs: [W(s.v(0, c), "step_missing", "한 막대만 답했다."), W(s.rows.reduce((a, _, i) => a + s.tot(i), 0), "scope", "전체를 답했다."), W(ans + s.U, "other", "한 눈금 어긋났다."), W(Math.max(...s.rows.map((_, i) => s.v(i, c))), "step_missing", "가장 큰 조각만 답했다.")], P: { c: s.cols[c] }, js: `return sTot(P.c);`, trace: [sbRead(s), [`각 막대의 ${s.cols[c]}: ${s.rows.map((_, i) => s.v(i, c)).join(", ")} 이다.`, "Read that segment in every bar."], [`합 = ${ans} 이다.`, "Add."]], variant: "category_total_across_bars", min: 3 }); } },
  ],
});

// ───────────────────────── two_variable_data.row_total.SB.P ─────────────────────────
export const rowTotalItem = () => defineItem({
  prefix: "tvd", itemId: "two_variable_data.row_total.SB.P",
  hard: [
    { op: "chain2", structure: "누적 막대에서 두 막대 각각의 조각을 모두 더해 두 막대의 합계를 구함", extra: "각 막대의 높이(조각의 합)를 구한 뒤 다시 더함 — medium 은 한 막대", concepts: ["누적 막대그래프", "막대 합계", "합"],
      gen(rng) { const s = makeSB(rng, { nr: 3 }); const [a, b] = two(rng, 3); const ans = s.tot(a) + s.tot(b);
        return SD(rng, s, { question: [`How many ${s.t.ent} are in ${s.rows[a]} and ${s.rows[b]} combined?`, `What is the total number of ${s.t.ent} in the bars for ${s.rows[a]} and ${s.rows[b]}?`], correct: ans, wrongs: [W(s.tot(a), "step_missing", "한 막대만 답했다."), W(s.tot(b), "step_missing", "다른 막대만 답했다."), W(s.rows.reduce((x, _, i) => x + s.tot(i), 0), "scope", "세 막대를 모두 더했다."), W(ans - s.U, "other", "한 눈금 어긋났다."), W(ans + s.U, "other", "한 눈금 어긋났다.")], P: { a: s.rows[a], b: s.rows[b] }, js: `return tot(P.a) + tot(P.b);`, trace: [sbRead(s), [`${s.rows[a]} 의 합계 = ${s.cols.map((_, j) => s.v(a, j)).join(" + ")} = ${s.tot(a)} 이다.`, "Total of the first bar."], [`${s.rows[b]} 의 합계 = ${s.cols.map((_, j) => s.v(b, j)).join(" + ")} = ${s.tot(b)} 이다.`, "Total of the second bar."], [`합 = ${ans} 이다.`, "Add the totals."]], variant: "two_bar_totals" }); } },
    { op: "compare_scenarios", structure: "두 막대의 합계를 각각 구해 그 차를 구함", extra: "각 막대의 조각을 모두 더해 비교 — medium 은 한 막대의 합계", concepts: ["누적 막대그래프", "막대 합계", "두 막대 비교"],
      gen(rng) { const s = makeSB(rng); const [a, b] = two(rng, s.rows.length); if (s.tot(a) === s.tot(b)) throw new GenFail("eq"); const hi = s.tot(a) > s.tot(b) ? a : b, lo = hi === a ? b : a; const d = s.tot(hi) - s.tot(lo);
        return SD(rng, s, { question: [`How many more ${s.t.ent} are in ${s.rows[hi]} than in ${s.rows[lo]}?`, `By how many does the total for ${s.rows[hi]} exceed the total for ${s.rows[lo]}?`], correct: d, wrongs: [W(s.tot(hi), "step_missing", "한 막대의 합계만 답했다."), W(s.tot(lo), "step_missing", "다른 막대의 합계만 답했다."), W(s.tot(hi) + s.tot(lo), "sign_error", "합을 구했다."), W(Math.abs(s.v(hi, 0) - s.v(lo, 0)), "scope", "첫 조각의 차만 답했다."), W(d + s.U, "other", "한 눈금 어긋났다.")], P: { a: s.rows[hi], b: s.rows[lo] }, js: `return tot(P.a) - tot(P.b);`, trace: [sbRead(s), [`${s.rows[hi]} 의 합계 = ${s.tot(hi)} 이다.`, "First total."], [`${s.rows[lo]} 의 합계 = ${s.tot(lo)} 이다.`, "Second total."], [`차 = ${d} 이다.`, "Subtract."]], variant: "bar_totals_difference" }); } },
    { op: "inverse", structure: "한 막대에 값이 더해져 합계가 T 가 되었을 때 더해진 수를 역으로 구함", extra: "원래 합계를 먼저 구하고 목표 합계와의 차를 구함 — medium 은 합계", concepts: ["누적 막대그래프", "막대 합계", "역산"],
      gen(rng) { const s = makeSB(rng); const r = rng.int(0, s.rows.length - 1); const add = rng.pick([1, 2, 3, 4]) * s.U; const T = s.tot(r) + add;
        return SD(rng, s, { stim: `After more ${s.t.ent} are counted in ${s.rows[r]}, the total for that bar becomes ${T}.`, question: [`How many more ${s.t.ent} were counted in ${s.rows[r]}?`, `How many ${s.t.ent} were added to ${s.rows[r]}?`], correct: add, wrongs: [W(T, "scope", "새 합계를 답했다."), W(s.tot(r), "step_missing", "원래 합계를 답했다."), W(T + s.tot(r), "sign_error", "합을 구했다."), W(add + s.U, "other", "한 눈금 어긋났다."), W(T - s.v(r, 0), "formula_misuse", "한 조각만 뺐다.")], P: { r: s.rows[r], T }, js: `return P.T - tot(P.r);`, trace: [sbRead(s), [`${s.rows[r]} 의 원래 합계 = ${s.tot(r)} 이다.`, "Original total."], [`새 합계 = ${T} 이다.`, "New total."], [`더해진 수 = ${T} - ${s.tot(r)} = ${add} 이다.`, "Subtract."]], variant: "added_to_reach_total" }); } },
    { op: "constraint_select", structure: "합계가 기준 T 보다 큰 막대의 개수를 셈", extra: "막대마다 조각을 합해 기준(같은 경우 제외)과 비교 — medium 은 한 막대", concepts: ["누적 막대그래프", "막대 합계", "조건 개수"],
      gen(rng) { for (let t = 0; t < 80; t++) { const s = makeSB(rng, { nr: 3 }); const T = rng.pick(s.rows.map((_, i) => s.tot(i))) + rng.pick([0, 0, s.U]); const cnt = s.rows.filter((_, i) => s.tot(i) > T).length; const ge = s.rows.filter((_, i) => s.tot(i) >= T).length; if (cnt < 1 || cnt > 2) continue;
        return SD(rng, s, { question: [`For how many of the bars is the total number of ${s.t.ent} greater than ${T}?`, `How many of the bars have a total greater than ${T}?`], correct: cnt, wrongs: [W(ge === cnt ? cnt + 1 : ge, "condition_ignored", "같은 경우까지 셌다."), W(s.rows.length - cnt, "opposite", "기준 이하를 셌다."), W(s.rows.length, "condition_ignored", "전체를 답했다."), W(cnt + 2, "other", "개수가 어긋났다."), W(0, "condition_ignored", "해당 막대가 없다고 보았다.")], P: { T }, js: `return C.filter((c) => tot(c) > P.T).length;`, trace: [sbRead(s), [`막대별 합계: ${s.rows.map((r, i) => `${r} ${s.tot(i)}`).join(", ")} 이다.`, "Total of each bar."], [`${T} 보다 큰 것(같은 것 제외)을 센다.`, "Strictly greater."], [`개수는 ${cnt} 이다.`, "Count."]], variant: "count_bars_above_total" }); } throw new GenFail("select"); } },
  ],
  em: [
    { lv: "easy", name: "one_bar_total", structure: "한 막대의 조각을 모두 더해 합계를 구함", extra: "easy: 조각 합", concepts: ["누적 막대그래프", "막대 합계"],
      gen(rng) { const s = makeSB(rng); const r = rng.int(0, s.rows.length - 1); return SD(rng, s, { question: `What is the total number of ${s.t.ent} in ${s.rows[r]}?`, correct: s.tot(r), wrongs: [W(s.v(r, 0), "step_missing", "첫 조각만 답했다."), W(s.tot(r) - s.v(r, s.cols.length - 1), "step_missing", "한 조각을 빠뜨렸다."), W(s.tot((r + 1) % s.rows.length), "axis_misread", "다른 막대를 읽었다."), W(s.tot(r) + s.U, "other", "한 눈금 어긋났다.")], P: { r: s.rows[r] }, js: `return tot(P.r);`, trace: [sbRead(s), [`${s.cols.map((_, j) => s.v(r, j)).join(" + ")} = ${s.tot(r)} 이다.`, "Add the segments."]], variant: "one_bar_total", min: 2 }); } },
    { lv: "medium", name: "grand_total", structure: "모든 막대의 조각을 더해 전체 합계를 구함", extra: "medium: 전체 합", concepts: ["누적 막대그래프", "합계"],
      gen(rng) { const s = makeSB(rng); const ans = s.rows.reduce((a, _, i) => a + s.tot(i), 0); return SD(rng, s, { question: `What is the total number of ${s.t.ent} shown in the whole graph?`, correct: ans, wrongs: [W(s.tot(0), "step_missing", "한 막대만 답했다."), W(ans - s.tot(s.rows.length - 1), "step_missing", "한 막대를 빠뜨렸다."), W(ans + s.U, "other", "한 눈금 어긋났다."), W(Math.max(...s.rows.map((_, i) => s.tot(i))), "step_missing", "가장 큰 막대만 답했다.")], js: `return grand;`, trace: [sbRead(s), [`막대별 합계: ${s.rows.map((_, i) => s.tot(i)).join(", ")} 이다.`, "Total of each bar."], [`합 = ${ans} 이다.`, "Add."]], variant: "grand_total", min: 3 }); } },
  ],
});

// ───────────────────────── two_variable_data.conditional_share.SB.P ─────────────────────────
export const conditionalItem = () => defineItem({
  prefix: "tvd", itemId: "two_variable_data.conditional_share.SB.P",
  hard: [
    { op: "chain2", structure: "한 막대에서 두 범주를 합한 조각이 그 막대 전체에서 차지하는 비율(조건부 비율)을 구함", extra: "조각 합 ÷ 막대 합계의 연쇄(전체가 아니라 그 막대가 분모) — medium 은 한 조각", concepts: ["누적 막대그래프", "조건부 비율", "합"],
      gen(rng) { const s = makeSB(rng, { nc: 3 }); const r = rng.int(0, s.rows.length - 1); const [a, b] = two(rng, 3); const n = s.v(r, a) + s.v(r, b), d = s.tot(r);
        return SF(rng, s, { stim: `One ${s.t.ent.replace(/s$/, "")} is chosen at random from those in ${s.rows[r]}.`, question: [`What is the probability that the ${s.t.ent.replace(/s$/, "")} is in the category "${s.cols[a]}" or "${s.cols[b]}"?`, `What fraction of the ${s.t.ent} in ${s.rows[r]} are in "${s.cols[a]}" or "${s.cols[b]}"?`], num: n, den: d, wrongs: [FW(s.v(r, a), d, "step_missing", "한 조각만 썼다."), FW(n, s.rows.reduce((x, _, i) => x + s.tot(i), 0), "scope", "전체를 분모로 썼다."), FW(d - n, d, "opposite", "나머지 조각을 썼다."), FW(n, d - n, "formula_misuse", "비(odds)를 구했다."), FW(n + s.U, d, "other", "분자가 어긋났다.")], P: { r: s.rows[r], a: s.cols[a], b: s.cols[b] }, js: `return (v(P.r, P.a) + v(P.r, P.b)) / tot(P.r);`, trace: [sbRead(s), [`${s.rows[r]} 의 두 조각 = ${s.v(r, a)} + ${s.v(r, b)} = ${n} 이다.`, "The two segments."], [`${s.rows[r]} 의 합계 = ${d} 이다.`, "The bar total is the denominator."], [`비율 = ${n}/${d} 이다.`, "Divide."]], variant: "share_of_two_segments_in_bar" }); } },
    { op: "compare_scenarios", structure: "두 막대에서 같은 범주의 비율을 각각 구해 그 차를 구함", extra: "막대 합계가 서로 달라 조각이 아닌 비율로 비교해야 함 — medium 은 한 막대의 비율", concepts: ["누적 막대그래프", "조건부 비율", "비율 비교"],
      gen(rng) { for (let t = 0; t < 80; t++) { const s = makeSB(rng); const [a, b] = two(rng, s.rows.length); const c = rng.int(0, s.cols.length - 1); const pa = s.v(a, c) / s.tot(a), pb = s.v(b, c) / s.tot(b); if (Math.abs(pa - pb) < 1e-9) continue; const hi = pa > pb ? a : b, lo = hi === a ? b : a; const nn = s.v(hi, c) * s.tot(lo) - s.v(lo, c) * s.tot(hi), dd = s.tot(hi) * s.tot(lo);
        return SF(rng, s, { question: [`How much greater is the fraction of ${s.rows[hi]}'s ${s.t.ent} in the "${s.cols[c]}" category than the fraction of ${s.rows[lo]}'s ${s.t.ent} in that category?`, `What is the difference between the share in "${s.cols[c]}" for ${s.rows[hi]} and for ${s.rows[lo]}?`], num: nn, den: dd, wrongs: [FW(s.v(hi, c), s.tot(hi), "step_missing", "한 비율만 답했다."), FW(s.v(lo, c), s.tot(lo), "step_missing", "다른 비율만 답했다."), FW(s.v(hi, c) - s.v(lo, c), s.tot(hi), "formula_misuse", "조각의 차를 한 합계로 나눴다."), FW(s.v(hi, c) - s.v(lo, c), s.tot(hi) + s.tot(lo), "formula_misuse", "합계의 합으로 나눴다."), FW(nn + 1, dd, "other", "분자가 어긋났다.")], P: { a: s.rows[hi], b: s.rows[lo], c: s.cols[c] }, js: `return v(P.a, P.c) / tot(P.a) - v(P.b, P.c) / tot(P.b);`, trace: [sbRead(s), [`${s.rows[hi]}: ${s.v(hi, c)}/${s.tot(hi)} 이다.`, "First share."], [`${s.rows[lo]}: ${s.v(lo, c)}/${s.tot(lo)} 이다.`, "Second share."], [`차 = ${frac(nn, dd)} 이다.`, "Subtract the fractions."]], variant: "share_difference_two_bars" }); } throw new GenFail("cmp"); } },
    { op: "compose_kind", structure: "한 범주를 고른 사람들 중에서 특정 막대에 속할 비율(역방향 조건부 비율)을 구함", extra: "분모가 막대 합계가 아니라 그 범주의 모든 막대 조각의 합임을 구분해야 함 — medium 은 막대 안의 비율", concepts: ["누적 막대그래프", "조건부 비율", "역조건"],
      gen(rng) { const s = makeSB(rng); const r = rng.int(0, s.rows.length - 1); const c = rng.int(0, s.cols.length - 1); const d = s.rows.reduce((a, _, i) => a + s.v(i, c), 0); if (d === s.v(r, c)) throw new GenFail("one");
        return SF(rng, s, { stim: `One ${s.t.ent.replace(/s$/, "")} is chosen at random from those in the "${s.cols[c]}" category.`, question: [`What is the probability that the ${s.t.ent.replace(/s$/, "")} is in ${s.rows[r]}?`, `What fraction of the ${s.t.ent} in "${s.cols[c]}" are in ${s.rows[r]}?`], num: s.v(r, c), den: d, wrongs: [FW(s.v(r, c), s.tot(r), "axis_misread", "막대 합계를 분모로 썼다."), FW(s.v(r, c), s.rows.reduce((a, _, i) => a + s.tot(i), 0), "scope", "전체를 분모로 썼다."), FW(d - s.v(r, c), d, "opposite", "나머지 막대를 답했다."), FW(s.v(r, c), d - s.v(r, c), "formula_misuse", "비(odds)를 구했다."), FW(s.v(r, c) + s.U, d, "other", "분자가 어긋났다.")], P: { r: s.rows[r], c: s.cols[c] }, js: `return v(P.r, P.c) / sTot(P.c);`, trace: [sbRead(s), [`"${s.cols[c]}" 범주의 모든 조각의 합 = ${d} 이다.`, "The category total is the denominator."], [`${s.rows[r]} 의 ${s.cols[c]} 조각 = ${s.v(r, c)} 이다.`, "The favorable segment."], [`비율 = ${s.v(r, c)}/${d} 이다.`, "Divide."]], variant: "reverse_conditional_share" }); } },
    { op: "constraint_select", structure: "한 막대에서 특정 범주가 아닌 사람 중 다른 범주에 속할 비율을 구함", extra: "표본 공간이 '그 범주가 아닌 것' 으로 줄어든다는 조건을 반영 — medium 은 한 조각의 비율", concepts: ["누적 막대그래프", "조건부 비율", "여사건 조건"],
      gen(rng) { const s = makeSB(rng, { nc: 3 }); const r = rng.int(0, s.rows.length - 1); const [a, b] = two(rng, 3); const den = s.tot(r) - s.v(r, a);
        return SF(rng, s, { stim: `One ${s.t.ent.replace(/s$/, "")} is chosen at random from those in ${s.rows[r]} who are not in the category "${s.cols[a]}".`, question: [`What is the probability that the ${s.t.ent.replace(/s$/, "")} is in the category "${s.cols[b]}"?`, `What fraction of those chosen from are in "${s.cols[b]}"?`], num: s.v(r, b), den, wrongs: [FW(s.v(r, b), s.tot(r), "condition_ignored", "조건을 쓰지 않고 막대 합계로 나눴다."), FW(s.v(r, b), s.v(r, a), "scope", "제외한 범주로 나눴다."), FW(s.v(r, a), den, "axis_misread", "두 범주를 바꿨다."), FW(den - s.v(r, b), den, "opposite", "나머지 범주를 답했다."), FW(s.v(r, b) + s.U, den, "other", "분자가 어긋났다.")], P: { r: s.rows[r], a: s.cols[a], b: s.cols[b] }, js: `return v(P.r, P.b) / (tot(P.r) - v(P.r, P.a));`, trace: [sbRead(s), [`${s.rows[r]} 의 합계 = ${s.tot(r)}, ${s.cols[a]} = ${s.v(r, a)} 이다.`, "Bar total and the excluded segment."], [`표본 공간 = ${s.tot(r)} - ${s.v(r, a)} = ${den} 이다.`, "The sample space shrinks."], [`${s.cols[b]} = ${s.v(r, b)} 이므로 비율은 ${s.v(r, b)}/${den} 이다.`, "Divide."]], variant: "conditional_excluding_one_category" }); } },
  ],
  em: [
    { lv: "easy", name: "share_in_bar", structure: "한 막대에서 한 조각이 차지하는 비율을 구함", extra: "easy: 조각 ÷ 합계", concepts: ["누적 막대그래프", "비율"],
      gen(rng) { const s = makeSB(rng); const r = rng.int(0, s.rows.length - 1), c = rng.int(0, s.cols.length - 1); return SF(rng, s, { stim: `One ${s.t.ent.replace(/s$/, "")} is chosen at random from those in ${s.rows[r]}.`, question: `What is the probability that the ${s.t.ent.replace(/s$/, "")} is in the category "${s.cols[c]}"?`, num: s.v(r, c), den: s.tot(r), wrongs: [FW(s.v(r, c), s.rows.reduce((a, _, i) => a + s.tot(i), 0), "scope", "전체를 분모로 썼다."), FW(s.tot(r) - s.v(r, c), s.tot(r), "opposite", "나머지를 답했다."), FW(s.v(r, c), s.tot(r) - s.v(r, c), "formula_misuse", "비(odds)를 구했다."), FW(s.v(r, c) + s.U, s.tot(r), "other", "분자가 어긋났다.")], P: { r: s.rows[r], c: s.cols[c] }, js: `return v(P.r, P.c) / tot(P.r);`, trace: [sbRead(s), [`${s.rows[r]} 의 ${s.cols[c]} = ${s.v(r, c)}, 합계 = ${s.tot(r)} 이다.`, "Segment and total."], [`비율 = ${frac(s.v(r, c), s.tot(r))} 이다.`, "Divide."]], variant: "share_one_segment", min: 3 }); } },
    { lv: "medium", name: "share_of_all", structure: "전체 중 한 막대가 차지하는 비율을 구함", extra: "medium: 막대 합계 ÷ 전체", concepts: ["누적 막대그래프", "비율"],
      gen(rng) { const s = makeSB(rng); const r = rng.int(0, s.rows.length - 1); const grand = s.rows.reduce((a, _, i) => a + s.tot(i), 0); return SF(rng, s, { stim: `One ${s.t.ent.replace(/s$/, "")} is chosen at random from all the ${s.t.ent} in the graph.`, question: `What is the probability that the ${s.t.ent.replace(/s$/, "")} is in ${s.rows[r]}?`, num: s.tot(r), den: grand, wrongs: [FW(s.tot(r), grand - s.tot(r), "formula_misuse", "비(odds)를 구했다."), FW(grand - s.tot(r), grand, "opposite", "나머지를 답했다."), FW(s.v(r, 0), grand, "step_missing", "한 조각만 분자로 썼다."), FW(s.tot(r) + s.U, grand, "other", "분자가 어긋났다.")], P: { r: s.rows[r] }, js: `return tot(P.r) / grand;`, trace: [sbRead(s), [`${s.rows[r]} 의 합계 = ${s.tot(r)}, 전체 = ${grand} 이다.`, "Bar total and grand total."], [`비율 = ${frac(s.tot(r), grand)} 이다.`, "Divide."]], variant: "share_of_grand_total", min: 3 }); } },
  ],
});

// ───────────────────────── percentages.percent_change.SB.P ─────────────────────────
type PcScene = SbScene & { per: [string, string] };
const PERIODS: [string, string][] = [["Last year", "This year"], ["Year 1", "Year 2"], ["Spring", "Summer"], ["Before", "After"], ["Week 1", "Week 2"]];
const PC_TOPICS = [
  { ent: "tickets", what: "tickets sold for three kinds of events", where: "by a theater", cols: ["Plays", "Concerts", "Comedy"], yUnit: "tickets" },
  { ent: "items", what: "items sold at a shop", where: "over two periods", cols: ["Books", "Games", "Toys"], yUnit: "items" },
  { ent: "meals", what: "meals served by a cafeteria", where: "over two periods", cols: ["Lunch", "Dinner", "Breakfast"], yUnit: "meals" },
  { ent: "visits", what: "visits to three exhibits", where: "at a science center", cols: ["Space", "Ocean", "Robots"], yUnit: "visits" },
  { ent: "downloads", what: "app downloads by type", where: "over two periods", cols: ["Games", "Music", "Photos"], yUnit: "downloads" },
];
function makePC(rng: Rng): PcScene {
  for (let tr = 0; tr < 80; tr++) {
    const tp = rng.pick(PC_TOPICS); const per = rng.pick(PERIODS); const U = rng.pick([10, 20, 25, 50]); const units = per.map(() => tp.cols.map(() => rng.int(1, 3))); if (units.some((r) => r.reduce((a, b) => a + b, 0) > 8)) continue;
    const maxTot = Math.max(...units.map((r) => r.reduce((a, b) => a + b, 0)));
    const fig: StackedBarSpec = { type: "stacked_bar", title: tp.what.charAt(0).toUpperCase() + tp.what.slice(1), categories: [...per], series: tp.cols.map((name, j) => ({ name, values: units.map((r) => r[j] * U) })), xTitle: "Period (time)", yTitle: `${tp.yUnit.charAt(0).toUpperCase() + tp.yUnit.slice(1)} (count)`, yStep: U, yMax: (maxTot + 1) * U, showValues: true };
    if (renderStackedBar(fig).issues.length) continue;
    const t: SbTopic = { ent: tp.ent, what: tp.what, where: tp.where, rowHead: "Period", axisUnit: "time", rowNoun: "period", rows: [...per], cols: tp.cols, yUnit: tp.yUnit };
    return { t, rows: [...per], cols: tp.cols, U, units, fig, v: (r, c) => units[r][c] * U, tot: (r) => units[r].reduce((a, b) => a + b, 0) * U, per };
  }
  throw new GenFail("퍼센트 변화 장면");
}
const pctChg = (a: number, b: number) => ((b - a) * 100) / a;
const intPc = (a: number, b: number) => Number.isInteger(pctChg(a, b)) && a !== b;
const PCD = (rng: Rng, s: PcScene, d: D): Instance => SD(rng, s, d);
export const percentChangeItem = () => defineItem({
  prefix: "pct", itemId: "percentages.percent_change.SB.P",
  hard: [
    { op: "chain2", structure: "두 기간의 막대 합계(조각의 합)를 각각 구한 뒤 전체의 퍼센트 변화를 구함", extra: "조각 합 → 두 합계 → 변화율의 연쇄 — medium 은 한 범주의 변화율", concepts: ["누적 막대그래프", "퍼센트 변화", "합"],
      gen(rng) { for (let t = 0; t < 120; t++) { const s = makePC(rng); const a = s.tot(0), b = s.tot(1); if (!intPc(a, b)) continue; const p = pctChg(a, b);
        return PCD(rng, s, { question: [`By what percent did the total number of ${s.t.ent} ${p > 0 ? "increase" : "decrease"} from ${s.per[0]} to ${s.per[1]}?`, `The total number of ${s.t.ent} ${p > 0 ? "rose" : "fell"} from ${s.per[0]} to ${s.per[1]}. By what percent?`], correct: Math.abs(p), wrongs: [W(Math.abs(pctChg(b, a)), "opposite", "기준을 바꿨다."), W(Math.abs(b - a), "unit_error", "수의 차를 답했다."), W(Math.round((b * 100) / a), "step_missing", "변화량이 아닌 비율을 답했다."), W(Math.abs(p) + 10, "other", "계산 중 어긋났다."), W(Math.abs(pctChg(s.v(0, 0), s.v(1, 0))), "scope", "한 범주의 변화율을 답했다.")], P: { a: s.per[0], b: s.per[1] }, js: `return Math.abs((tot(P.b) - tot(P.a)) / tot(P.a) * 100);`, trace: [sbRead(s), [`${s.per[0]} 합계 = ${a}, ${s.per[1]} 합계 = ${b} 이다.`, "Totals of the two bars."], [`변화량 = ${b} - ${a} = ${b - a} 이다.`, "Change."], [`${Math.abs(b - a)} ÷ ${a} = ${Math.abs(p) / 100} 이다.`, "Divide by the original."], [`퍼센트 변화의 크기는 ${f(Math.abs(p))}% 이다(${p > 0 ? "증가" : "감소"}).`, "Convert to a percent."]], variant: "percent_change_of_totals" }); } throw new GenFail("chain2"); } },
    { op: "compare_scenarios", structure: "두 범주의 퍼센트 변화를 각각 구해 그 차(퍼센트포인트)를 구함", extra: "범주마다 기준을 달리해 변화율을 구하고 비교 — medium 은 한 범주", concepts: ["누적 막대그래프", "퍼센트 변화", "두 범주 비교"],
      gen(rng) { for (let t = 0; t < 160; t++) { const s = makePC(rng); const [a, b] = two(rng, s.cols.length); if (!intPc(s.v(0, a), s.v(1, a)) || !intPc(s.v(0, b), s.v(1, b))) continue; const pa = pctChg(s.v(0, a), s.v(1, a)), pb = pctChg(s.v(0, b), s.v(1, b)); if (pa === pb) continue; const d = Math.abs(pa - pb);
        return PCD(rng, s, { question: [`The percent change in "${s.cols[a]}" from ${s.per[0]} to ${s.per[1]} differs from the percent change in "${s.cols[b]}" by how many percentage points?`, `By how many percentage points do the percent changes from ${s.per[0]} to ${s.per[1]} for "${s.cols[a]}" and "${s.cols[b]}" differ?`], correct: d, wrongs: [W(Math.abs(pa), "step_missing", "한 범주의 변화율만 답했다."), W(Math.abs(pb), "step_missing", "다른 범주의 변화율만 답했다."), W(Math.abs(pa) + Math.abs(pb), "sign_error", "크기의 합을 구했다."), W(Math.abs(s.v(1, a) - s.v(0, a) - (s.v(1, b) - s.v(0, b))), "unit_error", "수의 변화량 차를 답했다."), W(d + 10, "other", "계산 중 어긋났다.")], P: { a: s.cols[a], b: s.cols[b], p0: s.per[0], p1: s.per[1] }, js: `const pc=(s)=> (v(P.p1,s)-v(P.p0,s))/v(P.p0,s)*100; return r6(Math.abs(pc(P.a)-pc(P.b)));`, trace: [sbRead(s), [`${s.cols[a]}: ${s.v(0, a)} → ${s.v(1, a)}, ${f(pa)}% 이다.`, "First percent change."], [`${s.cols[b]}: ${s.v(0, b)} → ${s.v(1, b)}, ${f(pb)}% 이다.`, "Second percent change."], [`차 = |${f(pa)} - ${f(pb)}| = ${f(d)} 퍼센트포인트이다.`, "Difference."]], variant: "percent_change_difference_between_categories" }); } throw new GenFail("cmp"); } },
    { op: "inverse", structure: "한 범주가 다음 기간에도 같은 퍼센트로 변한다고 할 때 그 값을 구함", extra: "퍼센트 변화를 구한 뒤 그 비율을 다시 적용하는 2 단계 — medium 은 변화율", concepts: ["누적 막대그래프", "퍼센트 변화", "연속 적용"],
      gen(rng) { for (let t = 0; t < 160; t++) { const s = makePC(rng); const c = rng.int(0, s.cols.length - 1); const a = s.v(0, c), b = s.v(1, c); if (!intPc(a, b)) continue; const nxt = (b * (100 + pctChg(a, b))) / 100; if (!Number.isInteger(nxt) || nxt <= 0 || nxt > 999) continue;
        return PCD(rng, s, { stim: `Suppose the "${s.cols[c]}" category changes by the same percent again in the next period.`, question: [`How many ${s.t.ent} would there be in the "${s.cols[c]}" category in the next period?`, `Based on that assumption, how many "${s.cols[c]}" ${s.t.ent} would be counted next?`], correct: nxt, wrongs: [W(b, "step_missing", "현재 값을 답했다."), W(b + (b - a), "formula_misuse", "같은 퍼센트가 아니라 같은 변화량을 더했다."), W(Math.round((b * b) / a) === nxt ? nxt + 1 : Math.round((b * b) / a) + 1, "other", "계산 중 어긋났다."), W(Math.abs(pctChg(a, b)), "unit_error", "퍼센트를 답했다."), W(nxt + s.U, "other", "한 눈금 어긋났다.")], P: { c: s.cols[c], p0: s.per[0], p1: s.per[1] }, js: `const a=v(P.p0,P.c), b=v(P.p1,P.c); return r6(b*b/a);`, trace: [sbRead(s), [`${s.cols[c]}: ${a} → ${b} 이다.`, "Read the two values."], [`변화율 = (${b} - ${a}) ÷ ${a} = ${pctChg(a, b) / 100} 이다.`, "Percent change."], [`다음 기간 = ${b} × ${(100 + pctChg(a, b)) / 100} = ${nxt} 이다.`, "Apply the same percent change."]], variant: "same_percent_next_period" }); } throw new GenFail("inverse"); } },
    { op: "constraint_select", structure: "퍼센트 변화가 기준 P% 보다 큰 범주의 개수를 셈", extra: "범주마다 변화율을 구해 기준(같은 경우 제외)과 비교 — medium 은 한 범주", concepts: ["누적 막대그래프", "퍼센트 변화", "조건 개수"],
      gen(rng) { for (let t = 0; t < 200; t++) { const s = makePC(rng); const pcs = s.cols.map((_, c) => (s.v(0, c) > 0 ? pctChg(s.v(0, c), s.v(1, c)) : NaN)); if (pcs.some((x) => !Number.isFinite(x))) continue; const P0 = rng.pick([0, 25, 50, 100]); const cnt = pcs.filter((x) => x > P0).length; const ge = pcs.filter((x) => x >= P0).length; if (cnt < 1 || cnt >= s.cols.length || pcs.some((x) => x === P0 && P0 !== 0 && false)) continue; if (ge === cnt && rng.chance(0.3)) continue;
        return PCD(rng, s, { question: [`For how many categories did the number of ${s.t.ent} increase by more than ${P0}% from ${s.per[0]} to ${s.per[1]}?`, `How many categories had an increase of more than ${P0}% from ${s.per[0]} to ${s.per[1]}?`], correct: cnt, wrongs: [W(ge === cnt ? cnt + 1 : ge, "condition_ignored", "같은 경우까지 셌다."), W(s.cols.length - cnt, "opposite", "나머지를 셌다."), W(s.cols.filter((_, c) => s.v(1, c) > s.v(0, c)).length === cnt ? cnt + 2 : s.cols.filter((_, c) => s.v(1, c) > s.v(0, c)).length, "step_missing", "증가했는지만 보았다."), W(s.cols.length, "condition_ignored", "전체를 답했다."), W(cnt + 2, "other", "개수가 어긋났다."), W(cnt + 1, "other", "경계를 잘못 잡았다."), W(Math.max(0, cnt - 1), "other", "하나를 빠뜨렸다.")].filter((w) => w.v >= 0), P: { P0, p0: s.per[0], p1: s.per[1] }, js: `return S.filter((x)=> (x.values[ci(P.p1)] - x.values[ci(P.p0)]) / x.values[ci(P.p0)] * 100 > P.P0).length;`, trace: [sbRead(s), [`범주별 변화율: ${s.cols.map((c, i) => `${c} ${f(pcs[i])}%`).join(", ")} 이다.`, "Percent change of each category."], [`${P0}% 보다 큰 것(같은 것 제외)을 고른다.`, "Strictly greater."], [`개수는 ${cnt} 이다.`, "Count."]], variant: "count_categories_above_percent" }); } throw new GenFail("select"); } },
  ],
  em: [
    { lv: "easy", name: "percent_change_one", structure: "한 범주의 두 기간 값으로 퍼센트 변화를 구함", extra: "easy: (새 - 옛) ÷ 옛", concepts: ["누적 막대그래프", "퍼센트 변화"],
      gen(rng) { for (let t = 0; t < 120; t++) { const s = makePC(rng); const c = rng.int(0, s.cols.length - 1); const a = s.v(0, c), b = s.v(1, c); if (!intPc(a, b)) continue; const p = pctChg(a, b);
        return PCD(rng, s, { question: `By what percent did the number of ${s.t.ent} in the "${s.cols[c]}" category ${p > 0 ? "increase" : "decrease"} from ${s.per[0]} to ${s.per[1]}?`, correct: Math.abs(p), wrongs: [W(Math.abs(pctChg(b, a)), "opposite", "기준을 바꿨다."), W(Math.abs(b - a), "unit_error", "수의 차를 답했다."), W(Math.round((b * 100) / a), "step_missing", "비율을 답했다."), W(Math.abs(p) + 10, "other", "계산 중 어긋났다.")], P: { c: s.cols[c], p0: s.per[0], p1: s.per[1] }, js: `return Math.abs((v(P.p1,P.c)-v(P.p0,P.c))/v(P.p0,P.c)*100);`, trace: [sbRead(s), [`${s.cols[c]}: ${a} → ${b} 이다.`, "Read the two values."], [`(${b} - ${a}) ÷ ${a} = ${p / 100} 이므로 ${f(Math.abs(p))}% 이다.`, "Percent change."]], variant: "percent_change_one_category", min: 2 }); } throw new GenFail("easy"); } },
    { lv: "medium", name: "share_of_total", structure: "한 기간의 전체에서 한 범주가 차지하는 퍼센트를 구함", extra: "medium: 조각 ÷ 합계 × 100", concepts: ["누적 막대그래프", "퍼센트"],
      gen(rng) { for (let t = 0; t < 120; t++) { const s = makePC(rng); const r = rng.int(0, 1), c = rng.int(0, s.cols.length - 1); const p = (s.v(r, c) * 100) / s.tot(r); if (!Number.isInteger(p)) continue;
        return PCD(rng, s, { question: `What percent of the ${s.t.ent} in ${s.per[r]} were in the "${s.cols[c]}" category?`, correct: p, wrongs: [W((s.v(r, c) * 100) / s.tot(1 - r), "axis_misread", "다른 기간의 합계로 나눴다."), W(s.v(r, c), "unit_error", "수를 답했다."), W(100 - p, "opposite", "나머지를 답했다."), W(p + 5, "other", "계산 중 어긋났다.")], P: { r: s.per[r], c: s.cols[c] }, js: `return v(P.r, P.c) / tot(P.r) * 100;`, trace: [sbRead(s), [`${s.per[r]} 합계 = ${s.tot(r)}, ${s.cols[c]} = ${s.v(r, c)} 이다.`, "Segment and total."], [`${s.v(r, c)} ÷ ${s.tot(r)} = ${p / 100} = ${p}% 이다.`, "Divide."]], variant: "share_of_period_total", min: 3 }); } throw new GenFail("med"); } },
  ],
});
