// 입체도형(SO) 계열 자료 원형 공용 키트 — 조합 파일(items/<조합ID>.ts)이 함께 쓴다.
// 규칙: 치수는 그림 라벨에만 있고 지문은 "the solid shown" 으로 가리킨다. 입체의 겉모습 비율은 고정이라 숫자 치수가 있으면 notToScale('Note' 문구)로 둔다.
// verification_js 는 FIGURE.dims 라벨만 읽어 부피·겉넓이를 다시 계산한다(π 는 계수만 본다).
import { fmtNum } from "../../text";
import type { Rng } from "../../rng";
import { NUM_JS } from "./geo-kit";

export type SoKind = "rectangular_prism" | "cube" | "cylinder" | "cone" | "sphere" | "square_pyramid";
export type SoFig = { type: "solid"; kind: SoKind; dims: { length?: string; width?: string; height?: string; radius?: string; diameter?: string; slant?: string; edge?: string }; notToScale?: boolean };
export const soFig = (kind: SoKind, dims: SoFig["dims"]): SoFig => ({ type: "solid", kind, dims, notToScale: true });
/** FIGURE.dims 를 숫자로 읽는 JS: d('length') 등은 숫자 또는 NaN(미지수 라벨). */
export const SO_JS = `${NUM_JS}const D=FIGURE.dims||{}; const K=FIGURE.kind; const d=(k)=>D[k]===undefined?NaN:num(D[k]);\n`;
export const piFmt = (v: number) => (v === 1 ? "$\\pi$" : `$${fmtNum(v)}\\pi$`);
export const SPR_NO_PI_SO = "정답이 π 를 포함한 식(kπ)이라 순수한 수 하나로 낼 수 없다";
export const SO_LEAD = ["", "", "A student studies the solid shown. ", "An engineer sketches the container below. ", "A designer plans the object shown. ", "A warehouse worker looks at the package shown. ", "A teacher shows the class the solid below. ", "A craftsperson builds the object shown. ", "A shop owner measures the item shown. ", "A scientist describes the container shown. "];
export const SO_CTX = ["", "", "All lengths are in centimeters. ", "All lengths are in meters. ", "Lengths are given in inches. ", "Use the labels in the figure. ", "Read each label carefully before computing. ", "The figure is not meant to be measured; use the labels. ", "Check which label belongs to which edge. ", "A calculator is not necessary. ", "Pay attention to the units. ", "Think about which formula applies to this solid. "];
export const PRISM_SCENES = ["The figure shows a rectangular box with its length, width, and height labeled.", "A rectangular storage bin is shown in the figure, with its three dimensions marked.", "In the figure shown, a rectangular prism has labeled edge lengths.", "The solid in the figure is a rectangular tank whose dimensions are labeled.", "A shipping carton in the shape of a rectangular prism is shown, with its edges labeled.", "The figure displays a box-shaped container, and the length, width, and height are marked.", "A rectangular aquarium is modeled by the prism in the figure, with labeled dimensions.", "The figure shows a block shaped like a rectangular prism; its three edge lengths are labeled."];
export const CYL_SCENES = ["The figure shows a right circular cylinder with its labeled dimensions.", "A cylindrical can is shown in the figure, with the labeled measurements.", "In the figure shown, a cylinder has a labeled base and height.", "The solid in the figure is a cylindrical water tank with labeled measurements.", "A drum shaped like a right circular cylinder is shown, and its dimensions are labeled.", "The figure displays a cylinder-shaped candle, with its dimensions marked.", "A round pipe segment is modeled by the cylinder in the figure, with labeled measurements.", "The figure shows a cylindrical jar whose base and height are labeled."];
export const CONE_SCENES = ["The figure shows a right circular cone with its labeled dimensions.", "A cone-shaped paper cup is shown in the figure, with the labeled measurements.", "In the figure shown, a cone has a labeled base and height.", "The solid in the figure is a cone-shaped funnel with labeled measurements.", "A traffic cone is modeled by the right circular cone in the figure, with labeled dimensions."];
export const SPH_SCENES = ["The figure shows a sphere with its labeled measurement.", "A ball is modeled by the sphere shown in the figure, with its size labeled.", "In the figure shown, a sphere has a labeled radius or diameter.", "The solid in the figure is a spherical water balloon with a labeled measurement."];
export const PYR_SCENES = ["The figure shows a pyramid with a square base and its labeled dimensions.", "A pyramid-shaped monument with a square base is shown, with its measurements labeled.", "In the figure shown, a square pyramid has a labeled base edge and height.", "The solid in the figure is a square pyramid whose base edge and height are labeled."];
export const CUBE_SCENES = ["The figure shows a cube with its edge length labeled.", "A cube-shaped gift is shown in the figure, with the edge length marked.", "In the figure shown, a cube has a labeled edge.", "The solid in the figure is a cube whose edge length is labeled."];
export const soIntro = (rng: Rng, scenes: string[], extra = "") => `${rng.pick(SO_LEAD)}${rng.pick(SO_CTX)}${rng.pick(scenes)}${extra}`.replace(/ {2,}/g, " ").trim();
export const Q_VOL = (rng: Rng) => rng.pick(["What is the volume of the solid?", "Find the volume of the solid.", "How large is the volume of the solid?", "Determine the volume of the solid.", "Calculate the volume of the solid shown.", "The solid holds how much, as a volume?"]);
export const Q_VOL_PI = (rng: Rng) => rng.pick(["What is the volume of the solid, in terms of $\\pi$?", "Find the volume of the solid in terms of $\\pi$.", "Express the volume of the solid in terms of $\\pi$.", "The volume of the solid is how many cubic units, in terms of $\\pi$?", "Determine the solid's volume, leaving $\\pi$ in your answer.", "Which value gives the volume, written in terms of $\\pi$?"]);
