// Regenerates lib/legal/documents/generated.ts from docs/contracts/*.md.
// Run: node scripts/legal-docs/generate.mjs
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { parseContractMarkdown } from "./parse-markdown.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
export const SOURCES = {
  parentAgreement: "docs/contracts/parent-education-services-agreement-v0.3-en-california-draft.md",
  teacherCalifornia: "docs/contracts/teacher-california-employment-agreement-v0.2-en.md",
  teacherNonUs: "docs/contracts/teacher-non-us-services-agreement-v0.2-en.md",
  under13Notice: "docs/contracts/under-13-parental-notice-and-consent-en.md",
};

// The US independent-contractor form is optional until the planner delivers its source text; once the file exists the
// generator and the drift test pick it up automatically.
const US_CONTRACTOR = "docs/contracts/teacher-us-contractor-services-agreement-v0.1-en.md";
if (existsSync(path.join(root, US_CONTRACTOR))) SOURCES.teacherUsContractor = US_CONTRACTOR;

const out = {};
for (const [key, rel] of Object.entries(SOURCES)) {
  out[key] = parseContractMarkdown(readFileSync(path.join(root, rel), "utf8"));
}

const body = `// GENERATED by scripts/legal-docs/generate.mjs from docs/contracts/*.md — do not edit by hand.
// The English source files are the authoritative text; a drift test fails when they diverge.
import type { LegalDocumentData } from "../types";

export const GENERATED_LEGAL_DOCUMENTS: Record<"parentAgreement" | "teacherCalifornia" | "teacherNonUs" | "under13Notice", LegalDocumentData> & { teacherUsContractor?: LegalDocumentData } = ${JSON.stringify(out, null, 2)};
`;
writeFileSync(path.join(root, "lib/legal/documents/generated.ts"), body);
console.log("wrote lib/legal/documents/generated.ts");
