// Regenerates lib/legal/documents/generated.ts from docs/contracts/*.md.
// Run: node scripts/legal-docs/generate.mjs
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { parseContractMarkdown } from "./parse-markdown.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
export const SOURCES = {
  parentAgreement: "docs/contracts/parent-education-services-agreement-v0.3-en-california-draft.md",
  teacherCalifornia: "docs/contracts/teacher-california-employment-agreement-v0.2-en.md",
  teacherNonUs: "docs/contracts/teacher-non-us-services-agreement-v0.2-en.md",
  teacherUsContractor: "docs/contracts/teacher-us-contractor-services-agreement-v0.1-en.md",
  consultantServices: "docs/contracts/consultant-services-agreement-v0.1-en.md",
  teacherRateAddendum: "docs/contracts/teacher-rate-change-addendum-v0.2-en.md",
  under13Notice: "docs/contracts/under-13-parental-notice-and-consent-en.md",
};
// Internal-only files (e.g. legal-review-request-*.md) are deliberately NOT listed here and never reach generated.ts.

const out = {};
for (const [key, rel] of Object.entries(SOURCES)) {
  out[key] = parseContractMarkdown(readFileSync(path.join(root, rel), "utf8"));
}

const body = `// GENERATED by scripts/legal-docs/generate.mjs from docs/contracts/*.md — do not edit by hand.
// The English source files are the authoritative text; a drift test fails when they diverge.
import type { LegalDocumentData } from "../types";

export const GENERATED_LEGAL_DOCUMENTS: Record<"parentAgreement" | "teacherCalifornia" | "teacherNonUs" | "teacherUsContractor" | "consultantServices" | "teacherRateAddendum" | "under13Notice", LegalDocumentData> = ${JSON.stringify(out, null, 2)};
`;
writeFileSync(path.join(root, "lib/legal/documents/generated.ts"), body);
console.log("wrote lib/legal/documents/generated.ts");
