// coordinate_geometry — 수치 단답(SPR 가능) hard 원형 3 kind × 4 연산자 × 4 변형. 좌표를 지문에 직접 적는 직선·원·도형 문항(자료 그림 원형 fig/items 와 별개).
// 은행 import 는 coordinate_geometry 를 가장 가까운 실제 skill 로 옮긴다: 직선·기울기 → linear_equations_two_var, 원의 방정식 → circles, 도형 좌표 → lines_angles_triangles/area_volume.
import { need, isInt, sp, mkKind, type Var } from "./spr-a-kit";
import { lin } from "../text";
import type { Rng } from "../rng";
import type { Archetype } from "../types";

const SKILL = "coordinate_geometry";
const P = (x: number, y: number) => `(${x}, ${y})`;
const M = (s: string) => `$${s}$`;
const ln = (m: number, b: number) => `y = ${lin(m, b, "x")}`;
const sgn = (n: number) => (n < 0 ? `- ${-n}` : `+ ${n}`);
const TRI: [number, number, number][] = [[3, 4, 5], [6, 8, 10], [5, 12, 13], [8, 15, 17], [9, 12, 15]];
const LEAD = (rng: Rng) => sp(rng, "[[Work in the xy-plane.|Picture a coordinate grid.|A designer plots points on a coordinate plane.|A surveyor records positions on a coordinate map.|A student sketches on graph paper.|The following is set in the coordinate plane.|A game board is laid out on a coordinate grid.|]] ");
const TAIL = (rng: Rng) => sp(rng, "[[All coordinates are measured in the same unit.|Each grid unit has the same length.|Assume the axes use the same scale.|Use exact values.|Give the answer as a number.|The answer is a whole number or a simple fraction.|No calculator is needed.|Check the answer against a quick sketch.]]");
const dress = (vs: Var[]): Var[] => vs.map((v) => ({ name: v.name, gen: (rng: Rng) => { const q = v.gen(rng); return { ...q, s: `${LEAD(rng)}${q.s}`.trim(), q: `${q.q} ${TAIL(rng)}` }; } }));
const dist2 = "const d2 = (a, b) => (a[0]-b[0])*(a[0]-b[0]) + (a[1]-b[1])*(a[1]-b[1]);\n";

// ───────── kind L: line_equation_features — 직선의 기울기·절편·교점·평행/수직 조건을 수로 구한다 ─────────
const L_COMPOSE: Var[] = [
  { name: "x_intercept_from_two_points", gen(rng) { const m = rng.pick([1, 2, 3, -1, -2, -3, 4, -4, 5]); const a = rng.nz(-9, 9); const x1 = rng.int(-6, 6), d = rng.int(1, 4); const x2 = x1 + d; need(x1 !== a && x2 !== a); const y1 = m * (x1 - a), y2 = m * (x2 - a); need(Math.abs(y1) < 60 && Math.abs(y2) < 60);
    return { s: `The line ${M("\\ell")} passes through the points ${M(P(x1, y1))} and ${M(P(x2, y2))}.`, q: sp(rng, `[[What is the ${M("x")}-coordinate of the point where ${M("\\ell")} crosses the ${M("x")}-axis?|Where does ${M("\\ell")} cross the ${M("x")}-axis? Give the ${M("x")}-coordinate.]]`), a, w: [-a, y1, x1 - y1],
      p: { x1, y1, x2, y2 }, js: "const m = (P.y2 - P.y1) / (P.x2 - P.x1); return P.x1 - P.y1 / m;", t: [`기울기 = (${y2} − ${y1}) ÷ (${x2} − ${x1}) = ${m}.||Slope = ${m}.`, `점-기울기 꼴로 y − ${y1} = ${m}(x − ${x1}).||Point-slope form.`, "y = 0 을 대입한다.||Set y = 0.", `x = ${x1} − ${y1}/${m}.`, `x 절편은 ${a}.||The x-intercept is ${a}.`] }; } },
  { name: "triangle_area_with_axes", gen(rng) { const a = rng.int(2, 12), b = rng.int(2, 12); need(a !== b); const g = ((x: number, y: number): number => (y ? g2(y, x % y) : x)); const g2 = (x: number, y: number): number => (y ? g2(y, x % y) : x); const gg = g(a, b); const p = b / gg, q = a / gg, r = (a * b) / gg; const ans = (a * b) / 2; need(a * b < 100);
    return { s: `The line ${M(`${p === 1 ? "" : p}x + ${q === 1 ? "" : q}y = ${r}`)} and the two coordinate axes form a right triangle in the first quadrant.`, q: sp(rng, `[[What is the area of the triangle?|Find the area of the triangle bounded by the line and the axes.]]`), a: ans, w: [a + b, a * b, ans * 2 + 1],
      p: { p, q, r }, js: "const xi = P.r / P.p; const yi = P.r / P.q; return xi * yi / 2;", t: [`x 절편: y = 0 이면 x = ${r}/${p} = ${a}.||x-intercept ${a}.`, `y 절편: x = 0 이면 y = ${r}/${q} = ${b}.||y-intercept ${b}.`, "두 절편이 직각삼각형의 두 변이다.||The intercepts are the legs.", `넓이 = ${a} × ${b} ÷ 2.`, `답은 ${ans}.`] }; } },
  { name: "y_at_given_x", gen(rng) { const m = rng.pick([2, 3, -2, -3, 4, 5, -4]), p = rng.int(-5, 6), q = rng.int(-8, 9), t = rng.int(-7, 9); need(t !== p); const ans = q + m * (t - p); need(Math.abs(ans) < 90);
    return { s: `A line has slope ${m} and passes through the point ${M(P(p, q))}.`, q: sp(rng, `[[What is the ${M("y")}-coordinate of the point on the line whose ${M("x")}-coordinate is ${t}?|The line contains a point with ${M("x")}-coordinate ${t}. What is its ${M("y")}-coordinate?]]`), a: ans, w: [q + m * t, q + (t - p), m * t],
      p: { m, p, q, t }, js: "const b = P.q - P.m * P.p; return P.m * P.t + b;", t: [`y = ${m}x + b 에 (${p}, ${q}) 를 대입한다.||Substitute the point into y = ${m}x + b.`, `b = ${q} − ${m}×${p} = ${q - m * p}.`, `y = ${m}x ${sgn(q - m * p)}.`, `x = ${t} 이면 y = ${m}×${t} ${sgn(q - m * p)}.`, `답은 ${ans}.`] }; } },
  { name: "intercept_midpoint_sum", gen(rng) { const a = rng.int(2, 12), b = rng.int(2, 12); need(a !== b && (a + b) % 2 === 0); const ans = (a + b) / 2;
    return { s: `A line crosses the ${M("x")}-axis at ${M(P(a, 0))} and the ${M("y")}-axis at ${M(P(0, b))}.`, q: sp(rng, `[[What is the sum of the coordinates of the midpoint of the segment joining the two crossing points?|The midpoint of the segment between the two axis crossings has coordinates that add up to what?]]`), a: ans, w: [a + b, a * b / 2, a],
      p: { a, b }, js: "const mx = (P.a + 0) / 2, my = (0 + P.b) / 2; return mx + my;", t: [`중점의 x = (${a} + 0)/2 = ${a / 2}.||Midpoint x.`, `중점의 y = (0 + ${b})/2 = ${b / 2}.||Midpoint y.`, "두 좌표를 더한다.||Add the two coordinates.", `${a / 2} + ${b / 2}.`, `답은 ${ans}.`] }; } },
];
const L_CHAIN: Var[] = [
  { name: "parallel_line_intercept", gen(rng) { const m = rng.pick([2, 3, -2, -3, 4, -1, 1, 5]), b = rng.int(-9, 9), p = rng.nz(-6, 7), q = rng.int(-9, 9); const ans = q - m * p; need(ans !== b && Math.abs(ans) < 60);
    return { s: `The line ${M(ln(m, b))} is parallel to a second line that passes through the point ${M(P(p, q))}.`, q: sp(rng, `[[What is the ${M("y")}-intercept of the second line?|Where does the second line cross the ${M("y")}-axis? Give the ${M("y")}-coordinate.]]`), a: ans, w: [b, q + m * p, q],
      p: { m, p, q }, js: "return P.q - P.m * P.p;", t: [`평행하므로 기울기는 ${m}.||Parallel lines share the slope ${m}.`, `y = ${m}x + c 에 (${p}, ${q}) 대입.||Substitute the point.`, `${q} = ${m}×${p} + c.`, `c = ${q} − ${m * p}.`, `답은 ${ans}.`] }; } },
  { name: "perpendicular_line_intercept", gen(rng) { const m = rng.pick([2, 3, -2, -3, 4, -4, 5]); const k = rng.int(1, 4) * rng.pick([1, -1]); const p = m * k; need(Math.abs(p) < 30); const q = rng.int(-8, 9), b = rng.int(-6, 6); const ans = q + p / m; need(Math.abs(ans) < 40);
    return { s: `The line ${M(ln(m, b))} is perpendicular to a second line that passes through the point ${M(P(p, q))}.`, q: sp(rng, `[[What is the ${M("y")}-intercept of the second line?|At what ${M("y")}-coordinate does the second line cross the ${M("y")}-axis?]]`), a: ans, w: [q - p / m, q + p * m, q],
      p: { m, p, q }, js: "const s2 = -1 / P.m; return P.q - s2 * P.p;", t: [`수직이면 기울기의 곱이 −1: 기울기 = −1/${m}.||Perpendicular slope is -1/${m}.`, `y = (−1/${m})x + c.`, `${q} = (−1/${m})(${p}) + c.`, `c = ${q} + ${p}/${m}.`, `답은 ${ans}.`] }; } },
  { name: "intersection_sum", gen(rng) { const x0 = rng.int(-5, 6), y0 = rng.int(-6, 7); const m1 = rng.int(1, 5), m2 = rng.pick([-1, -2, -3, 0, 6, -4]); need(m1 !== m2); const b1 = y0 - m1 * x0, b2 = y0 - m2 * x0; need(Math.abs(b1) < 40 && Math.abs(b2) < 40); const ans = x0 + y0; need(ans !== 0);
    return { s: `The lines ${M(ln(m1, b1))} and ${M(ln(m2, b2))} intersect at one point.`, q: sp(rng, `[[What is the sum of the coordinates of the intersection point?|The intersection point has coordinates that add up to what number?]]`), a: ans, w: [x0, y0, x0 * y0],
      p: { m1, b1, m2, b2 }, js: "let sol = null; for (let x = -100; x <= 100; x++) { if (P.m1 * x + P.b1 === P.m2 * x + P.b2) sol = [x, P.m1 * x + P.b1]; } return sol[0] + sol[1];", t: [`${m1}x + ${b1} = ${m2}x + ${b2}.`, `x = (${b2} − ${b1}) ÷ (${m1} − ${m2}) = ${x0}.`, `y = ${m1}(${x0}) + ${b1} = ${y0}.`, "교점의 두 좌표를 더한다.||Add the coordinates.", `${x0} + ${y0} = ${ans}.`] }; } },
  { name: "slope_intercept_sum", gen(rng) { const m = rng.pick([2, 3, -2, -3, 4, -1, 5, -4]), b = rng.int(-9, 9); need(b !== 0); const x1 = rng.int(-5, 3), x2 = x1 + rng.int(2, 5); const y1 = m * x1 + b, y2 = m * x2 + b; const ans = m + b; need(ans !== 0);
    return { s: `A line passes through the points ${M(P(x1, y1))} and ${M(P(x2, y2))}. Its equation can be written as ${M("y = mx + b")}.`, q: sp(rng, `[[What is the value of ${M("m + b")}?|Find ${M("m + b")}.]]`), a: ans, w: [m, b, m * b],
      p: { x1, y1, x2, y2 }, js: "const m = (P.y2 - P.y1) / (P.x2 - P.x1); const b = P.y1 - m * P.x1; return m + b;", t: [`m = (${y2} − ${y1}) ÷ (${x2} − ${x1}) = ${m}.`, `b = ${y1} − ${m}×${x1} = ${b}.`, "두 점 모두에서 확인한다.||Check with the second point.", `m + b = ${m} + ${b}.`, `답은 ${ans}.`] }; } },
];
const L_INVERSE: Var[] = [
  { name: "missing_y_from_slope", gen(rng) { const m = rng.pick([2, 3, -2, -3, 4, -1, 1, 5]), a = rng.int(-6, 6), b = rng.int(-9, 9), c = a + rng.int(2, 6); const k = b + m * (c - a); need(Math.abs(k) < 70);
    return { s: `The line through ${M(P(a, b))} and ${M(`(${c}, k)`)} has slope ${m}.`, q: sp(rng, `[[What is the value of k?|Find k.]]`), a: k, w: [b + (c - a), m * c, b + m],
      p: { a, b, c, m }, js: "for (let k = -300; k <= 300; k++) { if ((k - P.b) === P.m * (P.c - P.a)) return k; } throw new Error('none');", t: [`기울기 = (k − ${b}) ÷ (${c} − ${a}) = ${m}.`, `k − ${b} = ${m} × ${c - a}.`, `k − ${b} = ${m * (c - a)}.`, `k = ${b} + ${m * (c - a)}.`, `k = ${k}.`] }; } },
  { name: "standard_form_constant", gen(rng) { const p = rng.int(2, 7), q = rng.nz(-7, 7), a = rng.int(-6, 7), b = rng.int(-6, 7); const r = p * a + q * b; need(Math.abs(r) < 90);
    return { s: `The line ${M(`${p === 1 ? "" : p}x ${q < 0 ? "-" : "+"} ${Math.abs(q) === 1 ? "" : Math.abs(q)}y = c`)} passes through the point ${M(P(a, b))}, where c is a constant.`, q: sp(rng, `[[What is the value of c?|Find c.]]`), a: r, w: [p * a, q * b, p + q + a + b],
      p: { p, q, a, b }, js: "return P.p * P.a + P.q * P.b;", t: [`점의 좌표를 x, y 에 대입한다.||Substitute the coordinates.`, `${p}(${a}) + ${q}(${b}).`, `= ${p * a} + ${q * b}.`, "식의 오른쪽이 c 이다.||The right side is c.", `c = ${r}.`] }; } },
  { name: "parallel_coefficient", gen(rng) { const m = rng.pick([2, 3, -2, -3, 1, -1, 4]), a = rng.int(2, 6); const x1 = rng.int(-4, 4), x2 = x1 + rng.int(1, 3); const y1 = rng.int(-6, 6), y2 = y1 + m * (x2 - x1); const k = -m * a; need(k !== 0);
    return { s: `The line ${M(`kx + ${a}y = 12`)} is parallel to the line through ${M(P(x1, y1))} and ${M(P(x2, y2))}, where k is a constant.`, q: sp(rng, `[[What is the value of k?|Find k.]]`), a: k, w: [m * a, -k, m],
      p: { a, x1, y1, x2, y2 }, js: "const m = (P.y2 - P.y1) / (P.x2 - P.x1); return -m * P.a;", t: [`두 점을 지나는 직선의 기울기 = ${m}.||Slope through the points is ${m}.`, `kx + ${a}y = 12 의 기울기는 −k/${a}.||The slope of kx + ${a}y = 12 is -k/${a}.`, `평행이므로 −k/${a} = ${m}.`, `k = −${m} × ${a}.`, `k = ${k}.`] }; } },
  { name: "perpendicular_coefficient", gen(rng) { const m = rng.pick([2, 3, 4, -2, -3, 5]), j = rng.int(1, 4); const a = Math.abs(m) * j * rng.pick([1, 1]); const k = a / m; need(isInt(k) && k !== 0); const b = rng.int(-8, 8);
    return { s: `The line ${M(ln(m, b))} is perpendicular to the line ${M(`kx + ${a}y = 9`)}, where k is a constant.`, q: sp(rng, `[[What is the value of k?|Find k.]]`), a: k, w: [-k, m * a, a],
      p: { m, a }, js: "for (let k = -100; k <= 100; k++) { if (k !== 0 && P.m * (-k / P.a) === -1) return k; } throw new Error('none');", t: [`kx + ${a}y = 9 의 기울기 = −k/${a}.`, `수직이면 두 기울기의 곱이 −1.||Perpendicular slopes multiply to -1.`, `${m} × (−k/${a}) = −1.`, `k = ${a} ÷ ${m}.`, `k = ${k}.`] }; } },
];
const L_COMPARE: Var[] = [
  { name: "slope_difference", gen(rng) { const m1 = rng.int(2, 7), m2 = rng.int(-4, 1); const x1 = rng.int(-4, 3), d1 = rng.int(1, 3), x3 = rng.int(-4, 3), d2 = rng.int(1, 3); const y1 = rng.int(-6, 6), y3 = rng.int(-6, 6); const ans = m1 - m2; need(m2 !== 0);
    return { s: `Line A passes through ${M(P(x1, y1))} and ${M(P(x1 + d1, y1 + m1 * d1))}. Line B passes through ${M(P(x3, y3))} and ${M(P(x3 + d2, y3 + m2 * d2))}.`, q: sp(rng, `[[By how much is the slope of Line A greater than the slope of Line B?|What is the slope of Line A minus the slope of Line B?]]`), a: ans, w: [m1 + m2, m1, Math.abs(m2)],
      p: { x1, y1, xa: x1 + d1, ya: y1 + m1 * d1, x3, y3, xb: x3 + d2, yb: y3 + m2 * d2 }, js: "const sa = (P.ya - P.y1) / (P.xa - P.x1); const sb = (P.yb - P.y3) / (P.xb - P.x3); return sa - sb;", t: [`A 의 기울기 = ${m1}.||Slope of A is ${m1}.`, `B 의 기울기 = ${m2}.||Slope of B is ${m2}.`, "각각 두 점의 변화율로 구한다.||Use rise over run for each.", `${m1} − (${m2}).`, `답은 ${ans}.`] }; } },
  { name: "value_gap_at_x", gen(rng) { const m1 = rng.int(2, 6), m2 = rng.int(-3, 1), b1 = rng.int(-6, 6), b2 = rng.int(-6, 9), t = rng.int(2, 9); const ans = (m1 * t + b1) - (m2 * t + b2); need(ans > 0);
    return { s: `Two lines are given by ${M(ln(m1, b1))} and ${M(ln(m2, b2))}. Consider the vertical line ${M(`x = ${t}`)}, which crosses both lines.`, q: sp(rng, `[[How far apart vertically are the two crossing points?|What is the difference between the ${M("y")}-coordinates of the two points where ${M(`x = ${t}`)} crosses the lines?]]`), a: ans, w: [t, b1 - b2, (m1 - m2)],
      p: { m1, b1, m2, b2, t }, js: "const y1 = P.m1 * P.t + P.b1; const y2 = P.m2 * P.t + P.b2; return Math.abs(y1 - y2);", t: [`첫 직선: y = ${m1}(${t}) + ${b1} = ${m1 * t + b1}.`, `둘째 직선: y = ${m2}(${t}) + ${b2} = ${m2 * t + b2}.`, "세로선 위의 두 점이므로 y 좌표의 차가 거리이다.||Vertical separation is the difference of y-values.", "큰 값에서 작은 값을 뺀다.||Subtract the smaller from the larger.", `답은 ${ans}.`] }; } },
  { name: "intercept_separation", gen(rng) { const a1 = rng.int(2, 12), a2 = rng.int(-12, -2), p1 = rng.int(1, 4), p2 = rng.int(1, 4); const r1 = p1 * a1, r2 = p2 * a2; const ans = a1 - a2; need(Math.abs(r1) < 90 && Math.abs(r2) < 90);
    return { s: `Line 1 has equation ${M(`${p1 === 1 ? "" : p1}x + y = ${r1}`)}${"" } and Line 2 has equation ${M(`${p2 === 1 ? "" : p2}x - y = ${r2}`)}. Both lines are drawn in the same plane.`, q: sp(rng, `[[How many units apart are the ${M("x")}-intercepts of the two lines?|What is the distance between the points where the two lines cross the ${M("x")}-axis?]]`), a: ans, w: [a1 + a2, Math.abs(r1 - r2), Math.abs(r1 / 2 - r2)],
      p: { p1, r1, p2, r2 }, js: "const x1 = P.r1 / P.p1; const x2 = P.r2 / P.p2; return Math.abs(x1 - x2);", t: [`첫 직선: y = 0 이면 x = ${r1}/${p1} = ${a1}.`, `둘째 직선: y = 0 이면 x = ${r2}/${p2} = ${a2}.`, "x 절편 두 점의 좌표를 구한다.||Find both x-intercepts.", "두 점 사이의 거리는 좌표의 차의 절댓값.||Distance is the absolute difference.", `답은 ${ans}.`] }; } },
  { name: "lattice_points_on_segment", gen(rng) { const g = rng.int(2, 7), u = rng.int(1, 5), v = rng.int(1, 5); need(Math.abs(u) !== Math.abs(v) && ((x: number, y: number) => { const h = (a: number, b: number): number => (b ? h(b, a % b) : a); return h(x, y) === 1; })(u, v)); const dx = g * u, dy = g * v * rng.pick([1, -1]); const x1 = rng.int(-5, 3), y1 = rng.int(-5, 5); const ans = g + 1;
    return { s: `A straight segment joins ${M(P(x1, y1))} and ${M(P(x1 + dx, y1 + dy))}.`, q: sp(rng, `[[How many points with integer coordinates lie on the segment, including both endpoints?|Counting both endpoints, how many lattice points does the segment contain?]]`), a: ans, w: [g, Math.abs(dx) + 1, Math.abs(dx) + Math.abs(dy)],
      p: { x1, y1, x2: x1 + dx, y2: y1 + dy }, js: "let c = 0; const dx = P.x2 - P.x1, dy = P.y2 - P.y1; const n = Math.max(Math.abs(dx), Math.abs(dy)); for (let i = 0; i <= n; i++) { const x = P.x1 + dx * i / n, y = P.y1 + dy * i / n; if (Number.isInteger(x) && Number.isInteger(y) && Math.abs(x - Math.round(x)) < 1e-9) c++; } return c;", t: [`변화량 dx = ${dx}, dy = ${dy}.`, `최대공약수 gcd(${Math.abs(dx)}, ${Math.abs(dy)}) = ${g}.||gcd = ${g}.`, "격자점 사이의 간격은 gcd 등분이다.||The segment splits into gcd equal steps.", `격자점 수 = gcd + 1.||Lattice points = gcd + 1.`, `답은 ${ans}.`] }; } },
];
// ───────── kind C: circle_equation_features — 원의 방정식에서 반지름·중심·현·접선·격자점을 구한다 ─────────
const eqExpanded = (D: number, E: number, c: number) => `x^2 + y^2 ${sgn(D)}x ${sgn(E)}y = ${c}`;
const C_COMPOSE: Var[] = [
  { name: "radius_from_expanded", gen(rng) { const h = rng.int(-5, 6), k = rng.int(-5, 6), r = rng.int(3, 10); need(h !== 0 || k !== 0); const D = -2 * h, E = -2 * k, c = r * r - h * h - k * k; need(c > 0 && D !== 0 && E !== 0);
    return { s: `A circle in the plane has equation ${M(eqExpanded(D, E, c))}.`, q: sp(rng, `[[What is the radius of the circle?|Find the radius.]]`), a: r, w: [Math.sqrt(c) | 0 || 1, c + h * h + k * k, r * r],
      p: { D, E, c }, js: "const h = -P.D / 2, k = -P.E / 2; return Math.sqrt(P.c + h * h + k * k);", t: [`x 항과 y 항을 각각 완전제곱식으로 만든다.||Complete the square in x and in y.`, `(x − ${h})² + (y − ${k})² = ${c} + ${h * h} + ${k * k}.`, `우변 = ${r * r}.`, "우변이 r² 이다.||The right side is r^2.", `r = ${r}.`] }; } },
  { name: "center_coordinate_sum", gen(rng) { const h = rng.int(-6, 7), k = rng.int(-6, 7); need(h + k !== 0); const D = -2 * h, E = -2 * k, F = rng.int(-20, 5);
    return { s: `A circle is given by ${M(`x^2 + y^2 ${sgn(D)}x ${sgn(E)}y ${sgn(F)} = 0`)}.`, q: sp(rng, `[[What is the sum of the coordinates of the center of the circle?|The center of the circle has coordinates that add up to what number?]]`), a: h + k, w: [D + E, -(h + k), h * k],
      p: { D, E }, js: "return (-P.D / 2) + (-P.E / 2);", t: [`x² + ${D}x 를 (x + ${D / 2})² 로 완성한다.||Complete the square in x.`, `중심의 x 좌표는 −D/2 = ${h}.||Center x is -D/2.`, `중심의 y 좌표는 −E/2 = ${k}.||Center y is -E/2.`, "두 좌표를 더한다.||Add them.", `답은 ${h + k}.`] }; } },
  { name: "area_over_pi_from_diameter", gen(rng) { const dx = 2 * rng.int(1, 6), dy = 2 * rng.int(1, 6); const x1 = rng.int(-6, 4), y1 = rng.int(-6, 4); const ans = (dx * dx + dy * dy) / 4; need(ans < 200);
    return { s: `The segment from ${M(P(x1, y1))} to ${M(P(x1 + dx, y1 + dy))} is a diameter of a circle. The area of the circle is ${M("k\\pi")}.`, q: sp(rng, `[[What is the value of k?|Find k.]]`), a: ans, w: [Math.sqrt(dx * dx + dy * dy), (dx * dx + dy * dy) / 2, dx * dx + dy * dy],
      p: { x1, y1, x2: x1 + dx, y2: y1 + dy }, js: "const d2 = (P.x2 - P.x1) ** 2 + (P.y2 - P.y1) ** 2; const r2 = d2 / 4; return r2;", t: [`지름의 제곱 = ${dx}² + ${dy}² = ${dx * dx + dy * dy}.||Diameter squared.`, "반지름의 제곱은 지름의 제곱의 1/4.||r^2 is one quarter of the diameter squared.", `r² = ${ans}.`, "넓이 = πr².||Area = pi r^2.", `k = ${ans}.`] }; } },
  { name: "chord_on_x_axis", gen(rng) { const [k0, s, r] = rng.pick(TRI.map((t) => [t[0], t[1], t[2]])); const h = rng.int(-5, 6), k = rng.pick([k0, -k0]); const ans = 2 * s;
    return { s: `A circle has center ${M(P(h, k))} and radius ${r}. It intersects the ${M("x")}-axis at two points.`, q: sp(rng, `[[What is the distance between the two points where the circle meets the ${M("x")}-axis?|How long is the chord of the circle that lies along the ${M("x")}-axis?]]`), a: ans, w: [s, r, 2 * r],
      p: { h, k, r }, js: "const half = Math.sqrt(P.r * P.r - P.k * P.k); return 2 * half;", t: [`중심에서 x 축까지의 거리 = |${k}| = ${Math.abs(k)}.||Distance from the center to the axis.`, `반현의 길이² = ${r}² − ${k0}² = ${s * s}.||Half-chord squared.`, `반현 = ${s}.||Half-chord = ${s}.`, "현의 길이는 반현의 두 배.||The chord is twice the half-chord.", `답은 ${ans}.`] }; } },
];
const C_CHAIN: Var[] = [
  { name: "tangent_to_x_axis_constant", gen(rng) { const h = rng.nz(-8, 8), k = rng.pick([-1, 1]) * rng.int(2, 7); const ans = h * h; const D = -2 * h, E = -2 * k;
    return { s: `A circle with center ${M(P(h, k))} is tangent to the ${M("x")}-axis. Its equation can be written as ${M(`x^2 + y^2 ${sgn(D)}x ${sgn(E)}y + c = 0`)}.`, q: sp(rng, `[[What is the value of c?|Find c.]]`), a: ans, w: [h * h + k * k, k * k, ans + k * k - 1 || 3],
      p: { h, k }, js: "const r2 = P.k * P.k; return P.h * P.h + P.k * P.k - r2;", t: [`x 축에 접하므로 r = |${k}| = ${Math.abs(k)}.||Tangent to the x-axis means r = |k|.`, `(x − ${h})² + (y − ${k})² = ${k * k}.`, `전개하면 상수항 ${h * h} + ${k * k} − ${k * k}.||Expand.`, "c 는 이동한 상수항이다.||c is the constant after moving everything to one side.", `c = ${ans}.`] }; } },
  { name: "nearest_distance_to_circle", gen(rng) { const m = rng.int(2, 4); const [a, b, c5] = [3, 4, 5]; const h = rng.int(-4, 4), k = rng.int(-4, 4); const px = h + a * m, py = k + b * m; const r = rng.int(1, 5 * m - 2); const ans = 5 * m - r;
    return { s: `A circle has center ${M(P(h, k))} and radius ${r}. The point ${M(P(px, py))} lies outside the circle.`, q: sp(rng, `[[What is the shortest distance from the point to the circle?|How far is the point from the nearest point of the circle?]]`), a: ans, w: [5 * m, a * m + b * m - r, r],
      p: { h, k, r, px, py }, js: dist2 + "return Math.sqrt(d2([P.h, P.k], [P.px, P.py])) - P.r;", t: [`중심에서 점까지의 거리 = √(${a * m}² + ${b * m}²) = ${5 * m}.||Center-to-point distance.`, "가장 가까운 점은 중심과 점을 잇는 선 위에 있다.||The nearest point lies on the line through the center.", `가장 짧은 거리 = ${5 * m} − ${r}.`, "반지름만큼 뺀다.||Subtract the radius.", `답은 ${ans}.`] }; } },
  { name: "diameter_circle_rhs", gen(rng) { const dx = 2 * rng.int(1, 6), dy = 2 * rng.int(1, 6); const x1 = rng.int(-6, 4), y1 = rng.int(-6, 4); const R = (dx * dx + dy * dy) / 4; const hx = x1 + dx / 2, hy = y1 + dy / 2;
    return { s: `The segment with endpoints ${M(P(x1, y1))} and ${M(P(x1 + dx, y1 + dy))} is a diameter of a circle with equation ${M(`(x ${sgn(-hx)})^2 + (y ${sgn(-hy)})^2 = R`)}.`, q: sp(rng, `[[What is the value of R?|Find R.]]`), a: R, w: [Math.sqrt(R), 2 * R, dx * dx + dy * dy],
      p: { x1, y1, x2: x1 + dx, y2: y1 + dy }, js: "const cx = (P.x1 + P.x2) / 2, cy = (P.y1 + P.y2) / 2; return (P.x1 - cx) ** 2 + (P.y1 - cy) ** 2;", t: [`중심 = 중점 = (${hx}, ${hy}).||The center is the midpoint.`, `반지름² = 끝점과 중심 사이 거리².||r^2 is the squared distance to the center.`, `(${x1} − ${hx})² + (${y1} − ${hy})².`, `= ${(x1 - hx) ** 2} + ${(y1 - hy) ** 2}.`, `R = ${R}.`] }; } },
  { name: "r_squared_from_point", gen(rng) { const h = rng.int(-6, 6), k = rng.int(-6, 6), px = h + rng.int(-7, 7), py = k + rng.int(-7, 7); const ans = (px - h) ** 2 + (py - k) ** 2; need(ans > 4 && ans < 200);
    return { s: `A circle has center ${M(P(h, k))} and passes through the point ${M(P(px, py))}. Its equation is ${M(`(x ${sgn(-h)})^2 + (y ${sgn(-k)})^2 = r^2`)}.`, q: sp(rng, `[[What is the value of ${M("r^2")}?|Find ${M("r^2")}.]]`), a: ans, w: [Math.abs(px - h) + Math.abs(py - k), Math.sqrt(ans), ans + 2 * (px - h)],
      p: { h, k, px, py }, js: "return (P.px - P.h) ** 2 + (P.py - P.k) ** 2;", t: [`점을 방정식에 대입한다.||Substitute the point.`, `(${px} − ${h})² + (${py} − ${k})².`, `= ${(px - h) ** 2} + ${(py - k) ** 2}.`, "합이 r² 이다.||The sum is r^2.", `r² = ${ans}.`] }; } },
];
const C_INVERSE: Var[] = [
  { name: "center_x_from_point", gen(rng) { const k = rng.int(-3, 3); const [u, w, r] = rng.pick(TRI.map((t) => [t[0], t[1], t[2]])); const py = k + u; const px = rng.int(1, w - 1); const h = px + w; need(h > 0 && px - w < 0);
    return { s: `A circle with center ${M(`(h, ${k})`)} and radius ${r} passes through the point ${M(P(px, py))}, where h is positive.`, q: sp(rng, `[[What is the value of h?|Find h.]]`), a: h, w: [px - w, px, h + 1],
      p: { k, r, px, py }, js: "let ans = null; for (let h = 1; h <= 200; h++) { if ((P.px - h) ** 2 + (P.py - P.k) ** 2 === P.r * P.r) ans = h; } return ans;", t: [`(${px} − h)² + (${py} − ${k})² = ${r}².`, `(${px} − h)² = ${r * r} − ${u * u} = ${w * w}.`, `${px} − h = ±${w}.`, `h > 0 이므로 h = ${px} + ${w}.||Since h is positive.`, `h = ${h}.`] }; } },
  { name: "single_point_constant", gen(rng) { const D = 2 * rng.nz(-6, 6), E = 2 * rng.nz(-6, 6); const F = (D * D + E * E) / 4;
    return { s: `The graph of ${M(`x^2 + y^2 ${sgn(D)}x ${sgn(E)}y + F = 0`)} is a single point in the plane, where F is a constant.`, q: sp(rng, `[[What is the value of F?|Find F.]]`), a: F, w: [(D + E) / 2, F + D, Math.abs(D * E) / 4 + 1],
      p: { D, E }, js: "for (let F = -300; F <= 600; F++) { const r2 = (P.D * P.D + P.E * P.E) / 4 - F; if (r2 === 0) return F; } throw new Error('none');", t: [`완전제곱식으로 만들면 r² = (D² + E²)/4 − F.||After completing the square, r^2 = (D^2+E^2)/4 - F.`, "그래프가 한 점이면 r² = 0.||A single point means r^2 = 0.", `(${D * D} + ${E * E})/4 = ${F}.`, "F 와 같다.||F equals that value.", `F = ${F}.`] }; } },
  { name: "diameter_from_area", gen(rng) { const r = rng.int(3, 15); const ans = 2 * r;
    return { s: `A circle in the coordinate plane has an area of ${M(`${r * r}\\pi`)} square units.`, q: sp(rng, `[[What is the length of a diameter of the circle?|How long is the diameter of the circle, in units?]]`), a: ans, w: [r, r * r, ans + 2],
      p: { A: r * r }, js: "for (let r = 1; r <= 200; r++) { if (r * r === P.A) return 2 * r; } throw new Error('none');", t: [`πr² = ${r * r}π.`, `r² = ${r * r}.`, `r = ${r}.`, "지름은 반지름의 두 배.||The diameter is twice the radius.", `답은 ${ans}.`] }; } },
  { name: "translated_center_sum", gen(rng) { const a = rng.int(-5, 6), b = rng.int(-5, 6), u = rng.nz(-6, 7), v = rng.nz(-6, 7); const R = rng.pick([9, 16, 25, 36]); const ans = a + b + u + v; need(ans !== 0);
    return { s: `The circle ${M(`(x ${sgn(-a)})^2 + (y ${sgn(-b)})^2 = ${R}`)} is translated ${Math.abs(u)} ${Math.abs(u) === 1 ? "unit" : "units"} ${u > 0 ? "right" : "left"} and ${Math.abs(v)} ${Math.abs(v) === 1 ? "unit" : "units"} ${v > 0 ? "up" : "down"}.`, q: sp(rng, `[[What is the sum of the coordinates of the center of the new circle?|The new circle's center has coordinates that add up to what number?]]`), a: ans, w: [a + b, u + v, ans + R],
      p: { a, b, u, v }, js: "const cx = P.a + P.u, cy = P.b + P.v; return cx + cy;", t: [`원래 중심 = (${a}, ${b}).`, `이동 = (${u}, ${v}).`, `새 중심 = (${a + u}, ${b + v}).`, "반지름은 바뀌지 않는다.||The radius does not change.", `합 = ${ans}.`] }; } },
];
const C_COMPARE: Var[] = [
  { name: "radius_gap", gen(rng) { const r1 = rng.int(6, 13), r2 = rng.int(2, 5); const h1 = rng.int(-4, 4), k1 = rng.int(-4, 4), h2 = rng.int(-4, 4), k2 = rng.int(-4, 4); const ans = r1 - r2;
    return { s: `Circle P has equation ${M(`(x ${sgn(-h1)})^2 + (y ${sgn(-k1)})^2 = ${r1 * r1}`)} and Circle Q has equation ${M(`(x ${sgn(-h2)})^2 + (y ${sgn(-k2)})^2 = ${r2 * r2}`)}.`, q: sp(rng, `[[How much longer is the radius of Circle P than the radius of Circle Q?|What is the radius of Circle P minus the radius of Circle Q?]]`), a: ans, w: [r1 * r1 - r2 * r2, r1 + r2, ans * ans],
      p: { R1: r1 * r1, R2: r2 * r2 }, js: "return Math.sqrt(P.R1) - Math.sqrt(P.R2);", t: [`P 의 r² = ${r1 * r1}.`, `Q 의 r² = ${r2 * r2}.`, "오른쪽 값은 r² 이므로 제곱근을 취한다.||The right side is r^2, so take square roots.", `${r1} − ${r2}.`, `답은 ${ans}.`] }; } },
  { name: "points_inside_count", gen(rng) { const h = rng.int(-3, 3), k = rng.int(-3, 3), r = rng.int(4, 7); const pts: [number, number][] = []; const seen = new Set<string>(); while (pts.length < 7) { const x = h + rng.int(-7, 7), y = k + rng.int(-7, 7); const key = `${x},${y}`; if (seen.has(key)) continue; const d = (x - h) ** 2 + (y - k) ** 2; if (d === r * r) continue; seen.add(key); pts.push([x, y]); } const ans = pts.filter(([x, y]) => (x - h) ** 2 + (y - k) ** 2 < r * r).length; need(ans >= 2 && ans <= 5);
    return { s: `A circle has center ${M(P(h, k))} and radius ${r}. Seven points are plotted: ${pts.map(([x, y]) => M(P(x, y))).join(", ")}.`, q: sp(rng, `[[How many of the seven points lie strictly inside the circle?|Counting only points inside the circle, not on it, how many of the seven are there?]]`), a: ans, w: [7 - ans, ans + 1, ans - 1],
      p: { h, k, r, pts: pts.flat() }, js: "let c = 0; for (let i = 0; i < P.pts.length; i += 2) { const d2 = (P.pts[i] - P.h) ** 2 + (P.pts[i + 1] - P.k) ** 2; if (d2 < P.r * P.r) c++; } return c;", t: [`${r}² = ${r * r}.`, "각 점의 중심까지 거리의 제곱을 구한다.||Compute each point's squared distance to the center.", "제곱이 반지름의 제곱보다 작은 점이 안쪽이다.||Inside means a smaller squared distance.", "경계 위의 점은 세지 않는다.||Points on the circle are not counted.", `안쪽의 점은 ${ans} 개.||${ans} points are inside.`] }; } },
  { name: "gap_between_circles", gen(rng) { const m = rng.int(2, 4); const d = 5 * m; const r1 = rng.int(1, 4), r2 = rng.int(1, 4); need(r1 + r2 < d); const ans = d - r1 - r2; const x1 = rng.int(-5, 3), y1 = rng.int(-5, 3);
    return { s: `Circle A has center ${M(P(x1, y1))} and radius ${r1}. Circle B has center ${M(P(x1 + 3 * m, y1 + 4 * m))} and radius ${r2}. The circles do not touch.`, q: sp(rng, `[[What is the shortest distance between the two circles?|What is the length of the shortest segment joining a point of Circle A to a point of Circle B?]]`), a: ans, w: [d, d - Math.abs(r1 - r2), r1 + r2],
      p: { x1, y1, x2: x1 + 3 * m, y2: y1 + 4 * m, r1, r2 }, js: "return Math.sqrt((P.x2 - P.x1) ** 2 + (P.y2 - P.y1) ** 2) - P.r1 - P.r2;", t: [`중심 거리 = √(${3 * m}² + ${4 * m}²) = ${d}.||Distance between centers.`, "두 원이 떨어져 있으므로 반지름의 합을 뺀다.||The circles are apart, so subtract both radii.", `${d} − ${r1} − ${r2}.`, "그 값이 두 원 사이의 최단 거리이다.||That is the shortest gap.", `답은 ${ans}.`] }; } },
  { name: "lattice_points_on_circle", gen(rng) { const R = rng.pick([25, 50, 65, 85, 100, 125, 130]); let c = 0; for (let x = -12; x <= 12; x++) for (let y = -12; y <= 12; y++) if (x * x + y * y === R) c++;
    return { s: `The circle ${M(`x^2 + y^2 = ${R}`)} is drawn on a grid. A lattice point is a point whose coordinates are both integers.`, q: sp(rng, `[[How many lattice points lie on the circle?|How many points with integer coordinates are on the circle?]]`), a: c, w: [c / 2, c + 4, c - 4],
      p: { R }, js: "let n = 0; for (let x = -30; x <= 30; x++) { for (let y = -30; y <= 30; y++) { if (x * x + y * y === P.R) n++; } } return n;", t: [`x² + y² = ${R} 의 정수해를 찾는다.||Find integer solutions of x^2 + y^2 = ${R}.`, "x 를 −11 부터 11 까지 대입해 y² 이 완전제곱인지 본다.||Try x values and test whether y^2 is a perfect square.", "부호 조합도 모두 센다.||Count all sign combinations.", "대칭이므로 사분면별로 같은 개수.||Symmetry gives equal counts per quadrant.", `답은 ${c}.`] }; } },
];
// ───────── kind T: plane_figure_measures — 좌표로 주어진 삼각형·사각형의 길이·넓이·꼭짓점 ─────────
const T_COMPOSE: Var[] = [
  { name: "triangle_area_from_vertices", gen(rng) { const x1 = rng.int(-5, 2), y1 = rng.int(-5, 3), x2 = x1 + rng.int(2, 8), y2 = y1 + rng.int(-3, 4), x3 = x1 + rng.int(-2, 6), y3 = y1 + rng.int(3, 9); const cr = (x2 - x1) * (y3 - y1) - (x3 - x1) * (y2 - y1); need(cr !== 0 && Math.abs(cr) % 2 === 0); const ans = Math.abs(cr) / 2; need(ans < 90);
    return { s: `A triangle has vertices ${M(P(x1, y1))}, ${M(P(x2, y2))}, and ${M(P(x3, y3))}.`, q: sp(rng, `[[What is the area of the triangle?|Find the area of the triangle.]]`), a: ans, w: [Math.abs(cr), ans + 1, Math.abs((x2 - x1) * (y3 - y1)) / 2],
      p: { x1, y1, x2, y2, x3, y3 }, js: "return Math.abs(P.x1 * (P.y2 - P.y3) + P.x2 * (P.y3 - P.y1) + P.x3 * (P.y1 - P.y2)) / 2;", t: [`두 변 벡터 (${x2 - x1}, ${y2 - y1}) 와 (${x3 - x1}, ${y3 - y1}).||Two side vectors.`, "외적의 절댓값을 2 로 나누면 넓이.||Half the absolute cross product is the area.", `${x2 - x1}·${y3 - y1} − ${x3 - x1}·${y2 - y1} = ${cr}.`, `|${cr}| ÷ 2.`, `답은 ${ans}.`] }; } },
  { name: "right_triangle_perimeter", gen(rng) { const [p, q, h] = rng.pick(TRI); const a = rng.int(-5, 3), b = rng.int(-5, 3); const ans = p + q + h;
    return { s: `A triangle has vertices ${M(P(a, b))}, ${M(P(a + p, b))}, and ${M(P(a, b + q))}.`, q: sp(rng, `[[What is the perimeter of the triangle?|Find the total length of the three sides.]]`), a: ans, w: [p + q, p * q, ans - 1],
      p: { a, b, bx: a + p, cy: b + q }, js: "const A = [P.a, P.b], B = [P.bx, P.b], C = [P.a, P.cy]; const len = (u, v) => Math.sqrt((u[0] - v[0]) ** 2 + (u[1] - v[1]) ** 2); return len(A, B) + len(B, C) + len(C, A);", t: [`두 변은 축과 평행: ${p} 와 ${q}.||Two sides are axis-parallel.`, "직각이므로 피타고라스 정리.||The angle is a right angle.", `빗변 = √(${p}² + ${q}²) = ${h}.`, `둘레 = ${p} + ${q} + ${h}.`, `답은 ${ans}.`] }; } },
  { name: "centroid_coordinate_sum", gen(rng) { const x = [rng.int(-5, 6), rng.int(-5, 6), 0], y = [rng.int(-5, 6), rng.int(-5, 6), 0]; const sx = x[0] + x[1], sy = y[0] + y[1]; x[2] = ((3 - (((sx % 3) + 3) % 3)) % 3) + 3 * rng.int(-1, 2) - 0; y[2] = ((3 - (((sy % 3) + 3) % 3)) % 3) + 3 * rng.int(-1, 2); const gx = (x[0] + x[1] + x[2]) / 3, gy = (y[0] + y[1] + y[2]) / 3; need(isInt(gx) && isInt(gy) && gx + gy !== 0);
    return { s: `A triangle has vertices ${M(P(x[0], y[0]))}, ${M(P(x[1], y[1]))}, and ${M(P(x[2], y[2]))}. The centroid is the point whose coordinates are the averages of the vertex coordinates.`, q: sp(rng, `[[What is the sum of the coordinates of the centroid?|The centroid has coordinates that add up to what number?]]`), a: gx + gy, w: [x[0] + x[1] + x[2] + y[0] + y[1] + y[2], gx * gy, gx],
      p: { x: x, y: y }, js: "let sx = 0, sy = 0; for (let i = 0; i < 3; i++) { sx += P.x[i]; sy += P.y[i]; } return sx / 3 + sy / 3;", t: [`x 좌표 평균 = (${x.join(" + ")}) ÷ 3 = ${gx}.`.replace(/\+ -/g, "+ -"), `y 좌표 평균 = (${y.join(" + ")}) ÷ 3 = ${gy}.`, "무게중심은 세 꼭짓점의 평균점.||The centroid is the average point.", "두 좌표를 더한다.||Add the coordinates.", `답은 ${gx + gy}.`] }; } },
  { name: "rectangle_area_from_corners", gen(rng) { const x1 = rng.int(-6, 2), y1 = rng.int(-6, 2), w = rng.int(2, 9), h = rng.int(2, 9); need(w !== h); const ans = w * h;
    return { s: `A rectangle has sides parallel to the axes. Two opposite corners are ${M(P(x1, y1))} and ${M(P(x1 + w, y1 + h))}.`, q: sp(rng, `[[What is the area of the rectangle?|Find the area of the rectangle.]]`), a: ans, w: [2 * (w + h), w + h, Math.sqrt(w * w + h * h)],
      p: { x1, y1, x2: x1 + w, y2: y1 + h }, js: "return Math.abs(P.x2 - P.x1) * Math.abs(P.y2 - P.y1);", t: [`가로 = |${x1 + w} − ${x1}| = ${w}.||Width.`, `세로 = |${y1 + h} − ${y1}| = ${h}.||Height.`, "변이 축과 평행하다.||The sides are parallel to the axes.", `넓이 = ${w} × ${h}.`, `답은 ${ans}.`] }; } },
];
const T_CHAIN: Var[] = [
  { name: "parallelogram_fourth_vertex", gen(rng) { const ax = rng.int(-5, 3), ay = rng.int(-5, 3), bx = ax + rng.int(2, 8), by = ay + rng.int(-2, 3), cx = bx + rng.int(-3, 4), cy = by + rng.int(2, 7); const dx = ax + cx - bx, dy = ay + cy - by; need(dx + dy !== 0);
    return { s: `The points ${M(`A${P(ax, ay)}`)}, ${M(`B${P(bx, by)}`)}, and ${M(`C${P(cx, cy)}`)} are three consecutive vertices of a parallelogram ABCD.`, q: sp(rng, `[[What is the sum of the coordinates of vertex D?|Vertex D has coordinates that add up to what number?]]`), a: dx + dy, w: [ax + ay, bx + by + cx + cy, dx * dy],
      p: { ax, ay, bx, by, cx, cy }, js: "const dx = P.ax + P.cx - P.bx, dy = P.ay + P.cy - P.by; return dx + dy;", t: [`평행사변형의 대각선은 서로 이등분한다.||The diagonals bisect each other.`, "AC 의 중점 = BD 의 중점.||The midpoint of AC equals that of BD.", `D = A + C − B = (${dx}, ${dy}).`, "두 좌표를 더한다.||Add the coordinates.", `답은 ${dx + dy}.`] }; } },
  { name: "median_length", gen(rng) { const m = rng.int(1, 3); const mx = rng.int(-4, 4), my = rng.int(-4, 4); const ux = rng.int(1, 5), uy = rng.int(-4, 4); const cx = mx + 3 * m, cy = my + 4 * m; const ans = 5 * m;
    return { s: `In a triangle, the endpoints of side AB are ${M(`A${P(mx - ux, my - uy)}`)} and ${M(`B${P(mx + ux, my + uy)}`)}. The third vertex is ${M(`C${P(cx, cy)}`)}.`, q: sp(rng, `[[What is the length of the median from C to side AB?|Find the distance from C to the midpoint of AB.]]`), a: ans, w: [3 * m + 4 * m, Math.sqrt(ux * ux + uy * uy), ans + m],
      p: { ax: mx - ux, ay: my - uy, bx: mx + ux, by: my + uy, cx, cy }, js: "const mx = (P.ax + P.bx) / 2, my = (P.ay + P.by) / 2; return Math.sqrt((P.cx - mx) ** 2 + (P.cy - my) ** 2);", t: [`AB 의 중점 = (${mx}, ${my}).||Midpoint of AB.`, `C 와의 가로 차 ${3 * m}, 세로 차 ${4 * m}.||Offsets.`, "피타고라스 정리로 거리를 구한다.||Use the distance formula.", `√(${3 * m}² + ${4 * m}²).`, `답은 ${ans}.`] }; } },
  { name: "dilated_area", gen(rng) { const bw = rng.int(2, 8), h = 2 * rng.int(1, 5), k = rng.int(2, 4); const x1 = rng.int(1, 3), y1 = rng.int(1, 3); const S = (bw * h) / 2; const ans = S * k * k; need(ans < 900);
    return { s: `A triangle has vertices ${M(P(x1, y1))}, ${M(P(x1 + bw, y1))}, and ${M(P(x1, y1 + h))}. The triangle is dilated by a factor of ${k} from the origin.`, q: sp(rng, `[[What is the area of the dilated triangle?|After the dilation, what is the area of the image triangle?]]`), a: ans, w: [S * k, S, ans / k + 1],
      p: { x1, y1, xb: x1 + bw, yh: y1 + h, k }, js: "const area = (P.xb - P.x1) * (P.yh - P.y1) / 2; return area * P.k * P.k;", t: [`원래 넓이 = ${bw} × ${h} ÷ 2 = ${S}.||Original area.`, "닮음비가 k 이면 넓이의 비는 k².||Area scales by k^2.", `k² = ${k * k}.`, `${S} × ${k * k}.`, `답은 ${ans}.`] }; } },
  { name: "apex_height_from_area", gen(rng) { const a = rng.int(-6, 0), len = rng.int(2, 9); const b = a + len; const hgt = rng.int(2, 9); const A = (len * hgt) / 2; need(isInt(A)); const ans = hgt;
    return { s: `A triangle has two vertices at ${M(P(a, 0))} and ${M(P(b, 0))}. Its third vertex is above the ${M("x")}-axis, and the area of the triangle is ${A}.`, q: sp(rng, `[[What is the ${M("y")}-coordinate of the third vertex?|How high above the ${M("x")}-axis is the third vertex?]]`), a: ans, w: [A, len, 2 * A],
      p: { a, b, A }, js: "const base = P.b - P.a; for (let y = 1; y <= 200; y++) { if (base * y / 2 === P.A) return y; } throw new Error('none');", t: [`밑변 = ${b} − ${a} = ${len}.||Base length.`, `넓이 = (1/2) × 밑변 × 높이.||Area = 1/2 base height.`, `${A} = ${len} × h ÷ 2.`, `h = ${2 * A} ÷ ${len}.`, `답은 ${ans}.`] }; } },
];
const T_INVERSE: Var[] = [
  { name: "collinear_k", gen(rng) { const m = rng.pick([1, 2, 3, -1, -2, -3]); const ax = rng.int(-5, 3), ay = rng.int(-5, 5), bx = ax + rng.int(1, 4), cx = bx + rng.int(1, 5); const by = ay + m * (bx - ax), k = ay + m * (cx - ax); need(Math.abs(k) < 60);
    return { s: `The points ${M(P(ax, ay))}, ${M(P(bx, by))}, and ${M(`(${cx}, k)`)} lie on one straight line.`, q: sp(rng, `[[What is the value of k?|Find k.]]`), a: k, w: [by, ay + (cx - ax), ay + m],
      p: { ax, ay, bx, by, cx }, js: "const m = (P.by - P.ay) / (P.bx - P.ax); return P.ay + m * (P.cx - P.ax);", t: [`첫 두 점의 기울기 = ${m}.||Slope from the first two points.`, "세 점이 한 직선 위에 있으면 기울기가 모두 같다.||All slopes must be equal.", `(k − ${ay}) ÷ (${cx} − ${ax}) = ${m}.`, `k = ${ay} + ${m}(${cx - ax}).`, `k = ${k}.`] }; } },
  { name: "equidistant_point_on_axis", gen(rng) { const pairs: [number, number, number, number][] = [[3, 4, 5, 0], [0, 5, 3, 4], [1, 7, 5, 5], [1, 8, 4, 7], [2, 6, 6, 2]]; const [u, v1, w, v2] = rng.pick(pairs); const x0 = rng.int(-4, 5); const ax = x0 + u, ay = v1, bx = x0 - w, by = rng.pick([v2, -v2]); need(ax !== bx);
    return { s: `The point ${M(`P(x, 0)`)} is on the ${M("x")}-axis and is the same distance from ${M(`A${P(ax, ay)}`)} as from ${M(`B${P(bx, by)}`)}.`, q: sp(rng, `[[What is the value of ${M("x")}?|Find the ${M("x")}-coordinate of P.]]`), a: x0, w: [(ax + bx) / 2, ax + bx, x0 + 1],
      p: { ax, ay, bx, by }, js: "let sol = null; for (let x = -200; x <= 200; x++) { if ((x - P.ax) ** 2 + P.ay ** 2 === (x - P.bx) ** 2 + P.by ** 2) sol = x; } return sol;", t: [`(x − ${ax})² + ${ay}² = (x − ${bx})² + ${by}².`, "양변을 전개하면 x² 항이 소거된다.||The x^2 terms cancel.", `${-2 * ax}x + ${ax * ax + ay * ay} = ${-2 * bx}x + ${bx * bx + by * by}.`, `x = (${bx * bx + by * by} − ${ax * ax + ay * ay}) ÷ ${-2 * bx + 2 * ax}.`, `x = ${x0}.`] }; } },
  { name: "rectangle_from_three_corners", gen(rng) { const x1 = rng.int(-6, 2), y1 = rng.int(-6, 2), w = rng.int(2, 9), h = rng.int(2, 9); need(w !== h); const ans = w * h;
    return { s: `Three corners of a rectangle with sides parallel to the axes are ${M(P(x1, y1))}, ${M(P(x1 + w, y1))}, and ${M(P(x1 + w, y1 + h))}.`, q: sp(rng, `[[What is the area of the rectangle?|Find the area of the rectangle.]]`), a: ans, w: [2 * (w + h), w + h, w * w],
      p: { x1, y1, x2: x1 + w, y3: y1 + h }, js: "return (P.x2 - P.x1) * (P.y3 - P.y1);", t: [`첫째와 둘째 점은 같은 높이: 가로 ${w}.||Width from the first two points.`, `둘째와 셋째 점은 같은 x: 세로 ${h}.||Height from the last two.`, "네 번째 꼭짓점은 필요 없다.||The fourth vertex is not needed.", `넓이 = ${w} × ${h}.`, `답은 ${ans}.`] }; } },
  { name: "square_area_from_diagonal", gen(rng) { const dx = rng.int(2, 10), dy = rng.int(2, 10); need((dx * dx + dy * dy) % 2 === 0); const x1 = rng.int(-6, 3), y1 = rng.int(-6, 3); const ans = (dx * dx + dy * dy) / 2;
    return { s: `Two opposite corners of a square are ${M(P(x1, y1))} and ${M(P(x1 + dx, y1 + dy))}.`, q: sp(rng, `[[What is the area of the square?|Find the area of the square.]]`), a: ans, w: [dx * dx + dy * dy, Math.sqrt(ans), dx * dy],
      p: { x1, y1, x2: x1 + dx, y2: y1 + dy }, js: "const d2 = (P.x2 - P.x1) ** 2 + (P.y2 - P.y1) ** 2; return d2 / 2;", t: [`대각선² = ${dx}² + ${dy}² = ${dx * dx + dy * dy}.||Diagonal squared.`, "정사각형의 넓이 = 대각선² ÷ 2.||Area of a square = d^2 / 2.", "한 변을 s 라 하면 대각선² = 2s².||With side s, d^2 = 2 s^2.", `s² = ${dx * dx + dy * dy} ÷ 2.`, `답은 ${ans}.`] }; } },
];
const T_COMPARE: Var[] = [
  { name: "triangle_area_gap", gen(rng) { const b1 = rng.int(3, 10), h1 = 2 * rng.int(2, 6), b2 = rng.int(2, 8), h2 = 2 * rng.int(1, 5); const A1 = (b1 * h1) / 2, A2 = (b2 * h2) / 2; need(A1 > A2); const ans = A1 - A2; const x0 = rng.int(0, 3), y0 = rng.int(0, 3);
    return { s: `Triangle T1 has vertices ${M(P(x0, y0))}, ${M(P(x0 + b1, y0))}, and ${M(P(x0, y0 + h1))}. Triangle T2 has vertices ${M(P(0, 0))}, ${M(P(b2, 0))}, and ${M(P(0, h2))}.`, q: sp(rng, `[[By how much is the area of T1 greater than the area of T2?|What is the area of T1 minus the area of T2?]]`), a: ans, w: [A1 + A2, b1 * h1 - b2 * h2, A1],
      p: { x0, y0, xb: x0 + b1, yh: y0 + h1, b2, h2 }, js: "return (P.xb - P.x0) * (P.yh - P.y0) / 2 - P.b2 * P.h2 / 2;", t: [`T1 넓이 = ${b1} × ${h1} ÷ 2 = ${A1}.`, `T2 넓이 = ${b2} × ${h2} ÷ 2 = ${A2}.`, "두 삼각형 모두 직각이므로 밑변×높이÷2.||Both are right triangles.", `${A1} − ${A2}.`, `답은 ${ans}.`] }; } },
  { name: "side_length_gap", gen(rng) { const t1 = rng.pick(TRI), t2 = rng.pick(TRI); need(t1[2] > t2[2]); const ans = t1[2] - t2[2]; const ox = rng.int(-4, 4), oy = rng.int(-4, 4);
    return { s: `The point ${M(`A${P(ox, oy)}`)} is joined to ${M(`B${P(ox + t1[0], oy + t1[1])}`)} and to ${M(`C${P(ox - t2[1], oy + t2[0])}`)}.`, q: sp(rng, `[[How much longer is AB than AC?|What is the length of AB minus the length of AC?]]`), a: ans, w: [t1[2] + t2[2], t1[0] - t2[0], ans + 1],
      p: { ox, oy, bx: ox + t1[0], by: oy + t1[1], cx: ox - t2[1], cy: oy + t2[0] }, js: "const len = (a, b, c, d) => Math.sqrt((a - c) ** 2 + (b - d) ** 2); return len(P.ox, P.oy, P.bx, P.by) - len(P.ox, P.oy, P.cx, P.cy);", t: [`AB: √(${t1[0]}² + ${t1[1]}²) = ${t1[2]}.`, `AC: √(${t2[1]}² + ${t2[0]}²) = ${t2[2]}.`, "각각 거리 공식을 쓴다.||Use the distance formula for each.", `${t1[2]} − ${t2[2]}.`, `답은 ${ans}.`] }; } },
  { name: "interior_lattice_count", gen(rng) { const w = rng.int(4, 12), h = rng.int(3, 10); need(w !== h); const ans = (w - 1) * (h - 1);
    return { s: `A rectangle has corners ${M(P(0, 0))}, ${M(P(w, 0))}, ${M(P(w, h))}, and ${M(P(0, h))}. A lattice point is a point whose coordinates are both integers.`, q: sp(rng, `[[How many lattice points lie strictly inside the rectangle, not on its sides?|How many integer-coordinate points are in the interior of the rectangle?]]`), a: ans, w: [(w + 1) * (h + 1), w * h, 2 * (w + h)],
      p: { w, h }, js: "let c = 0; for (let x = 1; x < P.w; x++) { for (let y = 1; y < P.h; y++) c++; } return c;", t: [`내부의 x 좌표: 1 부터 ${w - 1} 까지 ${w - 1} 개.||Interior x-values.`, `내부의 y 좌표: 1 부터 ${h - 1} 까지 ${h - 1} 개.||Interior y-values.`, "변 위의 점은 제외한다.||Exclude boundary points.", "각 조합이 하나의 점이다.||Each pair is one point.", `${w - 1} × ${h - 1} = ${ans}.`] }; } },
  { name: "taxicab_vs_straight", gen(rng) { const [a, b, h] = rng.pick(TRI); const ans = a + b - h; const x1 = rng.int(-5, 3), y1 = rng.int(-5, 3);
    return { s: `A delivery route runs from ${M(P(x1, y1))} to ${M(P(x1 + a, y1 + b))} along the grid lines only, moving horizontally and then vertically.`, q: sp(rng, `[[How much shorter would a straight segment between the two points be than the grid route?|By how many units does the grid route exceed the straight-line distance?]]`), a: ans, w: [h, a + b, ans + 1],
      p: { x1, y1, x2: x1 + a, y2: y1 + b }, js: "const route = Math.abs(P.x2 - P.x1) + Math.abs(P.y2 - P.y1); const straight = Math.sqrt((P.x2 - P.x1) ** 2 + (P.y2 - P.y1) ** 2); return route - straight;", t: [`격자 경로 = ${a} + ${b} = ${a + b}.||Grid route.`, `직선 거리 = √(${a}² + ${b}²) = ${h}.||Straight line.`, "두 길이의 차를 구한다.||Take the difference.", `${a + b} − ${h}.`, `답은 ${ans}.`] }; } },
];

const CG_BASE = { skill: SKILL, mediumSteps: 3 };
export const CG_SPR_A: Archetype[] = [
  ...mkKind({ ...CG_BASE, id: "cgl.line_equation_features", kind: "line_equation_features", concepts: ["직선의 방정식", "기울기와 절편", "좌표 계산"] }, [
    { op: "compose_kind", structure: "두 점·절편·점-기울기 정보를 합성해 x 절편·삼각형 넓이·함수값·절편 중점을 구함", extra: "직선의 식을 먼저 세운 뒤 다른 양(절편·넓이)으로 환산해야 함 — medium 은 기울기 한 번 계산", vars: dress(L_COMPOSE) },
    { op: "chain2", structure: "평행·수직 조건으로 새 직선의 기울기를 정한 뒤 절편이나 교점을 연쇄로 구함", extra: "앞 단계의 기울기가 다음 단계(절편·교점)의 입력이 됨 — medium 은 기울기 한 번 계산", vars: dress(L_CHAIN) },
    { op: "inverse", structure: "기울기·평행·수직·점 통과 조건에서 미지의 좌표나 계수를 거꾸로 구함", extra: "조건을 식으로 세워 미지 상수를 풀어야 함 — medium 은 정방향 계산", vars: dress(L_INVERSE) },
    { op: "compare_scenarios", structure: "두 직선의 기울기·값·절편 간격·선분 위 격자점 수를 비교", extra: "두 대상을 같은 기준으로 환산해 비교해야 함 — medium 은 직선 하나의 값", vars: dress(L_COMPARE) },
  ]),
  ...mkKind({ ...CG_BASE, id: "cgc.circle_equation_features", kind: "circle_equation_features", concepts: ["원의 방정식", "완전제곱식", "좌표 거리"] }, [
    { op: "compose_kind", structure: "전개된 원의 방정식·지름 끝점·현의 조건을 합성해 반지름·중심·넓이·현의 길이를 구함", extra: "완전제곱식이나 피타고라스를 거쳐야 값이 나옴 — medium 은 표준형에서 읽기", vars: dress(C_COMPOSE) },
    { op: "chain2", structure: "접선 조건·바깥 점 거리·지름 조건으로 r 을 먼저 정한 뒤 상수·거리를 구함", extra: "반지름을 먼저 구한 뒤 다음 양을 계산하는 2단계 — medium 은 표준형에서 읽기", vars: dress(C_CHAIN) },
    { op: "inverse", structure: "원 위의 점·한 점으로 퇴화하는 조건·넓이·평행이동에서 미지 양을 거꾸로 구함", extra: "방정식에 조건을 대입해 미지 상수를 풀어야 함 — medium 은 정방향 읽기", vars: dress(C_INVERSE) },
    { op: "compare_scenarios", structure: "두 원의 반지름·안쪽 점의 수·원 사이 거리·정수 격자점을 비교", extra: "여러 대상을 같은 기준(거리²)으로 비교해야 함 — medium 은 원 하나의 읽기", vars: dress(C_COMPARE) },
  ]),
  ...mkKind({ ...CG_BASE, id: "cgt.plane_figure_measures", kind: "plane_figure_measures", concepts: ["좌표로 주어진 도형", "거리·넓이 공식", "도형의 성질"] }, [
    { op: "compose_kind", structure: "좌표로 주어진 삼각형·직사각형의 넓이·둘레·무게중심을 합성해 구함", extra: "좌표에서 변·높이를 뽑아 공식에 연결해야 함 — medium 은 한 변의 길이", vars: dress(T_COMPOSE) },
    { op: "chain2", structure: "평행사변형 꼭짓점·중선·닮음 확대·높이로 앞 결과를 다음 계산에 연결", extra: "앞 단계에서 구한 점·길이가 다음 계산의 입력이 됨 — medium 은 한 번의 공식", vars: dress(T_CHAIN) },
    { op: "inverse", structure: "일직선 조건·등거리 조건·세 꼭짓점·대각선에서 미지 좌표나 넓이를 거꾸로 구함", extra: "조건을 식으로 세워 풀어야 함 — medium 은 정방향 계산", vars: dress(T_INVERSE) },
    { op: "compare_scenarios", structure: "두 도형의 넓이·변의 길이·격자 경로와 직선 거리·내부 격자점 수를 비교", extra: "여러 양을 같은 기준으로 환산해 비교해야 함 — medium 은 도형 하나의 값", vars: dress(T_COMPARE) },
  ]),
];
void need;
