// equivalent_expressions — 수치 단답(SPR 가능) hard 원형 3 kind × 4 연산자 × 4 변형. 식의 동치·전개·지수·항등식에서 정답이 하나의 수가 되는 문항(기존 식 선지형 원형과 별개).
import { GenFail } from "../types";
import { need, isInt, sp, mkKind, pickDiv, type Var } from "./spr-a-kit";
import { poly, shifted, M } from "../text";
import type { Rng } from "../rng";
import type { Archetype } from "../types";

const SKILL = "equivalent_expressions";
const VARS = ["x", "t", "n", "z"];
const vr = (rng: Rng) => rng.pick(VARS);
const B = (v: string, k: number) => `(${shifted(v, k)})`;
const pl2 = (a: number, b: number, v: string) => poly([a, b], v);
const pl3 = (a: number, b: number, c: number, v: string) => poly([a, b, c], v);
const nzr = (rng: Rng, lo: number, hi: number) => rng.nz(lo, hi);
const dress = (vs: Var[]): Var[] => vs;
const MUL = "const mul = (p, q) => { const r = Array(p.length + q.length - 1).fill(0); p.forEach((a, i) => q.forEach((b, j) => { r[i + j] += a * b; })); return r; };\n";
void GenFail;

// ───────── kind A: coefficient_matching — 전개한 식의 계수·상수항·계수 합을 수로 구한다 ─────────
const A_COMPOSE: Var[] = [
  { name: "three_binomials_x_coefficient", gen(rng) { const v = vr(rng); const a = nzr(rng, -6, 6), b = nzr(rng, -6, 6), c = nzr(rng, -6, 6); need(a !== b && b !== c && a !== c); const ans = a * b + b * c + c * a; need(ans !== 0 && Math.abs(ans) < 90);
    return { s: sp(rng, `[[The expression ${M(`${B(v, a)}${B(v, b)}${B(v, c)}`)} is written in the form ${M(`${v}^3 + p${v}^2 + q${v} + r`)}, where p, q, and r are constants.|Expanding ${M(`${B(v, a)}${B(v, b)}${B(v, c)}`)} gives a cubic ${M(`${v}^3 + p${v}^2 + q${v} + r`)} with constant coefficients p, q, and r.|A student multiplies three binomials, ${M(`${B(v, a)}${B(v, b)}${B(v, c)}`)}, and writes the result as ${M(`${v}^3 + p${v}^2 + q${v} + r`)}.|For every value of ${M(v)}, ${M(`${B(v, a)}${B(v, b)}${B(v, c)}`)} equals ${M(`${v}^3 + p${v}^2 + q${v} + r`)}, where p, q, and r are constants.]]`), q: sp(rng, `[[What is the value of q?|Find q.|What is the coefficient of ${M(v)} after the expression is expanded?]]`), a: ans, w: [a + b + c, a * b * c, -ans],
      p: { a, b, c }, js: MUL + "const f = mul(mul([P.a, 1], [P.b, 1]), [P.c, 1]); return f[1];", t: [`세 이항식을 차례로 곱한다.||Multiply the three binomials in turn.`, `x 항은 두 상수의 곱의 합: ab + bc + ca.||The x-term collects the pairwise products ab + bc + ca.`, `ab = ${a * b}, bc = ${b * c}, ca = ${c * a}.`, `합 = ${ans}.||Sum = ${ans}.`, `q = ${ans}.`] }; } },
  { name: "sum_of_two_squares_cross", gen(rng) { const v = vr(rng); const p = nzr(rng, -4, 5), q = nzr(rng, -6, 6), r = nzr(rng, -4, 5), s = nzr(rng, -6, 6); const ans = 2 * (p * q + r * s); need(ans !== 0 && Math.abs(ans) < 99);
    return { s: sp(rng, `[[The expression ${M(`(${pl2(p, q, v)})^2 + (${pl2(r, s, v)})^2`)} is equivalent to ${M(`A${v}^2 + B${v} + C`)}, where A, B, and C are constants.|Two squared binomials are added: ${M(`(${pl2(p, q, v)})^2 + (${pl2(r, s, v)})^2`)}. The sum is rewritten as ${M(`A${v}^2 + B${v} + C`)}.|Expand ${M(`(${pl2(p, q, v)})^2 + (${pl2(r, s, v)})^2`)} and collect terms to get ${M(`A${v}^2 + B${v} + C`)}, with constants A, B, and C.|For all ${M(v)}, ${M(`(${pl2(p, q, v)})^2 + (${pl2(r, s, v)})^2`)} = ${M(`A${v}^2 + B${v} + C`)}, where A, B, and C do not depend on ${M(v)}.]]`), q: sp(rng, `[[What is the value of B?|Find B.|What is the coefficient of ${M(v)} in the expanded form?]]`), a: ans, w: [p * q + r * s, q + s, 2 * (p * s + r * q)],
      p: { p, q, r, s }, js: MUL + "const f = mul([P.q, P.p], [P.q, P.p]); const g = mul([P.s, P.r], [P.s, P.r]); return f[1] + g[1];", t: [`각 제곱의 중간항은 2 × (x 계수) × (상수).||Each square's middle term is 2 x (coefficient) x (constant).`, `첫째: 2 × ${p} × ${q} = ${2 * p * q}.`, `둘째: 2 × ${r} × ${s} = ${2 * r * s}.`, "두 중간항을 더한다.||Add the middle terms.", `B = ${ans}.`] }; } },
  { name: "constant_after_difference", gen(rng) { const v = vr(rng); const a = rng.int(2, 6), b = rng.int(1, 9), c = rng.int(1, 6), d = rng.int(1, 9); const ans = -(b * b) - d * d;
    return { s: sp(rng, `[[The expression ${M(`(${pl2(a, b, v)})(${pl2(a, -b, v)}) - (${pl2(c, d, v)})^2`)} is rewritten as ${M(`P${v}^2 + Q${v} + R`)}, where P, Q, and R are constants.|A product and a squared binomial are subtracted: ${M(`(${pl2(a, b, v)})(${pl2(a, -b, v)}) - (${pl2(c, d, v)})^2`)}. The result is ${M(`P${v}^2 + Q${v} + R`)}.|Simplify ${M(`(${pl2(a, b, v)})(${pl2(a, -b, v)}) - (${pl2(c, d, v)})^2`)} into the form ${M(`P${v}^2 + Q${v} + R`)}, where P, Q, and R are constants.|For every ${M(v)}, the expression ${M(`(${pl2(a, b, v)})(${pl2(a, -b, v)}) - (${pl2(c, d, v)})^2`)} is equal to ${M(`P${v}^2 + Q${v} + R`)} for some constants P, Q, and R.]]`), q: sp(rng, `[[What is the value of R?|Find the constant term R.|What number is the constant term after the expression is simplified?]]`), a: ans, w: [b * b - d * d, -(b + d), b * b + d * d],
      p: { a, b, c, d }, js: MUL + "const f = mul([P.b, P.a], [-P.b, P.a]); const g = mul([P.d, P.c], [P.d, P.c]); return f[0] - g[0];", t: [`첫 곱은 차의 제곱 공식: (${a}${v})² − ${b}².||The first product is a difference of squares.`, `상수항은 −${b * b}.||Its constant term is -${b * b}.`, `제곱항의 상수항은 ${d * d}.||The square's constant term is ${d * d}.`, `빼므로 R = −${b * b} − ${d * d}.||Subtracting gives R = -${b * b} - ${d * d}.`, `R = ${ans}.`] }; } },
  { name: "sum_of_coefficients", gen(rng) { const v = vr(rng); const a = nzr(rng, -5, 6), b = nzr(rng, -6, 6), c = rng.int(1, 6); need(a !== 0); const ans = (1 + a + b) * (1 - c); need(ans !== 0);
    return { s: sp(rng, `[[The product ${M(`(${pl3(1, a, b, v)})(${v} ${c > 0 ? "-" : "+"} ${Math.abs(c)})`)} is expanded and written in standard form, and the coefficients of its terms are added together.|After ${M(`(${pl3(1, a, b, v)})(${v} ${c > 0 ? "-" : "+"} ${Math.abs(c)})`)} is multiplied out, add up every coefficient, including the constant term.|Write ${M(`(${pl3(1, a, b, v)})(${v} ${c > 0 ? "-" : "+"} ${Math.abs(c)})`)} as a polynomial in standard form and sum its coefficients.|A polynomial is obtained by expanding ${M(`(${pl3(1, a, b, v)})(${v} ${c > 0 ? "-" : "+"} ${Math.abs(c)})`)}. Its coefficients are then totaled.]]`), q: sp(rng, `[[What is the sum of all the coefficients?|What is the sum of the coefficients of the expanded polynomial, including the constant term?|Find the total of the coefficients.]]`), a: ans, w: [(1 + a + b) + (1 - c), 1 - c, -ans],
      p: { a, b, c }, js: MUL + "const f = mul([P.b, P.a, 1], [-P.c, 1]); return f.reduce((s, x) => s + x, 0);", t: [`계수의 합은 변수에 1 을 대입한 값이다.||The sum of coefficients is the value at 1.`, `첫 인수 = 1 + ${a} + ${b} = ${1 + a + b}.||First factor at 1 is ${1 + a + b}.`, `둘째 인수 = 1 − ${c} = ${1 - c}.||Second factor at 1 is ${1 - c}.`, "곱한다.||Multiply them.", `답은 ${ans}.`] }; } },
];
const A_CHAIN: Var[] = [
  { name: "vertex_form_constant", gen(rng) { const v = vr(rng); const a = nzr(rng, -4, 5), h = rng.int(1, 6) * rng.pick([1, -1]), k = nzr(rng, -9, 9); const ans = a * h * h + k; need(Math.abs(ans) < 99);
    return { s: sp(rng, `[[The function ${M(`f(${v}) = ${a === 1 ? "" : a === -1 ? "-" : a}${B(v, -h)}^2 ${k > 0 ? "+" : "-"} ${Math.abs(k)}`)} can also be written as ${M(`f(${v}) = A${v}^2 + B${v} + C`)}.|A function is given in vertex form, ${M(`f(${v}) = ${a === 1 ? "" : a === -1 ? "-" : a}${B(v, -h)}^2 ${k > 0 ? "+" : "-"} ${Math.abs(k)}`)}. In standard form it is ${M(`f(${v}) = A${v}^2 + B${v} + C`)}.|Rewrite ${M(`f(${v}) = ${a === 1 ? "" : a === -1 ? "-" : a}${B(v, -h)}^2 ${k > 0 ? "+" : "-"} ${Math.abs(k)}`)} as ${M(`f(${v}) = A${v}^2 + B${v} + C`)} by expanding the square.|The standard form ${M(`f(${v}) = A${v}^2 + B${v} + C`)} represents the same function as ${M(`f(${v}) = ${a === 1 ? "" : a === -1 ? "-" : a}${B(v, -h)}^2 ${k > 0 ? "+" : "-"} ${Math.abs(k)}`)}.]]`), q: sp(rng, `[[What is the value of C?|Find the constant term C of the standard form.|What does C equal?]]`), a: ans, w: [k, a * h + k, -a * h * h + k],
      p: { a, h, k }, js: MUL + "const sq = mul([-P.h, 1], [-P.h, 1]); return P.a * sq[0] + P.k;", t: [`(${v} − ${h})² = ${v}² − ${2 * h}${v} + ${h * h}.`, `상수항 ${h * h} 에 ${a} 를 곱한다.||Multiply the constant ${h * h} by ${a}.`, `${a * h * h}.`, `k = ${k} 를 더한다.||Add k = ${k}.`, `C = ${ans}.`] }; } },
  { name: "perfect_square_k", gen(rng) { const v = vr(rng); const m = rng.int(2, 9); const c = m * m; const k = 2 * m;
    return { s: sp(rng, `[[The expression ${M(`${v}^2 + k${v} + ${c}`)} is equivalent to the square of a binomial ${M(`(${v} + m)^2`)}, where k and m are positive constants.|For positive constants k and m, ${M(`${v}^2 + k${v} + ${c}`)} is the same as ${M(`(${v} + m)^2`)} for every value of ${M(v)}.|A trinomial ${M(`${v}^2 + k${v} + ${c}`)} is a perfect square, ${M(`(${v} + m)^2`)}, with k and m positive.|Expanding ${M(`(${v} + m)^2`)} gives ${M(`${v}^2 + k${v} + ${c}`)}. Here k and m are positive.]]`), q: sp(rng, `[[What is the value of k?|Find k.|What is k?]]`), a: k, w: [m, c, k + 2],
      p: { c }, js: "for (let k = 1; k <= 200; k++) { if (k * k - 4 * P.c === 0) return k; } throw new Error('none');", t: [`${v}² + k${v} + ${c} = (${v} + m)² = ${v}² + 2m${v} + m².`, `m² = ${c} 이므로 m = ${m} (양수).||m^2 = ${c}, so m = ${m}.`, "중간항 계수 k = 2m.||The middle coefficient is k = 2m.", `k = 2 × ${m}.`, `k = ${k}.`] }; } },
  { name: "factor_pair_square_sum", gen(rng) { const v = vr(rng); const p = nzr(rng, -9, 9), q = nzr(rng, -9, 9); need(p !== q); const b = p + q, c = p * q; const ans = p * p + q * q; need(b !== 0);
    return { s: sp(rng, `[[The expression ${M(pl3(1, b, c, v))} is equivalent to ${M(`(${v} + p)(${v} + q)`)}, where p and q are integers.|The trinomial ${M(pl3(1, b, c, v))} factors as ${M(`(${v} + p)(${v} + q)`)} for integers p and q.|Integers p and q satisfy ${M(pl3(1, b, c, v))} = ${M(`(${v} + p)(${v} + q)`)} for all ${M(v)}.|Factoring ${M(pl3(1, b, c, v))} over the integers gives ${M(`(${v} + p)(${v} + q)`)}.]]`), q: sp(rng, `[[What is the value of ${M("p^2 + q^2")}?|Find ${M("p^2 + q^2")}.|What is the sum of the squares of p and q?]]`), a: ans, w: [b * b, c * c, b * b + 2 * c],
      p: { b, c }, js: "for (let p = -60; p <= 60; p++) { for (let q = -60; q <= 60; q++) { if (p + q === P.b && p * q === P.c) return p * p + q * q; } } throw new Error('none');", t: [`p + q = ${b}, pq = ${c}.`, `합이 ${b}, 곱이 ${c} 인 두 정수를 찾는다.||Find integers with sum ${b} and product ${c}.`, `p, q = ${p}, ${q}.`, `p² + q² = (p + q)² − 2pq.`, `${b * b} − ${2 * c} = ${ans}.`] }; } },
  { name: "distribute_combine_constant", gen(rng) { const v = vr(rng); const a = rng.int(2, 6), b = nzr(rng, -6, 6), c = rng.int(2, 6), d = rng.int(1, 4), e = nzr(rng, -6, 6); const ans = a * b - c * -e; need(a * 1 !== c * d || true); need(a - c * d !== 0);
    return { s: sp(rng, `[[The expression ${M(`${a}(${pl2(1, b, v)}) - ${c}(${pl2(d, -e, v)})`)} is equivalent to ${M(`P${v} + Q`)}, where P and Q are constants.|After the parentheses in ${M(`${a}(${pl2(1, b, v)}) - ${c}(${pl2(d, -e, v)})`)} are distributed and like terms are combined, the result is ${M(`P${v} + Q`)}.|Simplify ${M(`${a}(${pl2(1, b, v)}) - ${c}(${pl2(d, -e, v)})`)} to the form ${M(`P${v} + Q`)} for constants P and Q.|For every ${M(v)}, ${M(`${a}(${pl2(1, b, v)}) - ${c}(${pl2(d, -e, v)})`)} equals ${M(`P${v} + Q`)}, where P and Q are constants.]]`), q: sp(rng, `[[What is the value of Q?|Find Q.|What is the constant term after the expression is simplified?]]`), a: ans, w: [a * b - c * e, a * b + c * e - 2, a - c * d],
      p: { a, b, c, d, e }, js: "const at0 = P.a * (0 + P.b) - P.c * (P.d * 0 - P.e); return at0;", t: [`첫 항: ${a}(${v} + ${b}) = ${a}${v} + ${a * b}.||First term: ${a}${v} + ${a * b}.`, `둘째 항: ${c}(${d}${v} − ${e}) = ${c * d}${v} − ${c * e}.||Second term: ${c * d}${v} - ${c * e}.`, "빼는 항 전체에 부호를 분배한다.||Distribute the minus sign.", `상수항 = ${a * b} − (−${c * e}).`, `Q = ${ans}.`] }; } },
];
const A_INVERSE: Var[] = [
  { name: "missing_product_constant", gen(rng) { const v = vr(rng); const a = nzr(rng, -7, 7), k = nzr(rng, -7, 7); need(a + k !== 0); const b = a + k, c = a * k;
    return { s: sp(rng, `[[The equation ${M(`(${v} ${a > 0 ? "+" : "-"} ${Math.abs(a)})(${v} + k) = ${v}^2 + ${b < 0 ? `(${b})` : b}${v} + c`)} is true for all values of ${M(v)}, where k and c are constants.|Both sides of ${M(`(${v} ${a > 0 ? "+" : "-"} ${Math.abs(a)})(${v} + k) = ${v}^2 + ${b < 0 ? `(${b})` : b}${v} + c`)} agree for every ${M(v)}; k and c are constants.|A product of two binomials is set equal to a trinomial: ${M(`(${v} ${a > 0 ? "+" : "-"} ${Math.abs(a)})(${v} + k) = ${v}^2 + ${b < 0 ? `(${b})` : b}${v} + c`)}. The equality holds for all ${M(v)}, and k and c are constants.|Constants k and c make the identity ${M(`(${v} ${a > 0 ? "+" : "-"} ${Math.abs(a)})(${v} + k) = ${v}^2 + ${b < 0 ? `(${b})` : b}${v} + c`)} true for every ${M(v)}.]]`), q: sp(rng, `[[What is the value of c?|Find c.|What is the constant term c?]]`), a: c, w: [b, k, a],
      p: { a, b }, js: "for (let k = -80; k <= 80; k++) { if (P.a + k === P.b) return P.a * k; } throw new Error('none');", t: [`우변의 ${v} 계수 = ${b} = ${a} + k.`, `k = ${b} − ${a} = ${k}.`, "상수항은 두 상수의 곱.||The constant term is the product of the constants.", `${a} × ${k}.`, `답은 ${c}.`] }; } },
  { name: "k_from_linear_coefficient", gen(rng) { const v = vr(rng); const k = nzr(rng, -5, 6), m = rng.int(1, 8), n = rng.int(1, 6); const q = -k * n + m; need(k !== 0 && Math.abs(q) < 50 && q !== 0);
    return { s: sp(rng, `[[The expression ${M(`(k${v} + ${m})(${v} - ${n})`)} is equivalent to ${M(`k${v}^2 + (${q})${v} - ${m * n}`)}, where k is a constant.|Expanding ${M(`(k${v} + ${m})(${v} - ${n})`)} gives ${M(`k${v}^2 + (${q})${v} - ${m * n}`)} for some constant k.|For every ${M(v)}, ${M(`(k${v} + ${m})(${v} - ${n})`)} = ${M(`k${v}^2 + (${q})${v} - ${m * n}`)}, with k a constant.|A student claims ${M(`(k${v} + ${m})(${v} - ${n})`)} equals ${M(`k${v}^2 + (${q})${v} - ${m * n}`)} when k is chosen correctly.]]`), q: sp(rng, `[[What is the value of k?|Find k.|What must k equal?]]`), a: k, w: [-k, k + 1, q],
      p: { m, n, q }, js: "for (let k = -60; k <= 60; k++) { if (-k * P.n + P.m === P.q) return k; } throw new Error('none');", t: [`${v} 계수: k·(−${n}) + ${m}.||The ${v}-coefficient is k(-${n}) + ${m}.`, `−${n}k + ${m} = ${q}.`, `−${n}k = ${q - m}.`, `k = ${q - m} ÷ (−${n}).`, `k = ${k}.`] }; } },
  { name: "other_factor_constant", gen(rng) { const v = vr(rng); const u = rng.int(1, 4), w = rng.int(1, 4), vv = nzr(rng, -5, 6), k = nzr(rng, -6, 6); const p = u * w, q = u * k + vv * w, r = vv * k; need(r !== 0 && q !== 0);
    return { s: sp(rng, `[[The equation ${M(`${pl3(p, q, r, v)} = (${pl2(u, vv, v)})(${w === 1 ? "" : w}${v} + k)`)} is true for all values of ${M(v)}. The second factor has constant term k.|For every ${M(v)}, ${M(`${pl3(p, q, r, v)} = (${pl2(u, vv, v)})(${w === 1 ? "" : w}${v} + k)`)} holds, where k is the constant term of the second factor.|A quadratic is factored as ${M(`${pl3(p, q, r, v)} = (${pl2(u, vv, v)})(${w === 1 ? "" : w}${v} + k)`)}, with an unknown constant k in the second factor.|The identity ${M(`${pl3(p, q, r, v)} = (${pl2(u, vv, v)})(${w === 1 ? "" : w}${v} + k)`)} holds for all ${M(v)}; k is a constant.]]`), q: sp(rng, `[[What is the value of k in the second factor?|Find the constant k.|What number is k?]]`), a: k, w: [vv, r, q - vv],
      p: { u, v: vv, w, r }, js: "for (let k = -80; k <= 80; k++) { if (P.v * k === P.r) return k; } throw new Error('none');", t: [`상수항끼리 곱한다: ${vv} × k = ${r}.||The constants multiply: ${vv} x k = ${r}.`, `k = ${r} ÷ ${vv}.`, `k = ${k}.`, "검산: x 계수 = " + `${u}k + ${vv}·${w} = ${q}.||Check the ${v}-coefficient: ${q}.`, `답은 ${k}.`] }; } },
  { name: "perfect_square_constant", gen(rng) { const v = vr(rng); const a = rng.int(2, 6), b = nzr(rng, -8, 8); const p = a * a, q = 2 * a * b, c = b * b; need(Math.abs(q) < 99);
    return { s: sp(rng, `[[The expression ${M(`${p}${v}^2 ${q > 0 ? "+" : "-"} ${Math.abs(q)}${v} + c`)} is the square of a binomial with integer coefficients, where c is a constant.|For which constant c is ${M(`${p}${v}^2 ${q > 0 ? "+" : "-"} ${Math.abs(q)}${v} + c`)} a perfect square of a binomial with integer coefficients?|A quadratic ${M(`${p}${v}^2 ${q > 0 ? "+" : "-"} ${Math.abs(q)}${v} + c`)} factors as the square of an integer binomial; c is unknown.|The trinomial ${M(`${p}${v}^2 ${q > 0 ? "+" : "-"} ${Math.abs(q)}${v} + c`)} equals (a binomial)^2 with integer coefficients; c is a constant.]]`), q: sp(rng, `[[What is the value of c?|Find c.|What is c?]]`), a: c, w: [Math.abs(q), b, p],
      p: { p, q }, js: "for (let a = 1; a <= 30; a++) { for (let b = -60; b <= 60; b++) { if (a * a === P.p && 2 * a * b === P.q) return b * b; } } throw new Error('none');", t: [`${p} = a² 이므로 a = ${a}.||p = a^2 gives a = ${a}.`, `중간항 2ab = ${q}.`, `b = ${q} ÷ (2 × ${a}) = ${b}.`, "c = b².||c = b^2.", `c = ${c}.`] }; } },
];
const A_COMPARE: Var[] = [
  { name: "square_vs_split_gap", gen(rng) { const v = vr(rng); const a = rng.int(2, 9), t = rng.int(2, 9); const ans = 2 * a * t;
    return { s: sp(rng, `[[A student claims that ${M(`(${v} + ${a})^2`)} is equal to ${M(`${v}^2 + ${a * a}`)}. The claim is not correct for most values of ${M(v)}. Let ${M(v)} = ${t}.|Someone writes ${M(`(${v} + ${a})^2 = ${v}^2 + ${a * a}`)}, which is not an identity. Evaluate both sides at ${M(`${v} = ${t}`)}.|At ${M(`${v} = ${t}`)}, compare the true value of ${M(`(${v} + ${a})^2`)} with the incorrect shortcut ${M(`${v}^2 + ${a * a}`)}.|The "shortcut" ${M(`${v}^2 + ${a * a}`)} is used in place of ${M(`(${v} + ${a})^2`)}. Take ${M(`${v} = ${t}`)}.]]`), q: sp(rng, `[[How much larger is the true value of ${M(`(${v} + ${a})^2`)} than the student's value?|By how much does ${M(`(${v} + ${a})^2`)} exceed ${M(`${v}^2 + ${a * a}`)} at this value?|How far off is the shortcut from the true value?]]`), a: ans, w: [a * a, 2 * a, a * t],
      p: { a, t }, js: "const truth = (P.t + P.a) * (P.t + P.a); const claim = P.t * P.t + P.a * P.a; return truth - claim;", t: [`참값 (${t} + ${a})² = ${(t + a) ** 2}.||True value ${(t + a) ** 2}.`, `학생의 값 ${t}² + ${a * a} = ${t * t + a * a}.||Student's value ${t * t + a * a}.`, "차이는 중간항 2ax 때문이다.||The gap is the missing middle term 2ax.", `2 × ${a} × ${t}.`, `답은 ${ans}.`] }; } },
  { name: "square_minus_rectangle_area", gen(rng) { const v = vr(rng); const a = rng.int(1, 6), b = rng.int(1, 5), t = rng.int(7, 20); need(a - b > 0 || true); const ans = b * b; const obj = rng.pick([["garden", "meters"], ["patio", "feet"], ["poster", "inches"], ["field", "yards"]]); const obj0 = obj[0], obj1 = obj[1];
    return { s: sp(rng, `[[A square ${obj0} has side length ${M(`${v} + ${a}`)} ${obj1}. A rectangular ${obj0} has length ${M(shifted(v, a + b))} ${obj1} and width ${M(shifted(v, a - b))} ${obj1}. Both are built with ${M(v)} = ${t}.|Both a square ${obj0} and a rectangular ${obj0} are built with ${M(v)} = ${t}. The square has side ${M(`${v} + ${a}`)} ${obj1}; the rectangle is ${M(shifted(v, a + b))} by ${M(shifted(v, a - b))} ${obj1}.|Compare a square of side ${M(`${v} + ${a}`)} ${obj1} with a rectangle measuring ${M(shifted(v, a + b))} by ${M(shifted(v, a - b))} ${obj1}, where ${M(v)} = ${t}. They are two designs for the same ${obj0}.|For ${M(v)} = ${t}, a ${obj0} can be planned as a square with side ${M(`${v} + ${a}`)} ${obj1} or as a rectangle with sides ${M(shifted(v, a + b))} and ${M(shifted(v, a - b))} ${obj1}.]]`), q: sp(rng, `[[By how many square ${obj1} is the area of the square larger than the area of the rectangle?|How many more square ${obj1} does the square cover than the rectangle?|What is the area of the square minus the area of the rectangle, in square ${obj1}?]]`), a: ans, w: [2 * b, a * b, b * b + a],
      p: { a, hi: a + b, lo: a - b, t }, js: "const sq = (P.t + P.a) * (P.t + P.a); const rect = (P.t + P.hi) * (P.t + P.lo); return sq - rect;", t: [`정사각형 넓이 (${t} + ${a})² = ${(t + a) ** 2}.||Square area ${(t + a) ** 2}.`, `직사각형 넓이 ${t + a + b} × ${t + a - b} = ${(t + a + b) * (t + a - b)}.||Rectangle area ${(t + a + b) * (t + a - b)}.`, "차이는 x 와 무관하게 b² 로 일정하다.||The difference is the constant b^2, independent of x.", `${b}² = ${b * b}.`, `답은 ${ans}.`] }; } },
  { name: "count_equivalent_forms", gen(rng) { const v = vr(rng); const a = rng.int(1, 6), b = rng.int(1, 6); need(a !== b); const ab = a * b;
    const good: [string, number[]][] = [[poly([1, a - b, -ab], v), [1, a - b, -ab]], [`${v}^2 + ${a}${v} - ${b}${v} - ${ab}`, [1, a - b, -ab]], [`(${shifted(v, -b)})(${shifted(v, a)})`, [1, a - b, -ab]]];
    const bad: [string, number[]][] = [[poly([1, a + b, -ab], v), [1, a + b, -ab]], [poly([1, 0, -ab], v), [1, 0, -ab]], [poly([1, b - a, -ab], v), [1, b - a, -ab]], [poly([1, ab, -(a + b)], v), [1, ab, -(a + b)]]];
    const ans = rng.int(1, 3); const picked = [...rng.shuffle(good).slice(0, ans), ...rng.shuffle(bad).slice(0, 5 - ans)]; const order = rng.shuffle(picked); const cands = order.map((x) => x[0]); const coefs = order.map((x) => x[1]).flat();
    return { s: sp(rng, `[[Five expressions are listed: ${cands.map((c) => M(c)).join(", ")}. The product ${M(`(${v} + ${a})(${v} - ${b})`)} is compared with each.|Compare ${M(`(${v} + ${a})(${v} - ${b})`)} with these five expressions: ${cands.map((c) => M(c)).join(", ")}.|A worksheet lists five possible expansions of ${M(`(${v} + ${a})(${v} - ${b})`)}: ${cands.map((c) => M(c)).join(", ")}.|Here are five candidates: ${cands.map((c) => M(c)).join(", ")}. Each is checked against the product ${M(`(${v} + ${a})(${v} - ${b})`)}.]]`), q: sp(rng, `[[How many of the five listed expressions are equivalent to the product?|For how many of the five expressions is the product equal for all values of ${M(v)}?|How many of the candidates are correct expansions?]]`), a: ans, w: [5 - ans, ans + 1, ans - 1 || 4],
      p: { a, b, coefs }, js: "let c = 0; for (let i = 0; i < P.coefs.length; i += 3) { let ok = true; for (let x = -4; x <= 4; x++) { if (P.coefs[i] * x * x + P.coefs[i + 1] * x + P.coefs[i + 2] !== (x + P.a) * (x - P.b)) ok = false; } if (ok) c++; } return c;", t: [`(${v} + ${a})(${v} − ${b}) = ${v}² + ${a - b}${v} − ${ab}.`, "각 보기를 같은 식으로 정리해 계수를 비교한다.||Rewrite each listed form in standard form and compare coefficients.", "서로 다른 값 몇 개를 대입해도 확인할 수 있다.||Substituting several values also checks equivalence.", "동치인 보기를 센다.||Count the equivalent ones.", `답은 ${ans}.`] }; } },
  { name: "solve_for_equal_value", gen(rng) { const v = vr(rng); const a = rng.int(2, 7), x0 = rng.int(1, 9); const c = a * a + 2 * a * x0; need(c < 200);
    return { s: sp(rng, `[[For which value of ${M(v)} does ${M(`(${v} + ${a})^2`)} equal ${M(`${v}^2 + ${c}`)}? The two expressions are not equivalent, but they take the same value for exactly one positive value of ${M(v)}.|The expressions ${M(`(${v} + ${a})^2`)} and ${M(`${v}^2 + ${c}`)} are not equivalent, yet they agree at exactly one positive value of ${M(v)}.|Setting ${M(`(${v} + ${a})^2`)} equal to ${M(`${v}^2 + ${c}`)} gives exactly one positive solution for ${M(v)}.|Two expressions, ${M(`(${v} + ${a})^2`)} and ${M(`${v}^2 + ${c}`)}, are equal for only one positive input.]]`), q: sp(rng, `[[What is that value of ${M(v)}?|Find the positive value of ${M(v)} at which the two expressions agree.|At which positive ${M(v)} are they equal?]]`), a: x0, w: [c - a, a, c / (2 * a)],
      p: { a, c }, js: "for (let x = 1; x <= 400; x++) { if ((x + P.a) * (x + P.a) === x * x + P.c) return x; } throw new Error('none');", t: [`(${v} + ${a})² = ${v}² + ${2 * a}${v} + ${a * a}.`, `${v}² + ${2 * a}${v} + ${a * a} = ${v}² + ${c}.`, `${v}² 항이 소거된다.||The squared terms cancel.`, `${2 * a}${v} = ${c - a * a}.`, `${v} = ${x0}.`] }; } },
];
// ───────── kind B: exponent_radical_forms — 지수·근호·분수식의 동치 변형으로 수를 구한다 ─────────
const B_COMPOSE: Var[] = [
  { name: "power_of_power_times", gen(rng) { const v = vr(rng); const a = rng.int(2, 6), b = rng.int(2, 5), c = rng.int(1, 9); const k = a * b + c;
    return { s: sp(rng, `[[For ${M(`${v} > 0`)}, the expression ${M(`(${v}^${a})^${b} \\cdot ${v}^${c}`)} is equivalent to ${M(`${v}^k`)}, where k is a constant.|Simplify ${M(`(${v}^${a})^${b} \\cdot ${v}^${c}`)} for positive ${M(v)}; the result can be written as ${M(`${v}^k`)}.|A student combines powers of ${M(v)}: ${M(`(${v}^${a})^${b} \\cdot ${v}^${c}`)} = ${M(`${v}^k`)} for ${M(v)} > 0.|For every positive ${M(v)}, ${M(`(${v}^${a})^${b} \\cdot ${v}^${c}`)} equals ${M(`${v}^k`)} for one constant k.]]`), q: sp(rng, `[[What is the value of k?|Find k.|What exponent k results?]]`), a: k, w: [a + b + c, a * (b + c), a * b * c],
      p: { a, b, c }, js: "for (const base of [2, 3, 5]) { const val = Math.pow(Math.pow(base, P.a), P.b) * Math.pow(base, P.c); let e = 0; let cur = 1; while (cur < val) { cur *= base; e++; } if (cur === val) { if (base === 2) return e; } } throw new Error('none');", t: [`(${v}^${a})^${b} = ${v}^(${a}·${b}) = ${v}^${a * b}.`, "거듭제곱의 거듭제곱은 지수를 곱한다.||A power of a power multiplies exponents.", `같은 밑의 곱은 지수를 더한다: ${a * b} + ${c}.||Same-base products add exponents.`, `k = ${a * b} + ${c}.`, `k = ${k}.`] }; } },
  { name: "two_variable_quotient", gen(rng) { const a = rng.int(5, 11), b = rng.int(5, 11), c = rng.int(1, a - 1), d = rng.int(1, b - 1); const p = a - c, q = b - d; need(p !== q);
    return { s: sp(rng, `[[For positive x and y, the expression ${M(`\\frac{x^{${a}} y^{${b}}}{x^{${c}} y^{${d}}}`)} is equivalent to ${M("x^p y^q")}, where p and q are constants.|Simplify ${M(`\\frac{x^{${a}} y^{${b}}}{x^{${c}} y^{${d}}}`)} for positive x and y to the form ${M("x^p y^q")}.|A quotient of monomials, ${M(`\\frac{x^{${a}} y^{${b}}}{x^{${c}} y^{${d}}}`)}, equals ${M("x^p y^q")} for all positive x and y.|Written as a single monomial, ${M(`\\frac{x^{${a}} y^{${b}}}{x^{${c}} y^{${d}}}`)} becomes ${M("x^p y^q")} (x, y > 0).]]`), q: sp(rng, `[[What is the value of ${M("p \\cdot q")}?|Find the product of p and q.|Compute p times q.]]`), a: p * q, w: [p + q, a * b - c * d, (a + b) - (c + d) + p],
      p: { a, b, c, d }, js: "let p = 0, q = 0; for (let i = 0; i < 40; i++) { if (i + P.c === P.a) p = i; if (i + P.d === P.b) q = i; } return p * q;", t: [`x 의 지수: ${a} − ${c} = ${p}.||Exponent of x: ${a} - ${c} = ${p}.`, `y 의 지수: ${b} − ${d} = ${q}.||Exponent of y: ${b} - ${d} = ${q}.`, "나눗셈은 같은 밑의 지수를 뺀다.||Division subtracts exponents of the same base.", `p·q = ${p} × ${q}.`, `답은 ${p * q}.`] }; } },
  { name: "cube_root_exponent", gen(rng) { const v = vr(rng); const m = rng.int(2, 7), b = rng.int(1, 6); const a = 3 * m; const k = m + b;
    return { s: sp(rng, `[[For ${M(`${v} > 0`)}, the expression ${M(`(${v}^{${a}})^{1/3} \\cdot ${v}^{${b}}`)} is equivalent to ${M(`${v}^k`)}, where k is a constant.|Rewrite the fractional power in ${M(`(${v}^{${a}})^{1/3} \\cdot ${v}^{${b}}`)} as a single power of ${M(v)}; for positive ${M(v)} the result is ${M(`${v}^k`)}.|The expression ${M(`(${v}^{${a}})^{1/3} \\cdot ${v}^{${b}}`)} simplifies to ${M(`${v}^k`)} when ${M(v)} is positive.|A cube root written as a power of 1/3 is multiplied by another power: ${M(`(${v}^{${a}})^{1/3} \\cdot ${v}^{${b}}`)} = ${M(`${v}^k`)} for positive ${M(v)}.]]`), q: sp(rng, `[[What is the value of k?|Find k.|What is the exponent k?]]`), a: k, w: [a + b, a / 3 * b, a - b],
      p: { a, b }, js: "for (let k = 0; k <= 60; k++) { if (Math.abs(Math.pow(Math.pow(2, P.a), 1 / 3) * Math.pow(2, P.b) - Math.pow(2, k)) < 1e-6) return k; } throw new Error('none');", t: [`세제곱근은 지수 1/3 이다.||A cube root is the exponent 1/3.`, `${v}^(${a}/3) = ${v}^${m}.`, `같은 밑의 곱: ${m} + ${b}.||Add exponents.`, `k = ${m} + ${b}.`, `k = ${k}.`] }; } },
  { name: "numeric_power_combination", gen(rng) { const c = rng.pick([2, 3, 5]); const a = rng.int(5, 10), b = rng.int(1, 4); const e = a - b; const val = Math.pow(c, e); need(val <= 9999 && val > 1);
    return { s: sp(rng, `[[The expression ${M(`${c}^{${a}} \\cdot ${c}^{-${b}}`)} is evaluated as a single number.|Evaluate ${M(`${c}^{${a}} \\cdot ${c}^{-${b}}`)}.|A calculator-free problem: combine the powers in ${M(`${c}^{${a}} \\cdot ${c}^{-${b}}`)} into one number.|The product of two powers of the same base, ${M(`${c}^{${a}} \\cdot ${c}^{-${b}}`)}, is a whole number.]]`), q: sp(rng, `[[What is its value?|What number is the expression equal to?|Find the value of the expression.]]`), a: val, w: [Math.pow(c, a + b), Math.pow(c, a) - Math.pow(c, b), Math.pow(c, a * b)],
      p: { c, a, b }, js: "return Math.pow(P.c, P.a) / Math.pow(P.c, P.b);", t: [`밑이 같으므로 지수를 더한다: ${a} + (−${b}) = ${e}.||Same base: add exponents.`, `${c}^${e}.`, "음수 지수는 분모로 간다.||A negative exponent places the factor in the denominator.", `${c}^${a} ÷ ${c}^${b}.`, `답은 ${val}.`] }; } },
];
const B_CHAIN: Var[] = [
  { name: "cancel_then_evaluate", gen(rng) { const v = vr(rng); const a = rng.int(2, 9), t = rng.int(a + 1, 15); const ans = t + a;
    return { s: sp(rng, `[[For ${M(`${v} \\ne ${a}`)}, the expression ${M(`\\frac{${v}^2 - ${a * a}}{${v} - ${a}}`)} is equivalent to a simpler expression. Let ${M(v)} = ${t}.|Simplify ${M(`\\frac{${v}^2 - ${a * a}}{${v} - ${a}}`)} by canceling a common factor, and then evaluate at ${M(`${v} = ${t}`)}. Assume ${M(`${v} \\ne ${a}`)}.|A rational expression ${M(`\\frac{${v}^2 - ${a * a}}{${v} - ${a}}`)} is evaluated at ${M(`${v} = ${t}`)}. The input ${M(`${v} = ${a}`)} is excluded.|Take ${M(`${v} = ${t}`)} in ${M(`\\frac{${v}^2 - ${a * a}}{${v} - ${a}}`)}, which is defined whenever ${M(`${v} \\ne ${a}`)}.]]`), q: sp(rng, `[[What is the value of the expression when ${M(v)} = ${t}?|Find the value of the expression at ${M(`${v} = ${t}`)}.|Evaluate the simplified expression at ${M(`${v} = ${t}`)}.]]`), a: ans, w: [t - a, t * t - a * a, ans + a],
      p: { a, t }, js: "return (P.t * P.t - P.a * P.a) / (P.t - P.a);", t: [`분자 ${v}² − ${a * a} = (${v} − ${a})(${v} + ${a}).||The numerator factors as a difference of squares.`, `(${v} − ${a}) 를 약분한다.||Cancel (${v} - ${a}).`, `식은 ${v} + ${a} 와 같다.||The expression equals ${v} + ${a}.`, `${t} + ${a}.`, `답은 ${ans}.`] }; } },
  { name: "partial_fraction_difference", gen(rng) { const A = nzr(rng, -6, 7), Bc = nzr(rng, -6, 7); need(A !== Bc); const p = A + Bc, q = Bc - A; need(p !== 0 && q !== 0);
    return { s: sp(rng, `[[For ${M("x \\ne \\pm 1")}, the sum ${M(`\\frac{${A}}{x + 1} + \\frac{${Bc}}{x - 1}`)} is equivalent to ${M("\\frac{px + q}{x^2 - 1}")}, where p and q are constants.|Combine ${M(`\\frac{${A}}{x + 1} + \\frac{${Bc}}{x - 1}`)} over a common denominator to get ${M("\\frac{px + q}{x^2 - 1}")} (x not equal to 1 or -1).|Adding two fractions gives ${M(`\\frac{${A}}{x + 1} + \\frac{${Bc}}{x - 1}`)} = ${M("\\frac{px + q}{x^2 - 1}")} for x not equal to 1 or -1, with constants p and q.|The fractions in ${M(`\\frac{${A}}{x + 1} + \\frac{${Bc}}{x - 1}`)} are added; the result is written as ${M("\\frac{px + q}{x^2 - 1}")}.]]`), q: sp(rng, `[[What is the value of ${M("p - q")}?|Find p − q.|Compute the difference p minus q.]]`), a: p - q, w: [p + q, p * q, A - Bc],
      p: { A, B: Bc }, js: "const num = x => P.A * (x - 1) + P.B * (x + 1); const p = num(1) - num(0); const q = num(0); return p - q;", t: [`공통분모 x² − 1.||The common denominator is x^2 - 1.`, `분자 = ${A}(x − 1) + ${Bc}(x + 1).||Numerator = ${A}(x-1) + ${Bc}(x+1).`, `x 계수 p = ${A} + ${Bc} = ${p}.`, `상수항 q = −${A} + ${Bc} = ${q}.`, `p − q = ${p - q}.`] }; } },
  { name: "radical_simplify_sum", gen(rng) { const m = rng.int(2, 9), r = rng.pick([2, 3, 5, 6, 7, 10, 11]); const N = m * m * r; need(N < 999); const ans = m + r;
    return { s: sp(rng, `[[The number ${M(`\\sqrt{${N}}`)} can be written in the form ${M("m\\sqrt{r}")}, where m and r are positive integers and r has no perfect-square factor greater than 1.|Simplify ${M(`\\sqrt{${N}}`)} to the form ${M("m\\sqrt{r}")} with positive integers m and r, where r is not divisible by any perfect square greater than 1.|Write the radical ${M(`\\sqrt{${N}}`)} as ${M("m\\sqrt{r}")} in simplest form, with m and r positive integers.|In simplest radical form, ${M(`\\sqrt{${N}}`)} equals ${M("m\\sqrt{r}")} for positive integers m and r.]]`), q: sp(rng, `[[What is the value of ${M("m + r")}?|Find m + r.|Compute the sum of m and r.]]`), a: ans, w: [m * r, N, m + r + 1],
      p: { N }, js: "let best = 1; for (let m = 1; m * m <= P.N; m++) { if (P.N % (m * m) === 0) best = m; } const r = P.N / (best * best); return best + r;", t: [`${N} = ${m * m} × ${r}.`, `√${m * m} = ${m}.`, `${r} 에는 1 보다 큰 제곱인수가 없다.||${r} has no square factor greater than 1.`, `√${N} = ${m}√${r}.`, `m + r = ${ans}.`] }; } },
  { name: "reciprocal_sum_value", gen(rng) { const [a, b] = rng.pick([[6, 3], [12, 4], [12, 6], [20, 5], [30, 6], [15, 10], [60, 20], [40, 10], [24, 8], [30, 15]]); const val = (a * b) / (a + b); need(isInt(val));
    const [u, w] = rng.pick([["resistors", "ohms"], ["pipes", "hours"], ["workers", "hours"]]);
    return { s: sp(rng, `[[Two ${u} have values ${a} and ${b}. The combined value is given by the expression ${M("\\frac{1}{\\frac{1}{a} + \\frac{1}{b}}")}, where a = ${a} and b = ${b}.|Evaluate ${M("\\frac{1}{\\frac{1}{a} + \\frac{1}{b}}")} for a = ${a} and b = ${b}; this expression gives the combined value of two ${u}.|The combined value of two ${u}, ${a} and ${b}, is ${M("\\frac{1}{\\frac{1}{a} + \\frac{1}{b}}")}, where a and b are those values.|A formula for two ${u} is ${M("\\frac{1}{\\frac{1}{a} + \\frac{1}{b}}")}. Use a = ${a} and b = ${b}.]]`), q: sp(rng, `[[What is the combined value?|What does the expression equal for these values?|Find the value of the expression.]]`), a: val, w: [a + b, (a + b) / 2, a * b],
      p: { a, b }, js: "return 1 / (1 / P.a + 1 / P.b);", t: [`1/${a} + 1/${b} = ${b + a}/${a * b}.`, "분수의 합을 먼저 구한다.||Add the fractions first.", "역수를 취한다.||Take the reciprocal.", `${a * b}/${a + b}.`, `답은 ${val}.`] }; } },
];
const B_INVERSE: Var[] = [
  { name: "exponent_unknown", gen(rng) { const v = vr(rng); const k = rng.int(2, 7), a = rng.int(1, 8); const m = 3 * k - a; need(m >= 1);
    return { s: sp(rng, `[[For ${M(`${v} > 0`)}, the expression ${M(`\\frac{(${v}^k)^3}{${v}^{${a}}}`)} is equivalent to ${M(`${v}^{${m}}`)}, where k is a positive integer.|The quotient ${M(`\\frac{(${v}^k)^3}{${v}^{${a}}}`)} simplifies to ${M(`${v}^{${m}}`)} for positive ${M(v)}; k is a positive integer.|Positive integer k makes ${M(`\\frac{(${v}^k)^3}{${v}^{${a}}}`)} = ${M(`${v}^{${m}}`)} true for every positive ${M(v)}.|A power is raised to the third power and divided: ${M(`\\frac{(${v}^k)^3}{${v}^{${a}}}`)} = ${M(`${v}^{${m}}`)}, with k a positive integer and ${M(v)} > 0.]]`), q: sp(rng, `[[What is the value of k?|Find k.|What integer is k?]]`), a: k, w: [m + a, (m - a) / 3 + 1, m],
      p: { a, m }, js: "for (let k = 1; k <= 60; k++) { if (3 * k - P.a === P.m) return k; } throw new Error('none');", t: [`(${v}^k)³ = ${v}^(3k).`, `나눗셈은 지수를 뺀다: 3k − ${a}.||Division subtracts: 3k - ${a}.`, `3k − ${a} = ${m}.`, `3k = ${m + a}.`, `k = ${k}.`] }; } },
  { name: "base_matching", gen(rng) { const v = vr(rng); const b = rng.int(3, 9), a = rng.int(1, 6); const x = 2 * b - a; need(x >= 1);
    return { s: sp(rng, `[[The equation ${M(`2^{${v} + ${a}} = 4^{${b}}`)} is true for exactly one value of ${M(v)}.|Solve ${M(`2^{${v} + ${a}} = 4^{${b}}`)} for ${M(v)}; there is exactly one solution.|Rewriting 4 as a power of 2 lets you solve ${M(`2^{${v} + ${a}} = 4^{${b}}`)} for ${M(v)}.|The exponential equation ${M(`2^{${v} + ${a}} = 4^{${b}}`)} has a single solution in ${M(v)}.]]`), q: sp(rng, `[[What is the value of ${M(v)}?|Find ${M(v)}.|What value of ${M(v)} satisfies the equation?]]`), a: x, w: [b - a, b, 2 * b + a],
      p: { a, b }, js: "for (let x = -50; x <= 100; x++) { if (Math.pow(2, x + P.a) === Math.pow(4, P.b)) return x; } throw new Error('none');", t: [`4 = 2² 이므로 4^${b} = 2^${2 * b}.||4 = 2^2, so 4^${b} = 2^${2 * b}.`, "밑이 같으니 지수를 같게 놓는다.||Equal bases force equal exponents.", `${v} + ${a} = ${2 * b}.`, `${v} = ${2 * b} − ${a}.`, `${v} = ${x}.`] }; } },
  { name: "scale_factor_root", gen(rng) { const v = vr(rng); const k = rng.int(2, 7), n = rng.pick([2, 3, 4]); const N = Math.pow(k, n); need(N < 1000);
    return { s: sp(rng, `[[The equation ${M(`(k${v})^{${n}} = ${N}${v}^{${n}}`)} is true for all values of ${M(v)}, where k is a positive constant.|For a positive constant k, ${M(`(k${v})^{${n}} = ${N}${v}^{${n}}`)} holds for every value of ${M(v)}.|A scaling factor k makes ${M(`(k${v})^{${n}} = ${N}${v}^{${n}}`)} an identity in ${M(v)}; k is positive.|Raising k${M(v)} to a power gives ${M(`(k${v})^{${n}} = ${N}${v}^{${n}}`)} for all ${M(v)}, with k positive.]]`), q: sp(rng, `[[What is the value of k?|Find k.|What positive number is k?]]`), a: k, w: [N / n, N, k + 1],
      p: { n, N }, js: "for (let k = 1; k <= 60; k++) { if (Math.pow(k, P.n) === P.N) return k; } throw new Error('none');", t: [`(k${v})^${n} = k^${n} ${v}^${n}.`, `k^${n} = ${N}.`, `${n} 제곱해서 ${N} 인 양수를 찾는다.||Find the positive number whose power ${n} is ${N}.`, `${k}^${n} = ${N}.`, `k = ${k}.`] }; } },
  { name: "improper_fraction_remainder", gen(rng) { const v = vr(rng); const a = rng.int(2, 6), c = rng.int(1, 7), k = nzr(rng, -9, 9); const b = k + a * c; need(b !== 0);
    return { s: sp(rng, `[[The expression ${M(`\\frac{${a}${v} ${b > 0 ? "+" : "-"} ${Math.abs(b)}}{${v} + ${c}}`)} is equivalent to ${M(`${a} + \\frac{k}{${v} + ${c}}`)}, where k is a constant and ${M(`${v} \\ne -${c}`)}.|Dividing the numerator of ${M(`\\frac{${a}${v} ${b > 0 ? "+" : "-"} ${Math.abs(b)}}{${v} + ${c}}`)} by the denominator gives ${M(`${a} + \\frac{k}{${v} + ${c}}`)} for some constant k (${M(`${v} \\ne -${c}`)}).|For ${M(`${v} \\ne -${c}`)}, ${M(`\\frac{${a}${v} ${b > 0 ? "+" : "-"} ${Math.abs(b)}}{${v} + ${c}}`)} = ${M(`${a} + \\frac{k}{${v} + ${c}}`)} with a constant k.|A rational expression ${M(`\\frac{${a}${v} ${b > 0 ? "+" : "-"} ${Math.abs(b)}}{${v} + ${c}}`)} is rewritten as ${M(`${a} + \\frac{k}{${v} + ${c}}`)}, where k is a constant.]]`), q: sp(rng, `[[What is the value of k?|Find k.|What number is k?]]`), a: k, w: [b, -k, a * c],
      p: { a, b, c }, js: "const x = 10; const lhs = (P.a * x + P.b) / (x + P.c); return Math.round((lhs - P.a) * (x + P.c));", t: [`${a}${v} + ${b} = ${a}(${v} + ${c}) + (${b} − ${a * c}).`, "분자를 분모의 배수와 나머지로 나눈다.||Split the numerator into a multiple of the denominator and a remainder.", `나머지 = ${b} − ${a}·${c}.`, `${b} − ${a * c} = ${k}.`, `k = ${k}.`] }; } },
];
const B_COMPARE: Var[] = [
  { name: "difference_of_squares_value", gen(rng) { const v = vr(rng); const a = rng.int(2, 7), t = rng.int(2, 9); const ans = 4 * a * t;
    return { s: sp(rng, `[[Let ${M(`E = (${v} + ${a})^2 - (${v} - ${a})^2`)}. The two squares are subtracted, and ${M(v)} is then set to ${t}.|Define ${M(`E = (${v} + ${a})^2 - (${v} - ${a})^2`)} and evaluate it at ${M(`${v} = ${t}`)}.|The difference of two squares, ${M(`E = (${v} + ${a})^2 - (${v} - ${a})^2`)}, is computed with ${M(`${v} = ${t}`)}.|Take ${M(`${v} = ${t}`)} in ${M(`E = (${v} + ${a})^2 - (${v} - ${a})^2`)}.]]`), q: sp(rng, `[[What is the value of E?|Find E when ${M(v)} = ${t}.|Compute E at this value.]]`), a: ans, w: [2 * a * a, 4 * a, 2 * a * t],
      p: { a, t }, js: "return (P.t + P.a) ** 2 - (P.t - P.a) ** 2;", t: [`(${t} + ${a})² = ${(t + a) ** 2}.`, `(${t} − ${a})² = ${(t - a) ** 2}.`, "먼저 전개하면 E = 4ax 로 간단해진다.||Expanding first gives E = 4ax.", `4 × ${a} × ${t}.`, `E = ${ans}.`] }; } },
  { name: "ratio_of_powers", gen(rng) { const a = rng.int(5, 9), b = rng.int(2, 4), c = rng.int(1, 3); const e = a + 2 * b - 3 * c; need(e >= 1 && e <= 11); const val = 2 ** e;
    return { s: sp(rng, `[[The expression ${M(`\\frac{2^{${a}} \\cdot 4^{${b}}}{8^{${c}}}`)} is evaluated as a single number.|Evaluate ${M(`\\frac{2^{${a}} \\cdot 4^{${b}}}{8^{${c}}}`)}.|Rewrite the bases in ${M(`\\frac{2^{${a}} \\cdot 4^{${b}}}{8^{${c}}}`)} as powers of 2 and compute its value.|A fraction of powers, ${M(`\\frac{2^{${a}} \\cdot 4^{${b}}}{8^{${c}}}`)}, equals a single number.]]`), q: sp(rng, `[[What is its value?|What number does the expression equal?|Find the value of the expression.]]`), a: val, w: [e, 2 ** (a + b - c), 2 ** (a * b - c)],
      p: { a, b, c }, js: "return (Math.pow(2, P.a) * Math.pow(4, P.b)) / Math.pow(8, P.c);", t: [`4 = 2², 8 = 2³ 으로 밑을 통일한다.||Rewrite 4 = 2^2 and 8 = 2^3.`, `분자: 2^${a} · 2^${2 * b} = 2^${a + 2 * b}.`, `분모: 2^${3 * c}.`, `지수 ${a + 2 * b} − ${3 * c} = ${e}.`, `2^${e} = ${val}.`] }; } },
  { name: "complete_square_minimum", gen(rng) { const v = vr(rng); const h = rng.int(1, 8), c = rng.int(h * h + 1, h * h + 20); const b = 2 * h; const ans = c - h * h; const [ob, ou] = rng.pick([["cost", "dollars"], ["height", "feet"], ["distance", "meters"]]);
    return { s: sp(rng, `[[The ${ob} of an item, in ${ou}, is modeled by ${M(`${v}^2 - ${b}${v} + ${c}`)}, where ${M(v)} is a real number.|A model gives the ${ob} (in ${ou}) as ${M(`${v}^2 - ${b}${v} + ${c}`)} for any real ${M(v)}.|For real ${M(v)}, the ${ob} in ${ou} equals ${M(`${v}^2 - ${b}${v} + ${c}`)}.|The expression ${M(`${v}^2 - ${b}${v} + ${c}`)} describes an item's ${ob} in ${ou}, with ${M(v)} real.]]`), q: sp(rng, `[[What is the minimum value of the ${ob}?|What is the least possible ${ob}, in ${ou}?|Find the smallest ${ob} the model can give.]]`), a: ans, w: [c, c - b, h],
      p: { b, c }, js: "let best = Infinity; for (let x = -100; x <= 100; x++) { best = Math.min(best, x * x - P.b * x + P.c); } return best;", t: [`${v}² − ${b}${v} + ${c} = (${v} − ${h})² + ${c - h * h}.`, "완전제곱식으로 고친다.||Complete the square.", "제곱은 0 이상이다.||A square is never negative.", `최솟값은 제곱이 0 일 때.||The minimum occurs when the square is 0.`, `답은 ${ans}.`] }; } },
  { name: "telescoping_sum", gen(rng) { const n = rng.int(6, 30); const ans = (n + 1) ** 2 - 1;
    return { s: sp(rng, `[[Because ${M("(x + 1)^2 - x^2 = 2x + 1")} for every x, the sum ${M(`(2 \\cdot 1 + 1) + (2 \\cdot 2 + 1) + \\cdots + (2 \\cdot ${n} + 1)`)} can be found without adding every term.|Use the identity ${M("(x + 1)^2 - x^2 = 2x + 1")} to add ${M(`(2 \\cdot 1 + 1) + (2 \\cdot 2 + 1) + \\cdots + (2 \\cdot ${n} + 1)`)} quickly.|The terms of ${M(`(2 \\cdot 1 + 1) + (2 \\cdot 2 + 1) + \\cdots + (2 \\cdot ${n} + 1)`)} each equal a difference of consecutive squares, because ${M("(x + 1)^2 - x^2 = 2x + 1")}.|Add the terms ${M(`(2 \\cdot 1 + 1) + (2 \\cdot 2 + 1) + \\cdots + (2 \\cdot ${n} + 1)`)}, noting that ${M("2x + 1")} equals ${M("(x + 1)^2 - x^2")}.]]`), q: sp(rng, `[[What is the value of the sum?|Find the sum of the ${n} terms.|Compute the total.]]`), a: ans, w: [n * n, (n + 1) ** 2, n * (2 * n + 1)],
      p: { n }, js: "let s = 0; for (let x = 1; x <= P.n; x++) s += 2 * x + 1; return s;", t: [`2x + 1 = (x + 1)² − x².`, "항을 이어서 쓰면 중간이 소거된다.||Written out, the middle terms cancel.", `남는 것: (${n} + 1)² − 1².`, `${(n + 1) ** 2} − 1.`, `답은 ${ans}.`] }; } },
];
// ───────── kind C: identity_parameters — 항등식·동치 조건으로 상수를 정해 수를 구한다 ─────────
const C_COMPOSE: Var[] = [
  { name: "linear_identity_constant", gen(rng) { const v = vr(rng); const p = nzr(rng, -5, 6), a = nzr(rng, -7, 7), q = nzr(rng, -5, 6), b = nzr(rng, -7, 7); const C = p * a + q * -b; need(p + q !== 0 && Math.abs(C) < 80);
    return { s: sp(rng, `[[The expression ${M(`${p}(${v} ${a > 0 ? "+" : "-"} ${Math.abs(a)}) + ${q}(${v} ${-b > 0 ? "+" : "-"} ${Math.abs(b)})`)} is equivalent to ${M(`R${v} + C`)}, where R and C are constants.|Distribute and combine like terms in ${M(`${p}(${v} ${a > 0 ? "+" : "-"} ${Math.abs(a)}) + ${q}(${v} ${-b > 0 ? "+" : "-"} ${Math.abs(b)})`)} to obtain ${M(`R${v} + C`)}.|For every ${M(v)}, ${M(`${p}(${v} ${a > 0 ? "+" : "-"} ${Math.abs(a)}) + ${q}(${v} ${-b > 0 ? "+" : "-"} ${Math.abs(b)})`)} equals ${M(`R${v} + C`)} for some constants R and C.|A sum of two scaled binomials, ${M(`${p}(${v} ${a > 0 ? "+" : "-"} ${Math.abs(a)}) + ${q}(${v} ${-b > 0 ? "+" : "-"} ${Math.abs(b)})`)}, is simplified to ${M(`R${v} + C`)}.]]`), q: sp(rng, `[[What is the value of C?|Find C.|What is the constant term C?]]`), a: C, w: [p + q, p * a + q * b, C + p],
      p: { p, a, q, b }, js: "const f = x => P.p * (x + P.a) + P.q * (x - P.b); return f(0);", t: [`${p}(${v} + ${a}) = ${p}${v} + ${p * a}.`, `${q}(${v} − ${b}) = ${q}${v} − ${q * b}.`, "두 식을 더하면 상수항끼리 합쳐진다.||Constant terms combine.", `${p * a} + (${-q * b}).`, `C = ${C}.`] }; } },
  { name: "quadratic_product_q_minus_p", gen(rng) { const v = vr(rng); const a = nzr(rng, -8, 8), b = nzr(rng, -8, 8); need(a !== b); const P2 = a + b, Q = a * b; const ans = Q - P2; need(ans !== 0);
    return { s: sp(rng, `[[The product ${M(`(${v} ${a > 0 ? "+" : "-"} ${Math.abs(a)})(${v} ${b > 0 ? "+" : "-"} ${Math.abs(b)})`)} is equivalent to ${M(`${v}^2 + p${v} + q`)}, where p and q are constants.|Expand ${M(`(${v} ${a > 0 ? "+" : "-"} ${Math.abs(a)})(${v} ${b > 0 ? "+" : "-"} ${Math.abs(b)})`)} to get ${M(`${v}^2 + p${v} + q`)}, with constants p and q.|For all ${M(v)}, ${M(`(${v} ${a > 0 ? "+" : "-"} ${Math.abs(a)})(${v} ${b > 0 ? "+" : "-"} ${Math.abs(b)})`)} = ${M(`${v}^2 + p${v} + q`)}, where p and q do not depend on ${M(v)}.|Multiplying two binomials, ${M(`(${v} ${a > 0 ? "+" : "-"} ${Math.abs(a)})(${v} ${b > 0 ? "+" : "-"} ${Math.abs(b)})`)}, gives the trinomial ${M(`${v}^2 + p${v} + q`)}.]]`), q: sp(rng, `[[What is the value of q − p?|Find q − p.|Compute q minus p.]]`), a: ans, w: [P2 + Q, P2 * Q, Q],
      p: { a, b }, js: MUL + "const f = mul([P.a, 1], [P.b, 1]); return f[0] - f[1];", t: [`p = ${a} + ${b} = ${P2}.`, `q = ${a} × ${b} = ${Q}.`, "x 계수는 두 상수의 합, 상수항은 곱이다.||The x-coefficient is the sum and the constant is the product.", `q − p = ${Q} − (${P2}).`, `답은 ${ans}.`] }; } },
  { name: "rational_numerator_sum", gen(rng) { const a = rng.int(1, 5), b = rng.int(a + 1, 8), A = nzr(rng, -5, 6), Bc = nzr(rng, -5, 6); need(A + Bc !== 0); const p = A + Bc, q = A * b + Bc * a; const ans = p + q;
    return { s: sp(rng, `[[For x not equal to −${a} or −${b}, the sum ${M(`\\frac{${A}}{x + ${a}} + \\frac{${Bc}}{x + ${b}}`)} is equivalent to ${M(`\\frac{px + q}{(x + ${a})(x + ${b})}`)}, where p and q are constants.|Add the fractions in ${M(`\\frac{${A}}{x + ${a}} + \\frac{${Bc}}{x + ${b}}`)} over a common denominator to obtain ${M(`\\frac{px + q}{(x + ${a})(x + ${b})}`)}.|The sum ${M(`\\frac{${A}}{x + ${a}} + \\frac{${Bc}}{x + ${b}}`)} is rewritten as the single fraction ${M(`\\frac{px + q}{(x + ${a})(x + ${b})}`)} (x not equal to −${a} or −${b}).|Combining ${M(`\\frac{${A}}{x + ${a}} + \\frac{${Bc}}{x + ${b}}`)} into one fraction gives ${M(`\\frac{px + q}{(x + ${a})(x + ${b})}`)} for constants p and q.]]`), q: sp(rng, `[[What is the value of p + q?|Find p + q.|Compute the sum of p and q.]]`), a: ans, w: [p, q, p * q],
      p: { A, B: Bc, a, b }, js: "const num = x => P.A * (x + P.b) + P.B * (x + P.a); const q = num(0); const p = num(1) - num(0); return p + q;", t: [`공통분모는 (x + ${a})(x + ${b}).||Common denominator.`, `분자 = ${A}(x + ${b}) + ${Bc}(x + ${a}).`, `p = ${A} + ${Bc} = ${p}.`, `q = ${A}·${b} + ${Bc}·${a} = ${q}.`, `p + q = ${ans}.`] }; } },
  { name: "difference_of_squares_coefficient", gen(rng) { const v = vr(rng); const a = rng.int(2, 9); const k = 4 * a;
    return { s: sp(rng, `[[The expression ${M(`(${v} + ${a})^2 - (${v} - ${a})^2`)} is equivalent to ${M(`k${v}`)} for every value of ${M(v)}, where k is a constant.|Expanding ${M(`(${v} + ${a})^2 - (${v} - ${a})^2`)} leaves a single term ${M(`k${v}`)}; k is a constant.|For all ${M(v)}, ${M(`(${v} + ${a})^2 - (${v} - ${a})^2`)} = ${M(`k${v}`)} with k constant.|Two squares are subtracted: ${M(`(${v} + ${a})^2 - (${v} - ${a})^2`)}. The result simplifies to ${M(`k${v}`)}.]]`), q: sp(rng, `[[What is the value of k?|Find k.|What number is k?]]`), a: k, w: [2 * a, a * a, 2 * a * a],
      p: { a }, js: "const E = x => (x + P.a) ** 2 - (x - P.a) ** 2; return E(1);", t: [`(${v} + ${a})² = ${v}² + ${2 * a}${v} + ${a * a}.`, `(${v} − ${a})² = ${v}² − ${2 * a}${v} + ${a * a}.`, "빼면 제곱항과 상수항이 소거된다.||Subtracting cancels the squared and constant terms.", `${2 * a}${v} − (−${2 * a}${v}).`, `k = ${k}.`] }; } },
];
const C_CHAIN: Var[] = [
  { name: "two_unknown_linear_product", gen(rng) { const v = vr(rng); const a = rng.int(1, 7), b = rng.int(1, 7); need(a !== b); const m = rng.int(1, 5), n = rng.int(1, 5); const Pc = a + b, Qc = a * m - b * n; need(Qc !== 0);
    return { s: sp(rng, `[[The equation ${M(`a(${v} + ${m}) + b(${v} - ${n}) = ${Pc}${v} ${Qc >= 0 ? "+" : "-"} ${Math.abs(Qc)}`)} is true for all values of ${M(v)}, where a and b are constants.|Constants a and b make ${M(`a(${v} + ${m}) + b(${v} - ${n}) = ${Pc}${v} ${Qc >= 0 ? "+" : "-"} ${Math.abs(Qc)}`)} an identity in ${M(v)}.|Matching coefficients in ${M(`a(${v} + ${m}) + b(${v} - ${n}) = ${Pc}${v} ${Qc >= 0 ? "+" : "-"} ${Math.abs(Qc)}`)}, which holds for every ${M(v)}, determines a and b.|For every ${M(v)}, ${M(`a(${v} + ${m}) + b(${v} - ${n}) = ${Pc}${v} ${Qc >= 0 ? "+" : "-"} ${Math.abs(Qc)}`)} holds, with constants a and b.]]`), q: sp(rng, `[[What is the value of ${M("ab")}?|Find the product of a and b.|Compute a times b.]]`), a: a * b, w: [a + b, a - b, Qc],
      p: { m, n, P: Pc, Q: Qc }, js: "for (let a = -40; a <= 40; a++) { for (let b = -40; b <= 40; b++) { if (a + b === P.P && a * P.m - b * P.n === P.Q) return a * b; } } throw new Error('none');", t: [`${v} 계수: a + b = ${Pc}.`, `상수항: ${m}a − ${n}b = ${Qc}.`, `연립하면 a = ${a}, b = ${b}.||Solve the system: a = ${a}, b = ${b}.`, "검산한다.||Check.", `ab = ${a * b}.`] }; } },
  { name: "three_coefficient_match", gen(rng) { const v = vr(rng); const a = rng.int(1, 5), b = nzr(rng, -6, 6), c = nzr(rng, -6, 6); const Pc = a, Qc = 2 * a + b, Rc = a + b + c; need(Rc !== 0 && Qc !== 0);
    return { s: sp(rng, `[[The equation ${M(`a(${v} + 1)^2 + b(${v} + 1) + c = ${pl3(Pc, Qc, Rc, v)}`)} is true for all values of ${M(v)}, where a, b, and c are constants.|Constants a, b, and c make ${M(`a(${v} + 1)^2 + b(${v} + 1) + c = ${pl3(Pc, Qc, Rc, v)}`)} an identity in ${M(v)}.|For every ${M(v)}, ${M(`a(${v} + 1)^2 + b(${v} + 1) + c = ${pl3(Pc, Qc, Rc, v)}`)} holds for some constants a, b, and c.|Expand the left side of ${M(`a(${v} + 1)^2 + b(${v} + 1) + c = ${pl3(Pc, Qc, Rc, v)}`)} and match coefficients; it holds for all ${M(v)}.]]`), q: sp(rng, `[[What is the value of c?|Find c.|What number is c?]]`), a: c, w: [Rc, b, a + b],
      p: { P: Pc, Q: Qc, R: Rc }, js: "const aa = P.P; const bb = P.Q - 2 * aa; return P.R - aa - bb;", t: [`(${v} + 1)² = ${v}² + 2${v} + 1.`, `${v}² 계수: a = ${Pc}.`, `${v} 계수: 2a + b = ${Qc}, b = ${b}.`, `상수항: a + b + c = ${Rc}.`, `c = ${c}.`] }; } },
  { name: "partial_fraction_A", gen(rng) { const A = nzr(rng, -6, 6), Bc = nzr(rng, -6, 6); need(A + Bc !== 0); const p = A + Bc, q = 2 * A - Bc;
    return { s: sp(rng, `[[For x not equal to 1 or −2, the equation ${M(`\\frac{A}{x - 1} + \\frac{B}{x + 2} = \\frac{${pl2(p, q, "x")}}{(x - 1)(x + 2)}`)} is true, where A and B are constants.|Constants A and B make the identity ${M(`\\frac{A}{x - 1} + \\frac{B}{x + 2} = \\frac{${pl2(p, q, "x")}}{(x - 1)(x + 2)}`)} hold for x not equal to 1 or −2.|Splitting a fraction: ${M(`\\frac{A}{x - 1} + \\frac{B}{x + 2} = \\frac{${pl2(p, q, "x")}}{(x - 1)(x + 2)}`)} holds for x not equal to 1 or −2 for constants A and B.|Combine the left side of ${M(`\\frac{A}{x - 1} + \\frac{B}{x + 2} = \\frac{${pl2(p, q, "x")}}{(x - 1)(x + 2)}`)} over a common denominator and compare with the right side (x not equal to 1 or −2).]]`), q: sp(rng, `[[What is the value of A?|Find A.|What number is A?]]`), a: A, w: [Bc, p, q],
      p: { p, q }, js: "for (let A = -40; A <= 40; A++) { for (let B = -40; B <= 40; B++) { if (A + B === P.p && 2 * A - B === P.q) return A; } } throw new Error('none');", t: [`분자: A(x + 2) + B(x − 1).`, `x 계수: A + B = ${p}.`, `상수항: 2A − B = ${q}.`, "두 식을 더하면 3A.||Adding the equations gives 3A.", `A = ${A}.`] }; } },
  { name: "difference_of_squares_roots", gen(rng) { const c = rng.int(2, 6), d = rng.int(1, 9); const a = c * c, b = d * d; need(a * b < 999);
    return { s: sp(rng, `[[The expression ${M(`${a}x^2 - ${b}`)} is equivalent to ${M("(cx - d)(cx + d)")}, where c and d are positive integers.|Factor ${M(`${a}x^2 - ${b}`)} as ${M("(cx - d)(cx + d)")} with positive integers c and d.|A difference of squares, ${M(`${a}x^2 - ${b}`)}, factors as ${M("(cx - d)(cx + d)")} for positive integers c and d.|For all x, ${M(`${a}x^2 - ${b}`)} = ${M("(cx - d)(cx + d)")}, where c and d are positive integers.]]`), q: sp(rng, `[[What is the value of c + d?|Find c + d.|Compute the sum of c and d.]]`), a: c + d, w: [c * d, a + b, c - d || 99],
      p: { a, b }, js: "for (let c = 1; c <= 40; c++) { for (let d = 1; d <= 40; d++) { if (c * c === P.a && d * d === P.b) return c + d; } } throw new Error('none');", t: [`(cx − d)(cx + d) = c²x² − d².`, `c² = ${a} 이므로 c = ${c}.||c^2 = ${a}, so c = ${c}.`, `d² = ${b} 이므로 d = ${d}.||d^2 = ${b}, so d = ${d}.`, "양의 정수이므로 제곱근은 양수.||Both are positive integers.", `c + d = ${c + d}.`] }; } },
];
const C_INVERSE: Var[] = [
  { name: "square_form_parameter", gen(rng) { const v = vr(rng); const a = nzr(rng, -4, 5), m = nzr(rng, -4, 5), n = nzr(rng, -9, 9), t = rng.int(1, 4); need(a !== 0 && t + m !== 0); const F = a * (t + m) ** 2 + n; need(Math.abs(F) < 200);
    return { s: sp(rng, `[[The function ${M(`f(${v}) = a(${v} ${m > 0 ? "+" : "-"} ${Math.abs(m)})^2 ${n > 0 ? "+" : "-"} ${Math.abs(n)}`)} has ${M(`f(${t}) = ${F}`)}, where a is a constant.|For the function ${M(`f(${v}) = a(${v} ${m > 0 ? "+" : "-"} ${Math.abs(m)})^2 ${n > 0 ? "+" : "-"} ${Math.abs(n)}`)}, the value at ${t} is ${F}: ${M(`f(${t}) = ${F}`)}. Here a is a constant.|A quadratic model ${M(`f(${v}) = a(${v} ${m > 0 ? "+" : "-"} ${Math.abs(m)})^2 ${n > 0 ? "+" : "-"} ${Math.abs(n)}`)} passes through the point where ${M(`f(${t}) = ${F}`)}; a is a constant.|Given ${M(`f(${v}) = a(${v} ${m > 0 ? "+" : "-"} ${Math.abs(m)})^2 ${n > 0 ? "+" : "-"} ${Math.abs(n)}`)} and the condition ${M(`f(${t}) = ${F}`)}, a is an unknown constant.]]`), q: sp(rng, `[[What is the value of a?|Find a.|What number is a?]]`), a, w: [F - n, a + 1, F],
      p: { m, n, t, F }, js: "for (let a = -60; a <= 60; a++) { if (a * (P.t + P.m) ** 2 + P.n === P.F) return a; } throw new Error('none');", t: [`f(${t}) = a(${t} + ${m})² + ${n}.`, `(${t + m})² = ${(t + m) ** 2}.`, `${(t + m) ** 2}a + ${n} = ${F}.`, `a = ${F - n} ÷ ${(t + m) ** 2}.`, `a = ${a}.`] }; } },
  { name: "zero_linear_term", gen(rng) { const v = vr(rng); const n = nzr(rng, -8, 8), m = nzr(rng, -8, 8); const k = m + n; need(k !== 0);
    return { s: sp(rng, `[[The expression ${M(`(${v} + k)(${shifted(v, -n)})`)} is expanded, and the coefficient of ${M(v)} in the result is ${m}. Here k is a constant.|After ${M(`(${v} + k)(${shifted(v, -n)})`)} is multiplied out, the coefficient of ${M(v)} is ${m}; k is a constant.|Expanding ${M(`(${v} + k)(${shifted(v, -n)})`)} gives a polynomial whose ${M(v)}-term has coefficient ${m}, where k is a constant.|The ${M(v)}-coefficient of the expanded product ${M(`(${v} + k)(${shifted(v, -n)})`)} equals ${m}, for a constant k.]]`), q: sp(rng, `[[What is the value of k?|Find k.|What number is k?]]`), a: k, w: [m, n, m - n],
      p: { n, m }, js: "for (let k = -80; k <= 80; k++) { if (k - P.n === P.m) return k; } throw new Error('none');", t: [`(${v} + k)(${v} − ${n}) = ${v}² + (k − ${n})${v} − ${n}k.`, `${v} 계수: k − ${n} = ${m}.`, `k = ${m} + ${n}.`, `상수항 ${-n}k = ${-k * n} 으로 검산.||Check with the constant term.`, `k = ${k}.`] }; } },
  { name: "infinite_solutions_shift", gen(rng) { const v = vr(rng); const p = rng.int(2, 9), k = rng.int(2, 12); const N = p * k;
    return { s: sp(rng, `[[The equation ${M(`${p}(${v} + k) = ${p}${v} + ${N}`)} is true for all values of ${M(v)}, where k is a constant.|Constant k makes ${M(`${p}(${v} + k) = ${p}${v} + ${N}`)} an identity in ${M(v)}.|For every ${M(v)}, ${M(`${p}(${v} + k) = ${p}${v} + ${N}`)} holds when k is chosen correctly.|The equation ${M(`${p}(${v} + k) = ${p}${v} + ${N}`)} has infinitely many solutions for one value of k.]]`), q: sp(rng, `[[What is the value of k?|Find k.|What number is k?]]`), a: k, w: [N, N - p, p],
      p: { p, N }, js: "for (let k = 0; k <= 200; k++) { if (P.p * k === P.N) return k; } throw new Error('none');", t: [`${p}(${v} + k) = ${p}${v} + ${p}k.`, `${v} 항은 양변이 같다.||The ${v} terms already match.`, `상수항: ${p}k = ${N}.`, `k = ${N} ÷ ${p}.`, `k = ${k}.`] }; } },
  { name: "constant_difference_of_products", gen(rng) { const a = rng.int(1, 6), b = rng.int(1, 6), c = rng.int(1, 6); const d = a + b - c; need(d >= 1 && d <= 9 && (a * b - c * d) !== 0); const ans = a * b - c * d; const vv = rng.pick(["x", "t"]);
    return { s: sp(rng, `[[The expression ${M(`(${vv} + ${a})(${vv} + ${b}) - (${vv} + ${c})(${vv} + d)`)} has the same value for every ${M(vv)}, where d is a constant.|For one particular constant d, ${M(`(${vv} + ${a})(${vv} + ${b}) - (${vv} + ${c})(${vv} + d)`)} does not depend on ${M(vv)}.|Choose d so that ${M(`(${vv} + ${a})(${vv} + ${b}) - (${vv} + ${c})(${vv} + d)`)} is constant in ${M(vv)}.|A difference of two products, ${M(`(${vv} + ${a})(${vv} + ${b}) - (${vv} + ${c})(${vv} + d)`)}, is the same number for all ${M(vv)}; d is a constant.]]`), q: sp(rng, `[[What is that constant value?|What number does the expression equal for every ${M(vv)}?|Find the value the expression always takes.]]`), a: ans, w: [d, a * b, c * d],
      p: { a, b, c }, js: "const d = P.a + P.b - P.c; const E = x => (x + P.a) * (x + P.b) - (x + P.c) * (x + d); return E(0);", t: [`${vv} 계수: (${a} + ${b}) − (${c} + d) = 0.`, `d = ${a + b} − ${c} = ${d}.`, "x 항이 사라져 상수가 된다.||The x-term vanishes.", `상수 = ${a}·${b} − ${c}·${d}.`, `답은 ${ans}.`] }; } },
];
const C_COMPARE: Var[] = [
  { name: "count_factorable_k", gen(rng) { const N = rng.pick([12, 16, 18, 20, 24, 30, 36]); const K = rng.int(8, 20); const sums = new Set<number>(); for (let p = 1; p <= N; p++) if (N % p === 0) sums.add(p + N / p); const ans = [...sums].filter((s) => s >= 1 && s <= K).length; need(ans >= 1);
    return { s: sp(rng, `[[For each integer k from 1 to ${K}, consider the expression ${M(`x^2 + kx + ${N}`)}. An expression is called factorable if it equals ${M("(x + p)(x + q)")} for integers p and q.|Let k run through the integers 1 to ${K}. The quadratic ${M(`x^2 + kx + ${N}`)} is factorable when it can be written as ${M("(x + p)(x + q)")} with integer p and q.|A trinomial ${M(`x^2 + kx + ${N}`)} is tested for each integer k from 1 through ${K}; it is factorable if it equals ${M("(x + p)(x + q)")} for some integers p and q.|Some integers k between 1 and ${K} allow ${M(`x^2 + kx + ${N}`)} to be written as ${M("(x + p)(x + q)")} with integers p and q.]]`), q: sp(rng, `[[For how many of these values of k is the expression factorable?|How many integers k from 1 to ${K} make the expression factorable?|Count the values of k for which the trinomial factors over the integers.]]`), a: ans, w: [K - ans, ans + 1, sums.size],
      p: { K, N }, js: "let c = 0; for (let k = 1; k <= P.K; k++) { let ok = false; for (let p = -100; p <= 100; p++) { for (let q = -100; q <= 100; q++) { if (p + q === k && p * q === P.N) ok = true; } } if (ok) c++; } return c;", t: [`x² + kx + ${N} = (x + p)(x + q) 이면 pq = ${N}, p + q = k.`, `${N} 의 약수 쌍의 합을 구한다.||List sums of factor pairs of ${N}.`, `가능한 k: ${[...sums].sort((x, y) => x - y).join(", ")}.`, `1 ~ ${K} 안의 값만 센다.||Count those between 1 and ${K}.`, `답은 ${ans}.`] }; } },
  { name: "cube_sum_from_sum_product", gen(rng) { const s = rng.int(3, 9), pr = rng.int(1, s * s / 4 | 0); need(pr >= 1); const ans = s ** 3 - 3 * pr * s; need(ans > 0 && ans < 9999);
    return { s: sp(rng, `[[The numbers a and b satisfy ${M(`a + b = ${s}`)} and ${M(`ab = ${pr}`)}.|Two numbers have sum ${s} and product ${pr}.|Given that ${M(`a + b = ${s}`)}, and that the numbers multiply to ${pr}, consider their cubes.|A pair of numbers a and b has a + b equal to ${s} and ab equal to ${pr}.]]`), q: sp(rng, `[[What is the value of ${M("a^3 + b^3")}?|Find ${M("a^3 + b^3")}.|Compute the sum of the cubes of the two numbers.]]`), a: ans, w: [s * s * s, s ** 3 - pr * s, s ** 3 - 3 * pr],
      p: { s, pr }, js: "const disc = P.s * P.s - 4 * P.pr; const r = Math.sqrt(disc); const a = (P.s + r) / 2, b = (P.s - r) / 2; return Math.round(a ** 3 + b ** 3);", t: [`${M("(a+b)^3")} 를 전개하면 a³ + b³ + 3ab(a + b).||(a+b)^3 = a^3 + b^3 + 3ab(a+b).`, `a³ + b³ = (a + b)³ − 3ab(a + b).`, `${s}³ = ${s ** 3}.`, `3 × ${pr} × ${s} = ${3 * pr * s}.`, `답은 ${ans}.`] }; } },
  { name: "square_sum_from_sum_product", gen(rng) { const s = rng.int(4, 12), pr = rng.int(2, 30); need(pr < s * s / 4); const ans = s * s - 2 * pr; need(ans > 0);
    return { s: sp(rng, `[[The numbers x and y satisfy ${M(`x + y = ${s}`)} and ${M(`xy = ${pr}`)}.|Two numbers have sum ${s} and product ${pr}.|Given that x + y equals ${s} and xy equals ${pr}, consider their squares.|A pair of numbers x and y has sum ${s} and product ${pr}.]]`), q: sp(rng, `[[What is the value of ${M("x^2 + y^2")}?|Find ${M("x^2 + y^2")}.|Compute the sum of the squares of the two numbers.]]`), a: ans, w: [s * s, s * s - pr, 2 * pr],
      p: { s, pr }, js: "const r = Math.sqrt(P.s * P.s - 4 * P.pr); const x = (P.s + r) / 2, y = (P.s - r) / 2; return Math.round(x * x + y * y);", t: [`(x + y)² = x² + 2xy + y².`, `x² + y² = (x + y)² − 2xy.`, `${s}² = ${s * s}.`, `2 × ${pr} = ${2 * pr}.`, `답은 ${ans}.`] }; } },
  { name: "reciprocal_square_sum", gen(rng) { const s = rng.int(3, 9); const ans = s * s - 2; const v = vr(rng);
    return { s: sp(rng, `[[The number ${M(v)} is positive and satisfies ${M(`${v} + \\frac{1}{${v}} = ${s}`)}.|For a positive number ${M(v)}, ${M(`${v} + \\frac{1}{${v}} = ${s}`)}.|A positive ${M(v)} is chosen so that ${M(`${v} + \\frac{1}{${v}} = ${s}`)}.|Suppose ${M(`${v} + \\frac{1}{${v}} = ${s}`)}, where ${M(v)} is positive.]]`), q: sp(rng, `[[What is the value of ${M(`${v}^2 + \\frac{1}{${v}^2}`)}?|Find ${M(`${v}^2 + \\frac{1}{${v}^2}`)}.|Compute the sum of the squares of the number and its reciprocal.]]`), a: ans, w: [s * s, s * s - 1, 2 * s],
      p: { s }, js: "const x = (P.s + Math.sqrt(P.s * P.s - 4)) / 2; return Math.round(x * x + 1 / (x * x));", t: [`(${v} + 1/${v})² = ${v}² + 2 + 1/${v}².`, `${v}² + 1/${v}² = (${v} + 1/${v})² − 2.`, `${s}² = ${s * s}.`, `${s * s} − 2.`, `답은 ${ans}.`] }; } },
];

const EE_BASE = { skill: SKILL, mediumSteps: 3 };
export const EE_SPR_A: Archetype[] = [
  ...mkKind({ ...EE_BASE, id: "ee.coefficient_matching", kind: "coefficient_matching", concepts: ["식의 전개", "계수 비교", "동류항 정리"] }, [
    { op: "compose_kind", structure: "여러 이항식·제곱·차의 제곱을 합성해 전개한 식의 특정 계수·상수항·계수 합을 구함", extra: "전개 결과 전체가 아니라 필요한 계수만 선택적으로 합산하거나 1 을 대입하는 요령이 필요 — medium 은 이항식 하나를 전개", vars: dress(A_COMPOSE) },
    { op: "chain2", structure: "꼴 변환(꼭짓점형·완전제곱·인수분해)을 한 뒤 그 계수로 값을 연결해 구함", extra: "앞 단계에서 얻은 계수·인수가 다음 계산의 입력이 되는 2단계 — medium 은 한 번의 전개", vars: dress(A_CHAIN) },
    { op: "inverse", structure: "전개된 식과 일부 인수를 주고 빠진 상수나 계수를 거꾸로 구함", extra: "전개 규칙을 뒤집어 미지 계수를 풀어야 함 — medium 은 정방향 전개", vars: dress(A_INVERSE) },
    { op: "compare_scenarios", structure: "동치가 아닌 식과 동치인 식을 값·넓이·보기 개수로 비교", extra: "같은 값처럼 보이는 두 식의 차이를 중간항이나 항등성으로 설명해야 함 — medium 은 한 식의 전개", vars: dress(A_COMPARE) },
  ]),
  ...mkKind({ ...EE_BASE, id: "ee.exponent_radical_forms", kind: "exponent_radical_forms", concepts: ["지수법칙", "근호와 분수식 변형", "동치 변형"] }, [
    { op: "compose_kind", structure: "거듭제곱의 거듭제곱·곱·몫·세제곱근·음의 지수를 합성해 지수나 값을 구함", extra: "여러 지수법칙을 올바른 순서로 합성해야 함 — medium 은 법칙 하나 적용", vars: dress(B_COMPOSE) },
    { op: "chain2", structure: "약분·통분·근호 정리·역수의 합을 거쳐 값이나 계수를 구함", extra: "한 변형의 결과가 다음 계산의 입력이 되는 2단계 — medium 은 한 번의 약분", vars: dress(B_CHAIN) },
    { op: "inverse", structure: "동치 조건에서 미지의 지수·밑·배율·나머지를 거꾸로 구함", extra: "동치 식의 구조를 비교해 미지수를 풀어야 함 — medium 은 정방향 간단히 하기", vars: dress(B_INVERSE) },
    { op: "compare_scenarios", structure: "원래 꼴과 변형한 꼴(제곱의 차·밑 통일·완전제곱·소거)로 값을 비교해 수를 구함", extra: "계산을 직접 하기보다 동치 변형으로 단순화하는 선택이 필요 — medium 은 직접 계산", vars: dress(B_COMPARE) },
  ]),
  ...mkKind({ ...EE_BASE, id: "ee.identity_parameters", kind: "identity_parameters", concepts: ["항등식", "계수 비교로 상수 결정", "동치 조건"] }, [
    { op: "compose_kind", structure: "두 식이 모든 값에서 같다는 조건을 계수 비교로 풀어 요구된 계수를 구함", extra: "양변을 전개·통분해 계수끼리 맞춰야 함 — medium 은 한 식의 전개", vars: dress(C_COMPOSE) },
    { op: "chain2", structure: "연립한 계수 조건을 풀어 얻은 상수로 곱·합을 구함", extra: "계수 비교로 세운 연립을 풀고 다시 계산해야 함 — medium 은 한 계수 비교", vars: dress(C_CHAIN) },
    { op: "inverse", structure: "항등 조건이나 한 점의 값에서 미지 상수를 거꾸로 구함", extra: "항등 조건 한 개를 식으로 세워 상수를 풀어야 함 — medium 은 미지수 없는 전개", vars: dress(C_INVERSE) },
    { op: "compare_scenarios", structure: "k 의 범위·합과 곱·역수의 합 등 여러 경우에서 동치 변형으로 수를 구함", extra: "경우를 하나씩 세거나 항등식으로 한 번에 계산해야 함 — medium 은 한 경우만 계산", vars: dress(C_COMPARE) },
  ]),
];
void pickDiv; void isInt;
