// evaluating_statistical_claims — 수치 단답(SPR 가능) hard 원형 3 kind × 4 연산자. 표본·실험·관찰 연구의 주장을 숫자로 평가한다(정성 선지형 원형과 별개).
import { GenFail } from "../types";
import { need, isInt, sp, mkKind, pickDiv, type Var } from "./spr-a-kit";
import type { Rng } from "../rng";
import type { Archetype } from "../types";

const SKILL = "evaluating_statistical_claims";
type Sc = { P: string; tr: string; home: string };
const SCN: Sc[] = [
  { P: "residents", tr: "support building a new bike lane", home: "the town of Fairview" }, { P: "students", tr: "ride the bus to school", home: "Lincoln High School" },
  { P: "customers", tr: "prefer ordering online", home: "the Greenfield Market grocery chain" }, { P: "employees", tr: "work from home at least one day a week", home: "the Apex Software company" },
  { P: "voters", tr: "favor the proposed park", home: "Marion County" }, { P: "members", tr: "attend the monthly meeting", home: "the Riverside Community Center" },
  { P: "households", tr: "recycle every week", home: "the city of Dayton" }, { P: "commuters", tr: "use public transit", home: "the Harborview metropolitan area" },
  { P: "teachers", tr: "use the new grading software", home: "the Lakeview School District" }, { P: "visitors", tr: "plan to return next year", home: "Glacier View National Park" },
];
const sc = (rng: Rng) => rng.pick(SCN);
const RS = (rng: Rng) => sp(rng, "[[A random sample|A simple random sample]]");

// ───────── kind A: sample_to_population — 무작위 표본의 비율을 모집단에 옮겨 주장을 수량으로 평가 ─────────
const A_COMPOSE: Var[] = [
  { name: "frame_total", gen(rng) { const c0 = sc(rng); const n = rng.pick([40, 50, 80, 100, 120, 150, 200]), f = rng.pick([20, 25, 30, 40, 60, 75]), N = rng.pick([240, 300, 360, 400, 480, 600, 800, 900]); const c = (n * f) / 100; need(isInt(c)); const a = (N * c) / n; need(isInt(a) && a < N);
    return { s: `${RS(rng)} of ${n} ${c0.P} was drawn from the list of all ${N} ${c0.P} of ${c0.home}. In the sample, ${c} ${c0.P} ${c0.tr}.`, q: sp(rng, `[[Based on the sample, about how many of the ${N} ${c0.P} on the list ${c0.tr}?|Using the sample, estimate the number of ${c0.P} on the list who ${c0.tr}.]]`), a, w: [c, N - a, (N * (n - c)) / n],
      p: { n, c, N }, js: "for (let k = 0; k <= P.N; k++) { if (k * P.n === P.c * P.N) return k; } throw new Error('none');", t: [`표본 비율 = ${c}/${n}.||The sample proportion is ${c}/${n}.`, "표본이 무작위이므로 명단 전체에 같은 비율을 적용한다.||The sample is random, so the proportion carries over to the whole list.", `추정 인원 = ${N} × ${c}/${n}.||Estimate = ${N} x ${c}/${n}.`, `${N} ÷ ${n} = ${N / n} 이므로 ${c} × ${N / n}.||${N}/${n} = ${N / n}, so multiply ${c} x ${N / n}.`, `답은 ${a}.||The estimate is ${a}.`] }; } },
  { name: "two_site_total", gen(rng) { const c0 = sc(rng); const n1 = rng.pick([40, 50, 60, 80]), n2 = rng.pick([25, 40, 50, 100]), k1 = rng.int(4, 12), k2 = rng.int(3, 9), c1 = rng.int(6, n1 - 6), c2 = rng.int(6, n2 - 6); const N1 = n1 * k1, N2 = n2 * k2; need(N1 < 1000 && N2 < 1000 && c1 / n1 !== c2 / n2); const a = c1 * k1 + c2 * k2;
    return { s: `Two groups of ${c0.P} were surveyed separately by random sampling. At the first site, ${c1} of ${n1} sampled ${c0.P} ${c0.tr}, and the site has ${N1} ${c0.P}. At the second site, ${c2} of ${n2} sampled ${c0.P} ${c0.tr}, and the site has ${N2} ${c0.P}.`, q: sp(rng, `[[Based on the samples, about how many ${c0.P} in all at the two sites ${c0.tr}?|What is the best estimate of the total number of ${c0.P} at both sites who ${c0.tr}?]]`), a,
      w: [((c1 + c2) * (N1 + N2)) / (n1 + n2), c1 + c2, a - c1], p: { n1, n2, c1, c2, N1, N2 }, js: "return P.c1 * (P.N1 / P.n1) + P.c2 * (P.N2 / P.n2);", t: ["두 지역의 표본은 따로 뽑았으므로 지역별로 추정한다.||The samples are separate, so estimate each site on its own.", `첫 지역: ${N1} × ${c1}/${n1} = ${c1 * k1}.||Site 1: ${N1} x ${c1}/${n1} = ${c1 * k1}.`, `둘째 지역: ${N2} × ${c2}/${n2} = ${c2 * k2}.||Site 2: ${N2} x ${c2}/${n2} = ${c2 * k2}.`, "두 추정값을 더한다.||Add the two estimates.", `${c1 * k1} + ${c2 * k2} = ${a}.`] }; } },
  { name: "weighted_percent", gen(rng) { const c0 = sc(rng); const [r1, r2] = rng.pick([[1, 3], [3, 2], [2, 3], [1, 4], [4, 1], [3, 1], [1, 1], [2, 3]]); const u = rng.pick([40, 60, 100, 120, 80]); const p1 = rng.pick([10, 20, 30, 40, 50, 60, 70]), p2 = rng.pick([15, 25, 35, 45, 55, 65, 75, 80, 90]); const a = (r1 * p1 + r2 * p2) / (r1 + r2); need(isInt(a) && p1 !== p2); const N1 = r1 * u, N2 = r2 * u;
    return { s: `A town has two neighborhoods with ${N1} and ${N2} ${c0.P}, respectively. A random sample taken in each neighborhood shows that ${p1}% of the ${c0.P} in the first neighborhood and ${p2}% of those in the second ${c0.tr}.`, q: sp(rng, `[[Based on the samples, what percent of all ${c0.P} in the town ${c0.tr}?|About what percent of the ${N1 + N2} ${c0.P} in the town ${c0.tr}, according to the samples?]]`), a, w: [(p1 + p2) / 2, p1 + p2, Math.abs(p2 - p1)],
      p: { N1, N2, p1, p2 }, js: "let k = 0; for (let i = 1; i <= P.N1; i++) k += P.p1 / 100; for (let i = 1; i <= P.N2; i++) k += P.p2 / 100; return Math.round(100 * k / (P.N1 + P.N2));", t: ["두 동네의 표본 비율을 각 동네 인구에 따로 적용한다.||Apply each sample percent to its own neighborhood's population.", `첫 동네: ${N1} × ${p1}% = ${(N1 * p1) / 100}.||Neighborhood 1: ${N1} x ${p1}% = ${(N1 * p1) / 100}.`, `둘째 동네: ${N2} × ${p2}% = ${(N2 * p2) / 100}.||Neighborhood 2: ${N2} x ${p2}% = ${(N2 * p2) / 100}.`, `전체 = ${(N1 * p1) / 100 + (N2 * p2) / 100} 명 ÷ ${N1 + N2} 명.||Total = ${(N1 * p1) / 100 + (N2 * p2) / 100} out of ${N1 + N2}.`, `답은 ${a}%.||The percent is ${a}.`] }; } },
  { name: "nonresponse_upper_bound", gen(rng) { const c0 = sc(rng); const S = rng.pick([200, 250, 300, 400, 500, 600]), R = rng.pick([60, 80, 90, 100, 120, 150]); const k = rng.int(Math.ceil(R * 0.3), Math.floor(R * 0.7)); need(R < S); const a = k + (S - R);
    return { s: `A survey form was mailed to all ${S} ${c0.P} of ${c0.home}, and only ${R} ${c0.P} returned it. Of those who returned the form, ${k} said they ${c0.tr}.`, q: sp(rng, `[[Without assuming anything about those who did not respond, what is the greatest number of the ${S} ${c0.P} who could ${c0.tr}?|What is the largest possible number of all ${S} ${c0.P} who ${c0.tr}, given that nothing is known about the nonrespondents?]]`), a, w: [k, S - R, Math.round((S * k) / R)],
      p: { S, R, k }, js: "let best = 0; for (let z = 0; z <= P.S - P.R; z++) { best = Math.max(best, P.k + z); } return best;", t: [`${S - R} 명은 응답하지 않았고 그들의 답은 알 수 없다.||${S - R} people did not respond and their answers are unknown.`, "응답자 중 확실히 해당하는 사람은 k 명이다.||Among respondents, exactly k certainly qualify.", "무응답자 전원이 해당한다면 최대가 된다.||The maximum occurs if every nonrespondent qualifies.", `${k} + ${S - R}.`, `최댓값은 ${a}.||The greatest possible number is ${a}.`] }; } },
  { name: "least_hits_for_claim", gen(rng) { const c0 = sc(rng); const N = rng.pick([400, 500, 600, 800, 900]), n = rng.pick([50, 60, 80, 100, 120, 150]), claim = rng.pick([100, 150, 200, 250, 300, 350, 450]); need(claim < N); let a = 0; while ((a * N) < claim * n) a++; need(a > 1 && a < n);
    return { s: `A group claims that at least ${claim} of the ${N} ${c0.P} of ${c0.home} ${c0.tr}. To check this, a random sample of ${n} ${c0.P} will be surveyed.`, q: sp(rng, `[[What is the least number of sampled ${c0.P} who must say they ${c0.tr} for the sample to give an estimate of at least ${claim} in the whole group?|How many of the ${n} sampled ${c0.P} must ${c0.tr} for the estimate for all ${N} to reach ${claim}?]]`), a, w: [Math.floor((claim * n) / N), a + 1, Math.round((claim * 100) / N)],
      p: { N, n, claim }, js: "for (let c = 0; c <= P.n; c++) { if (c * P.N >= P.claim * P.n) return c; } throw new Error('none');", t: [`표본 비율 c/${n} 을 전체 ${N} 에 곱한 값이 ${claim} 이상이어야 한다.||The estimate N x c/n must be at least ${claim}.`, `c × ${N} ≥ ${claim} × ${n}.`, `c ≥ ${(claim * n) / N}.`, "c 는 자연수이므로 올림한다.||c is a whole number, so round up.", `최솟값은 ${a}.||The least value is ${a}.`] }; } },
];
const A_CHAIN: Var[] = [
  { name: "subgroup_of_subgroup", gen(rng) { const c0 = sc(rng); const g = rng.pick(["are under 30 years old", "have lived there less than five years", "work full time", "have children at home"]); const p1 = rng.pick([20, 25, 40, 50, 60, 75]), p2 = rng.pick([20, 25, 40, 50, 60, 80]), N = rng.pick([200, 300, 400, 500, 600, 800]); const n = rng.pick([80, 100, 150, 200]); const a = (N * p1 * p2) / 10000; need(isInt(a) && a >= 5);
    return { s: `${RS(rng)} of ${n} ${c0.P} was taken from ${c0.home}, which has ${N} ${c0.P}. In the sample, ${p1}% of the ${c0.P} ${g}, and ${p2}% of those ${c0.P} also ${c0.tr}.`, q: sp(rng, `[[Based on the sample, about how many ${c0.P} in all of ${c0.home} both ${g} and ${c0.tr}?|Estimate the number of ${c0.P} of ${c0.home} who ${g} and ${c0.tr}.]]`), a, w: [(N * p1) / 100, (N * p2) / 100, (N * (p1 + p2)) / 200],
      p: { n, N, p1, p2 }, js: "let first = 0; for (let i = 0; i < P.N; i++) { first += P.p1 / 100; } return Math.round(first * P.p2 / 100);", t: [`첫 비율 ${p1}% 를 ${N} 에 적용한다.||Apply the first percent, ${p1}%, to ${N}.`, `${N} × ${p1}% = ${(N * p1) / 100}.`, `그 집단 안에서 ${p2}% 가 해당한다.||Within that group, ${p2}% qualify.`, `${(N * p1) / 100} × ${p2}% = ${a}.`, `답은 ${a}.||The estimate is ${a}.`] }; } },
  { name: "voucher_budget", gen(rng) { const c0 = sc(rng); const n = rng.pick([50, 80, 100, 125, 200]), c = rng.int(8, Math.floor(n / 2)), k = rng.int(3, 9); const N = n * k; need(N < 1000); const d = rng.pick([5, 8, 10, 12, 15, 20, 25]); const a = c * k * d;
    return { s: `${RS(rng)} of ${n} ${c0.P} was taken from ${N} ${c0.P} of ${c0.home}; ${c} of the sampled ${c0.P} ${c0.tr}. The organizers will give a voucher worth ${d} dollars to each of the ${c0.P} who ${c0.tr}.`, q: sp(rng, `[[Based on the sample, about how many dollars should the organizers budget for vouchers?|What is the estimated total value, in dollars, of the vouchers?]]`), a, w: [c * d, N * d, (N * c) / n],
      p: { n, c, N, d }, js: "let people = 0; while ((people + 1) * P.n <= P.c * P.N) people++; return people * P.d;", t: [`표본 비율 ${c}/${n}.||Sample proportion ${c}/${n}.`, `전체 해당 인원 = ${N} × ${c}/${n} = ${c * k}.||Estimated qualifying people = ${N} x ${c}/${n} = ${c * k}.`, `쿠폰은 한 명당 ${d} 달러.||Each voucher is worth ${d} dollars.`, `${c * k} × ${d}.`, `예산은 ${a} 달러.||The budget is ${a} dollars.`] }; } },
  { name: "weekly_to_monthly", gen(rng) { const n = rng.pick([20, 25, 40, 50]), k = rng.int(4, 16), T = rng.int(40, 180), W = rng.pick([3, 4, 5, 6, 8]); const N = n * k; need(N < 1000); const a = T * k * W; need(a < 20000); const c0 = rng.pick([["households", "pounds of recycling", "recycling"], ["restaurants", "pounds of food waste", "food waste"], ["offices", "reams of paper", "paper use"], ["cafes", "gallons of milk", "milk orders"]]);
    return { s: `A random sample of ${n} ${c0[0]} in a city of ${N} ${c0[0]} used a combined ${T} ${c0[1]} in one typical week.`, q: sp(rng, `[[Using the sample, estimate the total ${c0[1]} used by all ${N} ${c0[0]} in ${W} typical weeks.|About how many ${c0[1]} would all ${N} ${c0[0]} use over ${W} weeks, based on the sample?]]`), a, w: [T * W, T * k, (T * N * W) / 100],
      p: { n, N, T, W }, js: "let perWeek = 0; for (let g = 0; g < P.N / P.n; g++) perWeek += P.T; let all = 0; for (let w = 0; w < P.W; w++) all += perWeek; return all;", t: [`표본의 주당 합계 ${T}.||The sample uses ${T} per week in total.`, `도시는 표본의 ${N}/${n} = ${k} 배이다.||The city is ${N}/${n} = ${k} times the sample.`, `도시의 주당 사용량 = ${T} × ${k}.||City weekly use = ${T} x ${k}.`, `${W} 주 동안 곱한다.||Multiply by ${W} weeks.`, `답은 ${a}.||The estimate is ${a}.`] }; } },
  { name: "seats_shortfall", gen(rng) { const c0 = sc(rng); const n = rng.pick([40, 50, 80, 100]), k = rng.int(5, 12), c = rng.int(Math.ceil(n * 0.3), Math.floor(n * 0.7)); const N = n * k; need(N < 1000); const est = c * k; const S = rng.int(Math.floor(est * 0.4), est - 10); need(S > 20); const a = est - S;
    return { s: `${RS(rng)} of ${n} ${c0.P} was taken from ${N} ${c0.P} of ${c0.home}. In the sample, ${c} ${c0.P} ${c0.tr}. A hall that seats ${S} people will be reserved for an event for the ${c0.P} who ${c0.tr}.`, q: sp(rng, `[[Based on the sample, about how many more seats than the hall provides would be needed?|By the sample estimate, how many people who ${c0.tr} would not have a seat?]]`), a, w: [est, S, N - S],
      p: { n, c, N, S }, js: "const est = P.c * (P.N / P.n); return est - P.S;", t: [`표본 비율 ${c}/${n}.||Sample proportion ${c}/${n}.`, `추정 인원 = ${N} × ${c}/${n} = ${est}.||Estimated attendees = ${est}.`, `좌석은 ${S} 석이다.||There are ${S} seats.`, `부족 = ${est} − ${S}.||Shortfall = ${est} - ${S}.`, `답은 ${a}.||The shortfall is ${a}.`] }; } },
  { name: "two_wave_change", gen(rng) { const c0 = sc(rng); const base = rng.pick([50, 100, 200]); const n1 = base, n2 = base === 200 ? 100 : base === 50 ? 100 : 200; const N = rng.pick([400, 600, 800]); need(N % n1 === 0 && N % n2 === 0); const c1 = rng.int(Math.ceil(n1 * 0.2), Math.floor(n1 * 0.5)), c2 = rng.int(Math.ceil(n2 * 0.4), Math.floor(n2 * 0.8)); const a = (N * c2) / n2 - (N * c1) / n1; need(isInt(a) && a > 0);
    return { s: `Before an awareness campaign, ${RS(rng).toLowerCase()} of ${n1} ${c0.P} from ${c0.home} found that ${c1} of them ${c0.tr}. After the campaign, a new random sample of ${n2} ${c0.P} found that ${c2} ${c0.tr}. The group has ${N} ${c0.P} in all.`, q: sp(rng, `[[According to the two samples, by about how many did the number of ${c0.P} who ${c0.tr} increase?|Estimate the increase in the number of ${c0.P} in the group who ${c0.tr}.]]`), a, w: [c2 - c1, (N * c2) / n2, (N * (c2 - c1)) / n1],
      p: { N, n1, n2, c1, c2 }, js: "const before = P.c1 * (P.N / P.n1); const after = P.c2 * (P.N / P.n2); return after - before;", t: [`캠페인 전 비율 ${c1}/${n1}.||Before: proportion ${c1}/${n1}.`, `캠페인 후 비율 ${c2}/${n2}.||After: proportion ${c2}/${n2}.`, `전 추정 = ${(N * c1) / n1}.||Estimate before = ${(N * c1) / n1}.`, `후 추정 = ${(N * c2) / n2}.||Estimate after = ${(N * c2) / n2}.`, `차이는 ${a}.||The difference is ${a}.`] }; } },
];
const A_INVERSE: Var[] = [
  { name: "population_from_claim", gen(rng) { const c0 = sc(rng); const n = rng.pick([40, 50, 80, 100, 125]), c = rng.int(6, Math.floor(n / 2)), k = rng.int(4, 12); const N = n * k; need(N < 1000); const E = c * k; const g = rng.pick(["The organizers claim", "A report states", "The newsletter says", "An official claims"]);
    return { s: `${g} that about ${E} ${c0.P} of ${c0.home} ${c0.tr}. The claim is based on a random sample of ${n} ${c0.P}, of whom ${c} ${c0.tr}.`, q: sp(rng, `[[How many ${c0.P} does ${c0.home} have in all?|If the claim comes exactly from the sample proportion, what is the total number of ${c0.P}?]]`), a: N, w: [E, n * c, E + n],
      p: { n, c, E }, js: "for (let N = 1; N <= 5000; N++) { if (N * P.c === P.E * P.n) return N; } throw new Error('none');", t: [`표본 비율 = ${c}/${n}.||The sample proportion is ${c}/${n}.`, `추정 인원 = 전체 × ${c}/${n} = ${E}.||Estimate = total x ${c}/${n} = ${E}.`, `전체 = ${E} × ${n}/${c}.||Total = ${E} x ${n}/${c}.`, `${E} ÷ ${c} = ${k}.`, `전체는 ${N}.||The total is ${N}.`] }; } },
  { name: "sample_count_from_claim", gen(rng) { const c0 = sc(rng); const n = rng.pick([40, 50, 60, 80, 100, 150]); const N = rng.pick([300, 400, 500, 600, 800, 900]); const f = rng.pick([20, 25, 30, 40, 50, 60]); const E = (N * f) / 100; need(isInt(E)); const a = (n * f) / 100; need(isInt(a) && a > 1);
    return { s: `An analyst says that about ${E} of the ${N} ${c0.P} of ${c0.home} ${c0.tr}. The analyst's figure was computed from a random sample of ${n} ${c0.P}.`, q: sp(rng, `[[How many of the sampled ${c0.P} ${c0.tr}?|In the sample, how many ${c0.P} ${c0.tr}, if the analyst's figure is exactly the sample proportion applied to the group?]]`), a, w: [E, f, N - E],
      p: { n, N, E }, js: "for (let c = 0; c <= P.n; c++) { if (c * P.N === P.E * P.n) return c; } throw new Error('none');", t: [`추정 비율 = ${E}/${N}.||Claimed proportion = ${E}/${N}.`, "이 비율은 표본 비율과 같다.||It equals the sample proportion.", `c/${n} = ${E}/${N}.`, `c = ${n} × ${E}/${N}.`, `표본에서 ${a} 명.||${a} sampled people.`] }; } },
  { name: "percent_from_claim", gen(rng) { const c0 = sc(rng); const N = rng.pick([200, 250, 400, 500, 800, 900]); const f = rng.pick([12, 15, 24, 35, 36, 45, 48, 64, 72, 85]); const E = (N * f) / 100; need(isInt(E)); const g = rng.pick(["a poll", "a mail survey", "a phone survey", "an online sample"]);
    return { s: `Using ${g} of randomly chosen ${c0.P}, a researcher reports that about ${E} of the ${N} ${c0.P} of ${c0.home} ${c0.tr}.`, q: sp(rng, `[[The researcher's estimate corresponds to what percent of the ${c0.P}?|What percent of all ${N} ${c0.P} does the reported estimate represent?]]`), a: f, w: [E, N - E, 100 - f],
      p: { N, E }, js: "for (let f = 0; f <= 100; f++) { if (f * P.N === 100 * P.E) return f; } throw new Error('none');", t: [`추정 인원 ${E}, 전체 ${N}.||Estimate ${E}, total ${N}.`, `비율 = ${E}/${N}.||Fraction = ${E}/${N}.`, "100 을 곱해 퍼센트로 바꾼다.||Multiply by 100 to get a percent.", `${E} × 100 ÷ ${N}.`, `답은 ${f}%.||The answer is ${f}%.`] }; } },
  { name: "sample_size_from_percent", gen(rng) { const c0 = sc(rng); const f = rng.pick([20, 25, 40, 50, 60, 75]); const n = rng.pick([40, 60, 80, 100, 120, 160, 200, 240]); const c = (n * f) / 100; need(isInt(c) && c > 4);
    return { s: `A pollster reports that ${f}% of the ${c0.P} in a random sample ${c0.tr}. In all, ${c} ${c0.P} in the sample ${c0.tr}. The poll was about ${c0.home}.`, q: sp(rng, `[[How many ${c0.P} were in the sample?|What was the sample size?]]`), a: n, w: [c * f, 100 - f, c + f],
      p: { c, f }, js: "for (let n = 1; n <= 2000; n++) { if (n * P.f === 100 * P.c) return n; } throw new Error('none');", t: [`표본의 ${f}% 가 ${c} 명이다.||${f}% of the sample is ${c} people.`, `n × ${f}/100 = ${c}.`, `n = ${c} × 100 ÷ ${f}.`, `${c} ÷ ${f / 100}.`, `표본 크기는 ${n}.||The sample size is ${n}.`] }; } },
  { name: "missing_stratum_size", gen(rng) { const c0 = sc(rng); const n1 = rng.pick([20, 25, 40, 50]), n2 = rng.pick([20, 25, 40, 50]); const k1 = rng.int(4, 12), c1 = rng.int(5, n1 - 5), c2 = rng.int(5, n2 - 4), k2 = rng.int(3, 10); const N1 = n1 * k1; need(N1 < 1000 && n2 * k2 < 1000); const total = c1 * k1 + c2 * k2; const a = n2 * k2;
    return { s: `A town's ${c0.P} live in two districts. A random sample of ${n1} ${c0.P} from the first district, which has ${N1} ${c0.P}, found that ${c1} ${c0.tr}. A random sample of ${n2} ${c0.P} from the second district found that ${c2} ${c0.tr}. A report says that about ${total} ${c0.P} in the two districts together ${c0.tr}.`, q: sp(rng, `[[According to the report, how many ${c0.P} live in the second district?|If the report's estimate is exact, what is the population of the second district?]]`), a, w: [total - c1 * k1, N1, c2 * k2],
      p: { n1, n2, N1, c1, c2, total }, js: "const rest = P.total - P.c1 * P.N1 / P.n1; for (let N2 = 1; N2 <= 2000; N2++) { if (N2 * P.c2 === rest * P.n2) return N2; } throw new Error('none');", t: [`첫 지역 추정 = ${N1} × ${c1}/${n1} = ${c1 * k1}.||District 1 estimate = ${c1 * k1}.`, `둘째 지역 추정 = ${total} − ${c1 * k1} = ${total - c1 * k1}.||District 2 estimate = ${total} - ${c1 * k1}.`, `둘째 지역 비율 = ${c2}/${n2}.||District 2 proportion = ${c2}/${n2}.`, `N2 × ${c2}/${n2} = ${total - c1 * k1}.`, `N2 = ${a}.`] }; } },
];
const A_COMPARE: Var[] = [
  { name: "estimated_count_gap", gen(rng) { const c0 = sc(rng); const n1 = rng.pick([40, 50, 80]), n2 = rng.pick([25, 50, 100]); const k1 = rng.int(5, 12), k2 = rng.int(3, 9); const c1 = rng.int(8, n1 - 8), c2 = rng.int(6, n2 - 5); const N1 = n1 * k1, N2 = n2 * k2; need(N1 < 1000 && N2 < 1000); const a = Math.abs(c1 * k1 - c2 * k2); need(a > 3);
    return { s: `Two groups of ${c0.P} connected with ${c0.home} were studied. Group X has ${N1} ${c0.P}; a random sample of ${n1} of them found that ${c1} ${c0.tr}. Group Y has ${N2} ${c0.P}; a random sample of ${n2} of them found that ${c2} ${c0.tr}.`, q: sp(rng, `[[By how many does the estimated number of ${c0.P} who ${c0.tr} differ between the two groups?|What is the difference between the two groups in the estimated number of ${c0.P} who ${c0.tr}?]]`), a, w: [Math.abs(c1 - c2), Math.abs(N1 - N2), Math.abs(c1 / n1 - c2 / n2) * 100],
      p: { n1, n2, N1, N2, c1, c2 }, js: "const x = P.c1 * (P.N1 / P.n1), y = P.c2 * (P.N2 / P.n2); return Math.max(x, y) - Math.min(x, y);", t: [`X: ${N1} × ${c1}/${n1} = ${c1 * k1}.`, `Y: ${N2} × ${c2}/${n2} = ${c2 * k2}.`, "각 지점을 따로 추정한다(표본 크기와 지점 크기가 다르므로).||Estimate each branch separately because sizes differ.", "두 추정값의 차를 구한다.||Take the difference.", `답은 ${a}.||The difference is ${a}.`] }; } },
  { name: "percentage_point_gap", gen(rng) { const c0 = sc(rng); const n1 = rng.pick([50, 80, 100, 200]), n2 = rng.pick([40, 50, 100, 250]); const p1 = rng.pick([20, 25, 30, 35, 40]), p2 = rng.pick([45, 50, 55, 60, 65, 70]); const c1 = (n1 * p1) / 100, c2 = (n2 * p2) / 100; need(isInt(c1) && isInt(c2)); const a = p2 - p1;
    return { s: `Two independent random samples were taken before and after a policy change. Before the change, ${c1} of ${n1} sampled ${c0.P} ${c0.tr}. After the change, ${c2} of ${n2} sampled ${c0.P} ${c0.tr}.`, q: sp(rng, `[[By how many percentage points did the sample percent of ${c0.P} who ${c0.tr} change?|What is the change, in percentage points, between the two sample percents?]]`), a, w: [c2 - c1, (c2 * 100) / (n1 + n2), Math.round(((p2 - p1) * 100) / p1)],
      p: { n1, n2, c1, c2 }, js: "const before = 100 * P.c1 / P.n1, after = 100 * P.c2 / P.n2; return Math.round(after - before);", t: [`전 비율 = ${c1}/${n1} = ${p1}%.||Before: ${c1}/${n1} = ${p1}%.`, `후 비율 = ${c2}/${n2} = ${p2}%.||After: ${c2}/${n2} = ${p2}%.`, "표본 크기가 달라도 퍼센트로 비교한다.||Compare as percents because sample sizes differ.", `${p2} − ${p1}.`, `답은 ${a} 퍼센트포인트.||The change is ${a} percentage points.`] }; } },
  { name: "relative_increase", gen(rng) { const c0 = sc(rng); const n = rng.pick([100, 200, 250]); const c1 = rng.pick([20, 25, 40, 50, 60, 80]), up = rng.pick([20, 25, 40, 50, 60, 75, 100]); const c2 = (c1 * (100 + up)) / 100; need(isInt(c2) && c2 < n * 0.9);
    return { s: `A random sample of ${n} ${c0.P} in one year showed that ${c1} ${c0.tr}. In the next year, another random sample of ${n} ${c0.P} showed that ${c2} ${c0.tr}.`, q: sp(rng, `[[By what percent did the number of sampled ${c0.P} who ${c0.tr} increase from the first year to the second?|The count of sampled ${c0.P} who ${c0.tr} grew by what percent?]]`), a: up, w: [((c2 - c1) * 100) / n, c2 - c1, ((c2 - c1) * 100) / c2],
      p: { n, c1, c2 }, js: "let pct = 0; while (P.c1 * (100 + pct + 1) <= P.c2 * 100) pct++; return pct;", t: [`증가량 = ${c2} − ${c1} = ${c2 - c1}.||Increase = ${c2 - c1}.`, "증가율은 처음 값(첫해)을 기준으로 한다.||Percent increase is relative to the first-year count.", `(${c2 - c1}) ÷ ${c1}.`, "100 을 곱한다.||Multiply by 100.", `답은 ${up}%.||The increase is ${up}%.`] }; } },
  { name: "plan_cost_difference", gen(rng) { const c0 = sc(rng); const n = rng.pick([40, 50, 100]), k = rng.int(5, 12), c = rng.int(8, Math.floor(n / 2)); const N = n * k; need(N < 1000); const d = rng.pick([4, 5, 6, 8, 10]), F = rng.pick([300, 400, 500, 600, 800]); const a = c * k * d - F; need(a > 0);
    return { s: `${RS(rng)} of ${n} ${c0.P} from ${N} ${c0.P} of ${c0.home} showed that ${c} ${c0.P} ${c0.tr}. Plan A pays ${d} dollars for each of the ${c0.P} who ${c0.tr}. Plan B costs a flat ${F} dollars.`, q: sp(rng, `[[Based on the sample, how many more dollars would Plan A cost than Plan B?|By the sample estimate, Plan A costs how many dollars more than Plan B?]]`), a, w: [c * d - F, N * d - F, c * k * d],
      p: { n, c, N, d, F }, js: "const people = P.c * P.N / P.n; return people * P.d - P.F;", t: [`추정 인원 = ${N} × ${c}/${n} = ${c * k}.||Estimated qualifying people = ${c * k}.`, `플랜 A 비용 = ${c * k} × ${d} = ${c * k * d}.||Plan A cost = ${c * k * d}.`, `플랜 B 는 정액 ${F}.||Plan B is a flat ${F}.`, `${c * k * d} − ${F}.`, `답은 ${a}.||Plan A costs ${a} more.`] }; } },
  { name: "least_population_for_target", gen(rng) { const c0 = sc(rng); const n = rng.pick([50, 80, 100, 150]), c = rng.int(7, Math.floor(n * 0.45)); const T = rng.pick([250, 300, 400, 500, 600, 700]); let a = Math.ceil((T * n) / c); need(a < 1000 && a > T); 
    return { s: `In a random sample of ${n} ${c0.P}, ${c} ${c0.tr}. An organizer wants the estimate of the number of ${c0.P} who ${c0.tr} to be at least ${T} in a group with unknown size.`, q: sp(rng, `[[Assuming the sample proportion holds, what is the least whole number of ${c0.P} the group could have for the estimate to reach ${T}?|What is the smallest possible size of the group for the estimate to be at least ${T}?]]`), a, w: [Math.floor((T * n) / c), Math.round(T * c / n), T + n],
      p: { n, c, T }, js: "for (let N = 1; N <= 3000; N++) { if (N * P.c >= P.T * P.n) return N; } throw new Error('none');", t: [`표본 비율 ${c}/${n}.||Sample proportion ${c}/${n}.`, `N × ${c}/${n} ≥ ${T}.`, `N ≥ ${(T * n) / c}.`, "N 은 정수이므로 올림한다.||N is a whole number, so round up.", `최솟값 ${a}.||The least size is ${a}.`] }; } },
];

// ───────── kind B: experiment_effect_calc — 실험(무작위 배정) 결과로 처치 효과를 수량으로 평가 ─────────
type Bn = { who: string; tr: string; ok: string }; type Nm = { who: string; tr: string; m: string; u: string };
const BIN: Bn[] = [
  { who: "patients", tr: "a new stretching routine", ok: "reported less back pain" }, { who: "students", tr: "a weekly tutoring program", ok: "raised their grade by one letter" },
  { who: "employees", tr: "a standing desk", ok: "reported higher energy at work" }, { who: "runners", tr: "a new warm-up routine", ok: "finished without an injury" },
  { who: "gym members", tr: "a nutrition plan", ok: "reached their weight goal" }, { who: "volunteers", tr: "a sleep-hygiene class", ok: "fell asleep within twenty minutes" },
];
const NUM: Nm[] = [
  { who: "participants", tr: "a vocabulary app", m: "points on a vocabulary test", u: "points" }, { who: "students", tr: "a new study technique", m: "points on the final exam", u: "points" },
  { who: "adults", tr: "a walking program", m: "minutes of exercise per day", u: "minutes" }, { who: "cyclists", tr: "interval training", m: "minutes on a 20-mile ride", u: "minutes" },
  { who: "patients", tr: "a relaxation course", m: "hours of sleep per week", u: "hours" }, { who: "clerks", tr: "a new filing system", m: "files processed per hour", u: "files" },
];
const bn = (rng: Rng) => rng.pick(BIN), nm = (rng: Rng) => rng.pick(NUM);
const RA = (rng: Rng) => sp(rng, "[[were randomly assigned|were assigned by a random number generator|were placed by lottery]]");
const B_COMPOSE: Var[] = [
  { name: "mean_difference", gen(rng) { const c0 = nm(rng); const n1 = rng.pick([4, 5, 6, 8, 10]), n2 = rng.pick([4, 5, 6, 8, 10]); const m2 = rng.int(40, 80), d = rng.int(3, 15), m1 = m2 + d; const S1 = n1 * m1, S2 = n2 * m2; need(S1 < 1000);
    return { s: `${n1 + n2} ${c0.who} ${RA(rng)} to use ${c0.tr} (${n1} ${c0.who}) or not to use it (${n2} ${c0.who}). The ${n1} ${c0.who} who used it totaled ${S1} ${c0.m}; the other ${n2} totaled ${S2} ${c0.m}.`, q: sp(rng, `[[By how many ${c0.u} does the mean for the group that used ${c0.tr} exceed the mean for the other group?|What is the difference between the two group means, in ${c0.u}?]]`), a: d, w: [S1 - S2, Math.round((S1 - S2) / (n1 + n2)), m1],
      p: { n1, n2, S1, S2 }, js: "let m1 = 0, m2 = 0; for (let v = 0; v <= 200; v++) { if (v * P.n1 === P.S1) m1 = v; if (v * P.n2 === P.S2) m2 = v; } return m1 - m2;", t: [`처치군 평균 = ${S1}/${n1} = ${m1}.||Treatment mean = ${S1}/${n1} = ${m1}.`, `비교군 평균 = ${S2}/${n2} = ${m2}.||Comparison mean = ${m2}.`, "합계가 아니라 평균을 비교한다(집단 크기가 다르다).||Compare means, not totals, since group sizes differ.", `${m1} − ${m2}.`, `답은 ${d}.||The difference is ${d}.`] }; } },
  { name: "extra_cases_if_all_treated", gen(rng) { const c0 = bn(rng); const n = rng.pick([40, 50, 80, 100]), k = rng.int(4, 12); const c1 = rng.int(Math.ceil(n * 0.4), Math.floor(n * 0.7)), c2 = rng.int(Math.ceil(n * 0.15), c1 - 5); const N = n * k; need(N < 1000); const a = (c1 - c2) * k;
    return { s: `In an experiment, ${2 * n} ${c0.who} ${RA(rng)} to either ${c0.tr} or a control group, ${n} per group. Of those who used ${c0.tr}, ${c1} ${c0.ok}; in the control group, ${c2} ${c0.ok}.`, q: sp(rng, `[[If ${N} similar ${c0.who} all used ${c0.tr}, about how many more of them would be expected to be among those who ${c0.ok} than if none used it?|For ${N} similar ${c0.who}, estimate how many additional ones would be among those who ${c0.ok} because of ${c0.tr}.]]`), a, w: [c1 - c2, (N * c1) / n, N * c2 / n],
      p: { n, c1, c2, N }, js: "const t = P.c1 / P.n, c = P.c2 / P.n; return Math.round((t - c) * P.N);", t: [`처치군 비율 ${c1}/${n}.||Treatment rate ${c1}/${n}.`, `비교군 비율 ${c2}/${n}.||Control rate ${c2}/${n}.`, "무작위 배정이므로 비율의 차를 처치 효과로 본다.||Random assignment lets the difference in rates estimate the effect.", `차 = ${(c1 - c2)}/${n} 를 ${N} 에 곱한다.||Multiply the difference ${(c1 - c2)}/${n} by ${N}.`, `답은 ${a}.||The answer is ${a}.`] }; } },
  { name: "pooled_mean", gen(rng) { const c0 = nm(rng); const n1 = rng.pick([4, 6, 8, 12]), n2 = rng.pick([2, 4, 6, 12]); const m1 = rng.int(50, 90), m2 = rng.int(50, 90); need(m1 !== m2); const a = (n1 * m1 + n2 * m2) / (n1 + n2); need(isInt(a));
    return { s: `A researcher recorded ${c0.m} for two groups of ${c0.who} who used ${c0.tr}. The ${n1} ${c0.who} in the morning session had a mean of ${m1}, and the ${n2} ${c0.who} in the evening session had a mean of ${m2}.`, q: sp(rng, `[[What is the mean of all ${n1 + n2} ${c0.who} combined?|What was the overall mean for the ${n1 + n2} ${c0.who} taken together?]]`), a, w: [(m1 + m2) / 2, m1 + m2, Math.abs(m1 - m2)],
      p: { n1, n2, m1, m2 }, js: "let sum = 0, cnt = 0; for (let i = 0; i < P.n1; i++) { sum += P.m1; cnt++; } for (let i = 0; i < P.n2; i++) { sum += P.m2; cnt++; } return sum / cnt;", t: [`아침 합계 = ${n1} × ${m1}.||Morning total = ${n1} x ${m1}.`, `저녁 합계 = ${n2} × ${m2}.||Evening total = ${n2} x ${m2}.`, "두 평균을 단순 평균하지 않고 인원으로 가중한다.||Weight by group size rather than averaging the two means.", `(${n1 * m1} + ${n2 * m2}) ÷ ${n1 + n2}.`, `답은 ${a}.||The combined mean is ${a}.`] }; } },
  { name: "difference_in_differences", gen(rng) { const c0 = nm(rng); const bT = rng.int(40, 70), bC = rng.int(40, 70), gT = rng.int(6, 20), gC = rng.int(1, 5); const a = gT - gC; const aT = bT + gT, aC = bC + gC;
    return { s: `Participants ${RA(rng)} to use ${c0.tr} (treatment) or not (control). The mean of ${c0.m} was ${bT} for the treatment group and ${bC} for the control group before the study. After the study, the means were ${aT} for the treatment group and ${aC} for the control group.`, q: sp(rng, `[[How many ${c0.u} more did the treatment group's mean rise than the control group's mean?|By how many ${c0.u} did the treatment group's improvement exceed the control group's improvement?]]`), a, w: [aT - aC, gT, aC - bC],
      p: { bT, bC, aT, aC }, js: "return (P.aT - P.bT) - (P.aC - P.bC);", t: [`처치군 변화 = ${aT} − ${bT} = ${gT}.||Treatment change = ${gT}.`, `비교군 변화 = ${aC} − ${bC} = ${gC}.||Control change = ${gC}.`, "두 집단의 시작 값이 달랐으므로 사후 평균이 아니라 변화량을 비교한다.||The groups started differently, so compare changes, not final means.", `${gT} − ${gC}.`, `답은 ${a}.||The extra rise is ${a}.`] }; } },
  { name: "mean_after_removing_error", gen(rng) { const c0 = nm(rng); const n = rng.pick([5, 6, 8, 9, 11]); const m = rng.int(30, 70); const o = rng.pick([5, 9, 150, 160, 180, 200]); const rest = (n - 1) * m; const T = rest + o; need(T < 1000 && o !== m); 
    return { s: `For ${n} ${c0.who} who used ${c0.tr}, the recorded ${c0.m} added up to ${T}. One recorded value, ${o}, was found to be a data-entry error and must be removed.`, q: sp(rng, `[[What is the mean of the remaining ${n - 1} values?|After the erroneous value is removed, what is the mean of the other ${n - 1} values?]]`), a: m, w: [T / n, T / (n - 1), (T - o) / n],
      p: { n, T, o }, js: "return (P.T - P.o) / (P.n - 1);", t: [`전체 합 ${T}.||The total is ${T}.`, `오류값 ${o} 을 합에서 뺀다.||Remove the error ${o} from the total.`, `${T} − ${o} = ${rest}.`, `남은 값은 ${n - 1} 개이다.||${n - 1} values remain.`, `${rest} ÷ ${n - 1} = ${m}.`] }; } },
];
const B_CHAIN: Var[] = [
  { name: "assignment_ratio_expected", gen(rng) { const c0 = bn(rng); const [r, s] = rng.pick([[1, 1], [2, 1], [3, 2], [1, 3], [3, 1], [2, 3]]); const u = rng.pick([20, 30, 40, 60, 100]); const N = (r + s) * u; need(N < 1000); const p = rng.pick([20, 25, 40, 50, 60, 75]); const a = (r * u * p) / 100; need(isInt(a));
    return { s: `${N} ${c0.who} ${RA(rng)} to ${c0.tr} or to a control group in the ratio ${r} to ${s}. Based on an earlier trial, ${p}% of those who use ${c0.tr} are expected to have ${c0.ok.replace(/^reported /, "reported ")}.`, q: sp(rng, `[[How many ${c0.who} in the treatment group are expected to have ${c0.ok.replace(/^reported /, "reported ")}?|About how many of the ${c0.who} assigned to ${c0.tr} would be expected to have ${c0.ok.replace(/^reported /, "reported ")}?]]`), a, w: [(N * p) / 100, r * u, (s * u * p) / 100],
      p: { N, r, s, p }, js: "const groupSize = P.N * P.r / (P.r + P.s); return groupSize * P.p / 100;", t: [`비 ${r}:${s} 이므로 처치군은 전체의 ${r}/${r + s}.||The treatment share is ${r}/${r + s}.`, `처치군 인원 = ${N} × ${r}/${r + s} = ${r * u}.||Treatment group size = ${r * u}.`, `그중 ${p}% 가 해당한다.||${p}% of them are expected to qualify.`, `${r * u} × ${p}%.`, `답은 ${a}.||The answer is ${a}.`] }; } },
  { name: "completers_percent", gen(rng) { const c0 = bn(rng); const n = rng.pick([50, 60, 80, 90, 100, 120]), d = rng.pick([10, 12, 20, 30]); const left = n - d; const f = rng.pick([20, 25, 40, 50, 60, 75]); const c = (left * f) / 100; need(isInt(c) && c > 3 && left > 0);
    return { s: `In an experiment, ${n} ${c0.who} ${RA(rng)} to ${c0.tr}. ${d} of them dropped out before the end. Among the ${c0.who} who finished, ${c} ${c0.ok}.`, q: sp(rng, `[[What percent of the completers ${c0.ok}?|Among those who completed the study, what percent ${c0.ok}?]]`), a: f, w: [(c * 100) / n, (c * 100) / d, 100 - f],
      p: { n, d, c }, js: "const done = P.n - P.d; for (let f = 0; f <= 100; f++) { if (f * done === 100 * P.c) return f; } throw new Error('none');", t: [`끝까지 한 인원 = ${n} − ${d} = ${left}.||Completers = ${n} - ${d} = ${left}.`, `분모는 ${n} 이 아니라 ${left}.||The denominator is ${left}, not ${n}.`, `${c}/${left}.`, "100 을 곱해 퍼센트로.||Multiply by 100.", `답은 ${f}%.||The answer is ${f}%.`] }; } },
  { name: "beyond_placebo", gen(rng) { const c0 = bn(rng); const n = rng.pick([100, 120, 150, 200, 250]), pt = rng.pick([50, 60, 70, 75, 80]), pc = rng.pick([20, 25, 30, 35, 40]); const a = (n * (pt - pc)) / 100; need(isInt(a));
    return { s: `${2 * n} ${c0.who} ${RA(rng)} to ${c0.tr} or to a placebo version, ${n} per group. In the treatment group, ${pt}% ${c0.ok}; in the placebo group, ${pc}% ${c0.ok}.`, q: sp(rng, `[[How many ${c0.who} in the treatment group ${c0.ok} beyond the number expected from the placebo rate?|About how many of the improvements in the treatment group are due to more than the placebo effect?]]`), a, w: [(n * pt) / 100, (n * pc) / 100, pt - pc],
      p: { n, pt, pc }, js: "const treated = P.n * P.pt / 100; const placebo = P.n * P.pc / 100; return treated - placebo;", t: [`처치군 ${n} × ${pt}% = ${(n * pt) / 100}.||Treatment: ${(n * pt) / 100}.`, `위약 비율을 같은 크기에 적용 ${n} × ${pc}% = ${(n * pc) / 100}.||Placebo rate on the same size: ${(n * pc) / 100}.`, "위약 효과를 넘는 몫만 처치의 효과로 본다.||Only the excess over placebo is credited to the treatment.", `${(n * pt) / 100} − ${(n * pc) / 100}.`, `답은 ${a}.||The answer is ${a}.`] }; } },
  { name: "subgroup_rate_gap", gen(rng) { const c0 = bn(rng); const sg = rng.pick(["women", "adults over 40", "first-time participants", "beginners"]); const nT = rng.pick([20, 25, 40, 50]), nC = rng.pick([20, 25, 40, 50]); const pT = rng.pick([40, 50, 60, 70, 80]), pC = rng.pick([10, 20, 25, 30]); const cT = (nT * pT) / 100, cC = (nC * pC) / 100; need(isInt(cT) && isInt(cC)); const a = pT - pC;
    return { s: `An experiment randomly assigned ${c0.who} to ${c0.tr} or to a control group. Among ${sg}, ${cT} of the ${nT} who used ${c0.tr} ${c0.ok}, compared with ${cC} of the ${nC} ${sg} in the control group.`, q: sp(rng, `[[Among ${sg}, by how many percentage points was the rate in the treatment group higher than in the control group?|For ${sg} only, what is the difference in percent between the two groups?]]`), a, w: [cT - cC, Math.round(((cT + cC) * 100) / (nT + nC)), pT],
      p: { nT, nC, cT, cC }, js: "return Math.round(100 * P.cT / P.nT - 100 * P.cC / P.nC);", t: [`처치군 비율 ${cT}/${nT} = ${pT}%.||Treatment rate = ${pT}%.`, `비교군 비율 ${cC}/${nC} = ${pC}%.||Control rate = ${pC}%.`, "하위집단 안에서만 비교한다.||Compare only within the subgroup.", `${pT} − ${pC}.`, `답은 ${a}.||The gap is ${a} points.`] }; } },
  { name: "paired_crossover_mean", gen(rng) { const c0 = nm(rng); const n = rng.pick([4, 5, 8, 10]); const d = rng.int(2, 9); const SB = n * rng.int(30, 60); const SA = SB - n * d; need(SB < 1000 && SA > 0);
    return { s: `In a crossover experiment, each of ${n} ${c0.who} tried a standard method and ${c0.tr}, in a random order. Across the ${n} ${c0.who}, the standard method totaled ${SB} ${c0.m} and ${c0.tr} totaled ${SA} ${c0.m}.`, q: sp(rng, `[[What is the mean difference per person (standard method minus ${c0.tr})?|On average, how many ${c0.u} per person did the standard method exceed ${c0.tr}?]]`), a: d, w: [SB - SA, SB / n, SA / n],
      p: { n, SB, SA }, js: "return P.SB / P.n - P.SA / P.n;", t: [`합계 차 = ${SB} − ${SA} = ${SB - SA}.||Difference in totals = ${SB - SA}.`, "같은 사람이 두 방법을 모두 했으므로 쌍별 차의 평균이다.||Each person did both, so average the paired differences.", `${SB - SA} ÷ ${n}.`, "인원으로 나눈다.||Divide by the number of people.", `답은 ${d}.||The mean difference is ${d}.`] }; } },
];
const B_INVERSE: Var[] = [
  { name: "other_group_mean", gen(rng) { const c0 = nm(rng); const n1 = rng.pick([4, 5, 6, 10]), n2 = rng.pick([2, 4, 5, 6]); const m1 = rng.int(50, 90), m2 = rng.int(40, 95); need(m1 !== m2); const M = (n1 * m1 + n2 * m2) / (n1 + n2); need(isInt(M));
    return { s: `The ${c0.m} of ${n1 + n2} ${c0.who} who used ${c0.tr} had an overall mean of ${M}. The first ${n1} ${c0.who} had a mean of ${m1}.`, q: sp(rng, `[[What was the mean for the remaining ${n2} ${c0.who}?|What is the mean of the other ${n2} ${c0.who}?]]`), a: m2, w: [M - m1 + M, 2 * M - m1, m1],
      p: { n1, n2, M, m1 }, js: "const total = P.M * (P.n1 + P.n2); const rest = total - P.n1 * P.m1; for (let v = 0; v <= 300; v++) { if (v * P.n2 === rest) return v; } throw new Error('none');", t: [`전체 합 = ${M} × ${n1 + n2} = ${M * (n1 + n2)}.||Overall total = ${M * (n1 + n2)}.`, `앞 집단 합 = ${n1} × ${m1} = ${n1 * m1}.||First group total = ${n1 * m1}.`, `나머지 합 = ${M * (n1 + n2)} − ${n1 * m1}.||Remaining total = ${M * (n1 + n2) - n1 * m1}.`, `나머지 평균 = 합 ÷ ${n2}.||Divide by ${n2}.`, `답은 ${m2}.||The mean is ${m2}.`] }; } },
  { name: "other_group_rate", gen(rng) { const c0 = bn(rng); const n1 = rng.pick([40, 50, 60]), n2 = rng.pick([20, 25, 40, 50]); const c1 = rng.int(8, n1 - 10), f2 = rng.pick([20, 25, 40, 50, 60, 80]); const c2 = (n2 * f2) / 100; need(isInt(c2)); const tot = c1 + c2;
    return { s: `${n1 + n2} ${c0.who} ${RA(rng)} to two versions of ${c0.tr}. In all, ${tot} ${c0.who} ${c0.ok}. In version A, ${n1} ${c0.who} took part and ${c1} of them ${c0.ok}. Version B had ${n2} ${c0.who}.`, q: sp(rng, `[[What percent of the ${c0.who} in version B ${c0.ok}?|In version B, what percent of ${c0.who} ${c0.ok}?]]`), a: f2, w: [c2, (tot * 100) / (n1 + n2), 100 - f2],
      p: { n1, n2, c1, tot }, js: "const b = P.tot - P.c1; for (let f = 0; f <= 100; f++) { if (f * P.n2 === 100 * b) return f; } throw new Error('none');", t: [`전체 해당자 ${tot}.||All qualifying: ${tot}.`, `A 의 해당자 ${c1} 을 뺀다.||Subtract A's ${c1}.`, `B 해당자 = ${tot} − ${c1} = ${c2}.||B qualifying = ${c2}.`, `${c2}/${n2}.`, `답은 ${f2}%.||The answer is ${f2}%.`] }; } },
  { name: "group_size_from_count", gen(rng) { const c0 = bn(rng); const f = rng.pick([20, 25, 40, 50, 60, 75]); const n = rng.pick([40, 60, 80, 100, 120, 160, 200]); const c = (n * f) / 100; need(isInt(c) && c > 5); 
    return { s: `In the group that used ${c0.tr}, ${f}% of the ${c0.who} ${c0.ok}, which was ${c} ${c0.who}. The ${c0.who} were randomly assigned to groups of equal size.`, q: sp(rng, `[[How many ${c0.who} were in the entire experiment, counting both groups?|What was the total number of ${c0.who} in the experiment, including the other group?]]`), a: 2 * n, w: [n, c * 2, c * f],
      p: { f, c }, js: "for (let n = 1; n <= 1000; n++) { if (n * P.f === 100 * P.c) return 2 * n; } throw new Error('none');", t: [`한 집단의 ${f}% 가 ${c} 명.||${f}% of one group is ${c} people.`, `집단 크기 = ${c} ÷ ${f / 100} = ${n}.||Group size = ${n}.`, "집단은 크기가 같다.||The two groups are equal in size.", `전체 = 2 × ${n}.||Total = 2 x ${n}.`, `답은 ${2 * n}.||The total is ${2 * n}.`] }; } },
  { name: "control_count_from_effect", gen(rng) { const c0 = bn(rng); const nc = rng.pick([40, 50, 60, 80, 100, 120]); const pt = rng.pick([50, 60, 70, 75, 80]), e = rng.pick([20, 25, 30, 35, 40]); need(pt > e + 5); const a = (nc * (pt - e)) / 100; need(isInt(a) && a > 2);
    return { s: `In a randomized experiment, ${pt}% of the ${c0.who} who used ${c0.tr} ${c0.ok}. The researchers report that this rate was ${e} percentage points higher than the rate in the control group, which had ${nc} ${c0.who}.`, q: sp(rng, `[[How many ${c0.who} in the control group ${c0.ok}?|In the control group, how many ${c0.who} ${c0.ok}?]]`), a, w: [(nc * pt) / 100, (nc * e) / 100, pt - e],
      p: { nc, pt, e }, js: "const controlRate = P.pt - P.e; let cnt = 0; for (let i = 0; i < P.nc; i++) cnt += controlRate / 100; return Math.round(cnt);", t: [`처치군 비율 ${pt}%.||Treatment rate ${pt}%.`, `비교군 비율 = ${pt} − ${e} = ${pt - e}%.||Control rate = ${pt - e}%.`, `비교군은 ${nc} 명.||The control group has ${nc} people.`, `${nc} × ${pt - e}%.`, `답은 ${a}.||The answer is ${a}.`] }; } },
  { name: "treatment_size_from_gap", gen(rng) { const c0 = bn(rng); const half = rng.pick([40, 50, 60, 75, 80, 100]), k = rng.pick([10, 20, 30]); const N = 2 * half; const a = half + k / 2; need(isInt(a) && N < 1000); const nT = N / 2 + k / 2;
    return { s: `${N} ${c0.who} ${RA(rng)} to ${c0.tr} or to a control group. The treatment group ended up with ${k} more ${c0.who} than the control group.`, q: sp(rng, `[[How many ${c0.who} were in the treatment group?|What was the size of the treatment group?]]`), a: nT, w: [N / 2, nT + k, N - k],
      p: { N, k }, js: "for (let t = 0; t <= P.N; t++) { if (t - (P.N - t) === P.k) return t; } throw new Error('none');", t: [`처치군 − 비교군 = ${k}.||Treatment minus control = ${k}.`, `처치군 + 비교군 = ${N}.||Treatment plus control = ${N}.`, `두 식을 더하면 2 × 처치군 = ${N + k}.||Adding: 2 x treatment = ${N + k}.`, `처치군 = ${(N + k)} ÷ 2.||Treatment = ${N + k} / 2.`, `답은 ${nT}.||The treatment group has ${nT}.`] }; } },
];
const B_COMPARE: Var[] = [
  { name: "dose_rate_gap", gen(rng) { const c0 = bn(rng); const n1 = rng.pick([40, 50, 80, 100]), n2 = rng.pick([25, 40, 50, 100]); const p1 = rng.pick([30, 40, 45, 50, 55]), p2 = rng.pick([60, 65, 70, 75, 80, 85]); const c1 = (n1 * p1) / 100, c2 = (n2 * p2) / 100; need(isInt(c1) && isInt(c2)); const a = p2 - p1;
    return { s: `${n1 + n2} ${c0.who} ${RA(rng)} to a low dose (${n1} ${c0.who}) or a high dose (${n2} ${c0.who}) of ${c0.tr}. ${c1} in the low-dose group and ${c2} in the high-dose group ${c0.ok}.`, q: sp(rng, `[[By how many percentage points is the high-dose rate greater than the low-dose rate?|What is the gap, in percentage points, between the two dose groups?]]`), a, w: [c2 - c1, Math.round((c2 * 100) / n1 - p1), p2],
      p: { n1, n2, c1, c2 }, js: "return Math.round(100 * P.c2 / P.n2 - 100 * P.c1 / P.n1);", t: [`저용량 ${c1}/${n1} = ${p1}%.||Low dose: ${p1}%.`, `고용량 ${c2}/${n2} = ${p2}%.||High dose: ${p2}%.`, "집단 크기가 다르므로 비율로 비교한다.||Sizes differ, so compare rates.", `${p2} − ${p1}.`, `답은 ${a}.||The gap is ${a} points.`] }; } },
  { name: "cost_per_success_gap", gen(rng) { const c0 = bn(rng); const n1 = rng.pick([20, 25, 40]), n2 = rng.pick([20, 25, 40]); const d1 = rng.pick([20, 30, 40]), d2 = rng.pick([50, 60, 80]); const s1 = pickDiv(rng, n1 * d1, 5, n1 - 5), s2 = pickDiv(rng, n2 * d2, 8, n2 - 2); const x = (n1 * d1) / s1, y = (n2 * d2) / s2; need(x !== y); const a = Math.abs(x - y);
    return { s: `Two programs were tested on separate randomly assigned groups of ${c0.who}. Program A cost ${d1} dollars per person for ${n1} ${c0.who}, and ${s1} of them ${c0.ok}. Program B cost ${d2} dollars per person for ${n2} ${c0.who}, and ${s2} of them ${c0.ok}.`, q: sp(rng, `[[What is the difference, in dollars, between the two programs in cost per ${c0.who.replace(/s$/, "")} who ${c0.ok}?|How many dollars apart are the programs' costs for each success?]]`), a, w: [Math.abs(d2 - d1), Math.abs(n1 * d1 - n2 * d2), Math.abs(s1 - s2)],
      p: { n1, n2, d1, d2, s1, s2 }, js: "const a = (P.n1 * P.d1) / P.s1, b = (P.n2 * P.d2) / P.s2; return Math.abs(a - b);", t: [`A 총비용 = ${n1} × ${d1}.||Program A total = ${n1 * d1}.`, `A 의 성공당 비용 = ${n1 * d1}/${s1} = ${x}.||A cost per success = ${x}.`, `B 총비용 = ${n2 * d2}, 성공당 ${y}.||B cost per success = ${y}.`, "성공 한 명당 비용을 비교한다.||Compare cost per success.", `답은 ${a}.||The difference is ${a}.`] }; } },
  { name: "total_time_saved", gen(rng) { const c0 = nm(rng); const mo = rng.int(20, 60), sv = rng.int(2, 9); const mn = mo - sv; const N = rng.pick([20, 50, 80, 100, 150, 200]); const a = sv * N; need(a < 5000 && mn > 5);
    return { s: `${c0.who.charAt(0).toUpperCase() + c0.who.slice(1)} were randomly assigned to work the old way or with ${c0.tr}. The mean time per task was ${mo} minutes the old way and ${mn} minutes with ${c0.tr}.`, q: sp(rng, `[[Over ${N} tasks, about how many minutes in total would be saved by using ${c0.tr}?|If ${N} tasks are done with ${c0.tr} instead of the old way, how many total minutes are saved on average?]]`), a, w: [sv, mo * N, mn * N],
      p: { mo, mn, N }, js: "let saved = 0; for (let i = 0; i < P.N; i++) saved += P.mo - P.mn; return saved;", t: [`한 건당 절약 = ${mo} − ${mn} = ${sv}.||Saving per task = ${sv}.`, "무작위 배정이므로 평균 차이를 효과로 볼 수 있다.||Random assignment lets us use the mean difference.", `${N} 건을 곱한다.||Multiply by ${N} tasks.`, `${sv} × ${N}.`, `답은 ${a} 분.||The saving is ${a} minutes.`] }; } },
  { name: "rate_ratio", gen(rng) { const c0 = bn(rng); const pc = rng.pick([10, 15, 20, 25, 30, 40]); const r = rng.pick([1.5, 2, 2.5, 3]); const pt = pc * r; need(isInt(pt) && pt <= 95); const n = rng.pick([100, 200]);  
    return { s: `${2 * n} ${c0.who} ${RA(rng)} to ${c0.tr} or to a control group, ${n} per group. In the control group, ${pc}% ${c0.ok}; in the treatment group, ${pt}% ${c0.ok}.`, q: sp(rng, `[[How many times as large is the rate in the treatment group as the rate in the control group?|The rate for ${c0.tr} is what multiple of the control group's rate?]]`), a: r, w: [pt - pc, Math.round((pt / pc) * 10) / 10 + 0.5, pt / (pt + pc)],
      p: { pc, pt }, js: "return P.pt / P.pc;", t: [`처치군 비율 ${pt}%.||Treatment rate ${pt}%.`, `비교군 비율 ${pc}%.||Control rate ${pc}%.`, "차이가 아니라 비(배수)를 묻는다.||The question asks for a ratio, not a difference.", `${pt} ÷ ${pc}.`, `답은 ${r}.||The ratio is ${r}.`] }; } },
  { name: "number_needed_to_treat", gen(rng) { const c0 = bn(rng); const d = rng.pick([4, 5, 8, 10, 20, 25]); const pc = rng.pick([10, 15, 20, 30]); const pt = pc + d; const n = rng.pick([100, 200, 250]); const a = 100 / d; need(isInt(a) && pt <= 90);
    return { s: `In a randomized trial with ${n} ${c0.who} per group, ${pt}% of the treatment group ${c0.ok}, compared with ${pc}% of the control group.`, q: sp(rng, `[[On average, how many ${c0.who} would need to use ${c0.tr} for one additional ${c0.who.replace(/s$/, "")} to ${c0.ok}?|About how many ${c0.who} must be treated to produce one extra success?]]`), a, w: [d, pt, Math.round((100 * pt) / pc)],
      p: { pt, pc }, js: "const gain = P.pt - P.pc; for (let k = 1; k <= 100; k++) { if (k * gain >= 100) return k; } throw new Error('none');", t: [`처치군 ${pt}%, 비교군 ${pc}%.||Treatment ${pt}%, control ${pc}%.`, `추가 비율 = ${d} 퍼센트포인트.||Extra rate = ${d} points.`, `100 명당 추가 성공은 ${d} 명.||Per 100 people, ${d} extra successes.`, `1 명의 추가 성공에는 100 ÷ ${d} 명이 필요하다.||One extra success needs 100/${d} people.`, `답은 ${a}.||The answer is ${a}.`] }; } },
];

// ───────── kind C: study_bias_rates — 관찰 연구·표집의 편향·비율을 수치로 평가 ─────────
const C_COMPOSE: Var[] = [
  { name: "volunteer_bias_gap", gen(rng) { const c0 = sc(rng); const pv = rng.int(45, 80), pt = rng.int(20, 40); const a = pv - pt; const nv = rng.pick([100, 150, 200, 250]);
    return { s: `A website asked its visitors to volunteer for a poll about ${c0.home}. Among the ${nv} ${c0.P} who volunteered, ${pv}% said they ${c0.tr}. A census of all ${c0.P} later showed that ${pt}% of all ${c0.P} ${c0.tr}.`, q: sp(rng, `[[By how many percentage points did the volunteer poll overstate the true percent?|How many percentage points higher was the poll result than the census value?]]`), a, w: [Math.round((nv * pv) / 100), Math.round(((pv - pt) * 100) / pt), pv],
      p: { pv, pt }, js: "return P.pv - P.pt;", t: [`자원자 조사 결과 ${pv}%.||Volunteer poll: ${pv}%.`, `전수조사 결과 ${pt}%.||Census: ${pt}%.`, "자원자는 무작위 표본이 아니므로 편향이 생긴다.||Volunteers are not a random sample, so bias appears.", `편향 = ${pv} − ${pt}.||Bias = ${pv} - ${pt}.`, `답은 ${a} 퍼센트포인트.||The poll overstated by ${a} points.`] }; } },
  { name: "undercoverage_share", gen(rng) { const N = rng.pick([400, 500, 800, 900]); const f = rng.pick([20, 25, 30, 40, 50, 60]); const F = (N * f) / 100; need(isInt(F)); const a = 100 - f; const who = rng.pick(["households", "residents", "businesses"]); const how = rng.pick(["landline telephone numbers", "an email list", "a printed directory"]);
    return { s: `A pollster draws a random sample from ${how} that covers ${F} of the ${N} ${who} in a county. ${who.charAt(0).toUpperCase() + who.slice(1)} not on it have no chance of being selected.`, q: sp(rng, `[[What percent of the ${N} ${who} have no chance of being selected?|The sampling frame misses what percent of the ${who} in the county?]]`), a, w: [N - F, f, Math.round((F * 100) / (N - F))],
      p: { N, F }, js: "let missed = 0; for (let i = 0; i < P.N - P.F; i++) missed++; return Math.round(100 * missed / P.N);", t: [`명단에 있는 ${F} 곳.||${F} are on the list.`, `명단에 없는 곳 = ${N} − ${F} = ${N - F}.||Not covered = ${N - F}.`, "표본이 무작위여도 틀 밖은 뽑힐 수 없다.||Even a random sample cannot reach units outside the frame.", `${N - F}/${N} × 100.`, `답은 ${a}%.||The answer is ${a}%.`] }; } },
  { name: "response_rate", gen(rng) { const S = rng.pick([200, 250, 400, 500, 800]); const f = rng.pick([20, 25, 30, 40, 45, 60]); const R = (S * f) / 100; need(isInt(R)); const c0 = sc(rng);
    return { s: `A survey about whether ${c0.P} ${c0.tr} was mailed to a random sample of ${S} ${c0.P} of ${c0.home}. Only ${R} ${c0.P} returned the survey.`, q: sp(rng, `[[What was the response rate, as a percent?|What percent of the ${S} selected ${c0.P} responded?]]`), a: f, w: [S - R, 100 - f, R],
      p: { S, R }, js: "for (let f = 0; f <= 100; f++) { if (f * P.S === 100 * P.R) return f; } throw new Error('none');", t: [`뽑힌 ${S} 명, 응답 ${R} 명.||${S} selected, ${R} responded.`, "응답률은 응답자 ÷ 선택된 사람 수.||Response rate = respondents / selected.", `${R}/${S}.`, "100 을 곱한다.||Multiply by 100.", `답은 ${f}%.||The rate is ${f}%.`] }; } },
  { name: "reweighted_rate", gen(rng) { const c0 = sc(rng); const w = rng.pick([20, 30, 40, 60, 70]); const r1 = rng.pick([20, 30, 40, 50, 60]), r2 = rng.pick([55, 65, 70, 75, 80, 85]); const m = rng.pick([50, 60, 70, 80]); const a = (w * r1 + (100 - w) * r2) / 100; need(isInt(a) && m !== w);
    return { s: `${m}% of the ${c0.P} in a random sample were men, but only ${w}% of all ${c0.P} in ${c0.home} are men. In the sample, ${r1}% of the men and ${r2}% of the women ${c0.tr}.`, q: sp(rng, `[[Adjusting for the actual share of men, what percent of all ${c0.P} ${c0.tr}?|If the groups are weighted by their true shares in ${c0.home}, what percent ${c0.tr}?]]`), a, w: [(m * r1 + (100 - m) * r2) / 100, (r1 + r2) / 2, w],
      p: { w, r1, r2 }, js: "let t = 0; for (let i = 0; i < 100; i++) { t += i < P.w ? P.r1 : P.r2; } return t / 100;", t: [`실제 남성 비율 ${w}%, 여성 ${100 - w}%.||True shares: ${w}% men, ${100 - w}% women.`, `남성 기여 = ${w}% × ${r1}% = ${(w * r1) / 100}.||Men contribute ${(w * r1) / 100}.`, `여성 기여 = ${100 - w}% × ${r2}% = ${((100 - w) * r2) / 100}.||Women contribute ${((100 - w) * r2) / 100}.`, "표본의 성비가 아닌 실제 비율로 가중한다.||Weight by true shares, not sample shares.", `합 = ${a}.`] }; } },
];
const C_CHAIN: Var[] = [
  { name: "expected_false_alarms", gen(rng) { const k = rng.pick([20, 40, 50, 60, 80, 100, 120]), al = rng.pick([5, 10]); const a = (k * al) / 100; need(isInt(a) && a >= 2); const f = rng.pick(["foods", "supplements", "websites", "exercise habits"]);
    return { s: sp(rng, `[[A researcher independently tests|A lab runs separate tests on|An analyst checks, one at a time,]] ${k} different ${f} for a link to [[sleep quality|stress levels|test scores|mood]]. [[For each test, there is a ${al}% chance of reporting a link even when none exists.|Each test falsely reports a link ${al}% of the time when no link is present.|Whenever no real link exists, a test still reports one with probability ${al}%.]] Suppose none of the ${k} ${f} is actually linked.`), q: sp(rng, `[[How many of the tests are expected to report a link anyway?|On average, how many false links would the ${k} tests report?]]`), a, w: [al, k - a, k / al],
      p: { k, al }, js: "let expected = 0; for (let i = 0; i < P.k; i++) expected += P.al / 100; return Math.round(expected);", t: [`검정 ${k} 회, 각각 ${al}% 로 거짓 양성.||${k} tests, each with a ${al}% false-alarm chance.`, "실제 연관이 없어도 우연히 연관이 보고된다.||A link can be reported by chance alone.", "기댓값 = 검정 수 × 확률.||Expected = tests x probability.", `${k} × ${al}%.`, `답은 ${a}.||The expected number is ${a}.`] }; } },
  { name: "systematic_sample_size", gen(rng) { const k = rng.pick([5, 8, 10, 12, 20, 25]), m = rng.int(8, 40); const N = k * m; need(N < 1000); const who = rng.pick(["records", "invoices", "library cards", "patient files"]);
    return { s: sp(rng, `[[A clerk selects|An auditor draws|A staff member picks]] a systematic sample from ${N} ${who}: [[a starting|a first]] ${who.replace(/s$/, "")} is chosen at random among the first ${k}, and then [[every ${k}th ${who.replace(/s$/, "")} after it is chosen until the end of the list.|each ${k}th one after that is added to the sample until the list ends.|the list is walked in steps of ${k} until the end.]]`), q: sp(rng, `[[How many ${who} are in the sample?|What is the size of the sample?]]`), a: m, w: [k, N - k, N / k + 1],
      p: { N, k }, js: "let count = 0; for (let i = 1; i <= P.N; i++) { if (i % P.k === 0) count++; } return count;", t: [`${N} 개를 ${k} 개씩 묶는다.||Group the ${N} items into blocks of ${k}.`, "한 묶음에서 하나씩 뽑는다.||One item is taken from each block.", `묶음 수 = ${N} ÷ ${k}.||Number of blocks = ${N}/${k}.`, `${m}.`, `답은 ${m}.||The sample has ${m}.`] }; } },
  { name: "cluster_coverage", gen(rng) { const s = rng.pick([20, 25, 30, 40]), c = rng.pick([2, 3, 4, 5]), N = rng.pick([400, 500, 600, 800]); const a = (c * s * 100) / N; need(isInt(a) && a >= 5); const grp = rng.pick(["classrooms", "dorm floors", "church groups", "clinics"]);
    return { s: sp(rng, `[[A school has|A district office oversees|A college serves]] ${N} students. [[A researcher randomly selects|The survey team randomly picks|A planner chooses at random]] ${c} ${grp} and [[surveys every student in each selected one.|asks every student in each of them to respond.|includes all students of the chosen ones.]] [[Each selected one has ${s} students.|Every one of them has ${s} students.|The ${grp} are all of size ${s}.]]`), q: sp(rng, `[[What percent of all ${N} students are surveyed?|The survey reaches what percent of the school's ${N} students?]]`), a, w: [c * s, (c * 100) / s, a * 2],
      p: { c, s, N }, js: "let surveyed = 0; for (let i = 0; i < P.c; i++) surveyed += P.s; return Math.round(100 * surveyed / P.N);", t: [`선택된 집단 ${c} 개.||${c} groups selected.`, `각 집단 ${s} 명 전수 조사.||Every one of the ${s} students in each is surveyed.`, `조사 인원 = ${c} × ${s} = ${c * s}.||Surveyed = ${c * s}.`, `${c * s}/${N}.`, `답은 ${a}%.||The answer is ${a}%.`] }; } },
  { name: "proportional_allocation", gen(rng) { const u = rng.pick([40, 50, 60, 100]); const [a1, a2, a3] = rng.pick([[2, 3, 5], [1, 2, 2], [3, 3, 4], [1, 1, 3]]); const n = rng.pick([40, 50, 100, 200]); const N = (a1 + a2 + a3) * u; const a = (n * a2) / (a1 + a2 + a3); need(isInt(a) && N < 1000); const nm3 = rng.pick([["freshmen", "juniors", "seniors"], ["north", "central", "south"], ["day", "evening", "weekend"]]);
    return { s: sp(rng, `[[A college has|A school enrolls|An academy lists]] ${a1 * u} ${nm3[0]} students, ${a2 * u} ${nm3[1]} students, and ${a3 * u} ${nm3[2]} students. [[A stratified random sample of ${n} students is allocated in proportion to the number of students in each group.|A survey of ${n} students is split among the three groups in proportion to their sizes, with random selection inside each group.|The ${n} sampled students are divided across the groups in proportion to each group's enrollment.]]`), q: sp(rng, `[[How many ${nm3[1]} students should be in the sample?|The ${nm3[1]} group should contribute how many of the ${n} sampled students?]]`), a, w: [n / 3, a2 * u, (n * a1) / (a1 + a2 + a3)],
      p: { n, g1: a1 * u, g2: a2 * u, g3: a3 * u }, js: "const total = P.g1 + P.g2 + P.g3; for (let k = 0; k <= P.n; k++) { if (k * total === P.n * P.g2) return k; } throw new Error('none');", t: [`전체 ${N} 명.||The total is ${N}.`, `${nm3[1]} 비율 = ${a2 * u}/${N}.||Share = ${a2 * u}/${N}.`, "비례 배분이므로 표본에도 같은 비율.||Proportional allocation keeps the same share.", `${n} × ${a2 * u}/${N}.`, `답은 ${a}.||The group gets ${a}.`] }; } },
];
const C_INVERSE: Var[] = [
  { name: "mailed_from_response_rate", gen(rng) { const R = rng.pick([60, 75, 90, 120, 150]); const f = rng.pick([20, 25, 30, 40, 50, 60]); const S = (R * 100) / f; need(isInt(S) && S < 1000); const c0 = sc(rng);
    return { s: `${R} ${c0.P} of ${c0.home} returned a mailed survey about whether they ${c0.tr}. The response rate was ${f}%.`, q: sp(rng, `[[How many ${c0.P} were sent the survey?|How many surveys were mailed in all?]]`), a: S, w: [R * f, R + f, S - R],
      p: { R, f }, js: "for (let S = 1; S <= 5000; S++) { if (S * P.f === 100 * P.R) return S; } throw new Error('none');", t: [`응답 ${R} 명 = 발송의 ${f}%.||${R} responses = ${f}% of those mailed.`, `S × ${f}/100 = ${R}.`, `S = ${R} ÷ ${f / 100}.`, "응답률의 분모는 발송 수.||The denominator of a response rate is the number mailed.", `답은 ${S}.||${S} were mailed.`] }; } },
  { name: "nonvolunteers_count", gen(rng) { const n = rng.pick([80, 100, 150, 200, 250]), f = rng.pick([20, 30, 40, 60, 70]); const v = (n * f) / 100; need(isInt(v)); const a = n - v; const c0 = sc(rng);
    return { s: `A radio show invites ${c0.P} to call in about whether they ${c0.tr}. ${f}% of the ${n} callers said they do. Everyone else who called said they do not.`, q: sp(rng, `[[How many callers said they do not?|How many of the ${n} callers gave the opposite answer?]]`), a, w: [v, f, n + v],
      p: { n, f }, js: "let yes = 0; for (let i = 0; i < P.n; i++) { if (i * 100 < P.n * P.f) yes++; } return P.n - yes;", t: [`찬성 비율 ${f}%.||${f}% said yes.`, `찬성 = ${n} × ${f}% = ${v}.||Yes = ${v}.`, "전화 참여자는 자발적 표본이라 일반화는 못 하지만 이 표본의 수는 셀 수 있다.||Callers are self-selected, but we can still count within this group.", `${n} − ${v}.`, `답은 ${a}.||The answer is ${a}.`] }; } },
  { name: "unexposed_rate_from_table", gen(rng) { const n = rng.pick([100, 200, 250, 400]); const e = rng.pick([40, 50, 60, 80, 100, 150]); need(e < n); const ue = n - e; const rate = rng.pick([10, 20, 25, 30, 40]); const bu = (ue * rate) / 100; need(isInt(bu) && bu > 2); const rate2 = rng.pick([40, 50, 60]); const be = (e * rate2) / 100; need(isInt(be) && be > 2); const o = bu + be; const out = rng.pick(["a cold", "a headache", "poor sleep", "a stomachache"]), [ex, nex] = rng.pick([["drank coffee daily", "did not drink coffee daily"], ["ate breakfast", "skipped breakfast"], ["used a phone at night", "did not use a phone at night"], ["exercised", "did not exercise"]]);
    return { s: `An observational study followed ${n} adults. ${e} of them ${ex}, and ${o} adults in all reported ${out}. Among the adults who ${ex}, ${be} reported ${out}.`, q: sp(rng, `[[What percent of the adults who ${nex} reported ${out}?|Among the adults who ${nex}, what percent reported ${out}?]]`), a: rate, w: [(o * 100) / n, rate2, Math.round((bu * 100) / o)],
      p: { n, e, o, be }, js: "const unexposedTotal = P.n - P.e; const unexposedCases = P.o - P.be; for (let f = 0; f <= 100; f++) { if (f * unexposedTotal === 100 * unexposedCases) return f; } throw new Error('none');", t: [`노출 ${e} 명, 비노출 ${ue} 명.||${e} exposed, ${ue} not.`, `전체 증상자 ${o}, 노출 중 ${be}.||${o} total cases, ${be} among exposed.`, `비노출 증상자 = ${o} − ${be} = ${bu}.||Unexposed cases = ${bu}.`, `${bu}/${ue}.`, `답은 ${rate}%.||The rate is ${rate}%.`] }; } },
  { name: "sample_for_expected_cases", gen(rng) { const p = rng.pick([2, 4, 5, 8, 10, 20]); const k = rng.pick([6, 10, 12, 15, 20, 30]); const a = (100 * k) / p; need(isInt(a) && a < 1000);
    const dz = rng.pick(["a rare allergy", "color blindness", "left-handedness", "a particular gene variant"]);
    return { s: `${dz.charAt(0).toUpperCase() + dz.slice(1)} affects about ${p}% of people. A researcher plans to study ${dz} using a random sample.`, q: sp(rng, `[[How many people must be sampled to expect ${k} people with ${dz} in the sample?|What sample size is expected to include ${k} people with ${dz}?]]`), a, w: [k * p, k + p, a / 2],
      p: { p, k }, js: "for (let n = 1; n <= 5000; n++) { if (n * P.p === 100 * P.k) return n; } throw new Error('none');", t: [`사건 비율 ${p}%.||The prevalence is ${p}%.`, `n × ${p}% = ${k}.`, `n = ${k} ÷ ${p / 100}.`, "기댓값을 맞추는 표본 크기를 구한다.||Solve for the sample size that gives the expected count.", `답은 ${a}.||The sample size is ${a}.`] }; } },
];
const C_COMPARE: Var[] = [
  { name: "overall_rate_by_group", gen(rng) { const n1 = rng.pick([20, 40, 60, 80, 100]), n2 = rng.pick([20, 40, 60, 100, 120]); const s1 = rng.int(5, n1 - 5), s2 = rng.int(5, n2 - 5); const a = (100 * (s1 + s2)) / (n1 + n2); need(isInt(a)); const nm2 = rng.pick([["Hospital A", "mild cases", "severe cases"], ["Clinic X", "younger patients", "older patients"], ["Program 1", "beginners", "advanced students"]]);
    return { s: `${nm2[0]} treated ${n1} ${nm2[1]} and ${n2} ${nm2[2]}. It had ${s1} successes among the ${nm2[1]} and ${s2} successes among the ${nm2[2]}.`, q: sp(rng, `[[What was ${nm2[0]}'s overall success rate, as a percent?|Across both groups combined, what percent of cases at ${nm2[0]} were successes?]]`), a, w: [(s1 * 100) / n1 + (s2 * 100) / n2, (100 * s1) / n1, Math.round(((100 * s1) / n1 + (100 * s2) / n2) / 2)],
      p: { n1, n2, s1, s2 }, js: "let s = 0, n = 0; s += P.s1; s += P.s2; n += P.n1; n += P.n2; return 100 * s / n;", t: [`성공 합 = ${s1} + ${s2} = ${s1 + s2}.||Total successes = ${s1 + s2}.`, `사례 합 = ${n1} + ${n2} = ${n1 + n2}.||Total cases = ${n1 + n2}.`, "집단별 비율을 평균하지 않고 합쳐서 계산한다.||Pool the counts instead of averaging the group rates.", `${s1 + s2}/${n1 + n2}.`, `답은 ${a}%.||The overall rate is ${a}%.`] }; } },
  { name: "per_capita_gap", gen(rng) { const pa = rng.pick([2, 4, 5, 8]), pb = rng.pick([10, 20, 25, 40]); const ra = rng.int(6, 30), rb = rng.int(2, 5); const xa = ra * pa, xb = rb * pb; const a = ra - rb; need(a > 0 && xa < 1000 && xb < 1000); const ev = rng.pick(["bicycle thefts", "traffic accidents", "library visits", "emergency calls"]);
    return { s: `Town A, with ${pa} thousand residents, had ${xa} ${ev} last year. Town B, with ${pb} thousand residents, had ${xb} ${ev}. Town B had more residents, and a newspaper claims that Town B is the more affected town.`, q: sp(rng, `[[How many more ${ev} per thousand residents did Town A have than Town B?|Per 1,000 residents, by how many does Town A's number of ${ev} exceed Town B's?]]`), a, w: [xa - xb, Math.abs(xa / pb - xb / pa), ra],
      p: { pa, pb, xa, xb }, js: "return P.xa / P.pa - P.xb / P.pb;", t: [`A: ${xa}/${pa} = ${ra} 건 (천 명당).||A: ${ra} per thousand.`, `B: ${xb}/${pb} = ${rb} 건 (천 명당).||B: ${rb} per thousand.`, "총건수가 아니라 인구 대비 비율로 비교한다.||Compare rates per resident, not raw counts.", `${ra} − ${rb}.`, `답은 ${a}.||The difference is ${a}.`] }; } },
  { name: "linear_trend_forecast", gen(rng) { const g = rng.pick([2, 4, 5]); const dy = rng.pick([1, 2, 3, 4]); const p1 = rng.int(20, 40), step = rng.int(2, 6); const p2 = p1 + step; const a = p2 + step * dy; need(a < 100); const c0 = sc(rng); const later = g * dy;
    return { s: `A first poll found that ${p1}% of ${c0.P} ${c0.tr}. The poll was repeated ${g} years later, and ${p2}% of ${c0.P} ${c0.tr}. Assume that the percent changes by the same amount every ${g} years.`, q: sp(rng, `[[Under this assumption, what percent would ${c0.tr} ${later} years after the second poll?|If the pattern continues, what would the percent be ${later} years after the second poll?]]`), a, w: [p2 + step, p2 + step * later, 2 * p2 - p1 + dy],
      p: { g, later, p1, p2 }, js: "const perYear = (P.p2 - P.p1) / P.g; return P.p2 + perYear * P.later;", t: [`첫 조사 ${p1}%, ${g} 년 뒤 ${p2}%.||The first poll: ${p1}%; after ${g} years: ${p2}%.`, `${g} 년마다 ${step} 퍼센트포인트 변화.||It changes by ${step} points every ${g} years.`, `${later} 년은 ${dy} 번의 변화 구간.||${later} years is ${dy} intervals.`, `${p2} + ${step} × ${dy}.`, `답은 ${a}%.||The percent would be ${a}.`] }; } },
  { name: "volunteer_vs_random_count", gen(rng) { const c0 = sc(rng); const N = rng.pick([400, 500, 600, 800, 900]); const pv = rng.pick([60, 65, 70, 75, 80]), pr = rng.pick([20, 25, 30, 35, 40]); const a = (N * (pv - pr)) / 100; need(isInt(a)); const nr = rng.pick([50, 100, 150]);
    return { s: `${c0.home.charAt(0).toUpperCase() + c0.home.slice(1)} has ${N} ${c0.P}. In a poll of volunteers, ${pv}% said they ${c0.tr}. In a random sample of ${nr} ${c0.P}, ${pr}% said they ${c0.tr}. The random sample is considered reliable.`, q: sp(rng, `[[If the volunteer result were applied to all ${N} ${c0.P}, how many more ${c0.P} would be counted as ones who ${c0.tr} than the random sample suggests?|Applying each result to all ${N} ${c0.P}, how large is the gap in the estimated number who ${c0.tr}?]]`), a, w: [(N * pv) / 100, (N * pr) / 100, pv - pr],
      p: { N, pv, pr }, js: "const v = P.N * P.pv / 100, r = P.N * P.pr / 100; return v - r;", t: [`자원자 결과 적용 ${N} × ${pv}% = ${(N * pv) / 100}.||Volunteer result: ${(N * pv) / 100}.`, `무작위 표본 적용 ${N} × ${pr}% = ${(N * pr) / 100}.||Random sample result: ${(N * pr) / 100}.`, "두 추정 인원의 차이가 자발적 응답의 과대 추정분이다.||The gap is the overcount from self-selection.", `${(N * pv) / 100} − ${(N * pr) / 100}.`, `답은 ${a}.||The gap is ${a}.`] }; } },
];

const ESC_BASE = { skill: SKILL, mediumSteps: 3 };
export const ESC_SPR_A: Archetype[] = [
  ...mkKind({ ...ESC_BASE, id: "esc.sample_to_population", kind: "sample_to_population", concepts: ["무작위 표본의 일반화", "비율의 환산", "주장의 수량 평가"] }, [
    { op: "compose_kind", structure: "무작위 표본의 비율을 명단·구역·무응답 구조와 합성해 전체 수량을 추정", extra: "표본 비율을 모집단 틀에 맞게 가중·분할하거나 무응답의 한계를 따져야 함 — medium 은 한 표본 비율에 한 번 곱함", vars: A_COMPOSE },
    { op: "chain2", structure: "표본에서 얻은 추정 수량을 다음 단계(비용·시간·좌석·하위 집단)의 입력으로 연결", extra: "첫 추정값이 다음 계산의 기준이 되는 2단계 연쇄 — medium 은 한 번의 표본→모집단 곱셈", vars: A_CHAIN },
    { op: "inverse", structure: "추정값과 표본 정보 중 일부가 주어질 때 모집단 크기·표본 수·퍼센트·누락된 층을 거꾸로 구함", extra: "정방향 추정식을 세워 알려지지 않은 입력을 풀어야 함 — medium 은 정방향 추정", vars: A_INVERSE },
    { op: "compare_scenarios", structure: "서로 다른 표본·시점·계획의 추정을 퍼센트포인트·상대 변화·비용·임계 크기로 비교", extra: "표본 크기가 다른 두 상황을 같은 기준(비율·추정 인원)으로 맞춰 비교해야 함 — medium 은 한 상황의 추정", vars: A_COMPARE },
  ]),
  ...mkKind({ ...ESC_BASE, id: "esc.experiment_effect_calc", kind: "experiment_effect_calc", concepts: ["무작위 배정 실험", "처치 효과의 수량화", "집단 비교"] }, [
    { op: "compose_kind", structure: "무작위 배정 실험의 평균·비율을 합치거나 변화량·오류값을 처리해 효과 크기를 구함", extra: "집단 크기·시작 값·오류값을 고려한 가중·변화량 비교가 필요 — medium 은 두 평균을 그대로 뺌", vars: B_COMPOSE },
    { op: "chain2", structure: "배정 비율·탈락·위약·하위집단·교차 설계를 거친 뒤 효과를 계산하는 2단계 연결", extra: "배정·탈락 같은 앞 단계 결과가 분모·기준이 되는 연쇄 — medium 은 한 비율 계산", vars: B_CHAIN },
    { op: "inverse", structure: "전체 평균·전체 성공 수·효과 크기 등으로 누락된 집단 값을 거꾸로 구함", extra: "결합식을 세워 미지 집단의 값을 풀어야 함 — medium 은 정방향 집계", vars: B_INVERSE },
    { op: "compare_scenarios", structure: "용량·비용·시간·비율의 배수·치료 필요 인원으로 두 처치 조건을 비교", extra: "차이·비·역수 중 묻는 형태에 맞게 효과를 다시 표현해야 함 — medium 은 한 집단의 비율 계산", vars: B_COMPARE },
  ]),
  ...mkKind({ ...ESC_BASE, id: "esc.study_bias_rates", kind: "study_bias_rates", concepts: ["표집 편향과 틀", "비율·가중 계산", "관찰 연구의 한계"] }, [
    { op: "compose_kind", structure: "자원 응답·틀 누락·응답률·성비 가중 등 표집 문제를 수치로 정량화", extra: "편향의 크기를 맞는 기준 집단으로 환산해야 함 — medium 은 정성적 편향 식별", vars: C_COMPOSE },
    { op: "chain2", structure: "다중 검정의 거짓 양성·계통·군집·층화 추출의 표본 크기를 두 단계로 계산", extra: "추출 설계가 정한 크기·비율을 먼저 구한 뒤 다음 양으로 연결 — medium 은 설계 이름 고르기", vars: C_CHAIN },
    { op: "inverse", structure: "응답률·자발 참여 비율·교차표·유병률에서 발송 수·표본 크기·미노출 비율을 거꾸로 구함", extra: "주어진 비율 관계를 뒤집어 미지 양을 풀어야 함 — medium 은 정방향 비율 계산", vars: C_INVERSE },
    { op: "compare_scenarios", structure: "합산 vs 집단별 비율·인구 대비 비율·추세 외삽·자발 vs 무작위 추정을 비교", extra: "비교 기준(합산·인구 대비·시점)을 맞춘 뒤 계산해야 함 — medium 은 한 비율 계산", vars: C_COMPARE },
  ]),
];
void GenFail;
