// inference_margin_error — 수치 단답(SPR 가능) hard 원형 1 kind × 4 연산자 × 6 변형. 오차 한계·구간·신뢰 수준을 수치로 다룬다(기존 3개 kind 와 묻는 양·풀이 경로가 다르다).
import { need, isInt, sp, mkKind, type Var } from "./spr-a-kit";
import type { Rng } from "../rng";
import type { Archetype } from "../types";

const SKILL = "inference_margin_error";
type Pl = { P: string; ev: string; ctx: string };
const POLL: Pl[] = [
  { P: "voters", ev: "support the ballot measure", ctx: "a county" }, { P: "students", ev: "favor a later start time", ctx: "a high school" },
  { P: "residents", ev: "approve of the new transit plan", ctx: "a city" }, { P: "customers", ev: "would recommend the store", ctx: "a retail chain" },
  { P: "employees", ev: "prefer a four-day work week", ctx: "a large company" }, { P: "members", ev: "want longer gym hours", ctx: "a fitness club" },
  { P: "teachers", ev: "support the new curriculum", ctx: "a school district" }, { P: "commuters", ev: "would pay for express lanes", ctx: "a metropolitan area" },
];
const pl = (rng: Rng) => rng.pick(POLL);
const POLLSTER = (rng: Rng) => sp(rng, "[[A polling firm|A research group|A newspaper|A university survey center]]");

const COMPOSE: Var[] = [
  { name: "upper_count_of_range", gen(rng) { const c0 = pl(rng); const N = rng.pick([200, 300, 400, 500, 800, 900]), p = rng.int(35, 65), m = rng.pick([2, 3, 4, 5]); const a = (N * (p + m)) / 100; need(isInt(a));
    return { s: `${POLLSTER(rng)} reports that ${p}% of ${c0.P} in ${c0.ctx} ${c0.ev}, with a margin of error of ${m} percentage points. ${c0.ctx.charAt(0).toUpperCase() + c0.ctx.slice(1)} has ${N} ${c0.P} in the study population.`, q: sp(rng, `[[What is the greatest number of the ${N} ${c0.P} consistent with the poll who ${c0.ev}?|Using the upper end of the interval, how many of the ${N} ${c0.P} could ${c0.ev}?]]`), a, w: [(N * p) / 100, (N * m) / 100, (N * (p - m)) / 100],
      p: { N, p, m }, js: "let best = 0; for (let k = 0; k <= P.N; k++) { if (k * 100 <= P.N * (P.p + P.m)) best = k; } return best;", t: [`구간은 ${p}% ± ${m} 퍼센트포인트.||The interval is ${p}% plus or minus ${m} points.`, `상한 = ${p} + ${m} = ${p + m}%.||Upper end = ${p + m}%.`, "구간의 상한을 인원으로 바꾼다.||Convert the upper end to a count.", `${N} × ${p + m}%.`, `답은 ${a}.||The greatest count is ${a}.`] }; } },
  { name: "range_width_in_people", gen(rng) { const c0 = pl(rng); const N = rng.pick([250, 400, 500, 600, 800]), p = rng.int(30, 70), m = rng.pick([2, 3, 4, 5, 6]); const a = (N * 2 * m) / 100; need(isInt(a));
    return { s: `A poll estimates that ${p}% of the ${N} ${c0.P} of ${c0.ctx} ${c0.ev}. The poll's margin of error is ${m} percentage points.`, q: sp(rng, `[[The plausible values for the number of ${c0.P} who ${c0.ev} form a range. How many people wide is that range?|By how many people do the largest and smallest plausible counts differ?]]`), a, w: [(N * m) / 100, (N * p) / 100, 2 * m],
      p: { N, m }, js: "const hi = P.N * P.m / 100, lo = -P.N * P.m / 100; return hi - lo;", t: [`구간은 추정치 ± ${m} 퍼센트포인트.||The interval is the estimate +/- ${m} points.`, `구간의 폭 = 2 × ${m} = ${2 * m} 퍼센트포인트.||Width = ${2 * m} points.`, "추정 비율의 위치(p)는 폭에 영향이 없다.||The estimate itself does not change the width.", `${N} × ${2 * m}%.`, `답은 ${a}.||The range is ${a} people wide.`] }; } },
  { name: "claims_inside_interval", gen(rng) { const c0 = pl(rng); const p = rng.int(40, 60), m = rng.pick([3, 4, 5]); const claims = rng.shuffle([p - m - 2, p - m, p - 1, p, p + 2, p + m, p + m + 1, p - m - 5]).slice(0, 6); const a = claims.filter((x) => x >= p - m && x <= p + m).length; need(a >= 2 && a <= 5); const list = claims.map((x) => `${x}%`).join(", ");
    return { s: `A poll finds that ${p}% of ${c0.P} in ${c0.ctx} ${c0.ev}, with a margin of error of ${m} percentage points. Six advocates each claim a different true percent: ${list}.`, q: sp(rng, `[[How many of the six claims are consistent with the poll, meaning they fall within the interval, endpoints included?|How many of the claimed percents lie in the poll's interval, including its endpoints?]]`), a, w: [6 - a, a + 1, a - 1],
      p: { p, m, claims }, js: "let c = 0; for (const x of P.claims) { if (x >= P.p - P.m && x <= P.p + P.m) c++; } return c;", t: [`구간 = [${p - m}%, ${p + m}%].||The interval is [${p - m}%, ${p + m}%].`, "끝점도 포함한다.||Endpoints are included.", `각 주장 ${list} 를 구간과 비교한다.||Compare each claim with the interval.`, `구간 안의 값을 센다.||Count the values inside.`, `답은 ${a}.||${a} claims are consistent.`] }; } },
  { name: "overlap_length", gen(rng) { const c0 = pl(rng); const p1 = rng.int(40, 50), m1 = rng.pick([3, 4, 5]), p2 = p1 + rng.int(1, 4), m2 = rng.pick([3, 4, 5]); const lo = Math.max(p1 - m1, p2 - m2), hi = Math.min(p1 + m1, p2 + m2); need(hi > lo); const a = hi - lo;
    return { s: `Two polls of ${c0.P} in ${c0.ctx} estimate the percent who ${c0.ev}. Poll 1 reports ${p1}% with a margin of error of ${m1} points. Poll 2 reports ${p2}% with a margin of error of ${m2} points.`, q: sp(rng, `[[The two intervals overlap. How many percentage points long is the overlap?|What is the length, in percentage points, of the part of the two intervals that they share?]]`), a, w: [Math.abs(p2 - p1), m1 + m2, 2 * Math.min(m1, m2)],
      p: { p1, m1, p2, m2 }, js: "let len = 0; for (let x = 0; x < 100; x += 0.5) { if (x >= P.p1 - P.m1 && x < P.p1 + P.m1 && x >= P.p2 - P.m2 && x < P.p2 + P.m2) len += 0.5; } return len;", t: [`구간 1 = [${p1 - m1}, ${p1 + m1}].||Interval 1 = [${p1 - m1}, ${p1 + m1}].`, `구간 2 = [${p2 - m2}, ${p2 + m2}].||Interval 2 = [${p2 - m2}, ${p2 + m2}].`, `겹침의 시작은 큰 하한 ${lo}.||The overlap starts at the larger lower end, ${lo}.`, `겹침의 끝은 작은 상한 ${hi}.||The overlap ends at the smaller upper end, ${hi}.`, `길이 ${hi} − ${lo} = ${a}.||The overlap is ${a}.`] }; } },
  { name: "rule_of_thumb_margin", gen(rng) { const c0 = pl(rng); const m = rng.pick([4, 5, 10]); const n = (100 / m) ** 2; need(isInt(n)); const dis = rng.pick(["margin of error", "approximate margin of error"]);
    return { s: `A poll of ${n} randomly selected ${c0.P} in ${c0.ctx} asks whether they ${c0.ev}. A rule of thumb says the ${dis} for such a poll is about 100 divided by the square root of the sample size, in percentage points.`, q: sp(rng, `[[According to the rule of thumb, what is the margin of error, in percentage points?|What margin of error, in percentage points, does the rule of thumb give for this poll?]]`), a: m, w: [n / 100, 100 / n, Math.sqrt(n)],
      p: { n }, js: "for (let m = 1; m <= 100; m++) { if (m * m * P.n === 10000) return m; } throw new Error('none');", t: [`표본 크기 n = ${n}.||The sample size is ${n}.`, `√${n} = ${Math.sqrt(n)}.`, "어림 규칙 오차 = 100 ÷ √n.||Rule: margin = 100 / sqrt(n).", `100 ÷ ${Math.sqrt(n)}.`, `답은 ${m}.||The margin is ${m} points.`] }; } },
  { name: "mean_from_interval_ends", gen(rng) { const m = rng.int(3, 12); const mu = rng.int(20, 90); const lo = mu - m, hi = mu + m; const what = rng.pick([["hours of sleep per month", "sleepers"], ["minutes of commuting per week", "commuters"], ["dollars spent per visit", "shoppers"], ["pages read per month", "readers"]]); const n = rng.pick([40, 50, 60, 100]);
    return { s: `A random sample of ${n} ${what[1]} was used to build an interval for the mean number of ${what[0]} for all ${what[1]}. The interval runs from ${lo} to ${hi}, and it was built symmetrically around the sample mean.`, q: sp(rng, `[[What was the sample mean?|What is the sample mean used to build the interval?]]`), a: mu, w: [m, hi - lo, mu + m],
      p: { lo, hi }, js: "return (P.lo + P.hi) / 2;", t: [`구간은 ${lo} ~ ${hi}.||The interval is ${lo} to ${hi}.`, "구간은 표본 평균을 중심으로 좌우 대칭이다.||The interval is symmetric around the sample mean.", "표본 평균은 두 끝의 가운데.||The mean is the midpoint of the ends.", `(${lo} + ${hi}) ÷ 2.`, `답은 ${mu}.||The sample mean is ${mu}.`] }; } },
];
const CHAIN: Var[] = [
  { name: "sample_for_target_margin", gen(rng) { const c0 = pl(rng); const m = rng.pick([2, 2.5, 4, 5]); const a = (100 / m) ** 2; need(isInt(a) && a <= 2500);
    return { s: `A planner wants a poll of ${c0.P} in ${c0.ctx} about whether they ${c0.ev}. For a simple random sample of size n, the margin of error is about 100 divided by the square root of n, in percentage points.`, q: sp(rng, `[[What sample size is needed for a margin of error of ${m} percentage points?|How many ${c0.P} must be sampled to reach a margin of error of ${m} points?]]`), a, w: [100 / m, (100 / m) * 2, a / 2],
      p: { m }, js: "for (let n = 1; n <= 20000; n++) { if (Math.abs(100 / Math.sqrt(n) - P.m) < 1e-9) return n; } throw new Error('none');", t: [`${m} = 100 ÷ √n.`, `√n = 100 ÷ ${m} = ${100 / m}.`, "양변을 제곱한다.||Square both sides.", `n = ${100 / m}².`, `답은 ${a}.||The sample size is ${a}.`] }; } },
  { name: "survey_cost_for_margin", gen(rng) { const c0 = pl(rng); const m = rng.pick([2, 4, 5, 10]); const n = (100 / m) ** 2; const d = rng.pick([2, 3, 4, 5, 6]); const a = n * d; need(isInt(n) && a <= 20000);
    return { s: `For a simple random sample of size n, the margin of error is about 100 divided by the square root of n, in percentage points. A firm will survey ${c0.P} in ${c0.ctx} and pays ${d} dollars per respondent.`, q: sp(rng, `[[What is the total cost, in dollars, to reach a margin of error of ${m} percentage points?|How many dollars will the firm spend to get a margin of error of ${m} points?]]`), a, w: [n, d * m, d * (100 / m)],
      p: { m, d }, js: "let n = 0; for (let k = 1; k <= 20000; k++) { if (k * P.m * P.m === 10000) n = k; } return n * P.d;", t: [`${m} = 100 ÷ √n.`, `n = (100 ÷ ${m})² = ${n}.`, `응답자 ${n} 명.||${n} respondents are needed.`, `비용 = ${n} × ${d}.||Cost = ${n} x ${d}.`, `답은 ${a} 달러.||The cost is ${a} dollars.`] }; } },
  { name: "gap_beyond_margins", gen(rng) { const c0 = pl(rng); const m1 = rng.pick([2, 3, 4]), m2 = rng.pick([2, 3, 4]); const ex = rng.int(1, 6); const gap = m1 + m2 + ex; const p2 = rng.int(25, 40); const p1 = p2 + gap; const a = ex;
    return { s: `In a poll of ${c0.P} in ${c0.ctx}, Option A is chosen by ${p1}% (margin of error ${m1} points) and Option B by ${p2}% (margin of error ${m2} points). The intervals for A and B would just touch if the gap between the estimates were exactly the sum of the two margins.`, q: sp(rng, `[[By how many percentage points does the actual gap between the estimates exceed the sum of the two margins?|How many points larger than the combined margins is the gap between A and B?]]`), a, w: [gap, m1 + m2, p1 - p2 - m1],
      p: { p1, p2, m1, m2 }, js: "return (P.p1 - P.p2) - (P.m1 + P.m2);", t: [`추정치의 차 = ${p1} − ${p2} = ${gap}.||Gap = ${gap}.`, `오차 한계의 합 = ${m1} + ${m2} = ${m1 + m2}.||Combined margins = ${m1 + m2}.`, "구간이 맞닿는 기준과 비교한다.||Compare with the touching threshold.", `${gap} − ${m1 + m2}.`, `답은 ${a}.||The excess is ${a}.`] }; } },
  { name: "lowest_total_two_towns", gen(rng) { const c0 = pl(rng); const NA = rng.pick([200, 300, 400, 500]), NB = rng.pick([100, 200, 300, 600]); const pa = rng.int(40, 60), pb = rng.int(30, 55), ma = rng.pick([2, 4, 5]), mb = rng.pick([2, 4, 5]); const a = (NA * (pa - ma) + NB * (pb - mb)) / 100; need(isInt(a));
    return { s: `Separate polls were run for two towns. In Town A, which has ${NA} ${c0.P}, ${pa}% (margin of error ${ma} points) ${c0.ev}. In Town B, which has ${NB} ${c0.P}, ${pb}% (margin of error ${mb} points) ${c0.ev}.`, q: sp(rng, `[[What is the smallest total number of ${c0.P} in the two towns who could ${c0.ev}, given both intervals?|Using the lower end of each interval, how many ${c0.P} in both towns together ${c0.ev}?]]`), a, w: [(NA * pa + NB * pb) / 100, ((NA + NB) * (pa + pb - ma - mb)) / 200, (NA * (pa + ma) + NB * (pb + mb)) / 100],
      p: { NA, NB, pa, pb, ma, mb }, js: "let t = 0; for (let i = 0; i < P.NA; i++) t += (P.pa - P.ma) / 100; for (let i = 0; i < P.NB; i++) t += (P.pb - P.mb) / 100; return Math.round(t);", t: [`A 의 하한 = ${pa} − ${ma} = ${pa - ma}%.||A lower end = ${pa - ma}%.`, `A 의 최소 인원 = ${NA} × ${pa - ma}%.||A minimum = ${(NA * (pa - ma)) / 100}.`, `B 의 하한 = ${pb - mb}%, 인원 ${(NB * (pb - mb)) / 100}.||B minimum = ${(NB * (pb - mb)) / 100}.`, "두 마을을 따로 계산해 더한다.||Compute each town and add.", `답은 ${a}.||The smallest total is ${a}.`] }; } },
  { name: "least_yes_respondents", gen(rng) { const c0 = pl(rng); const n = rng.pick([200, 250, 400, 500, 800]), p = rng.int(40, 60), m = rng.pick([2, 4, 5, 6]); const a = (n * (p - m)) / 100; need(isInt(a));
    return { s: `A poll of ${n} randomly selected ${c0.P} in ${c0.ctx} reports ${p}% who ${c0.ev}, with a margin of error of ${m} percentage points. The poll's interval describes the percent among all ${c0.P}.`, q: sp(rng, `[[If a new sample of ${n} ${c0.P} had the lowest percent consistent with the interval, how many of the ${n} would ${c0.ev}?|How many of ${n} ${c0.P} would ${c0.ev} if the true percent were the lower end of the interval?]]`), a, w: [(n * p) / 100, (n * m) / 100, (n * (p + m)) / 100],
      p: { n, p, m }, js: "let k = 0; for (let i = 1; i <= P.n; i++) { if (i * 100 <= P.n * (P.p - P.m)) k = i; } return k;", t: [`구간 하한 = ${p} − ${m} = ${p - m}%.||Lower end = ${p - m}%.`, "하한이 참값이라고 가정한다.||Assume the true percent equals the lower end.", `${n} 명에 적용한다.||Apply to ${n} people.`, `${n} × ${p - m}%.`, `답은 ${a}.||The count is ${a}.`] }; } },
  { name: "extra_respondents_needed", gen(rng) { const c0 = pl(rng); const m = rng.pick([2, 4, 5, 10]); const need2 = (100 / m) ** 2; const n = rng.pick([100, 150, 200, 225, 400].filter((x) => x < need2)); need(isInt(need2) && n !== undefined); const a = need2 - n;
    return { s: `A pilot poll of ${n} ${c0.P} in ${c0.ctx} about whether they ${c0.ev} was too small. For a simple random sample of size n, the margin of error is about 100 divided by the square root of n, in percentage points. The planners want a margin of ${m} points.`, q: sp(rng, `[[How many additional ${c0.P} must be surveyed beyond the pilot sample?|How many more respondents are needed than the ${n} already surveyed?]]`), a, w: [need2, 100 / m, a + n],
      p: { n, m }, js: "let need = 0; for (let k = 1; k <= 20000; k++) { if (k * P.m * P.m === 10000) need = k; } return need - P.n;", t: [`${m} = 100 ÷ √n.`, `n = (100 ÷ ${m})² = ${need2}.`, `이미 ${n} 명을 조사했다.||${n} are already surveyed.`, `추가 = ${need2} − ${n}.||Additional = ${need2} - ${n}.`, `답은 ${a}.||${a} more are needed.`] }; } },
];
const INVERSE: Var[] = [
  { name: "sample_percent_from_count_range", gen(rng) { const c0 = pl(rng); const N = rng.pick([200, 400, 500, 800]), p = rng.int(35, 65), m = rng.pick([2, 4, 5]); const lo = (N * (p - m)) / 100, hi = (N * (p + m)) / 100; need(isInt(lo) && isInt(hi));
    return { s: `A poll's results imply that between ${lo} and ${hi} of the ${N} ${c0.P} in ${c0.ctx} ${c0.ev}. The interval is symmetric around the poll's estimate.`, q: sp(rng, `[[What percent of those polled ${c0.ev}?|What was the poll's estimated percent?]]`), a: p, w: [m, (hi - lo) / 2, (N * p) / 100],
      p: { lo, hi, N }, js: "const mid = (P.lo + P.hi) / 2; for (let q = 0; q <= 100; q++) { if (q * P.N === 100 * mid) return q; } throw new Error('none');", t: [`구간 인원 ${lo} ~ ${hi}.||The count interval is ${lo} to ${hi}.`, `가운데 = (${lo} + ${hi}) ÷ 2 = ${(lo + hi) / 2}.||The midpoint is ${(lo + hi) / 2}.`, "가운데가 추정치에 해당한다.||The midpoint corresponds to the estimate.", `${(lo + hi) / 2} ÷ ${N} × 100.`, `답은 ${p}%.||The estimate is ${p}%.`] }; } },
  { name: "margin_points_from_count_range", gen(rng) { const c0 = pl(rng); const N = rng.pick([200, 250, 400, 500, 800]), p = rng.int(35, 65), m = rng.pick([2, 3, 4, 5]); const lo = (N * (p - m)) / 100, hi = (N * (p + m)) / 100; need(isInt(lo) && isInt(hi));
    return { s: `An analysis says that between ${lo} and ${hi} of the ${N} ${c0.P} in ${c0.ctx} ${c0.ev}. The range is the poll estimate plus or minus its margin of error.`, q: sp(rng, `[[What is the poll's margin of error, in percentage points?|What margin of error, in percentage points, produced this range?]]`), a: m, w: [(hi - lo) / 2, hi - lo, ((hi - lo) * 100) / N],
      p: { lo, hi, N }, js: "const halfCount = (P.hi - P.lo) / 2; for (let m = 0; m <= 50; m++) { if (m * P.N === 100 * halfCount) return m; } throw new Error('none');", t: [`범위의 폭 = ${hi} − ${lo} = ${hi - lo} 명.||Width = ${hi - lo} people.`, `절반 = ${(hi - lo) / 2} 명이 오차 한계에 해당.||Half-width = ${(hi - lo) / 2} people.`, "인원을 퍼센트포인트로 바꾼다.||Convert to percentage points.", `${(hi - lo) / 2} ÷ ${N} × 100.`, `답은 ${m}.||The margin is ${m} points.`] }; } },
  { name: "yes_count_from_interval", gen(rng) { const c0 = pl(rng); const n = rng.pick([200, 250, 400, 500]), p = rng.int(35, 65), m = rng.pick([2, 3, 4, 5]); const yes = (n * p) / 100; need(isInt(yes)); const lo = p - m, hi = p + m;
    return { s: `A poll of ${n} randomly selected ${c0.P} in ${c0.ctx} gives the interval from ${lo}% to ${hi}% for the percent who ${c0.ev}. The interval is centered on the percent in the sample.`, q: sp(rng, `[[How many of the ${n} sampled ${c0.P} said they ${c0.ev}?|In the sample, how many ${c0.P} ${c0.ev}?]]`), a: yes, w: [(n * m) / 100, (n * hi) / 100, (n * lo) / 100],
      p: { n, lo, hi }, js: "const center = (P.lo + P.hi) / 2; let c = 0; for (let i = 1; i <= P.n; i++) { if (i * 100 <= P.n * center) c = i; } return c;", t: [`구간 ${lo}% ~ ${hi}%.||The interval is ${lo}% to ${hi}%.`, `중심 = ${p}%.||The center is ${p}%.`, "중심이 표본 비율이다.||The center is the sample percent.", `${n} × ${p}%.`, `답은 ${yes}.||${yes} said yes.`] }; } },
  { name: "population_from_margin_people", gen(rng) { const c0 = pl(rng); const m = rng.pick([2, 4, 5, 10]); const k = rng.pick([10, 12, 15, 20, 30, 40]); const N = (100 * k) / m; need(isInt(N) && N < 1000);
    return { s: `A poll of ${c0.P} in ${c0.ctx} has a margin of error of ${m} percentage points. When the margin is applied to the whole population, it amounts to ${k} ${c0.P}.`, q: sp(rng, `[[How many ${c0.P} are in the whole population?|What is the size of the population of ${c0.P}?]]`), a: N, w: [k * m, N / 2, N + k],
      p: { m, k }, js: "for (let N = 1; N <= 5000; N++) { if (N * P.m === 100 * P.k) return N; } throw new Error('none');", t: [`${m}% 가 ${k} 명에 해당.||${m}% of the population is ${k} people.`, `N × ${m}/100 = ${k}.`, `N = ${k} × 100 ÷ ${m}.`, "퍼센트포인트와 인원의 관계를 이용한다.||Use the link between percentage points and people.", `답은 ${N}.||The population is ${N}.`] }; } },
  { name: "lower_end_from_claim", gen(rng) { const c0 = pl(rng); const p = rng.int(42, 60); const m = rng.pick([3, 4, 5, 6]); const U = p + m; const a = p - m;
    return { s: `A poll reports that ${p}% of ${c0.P} in ${c0.ctx} ${c0.ev}. The pollster says that the true percent is at most ${U}%, and that this bound is exactly the poll's estimate plus its margin of error.`, q: sp(rng, `[[What is the lower end of the poll's interval?|According to the pollster's statement, what is the smallest percent consistent with the poll?]]`), a, w: [m, U, p],
      p: { p, U }, js: "const margin = P.U - P.p; return P.p - margin;", t: [`상한 = ${U}%, 추정치 = ${p}%.||Upper end ${U}%, estimate ${p}%.`, `오차 한계 = ${U} − ${p} = ${m}.||Margin = ${m}.`, "구간은 추정치 좌우 대칭이다.||The interval is symmetric.", `하한 = ${p} − ${m}.||Lower end = ${p} - ${m}.`, `답은 ${a}%.||The lower end is ${a}%.`] }; } },
  { name: "n_from_two_polls_ratio", gen(rng) { const c0 = pl(rng); const m1 = rng.pick([10, 5, 4]); const k = rng.pick([2, 2.5, 4, 5].filter((x) => m1 / x >= 1 && Number.isInteger((100 / (m1 / x)) ** 2))); need(k !== undefined); const m2 = m1 / k; const n1 = (100 / m1) ** 2, n2 = (100 / m2) ** 2; need(isInt(n1) && isInt(n2) && n2 <= 2500); const a = n2;
    return { s: `For a simple random sample of size n, the margin of error is about 100 divided by the square root of n, in percentage points. A first poll of ${n1} ${c0.P} in ${c0.ctx} had a margin of error of ${m1} points. A second poll about whether they ${c0.ev} was designed to have a margin of ${m2} points.`, q: sp(rng, `[[How many ${c0.P} should the second poll include?|What sample size does the second poll need?]]`), a, w: [n1 * k, n1 * 2 * k, n1 + k],
      p: { n1, m1, m2 }, js: "for (let n = 1; n <= 20000; n++) { if (Math.abs(100 / Math.sqrt(n) - P.m2) < 1e-9) return n; } throw new Error('none');", t: [`첫 조사: 100/√${n1} = ${m1}.||First poll: 100/sqrt(${n1}) = ${m1}.`, `둘째 목표 오차 ${m2}.||Second target margin ${m2}.`, `${m2} = 100 ÷ √n.`, `n = (100 ÷ ${m2})².`, `답은 ${a}.||The sample size is ${a}.`] }; } },
];
const COMPARE: Var[] = [
  { name: "interval_width_difference", gen(rng) { const c0 = pl(rng); const m1 = rng.int(2, 4), m2 = rng.int(5, 9); const p1 = rng.int(40, 60), p2 = rng.int(40, 60); const a = 2 * (m2 - m1);
    return { s: `Two polls ask ${c0.P} in ${c0.ctx} whether they ${c0.ev}. Poll A finds ${p1}% with a margin of error of ${m1} points. Poll B finds ${p2}% with a margin of error of ${m2} points.`, q: sp(rng, `[[How many percentage points wider is the interval from Poll B than the interval from Poll A?|By how many points does the width of Poll B's interval exceed the width of Poll A's?]]`), a, w: [m2 - m1, Math.abs(p1 - p2), m1 + m2],
      p: { m1, m2 }, js: "const wa = 2 * P.m1, wb = 2 * P.m2; return wb - wa;", t: [`A 의 폭 = 2 × ${m1} = ${2 * m1}.||A width = ${2 * m1}.`, `B 의 폭 = 2 × ${m2} = ${2 * m2}.||B width = ${2 * m2}.`, "폭은 추정치가 아니라 오차 한계로 정해진다.||Width depends on the margin, not the estimate.", `${2 * m2} − ${2 * m1}.`, `답은 ${a}.||The difference is ${a}.`] }; } },
  { name: "lead_to_touch", gen(rng) { const c0 = pl(rng); const m = rng.pick([2, 3, 4, 5]); const L = rng.int(1, 2 * m - 1); const a = 2 * m - L; const pa = rng.int(46, 52); const pb = pa - L;
    return { s: `A poll of ${c0.P} in ${c0.ctx} finds Option A at ${pa}% and Option B at ${pb}%. Each percent has a margin of error of ${m} points. The two intervals just touch when the lower end of A's interval equals the upper end of B's interval.`, q: sp(rng, `[[By how many more percentage points would A's lead need to grow for the two intervals to just touch?|How many additional points of lead does A need before A's lower end reaches B's upper end?]]`), a, w: [L, 2 * m, m],
      p: { pa, pb, m }, js: "let extra = 0; while ((P.pa - P.pb) + extra < 2 * P.m) extra++; return extra;", t: [`현재 격차 = ${pa} − ${pb} = ${L}.||Current lead = ${L}.`, `구간이 맞닿으려면 A 하한 = B 상한.||The intervals touch when A's lower end equals B's upper end.`, `그때의 격차는 ${2 * m} 퍼센트포인트.||The lead at that point is ${2 * m} points.`, `추가 필요량 = ${2 * m} − ${L}.||Needed extra = ${2 * m} - ${L}.`, `답은 ${a}.||The answer is ${a}.`] }; } },
  { name: "expected_missing_intervals", gen(rng) { const k = rng.pick([50, 100, 200, 400, 500]), cl = rng.pick([90, 95, 99]); const a = (k * (100 - cl)) / 100; need(isInt(a) && a >= 2); const c0 = pl(rng); const R = rng.pick(["polling firms", "student teams", "research labs"]);
    return { s: `${k} independent ${R} each take a random sample of ${c0.P} in ${c0.ctx} and build a ${cl}% confidence interval for the percent who ${c0.ev}. A ${cl}% confidence interval captures the true percent in ${cl}% of such samples, in the long run.`, q: sp(rng, `[[About how many of the ${k} intervals are expected to miss the true percent?|How many of the ${k} intervals would you expect not to contain the true percent?]]`), a, w: [(k * cl) / 100, 100 - cl, k - cl],
      p: { k, cl }, js: "let miss = 0; for (let i = 0; i < P.k; i++) miss += (100 - P.cl) / 100; return Math.round(miss);", t: [`신뢰 수준 ${cl}% = 구간이 참값을 포함할 장기 비율.||${cl}% is the long-run capture rate.`, `놓칠 비율 = ${100 - cl}%.||Miss rate = ${100 - cl}%.`, `${k} 개 구간에 적용한다.||Apply to ${k} intervals.`, `${k} × ${100 - cl}%.`, `답은 ${a}.||About ${a} intervals miss.`] }; } },
  { name: "survey_plan_cost_gap", gen(rng) { const c0 = pl(rng); const mA = rng.pick([2, 4, 5]), mB = rng.pick([5, 10]); need(mA < mB); const nA = (100 / mA) ** 2, nB = (100 / mB) ** 2; const dA = rng.pick([2, 3]), dB = rng.pick([4, 5, 6]); const a = nA * dA - nB * dB; need(isInt(nA) && isInt(nB) && a > 0 && nA <= 2500);
    return { s: `For a simple random sample of size n, the margin of error is about 100 divided by the square root of n, in percentage points. A firm compares two plans for polling ${c0.P} in ${c0.ctx}. Plan A targets a margin of ${mA} points and pays ${dA} dollars per respondent. Plan B targets a margin of ${mB} points and pays ${dB} dollars per respondent.`, q: sp(rng, `[[How many dollars more does Plan A cost than Plan B?|By how many dollars does Plan A's total cost exceed Plan B's?]]`), a, w: [nA - nB, (nA - nB) * dA, nB * dB],
      p: { mA, mB, dA, dB }, js: "let nA = 0, nB = 0; for (let k = 1; k <= 20000; k++) { if (k * P.mA * P.mA === 10000) nA = k; if (k * P.mB * P.mB === 10000) nB = k; } return nA * P.dA - nB * P.dB;", t: [`A: n = (100 ÷ ${mA})² = ${nA}.`, `B: n = (100 ÷ ${mB})² = ${nB}.`, `A 비용 = ${nA} × ${dA} = ${nA * dA}.||A cost = ${nA * dA}.`, `B 비용 = ${nB} × ${dB} = ${nB * dB}.||B cost = ${nB * dB}.`, `차이 = ${a}.||The gap is ${a} dollars.`] }; } },
  { name: "worst_case_count_gap", gen(rng) { const c0 = pl(rng); const NA = rng.pick([300, 400, 500]), NB = rng.pick([200, 250, 400]); const pa = rng.int(55, 65), pb = rng.int(40, 50), m = rng.pick([2, 4, 5]); const lo = (NA * (pa - m)) / 100, hi = (NB * (pb + m)) / 100; need(isInt(lo) && isInt(hi)); const a = lo - hi; need(a > 0);
    return { s: `Town A has ${NA} ${c0.P}, and a poll there estimates that ${pa}% ${c0.ev}. Town B has ${NB} ${c0.P}, and a poll there estimates that ${pb}% ${c0.ev}. Each poll has a margin of error of ${m} points.`, q: sp(rng, `[[What is the smallest possible amount by which Town A's number of such ${c0.P} exceeds Town B's, given both intervals?|Taking the least favorable end of each interval, by how many does Town A's count exceed Town B's?]]`), a, w: [(NA * pa - NB * pb) / 100, (NA * (pa + m) - NB * (pb - m)) / 100, hi],
      p: { NA, NB, pa, pb, m }, js: "const lowA = P.NA * (P.pa - P.m) / 100; const highB = P.NB * (P.pb + P.m) / 100; return lowA - highB;", t: [`A 최소 = ${NA} × ${pa - m}% = ${lo}.||A minimum = ${lo}.`, `B 최대 = ${NB} × ${pb + m}% = ${hi}.||B maximum = ${hi}.`, "격차가 가장 작아지는 경우는 A 가 최소이고 B 가 최대일 때.||The gap is smallest when A is lowest and B is highest.", `${lo} − ${hi}.`, `답은 ${a}.||The smallest gap is ${a}.`] }; } },
  { name: "share_of_interval_above_majority", gen(rng) { const c0 = pl(rng); const m = rng.pick([4, 5, 6, 8]); const p = rng.int(50 - m + 1, 49); const hi = p + m; const a = hi - 50; need(a > 0);
    return { s: `A poll finds that ${p}% of ${c0.P} in ${c0.ctx} ${c0.ev}, with a margin of error of ${m} percentage points. A measure passes only with more than 50% support.`, q: sp(rng, `[[How many percentage points of the poll's interval lie above 50%?|The part of the interval above the 50% mark is how many percentage points long?]]`), a, w: [50 - p, m, 2 * m - a],
      p: { p, m }, js: "let len = 0; for (let x = P.p - P.m; x < P.p + P.m; x += 0.5) { if (x >= 50) len += 0.5; } return len;", t: [`구간 = [${p - m}%, ${hi}%].||Interval = [${p - m}%, ${hi}%].`, "50% 기준선이 구간 안에 있다.||The 50% line lies inside the interval.", `기준선 위쪽 구간 = ${hi} − 50.||Part above 50 = ${hi} - 50.`, "하한이 50 미만이므로 위쪽 구간은 50 부터 상한까지.||Since the lower end is below 50, the upper part runs from 50 to the top.", `답은 ${a}.||The part is ${a} points long.`] }; } },
];

const IME_BASE = { skill: SKILL, mediumSteps: 3 };
export const IME_SPR_A: Archetype[] = mkKind({ ...IME_BASE, id: "ime.poll_precision_calc", kind: "poll_precision_calc", concepts: ["오차 한계와 구간", "표본 크기 어림 규칙", "추정의 정밀도"] }, [
  { op: "compose_kind", structure: "표본 추정치와 오차 한계를 구간의 끝·폭·겹침·포함 여부로 바꿔 수량을 구함", extra: "구간의 한 끝이나 폭을 인원·비율로 환산해야 함 — medium 은 구간의 한 끝값만 구함", vars: COMPOSE },
  { op: "chain2", structure: "어림 규칙의 표본 크기를 구한 뒤 비용·추가 인원·인원 단위로 연결", extra: "표본 크기를 먼저 구한 뒤 다음 양을 계산하는 2단계 — medium 은 오차 한계 한 번 계산", vars: CHAIN },
  { op: "inverse", structure: "인원 구간·구간 끝·오차 한계의 인원 환산에서 추정 비율·표본·모집단을 거꾸로 구함", extra: "구간이 추정치를 중심으로 대칭이라는 관계를 뒤집어 사용해야 함 — medium 은 정방향 구간 계산", vars: INVERSE },
  { op: "compare_scenarios", structure: "두 조사의 폭·격차 기준·신뢰 수준의 장기 빈도·비용을 비교", extra: "비교 기준(폭·분명한 격차·장기 놓침 비율)을 해석해 수량으로 만들어야 함 — medium 은 한 조사의 구간 계산", vars: COMPARE },
]);
