// two_variable_data 자료 원형의 easy/medium 문장 틀 — 항목당 2개(15항목 → 30개). hard 와 같은 프레임워크(원형 ID + 시드 재현, verification_js 재계산, 그룹 키 = 원형ID/변형).
// easy: 자료에서 값 하나를 읽는다 / medium: 읽은 값으로 한 번 계산한다. hard 가 더하는 '추가 요구 사고'(역산·연쇄·단위·정수 경계 등)는 넣지 않는다.
import { GenFail, type Instance } from "../types";
import type { Rng } from "../rng";
import { fmtNum, frac } from "../text";
import { asLevel, withBind, type Level, type LArch } from "../levels-d";
import { W } from "./d-kit";
import { ABCD, figInst, figJs, makeLineSrc, makeScatter, makeTw, oneDec, r1d, placeChoices, planeScatter, twFig, TW_JS, SE_TOPICS, TW_TOPICS, type LineSrc, type TwScene } from "../figure-kit";
import { choiceInst, ctPlot, CLASS_JS, lineDiag, mkAssocFig, PARSE_JS, claimOf, indexInst, pickLine, samplePts, SC_PRED, scChoices, scTopicWords, TWC_PRED, twChoices, twIntro, twRulesDiag, PX, type AClass } from "./tvd-fig-choice";

const SKILL = "two_variable_data";
const lc = (s: string) => s.charAt(0).toLowerCase() + s.slice(1);
const sing = (u: string) => u.replace(/s$/, "");
const isInt = Number.isInteger;
type Lv = "easy" | "medium";
type Def = { kind: string; fig: string; loc: "P" | "C"; lv: Lv; name: string; structure: string; extra: string; concepts: string[]; spr: boolean; reason: string; gen: (rng: Rng) => Instance };
const MC_ONLY = "정답이 선택지(그림 4개 중 하나·서술 선지)를 고르는 것이 문제의 핵심이라 선택지 없이는 성립하지 않는다";
const ok = "정답이 하나의 수이고 질문이 선택지를 가리키지 않아 선택지 없이 낼 수 있다";
const mk = (d: Def): LArch => ({
  ...asLevel({
    id: `tvd.${d.kind}.${d.fig}.${d.loc}.${d.lv === "easy" ? "easy" : "med"}_${d.name}`, skill: SKILL, kind: `${d.kind}.${d.fig}.${d.loc}`, operator: "repr_shift", structure: d.structure, extraThinking: d.extra, concepts: d.concepts,
    mediumSteps: d.lv === "easy" ? 1 : 2, figureItem: `two_variable_data.${d.kind}.${d.fig}.${d.loc}`, spr: { capable: d.spr, reason: d.reason }, generate: (rng) => d.gen(rng),
  }, d.lv as Level),
});
const rd = (s: TwScene): [string, string] => [`표에서 칸을 읽는다: ${s.t.r1} — ${s.cells[0][0]}, ${s.cells[0][1]}; ${s.t.r2} — ${s.cells[1][0]}, ${s.cells[1][1]}.`, "Read the cells of the table."];
const tin = (rng: Rng, s: TwScene) => rng.pick([`The table shows the responses of ${s.t.ent} ${s.t.where}, organized by ${s.t.rowHeader.toLowerCase()}.`, `The two-way table below summarizes responses from ${s.t.ent} ${s.t.where}.`, `The table gives the results of a survey of ${s.t.ent} ${s.t.where}.`]);
const NICE_R = [20, 25, 40, 50, 60, 80, 100, 120, 200], NICE_P = [10, 20, 25, 30, 40, 50, 60, 75, 80];
const lineRead = (s: LineSrc): [string, string] => [`그림에서 직선 위의 두 격자점 (${s.p1[0]}, ${s.p1[1]}) 과 (${s.p2[0]}, ${s.p2[1]}) 를 읽는다.`, "Read two lattice points on the line."];
const slopeStep = (s: LineSrc): [string, string] => [`기울기 m = (${s.p2[1]} - ${s.p1[1]}) ÷ (${s.p2[0]} - ${s.p1[0]}) = ${fmtNum(s.m)} 이다.`, "Compute the slope."];

const defs: Def[] = [];
const push = (d: Def) => defs.push(d);

// ── 이원표 지문형 ──
push({ kind: "cell", fig: "TW", loc: "P", lv: "easy", name: "read_cell", structure: "이원표에서 한 칸의 값을 읽음", extra: "easy: 표에서 칸 하나 읽기", concepts: ["이원표", "칸 읽기"], spr: true, reason: ok, gen(rng) {
  const s = makeTw(rng); const t = s.t; const [c11, c12] = s.cells[0], [c21, c22] = s.cells[1];
  return withBind(figInst(rng, { stimulus: tin(rng, s), question: `How many of the ${t.r1} ${t.yp}?`, correct: c11, wrongs: [W(c12, "axis_misread", "다른 열의 값을 읽었다."), W(c21, "axis_misread", "다른 행의 값을 읽었다."), W(s.r1, "step_missing", "행 합계를 답했다."), W(s.cy, "step_missing", "열 합계를 답했다."), W(c22, "axis_misread", "대각선 칸을 읽었다."), W(s.N, "step_missing", "전체를 답했다.")], verificationJs: figJs({}, s.fig, `${TW_JS}return c11;`), trace: [rd(s), [`${t.r1} 행과 응답 열이 만나는 칸은 ${c11} 이다.`, "Locate the cell."]] as [string, string][], variant: "read_cell" }, s.fig), []);
} });
push({ kind: "cell", fig: "TW", loc: "P", lv: "medium", name: "sum_cells", structure: "이원표에서 응답 열의 두 칸을 더함", extra: "medium: 열의 두 칸 합", concepts: ["이원표", "열 합계"], spr: true, reason: ok, gen(rng) {
  const s = makeTw(rng); const t = s.t; const [c11, c12] = s.cells[0], [c21, c22] = s.cells[1]; const correct = c11 + c21;
  return withBind(figInst(rng, { stimulus: tin(rng, s), question: `In all, how many of the ${t.ent} ${t.yp}?`, correct, wrongs: [W(c11, "step_missing", "한 집단만 답했다."), W(c21, "step_missing", "한 집단만 답했다."), W(c12 + c22, "opposite", "응답하지 않은 열을 더했다."), W(s.N, "step_missing", "전체를 답했다."), W(c11 + c22, "axis_misread", "대각선 칸을 더했다."), W(s.r1, "step_missing", "행 합계를 답했다.")], verificationJs: figJs({}, s.fig, `${TW_JS}return cy;`), trace: [rd(s), [`${t.r1} 의 응답 칸은 ${c11} 이다.`, "First cell."], [`${t.r2} 의 응답 칸은 ${c21} 이다.`, "Second cell."], [`합 = ${c11} + ${c21} = ${correct} 이다.`, "Add the two cells."]] as [string, string][], variant: "column_sum" }, s.fig), []);
} });
push({ kind: "row_total", fig: "TW", loc: "P", lv: "easy", name: "row_total", structure: "이원표에서 한 행의 합계를 읽음", extra: "easy: 합계 열 읽기", concepts: ["이원표", "행 합계"], spr: true, reason: ok, gen(rng) {
  const s = makeTw(rng); const t = s.t;
  return withBind(figInst(rng, { stimulus: tin(rng, s), question: `How many ${t.r1} were surveyed?`, correct: s.r1, wrongs: [W(s.cells[0][0], "step_missing", "응답 칸만 답했다."), W(s.r2, "axis_misread", "다른 행의 합계를 답했다."), W(s.N, "step_missing", "전체를 답했다."), W(s.cy, "axis_misread", "열 합계를 답했다."), W(s.cells[0][1], "step_missing", "한 칸만 답했다.")], verificationJs: figJs({}, s.fig, `${TW_JS}return r1;`), trace: [rd(s), [`${t.r1} 의 합계는 ${s.cells[0][0]} + ${s.cells[0][1]} = ${s.r1} 이다.`, "Row total."]] as [string, string][], variant: "read_row_total" }, s.fig), []);
} });
push({ kind: "row_total", fig: "TW", loc: "P", lv: "medium", name: "row_gap", structure: "이원표에서 두 행 합계의 차를 구함", extra: "medium: 두 행 합계의 차", concepts: ["이원표", "행 합계 비교"], spr: true, reason: ok, gen(rng) {
  const s = makeTw(rng); const t = s.t; if (s.r1 === s.r2) throw new GenFail("tie"); const correct = Math.abs(s.r1 - s.r2);
  return withBind(figInst(rng, { stimulus: tin(rng, s), question: `What is the positive difference between the number of ${t.r1} and the number of ${t.r2} surveyed?`, correct, wrongs: [W(s.r1 + s.r2, "sign_error", "차가 아니라 합을 구했다."), W(s.r1, "step_missing", "한 행만 답했다."), W(s.r2, "step_missing", "한 행만 답했다."), W(Math.abs(s.cells[0][0] - s.cells[1][0]), "axis_misread", "응답 열의 두 칸의 차를 구했다."), W(correct + 5, "other", "계산 중 어긋났다."), W(Math.max(1, correct - 5), "other", "계산 중 어긋났다.")], verificationJs: figJs({}, s.fig, `${TW_JS}return Math.abs(r1 - r2);`), trace: [rd(s), [`${t.r1} 의 합계는 ${s.r1} 이다.`, "First row total."], [`${t.r2} 의 합계는 ${s.r2} 이다.`, "Second row total."], [`차 = |${s.r1} - ${s.r2}| = ${correct} 이다.`, "Take the difference."]] as [string, string][], variant: "row_total_gap" }, s.fig), []);
} });
push({ kind: "conditional_share", fig: "TW", loc: "P", lv: "easy", name: "row_percent", structure: "이원표에서 한 행의 응답 비율(퍼센트)을 구함", extra: "easy: 칸 ÷ 행 합계", concepts: ["이원표", "퍼센트"], spr: true, reason: ok, gen(rng) {
  const t = rng.pick(TW_TOPICS); const r1 = rng.pick(NICE_R), r2 = rng.pick(NICE_R); const p = rng.pick(NICE_P); const c11 = (r1 * p) / 100; const c21 = rng.int(6, r2 - 4); const cells = [[c11, r1 - c11], [c21, r2 - c21]]; const fig = twFig(t, cells); const s: TwScene = { t, cells, fig, r1, r2, cy: c11 + c21, cn: 0, N: r1 + r2 };
  return withBind(figInst(rng, { stimulus: tin(rng, s), question: `What percent of the ${t.r1} ${t.yp}?`, correct: p, wrongs: [W(100 - p, "opposite", "반대 칸의 비율을 답했다."), W(Math.round((c11 * 100) / (r1 + r2)), "formula_misuse", "분모를 전체로 잡았다."), W(c11, "unit_error", "퍼센트가 아니라 인원수를 답했다."), W(Math.round((c11 * 100) / (c11 + c21)), "formula_misuse", "분모를 열 합계로 잡았다."), W(p + 10, "other", "계산 중 어긋났다."), W(Math.max(1, p - 10), "other", "계산 중 어긋났다.")], verificationJs: figJs({}, fig, `${TW_JS}return c11 * 100 / r1;`), trace: [rd(s), [`${t.r1} 의 합계는 ${r1}, 응답 칸은 ${c11} 이다.`, "Row total and cell."], [`비율 = ${c11} ÷ ${r1} × 100 = ${p}% 이다.`, "Compute the percent."]] as [string, string][], variant: "row_percent" }, fig), []);
} });
push({ kind: "conditional_share", fig: "TW", loc: "P", lv: "medium", name: "overall_percent", structure: "이원표에서 전체 중 응답한 사람의 퍼센트를 구함", extra: "medium: 열 합계 ÷ 전체", concepts: ["이원표", "전체 대비 퍼센트"], spr: true, reason: ok, gen(rng) {
  const t = rng.pick(TW_TOPICS); const N = rng.pick([100, 200, 250, 400]); const pct = rng.pick(NICE_P); const cy = (N * pct) / 100; const r1 = rng.int(Math.ceil(N * 0.3), Math.floor(N * 0.7)); const c11 = rng.int(Math.max(3, cy - (N - r1) + 3), Math.min(r1 - 3, cy - 3)); const c21 = cy - c11; const r2 = N - r1; if (c21 < 3 || c21 > r2 - 3 || c11 < 3) throw new GenFail("range");
  const cells = [[c11, r1 - c11], [c21, r2 - c21]]; const fig = twFig(t, cells); const s: TwScene = { t, cells, fig, r1, r2, cy, cn: N - cy, N };
  return withBind(figInst(rng, { stimulus: tin(rng, s), question: `What percent of all the ${t.ent} surveyed ${t.yp}?`, correct: pct, wrongs: [W(100 - pct, "opposite", "응답하지 않은 비율을 답했다."), W(Math.round((c11 * 100) / r1), "condition_ignored", "한 집단의 비율만 답했다."), W(cy, "unit_error", "퍼센트가 아니라 인원수를 답했다."), W(Math.round((cy * 100) / r1), "formula_misuse", "분모를 한 행으로 잡았다."), W(pct + 10, "other", "계산 중 어긋났다."), W(Math.max(1, pct - 10), "other", "계산 중 어긋났다.")], verificationJs: figJs({}, fig, `${TW_JS}return cy * 100 / N;`), trace: [rd(s), [`응답 열의 합계는 ${c11} + ${c21} = ${cy} 이다.`, "Column total of responders."], [`전체는 ${N} 이다.`, "Grand total."], [`비율 = ${cy} ÷ ${N} × 100 = ${pct}% 이다.`, "Compute the percent."]] as [string, string][], variant: "overall_percent" }, fig), []);
} });

// ── 이원표 선택지형 ──
push({ kind: "conditional_share", fig: "TW", loc: "C", lv: "easy", name: "table_row_share", structure: "한 집단의 인원과 응답 비율을 주고 맞는 이원표를 고름", extra: "easy: 한 집단의 칸 하나로 표 고르기", concepts: ["이원표", "비율"], spr: false, reason: MC_ONLY, gen(rng) {
  const t = rng.pick(TW_TOPICS); const r1 = rng.pick(NICE_R), r2 = rng.int(24, 90); const p = rng.pick(NICE_P); const c11 = (r1 * p) / 100; const c21 = rng.int(8, r2 - 8); const okc = [[c11, r1 - c11], [c21, r2 - c21]]; const test = (c: number[][]) => c[0][0] + c[0][1] === r1 && c[0][0] * 100 === p * r1;
  const { choices, correctIndex, rules } = twChoices(rng, t, okc, test);
  return choiceInst(rng, { stimulus: `${twIntro(t)} There were ${r1} ${t.r1}, and ${p}% of them ${t.yp}.`, question: `Which table could show the results for the ${t.r1}?`, choices, correctIndex, rules, P: { r1, p }, predicateJs: TWC_PRED("r1 === P.r1 && c11 * 100 === P.p * r1"), diagnoseJs: twRulesDiag, trace: [[`${t.r1} 는 ${r1} 명이므로 첫 행의 합계가 ${r1} 이다.`, "Row total."], [`응답 칸은 ${r1} × ${p}% = ${c11} 이다.`, "The responder cell."]] as [string, string][], variant: "table_from_one_row", explainKo: "", explainEn: "" });
} });
push({ kind: "conditional_share", fig: "TW", loc: "C", lv: "medium", name: "table_two_totals", structure: "두 집단 인원과 한 집단의 응답 비율을 주고 맞는 이원표를 고름", extra: "medium: 두 행 합계와 한 비율", concepts: ["이원표", "행 합계", "비율"], spr: false, reason: MC_ONLY, gen(rng) {
  const t = rng.pick(TW_TOPICS); const r1 = rng.pick(NICE_R), r2 = rng.pick(NICE_R); if (r1 === r2) throw new GenFail("same"); const p = rng.pick(NICE_P); const c11 = (r1 * p) / 100; const c21 = rng.int(6, r2 - 6); const okc = [[c11, r1 - c11], [c21, r2 - c21]]; const test = (c: number[][]) => c[0][0] + c[0][1] === r1 && c[1][0] + c[1][1] === r2 && c[0][0] * 100 === p * r1;
  const { choices, correctIndex, rules } = twChoices(rng, t, okc, test);
  return choiceInst(rng, { stimulus: `${twIntro(t)} There were ${r1} ${t.r1} and ${r2} ${t.r2}, and ${p}% of the ${t.r1} ${t.yp}.`, question: `Which table could show the results of this survey?`, choices, correctIndex, rules, P: { r1, r2, p }, predicateJs: TWC_PRED("r1 === P.r1 && r2 === P.r2 && c11 * 100 === P.p * r1"), diagnoseJs: twRulesDiag, trace: [[`첫 행의 합계는 ${r1}, 둘째 행의 합계는 ${r2} 이다.`, "Row totals."], [`${t.r1} 의 응답 칸은 ${r1} × ${p}% = ${c11} 이다.`, "First row's cell."], [`네 표의 합계와 칸을 대어 본다.`, "Test the tables."]] as [string, string][], variant: "table_from_two_totals", explainKo: "", explainEn: "" });
} });

// ── 산점도·선그래프 지문형 ──
for (const shape of ["SC", "LG"] as const) {
  const nm = shape === "SC" ? "산점도" : "선그래프";
  push({ kind: "scatter_equation", fig: shape, loc: "P", lv: "easy", name: "slope", structure: `${nm}의 직선에서 기울기를 읽음`, extra: "easy: 두 격자점으로 기울기", concepts: [nm, "기울기"], spr: true, reason: ok, gen(rng) {
    const s = makeLineSrc(shape, rng); const t = s.topic;
    return withBind(figInst(rng, { stimulus: s.intro, question: `What is the slope of ${s.lineRef}?`, correct: r1d(s.m), wrongs: [W(r1d(-s.m), "sign_error", "부호를 거꾸로 읽었다."), W(r1d(s.b), "axis_misread", "절편을 기울기로 읽었다."), W(r1d(1 / s.m), "formula_misuse", "기울기의 역수를 답했다."), W(r1d(s.p2[1]), "axis_misread", "끝점의 y 값을 답했다."), W(r1d(s.m * 2), "other", "계산 중 어긋났다."), W(r1d(s.m + 1), "other", "계산 중 어긋났다.")], verificationJs: figJs({}, s.figure, `${s.extractJs}return m;`), trace: [lineRead(s), slopeStep(s)] as [string, string][], variant: "read_slope" }, s.figure), []);
  } });
  push({ kind: "scatter_equation", fig: shape, loc: "P", lv: "medium", name: "intercept", structure: `${nm}의 직선에서 y 절편(x=0 의 값)을 구함`, extra: "medium: 기울기와 한 점으로 절편 계산", concepts: [nm, "직선의 방정식"], spr: true, reason: ok, gen(rng) {
    const s = makeLineSrc(shape, rng); const t = s.topic;
    return withBind(figInst(rng, { stimulus: s.intro, question: `According to ${s.lineRef}, what is the predicted ${lc(t.ya)} (in ${t.yu}) when ${lc(t.xa)} is 0?`, correct: r1d(s.b), wrongs: [W(r1d(s.m), "axis_misread", "기울기를 절편으로 읽었다."), W(r1d(-s.b), "sign_error", "부호를 거꾸로 답했다."), W(r1d(s.p1[1]), "step_missing", "첫 점의 y 값을 그대로 답했다."), W(r1d(s.p2[1]), "step_missing", "끝점의 y 값을 답했다."), W(r1d(s.b + s.m), "other", "x = 1 의 값을 답했다."), W(r1d(s.b + 5), "other", "계산 중 어긋났다.")], verificationJs: figJs({}, s.figure, `${s.extractJs}return b;`), trace: [lineRead(s), slopeStep(s), [`식 y = ${fmtNum(s.m)}x + b 에 한 점을 대입하면 b = ${fmtNum(s.b)} 이다.`, "Solve for the intercept."]] as [string, string][], variant: "read_intercept" }, s.figure), []);
  } });
  push({ kind: "scatter_predict", fig: shape, loc: "P", lv: "easy", name: "read_end", structure: `${nm}에서 가장 오른쪽 격자의 값을 읽음`, extra: "easy: 그림에서 값 읽기", concepts: [nm, "값 읽기"], spr: true, reason: ok, gen(rng) {
    const s = makeLineSrc(shape, rng); const t = s.topic; const [x2, y2] = s.p2;
    return withBind(figInst(rng, { stimulus: s.intro, question: `According to ${s.lineRef}, what is the predicted ${lc(t.ya)} (in ${t.yu}) when ${lc(t.xa)} is ${x2} ${t.xu}?`, correct: r1d(y2), wrongs: [W(r1d(s.p1[1]), "axis_misread", "첫 점의 값을 읽었다."), W(r1d(y2 + s.S), "axis_misread", "격자 한 칸 위를 읽었다."), W(r1d(Math.max(1, y2 - s.S)), "axis_misread", "격자 한 칸 아래를 읽었다."), W(x2, "axis_misread", "x 값을 답했다."), W(r1d(y2 + s.m), "other", "x 를 한 칸 어긋나게 읽었다.")], verificationJs: figJs({ x2 }, s.figure, `${s.extractJs}return m * P.x2 + b;`), trace: [lineRead(s), [`x = ${x2} 에서 직선의 높이를 격자로 읽으면 ${fmtNum(y2)} 이다.`, "Read the height on the grid."]] as [string, string][], variant: "read_value" }, s.figure), []);
  } });
  push({ kind: "scatter_predict", fig: shape, loc: "P", lv: "medium", name: "predict", structure: `${nm}의 직선으로 x=a 의 예측값을 구함`, extra: "medium: 식을 세워 대입", concepts: [nm, "직선 예측"], spr: true, reason: ok, gen(rng) {
    const s = makeLineSrc(shape, rng); const t = s.topic; const a = rng.int(1, s.X - 1); const pred = s.m * a + s.b; if (!oneDec(pred) || pred <= 0) throw new GenFail("pred");
    return withBind(figInst(rng, { stimulus: s.intro, question: `According to ${s.lineRef}, what is the predicted ${lc(t.ya)} (in ${t.yu}) when ${lc(t.xa)} is ${a} ${t.xu}?`, correct: r1d(pred), wrongs: [W(r1d(s.m * a), "step_missing", "절편을 더하지 않았다."), W(r1d(s.b - s.m * a), "sign_error", "부호를 거꾸로 계산했다."), W(r1d(pred + s.m), "other", "x 를 한 칸 어긋나게 대입했다."), W(r1d(pred - s.m), "other", "x 를 한 칸 어긋나게 대입했다."), W(r1d(s.m + s.b + a), "formula_misuse", "곱하지 않고 더했다."), W(r1d(a * s.b), "formula_misuse", "절편에 x 를 곱했다.")], verificationJs: figJs({ a }, s.figure, `${s.extractJs}return m * P.a + b;`), trace: [lineRead(s), slopeStep(s), [`식은 y = ${fmtNum(s.m)}x + ${fmtNum(s.b)} 이다.`, "Write the equation."], [`x = ${a} 을 대입하면 ${fmtNum(r1d(pred))} 이다.`, "Substitute."]] as [string, string][], variant: "predict_at_value" }, s.figure), []);
  } });
  push({ kind: "scatter_slope_context", fig: shape, loc: "P", lv: "easy", name: "range_change", structure: `${nm}에서 두 격자점 사이의 y 변화량을 읽음`, extra: "easy: 두 값의 차", concepts: [nm, "변화량"], spr: true, reason: ok, gen(rng) {
    const s = makeLineSrc(shape, rng); const t = s.topic; const ans = Math.abs(s.p2[1] - s.p1[1]); if (ans === 0) throw new GenFail("flat");
    return withBind(figInst(rng, { stimulus: s.intro, question: `According to ${s.lineRef}, by how many ${t.yu} does the predicted ${lc(t.ya)} change as ${lc(t.xa)} goes from ${s.p1[0]} to ${s.p2[0]} ${t.xu}?`, correct: r1d(ans), wrongs: [W(r1d(s.p2[1]), "step_missing", "끝값만 답했다."), W(r1d(s.p1[1] + s.p2[1]), "sign_error", "차가 아니라 합을 구했다."), W(r1d(Math.abs(s.m)), "step_missing", "기울기를 답했다."), W(r1d(ans + s.S), "axis_misread", "격자 한 칸 어긋나게 읽었다."), W(r1d(Math.max(1, ans - s.S)), "axis_misread", "격자 한 칸 어긋나게 읽었다.")], verificationJs: figJs({}, s.figure, `${s.extractJs}return Math.abs(m * (${s.p2[0]} - ${s.p1[0]}));`), trace: [lineRead(s), [`변화량 = |${s.p2[1]} - ${s.p1[1]}| = ${fmtNum(ans)} 이다.`, "Take the difference of the two values."]] as [string, string][], variant: "change_over_range" }, s.figure), []);
  } });
  push({ kind: "scatter_slope_context", fig: shape, loc: "P", lv: "medium", name: "unit_slope", structure: `${nm}의 직선에서 x 가 1 늘 때의 y 변화량(기울기)을 구함`, extra: "medium: 변화량 ÷ x 의 변화", concepts: [nm, "기울기의 의미"], spr: true, reason: ok, gen(rng) {
    const s = makeLineSrc(shape, rng); const t = s.topic; const ans = Math.abs(s.m);
    return withBind(figInst(rng, { stimulus: s.intro, question: `According to ${s.lineRef}, by how many ${t.yu} does the predicted ${lc(t.ya)} change for each 1-${sing(t.xu)} increase in ${lc(t.xa)}?`, correct: r1d(ans), wrongs: [W(r1d(ans * (s.p2[0] - s.p1[0])), "step_missing", "x 의 변화로 나누지 않았다."), W(r1d(ans + 1), "other", "계산 중 어긋났다."), W(r1d(Math.max(1, ans - 1)), "other", "계산 중 어긋났다."), W(r1d(s.b), "axis_misread", "절편을 답했다."), W(r1d(ans * 2), "other", "계산 중 어긋났다."), W(r1d((s.p2[0] - s.p1[0]) / ans), "formula_misuse", "기울기의 역수를 답했다.")], verificationJs: figJs({}, s.figure, `${s.extractJs}return Math.abs(m);`), trace: [lineRead(s), slopeStep(s), [`기울기의 크기 ${fmtNum(ans)} 가 x 1 당 변화량이다.`, "The slope is the change per unit."]] as [string, string][], variant: "per_unit_change" }, s.figure), []);
  } });
}

// ── 산점도 추세선 위 점 수(지문형) ──
push({ kind: "scatter_count_above", fig: "SC", loc: "P", lv: "easy", name: "count_points", structure: "산점도에 찍힌 점의 개수를 셈", extra: "easy: 점 개수 세기", concepts: ["산점도", "개수 세기"], spr: true, reason: ok, gen(rng) {
  const s = makeScatter(rng); const n = s.points!.length;
  return withBind(figInst(rng, { stimulus: s.intro, question: `How many data points are shown in the scatterplot?`, correct: n, wrongs: [W(n + 1, "other", "한 개 더 셌다."), W(n - 1, "other", "한 개 덜 셌다."), W(n + 2, "other", "두 개 더 셌다."), W(s.X, "axis_misread", "가로축 끝 값을 답했다."), W(Math.max(1, n - 2), "other", "두 개 덜 셌다.")], verificationJs: figJs({}, s.figure, `return FIGURE.points.length;`), trace: [["산점도의 점을 하나씩 센다.", "Count the dots."], [`점은 모두 ${n}개이다.`, "The total number of dots."]] as [string, string][], variant: "count_points" }, s.figure), []);
} });
push({ kind: "scatter_count_above", fig: "SC", loc: "P", lv: "medium", name: "count_above", structure: "산점도에서 추세선 위에 있는 점의 개수를 셈", extra: "medium: 위쪽 점 수", concepts: ["산점도", "추세선 위·아래"], spr: true, reason: ok, gen(rng) {
  const s = makeScatter(rng); const pts = s.points!; const above = pts.filter((p) => p[1] > s.m * p[0] + s.b).length; if (above === 0 || above === pts.length) throw new GenFail("trivial");
  return withBind(figInst(rng, { stimulus: s.intro, question: `How many of the data points are above the line of best fit?`, correct: above, wrongs: [W(pts.length - above, "opposite", "아래쪽 점의 수를 답했다."), W(pts.length, "condition_ignored", "전체 점의 수를 답했다."), W(above + 1, "other", "한 개 더 셌다."), W(Math.max(0, above - 1), "other", "한 개 덜 셌다."), W(above + 2, "other", "두 개 더 셌다.")], verificationJs: figJs({}, s.figure, `const pts = FIGURE.points, m = FIGURE.fitLine.slope, b = FIGURE.fitLine.intercept; return pts.filter((p) => p[1] > m * p[0] + b).length;`), trace: [["그림에서 추세선의 위치를 읽는다.", "Locate the line."], ["각 점이 추세선보다 위인지 판정한다.", "Judge each point."], [`위쪽 점은 ${above}개이다.`, "Count the points above."]] as [string, string][], variant: "count_above" }, s.figure), []);
} });

// ── 선택지형 산점도(추세선·위 점 수) ──
push({ kind: "scatter_equation", fig: "SC", loc: "C", lv: "easy", name: "sign_intercept", structure: "추세선의 기울기 부호와 y 절편을 주고 그 산점도를 고름", extra: "easy: 부호와 절편 두 가지만 확인", concepts: ["추세선", "기울기 부호·절편"], spr: false, reason: MC_ONLY, gen(rng) {
  const t = rng.pick(SE_TOPICS); const S = rng.pick([5, 10, 20]); const ln = pickLine(rng, S, 10 * S); const up = ln.m > 0; const test = (m: number, b: number) => Math.sign(m) === Math.sign(ln.m) && Math.abs(b - ln.b) < 1e-9;
  const { choices, correctIndex, rules } = scChoices(rng, t, ln, test);
  return choiceInst(rng, { stimulus: `Researchers studied ${scTopicWords(t)}. A line of best fit for the data predicts ${ln.b} ${t.yu} when ${lc(t.xa)} is 0, and the predicted value ${up ? "increases" : "decreases"} as ${lc(t.xa)} increases.`, question: `Which scatterplot shows this line of best fit?`, choices, correctIndex, rules, P: { b: ln.b, dir: up ? 1 : -1 }, predicateJs: SC_PRED("Math.sign(m) === P.dir && Math.abs(b - P.b) < 1e-9"), diagnoseJs: lineDiag, trace: [[`x = 0 에서 ${ln.b} 이므로 y 절편은 ${ln.b} 이다.`, "Read the intercept."], [`${up ? "증가" : "감소"}하므로 기울기는 ${up ? "양수" : "음수"}이다.`, "Read the slope's sign."], [`두 조건을 모두 만족하는 그래프를 고른다.`, "Pick the graph meeting both."]] as [string, string][], variant: "line_from_sign_and_intercept", explainKo: "", explainEn: "" });
} });
push({ kind: "scatter_equation", fig: "SC", loc: "C", lv: "medium", name: "slope_and_point", structure: "추세선의 기울기와 한 점의 예측값을 주고 그 산점도를 고름", extra: "medium: 기울기와 한 예측값으로 절편을 구함", concepts: ["추세선", "한 점으로 절편"], spr: false, reason: MC_ONLY, gen(rng) {
  const t = rng.pick(SE_TOPICS); const S = rng.pick([5, 10, 20]); const x0 = rng.pick([2, 4, 6]); const ln = pickLine(rng, S, 10 * S, (m, b) => oneDec(m * x0 + b)); const y0 = r1d(ln.m * x0 + ln.b); const test = (m: number, b: number) => Math.abs(m - ln.m) < 1e-9 && Math.abs(m * x0 + b - y0) < 1e-9; const up = ln.m > 0;
  const { choices, correctIndex, rules } = scChoices(rng, t, ln, test);
  return choiceInst(rng, { stimulus: `Researchers studied ${scTopicWords(t)}. A line of best fit for the data has a slope of ${fmtNum(ln.m)} and predicts ${fmtNum(y0)} ${t.yu} when ${lc(t.xa)} is ${x0} ${t.xu}.`, question: `Which scatterplot shows this line of best fit?`, choices, correctIndex, rules, P: { m: ln.m, x0, y0 }, predicateJs: SC_PRED("Math.abs(m - P.m) < 1e-9 && Math.abs(m * P.x0 + b - P.y0) < 1e-9"), diagnoseJs: lineDiag, trace: [[`기울기는 ${fmtNum(ln.m)} (${up ? "증가" : "감소"})이다.`, "The slope is given."], [`x = ${x0} 에서 ${fmtNum(y0)} 이므로 ${fmtNum(y0)} = ${fmtNum(ln.m)}·${x0} + b 이다.`, "Use the one prediction."], [`b = ${ln.b} 이다.`, "Solve for b."], [`그 직선이 그려진 그래프를 고른다.`, "Pick the graph with that line."]] as [string, string][], variant: "line_from_slope_and_point", explainKo: "", explainEn: "" });
} });
const ctByCount = (rng: Rng, S: number, yMax: number, t: (typeof SE_TOPICS)[number], A: number, wrongCounts: number[]) => placeChoices(rng, ctPlot(rng, t, S, yMax, A), wrongCounts.map((k) => ({ fig: ctPlot(rng, t, S, yMax, k), rule: `above_${k}` })));
const ctGenericDiag = `const cnt = (ch) => { const s = ch.objects.find((o) => o.kind === 'scatter'); return s.points.filter((p) => p[1] > s.fitLine.slope * p[0] + s.fitLine.intercept).length; }; return 'above_' + cnt(c);`;
push({ kind: "scatter_count_above", fig: "SC", loc: "C", lv: "easy", name: "majority_above", structure: "추세선 위의 점이 아래보다 많은 산점도를 고름", extra: "easy: 위·아래 개수 비교(많다/적다)", concepts: ["산점도", "위·아래 비교"], spr: false, reason: MC_ONLY, gen(rng) {
  const t = rng.pick(SE_TOPICS); const S = rng.pick([5, 10, 20]); const yMax = 10 * S; const A = rng.int(6, 9); const wrong = rng.shuffle([1, 2, 3, 4]).slice(0, 3); const { choices, correctIndex, rules } = ctByCount(rng, S, yMax, t, A, wrong);
  return choiceInst(rng, { stimulus: `Each scatterplot shows ${scTopicWords(t)} for 10 data points, along with a line of best fit.`, question: `Which scatterplot has more data points above its line of best fit than below it?`, choices, correctIndex, rules, P: {}, predicateJs: `const s = c.objects.find((o) => o.kind === 'scatter'); const above = s.points.filter((p) => p[1] > s.fitLine.slope * p[0] + s.fitLine.intercept).length; return above > s.points.length - above;`, diagnoseJs: ctGenericDiag, trace: [["각 그래프에서 추세선의 위치를 읽는다.", "Locate each line."], ["점을 위·아래로 나눠 센다.", "Count above and below."], ["위쪽이 더 많은 그래프를 고른다.", "Pick the graph with more above."]] as [string, string][], variant: "more_above_than_below", explainKo: "", explainEn: "" });
} });
push({ kind: "scatter_count_above", fig: "SC", loc: "C", lv: "medium", name: "at_least", structure: "추세선 위의 점이 7개 이상인 산점도를 고름", extra: "medium: 임계 개수(이상)", concepts: ["산점도", "개수 임계"], spr: false, reason: MC_ONLY, gen(rng) {
  const t = rng.pick(SE_TOPICS); const S = rng.pick([5, 10, 20]); const yMax = 10 * S; const A = rng.int(7, 9); const wrong = rng.shuffle([2, 3, 4, 5, 6]).slice(0, 3); const { choices, correctIndex, rules } = ctByCount(rng, S, yMax, t, A, wrong);
  return choiceInst(rng, { stimulus: `Each scatterplot shows ${scTopicWords(t)} for 10 data points, along with a line of best fit.`, question: `Which scatterplot has at least 7 data points above its line of best fit?`, choices, correctIndex, rules, P: {}, predicateJs: `const s = c.objects.find((o) => o.kind === 'scatter'); return s.points.filter((p) => p[1] > s.fitLine.slope * p[0] + s.fitLine.intercept).length >= 7;`, diagnoseJs: ctGenericDiag, trace: [["각 그래프에서 추세선의 위치를 읽는다.", "Locate each line."], ["그래프마다 위쪽 점 수를 센다.", "Count above in each graph."], ["위쪽이 7개 이상인 그래프를 고른다.", "Pick the graph with at least 7 above."]] as [string, string][], variant: "at_least_seven_above", explainKo: "", explainEn: "" });
} });

// ── 연관 방향·강도 ──
const DIRCLAIMS = ["As the horizontal value increases, the vertical value tends to increase.", "As the horizontal value increases, the vertical value tends to decrease.", "As the horizontal value increases, the vertical value stays about the same.", "As the horizontal value increases, the vertical value first increases and then decreases."];
push({ kind: "association_direction_strength", fig: "SC", loc: "P", lv: "easy", name: "direction", structure: "산점도를 보고 x 가 늘 때 y 의 경향(증가·감소·변화 없음)을 고름", extra: "easy: 방향만 판단", concepts: ["산점도", "상관의 방향"], spr: false, reason: MC_ONLY, gen(rng) {
  const t = rng.pick(SE_TOPICS); const c = rng.pick(["pos_strong", "neg_strong", "none"] as AClass[]); const pts = samplePts(rng, c); const order = rng.shuffle([0, 1, 2, 3]); const opts = order.map((i) => DIRCLAIMS[i]); const want = c === "none" ? 2 : c.startsWith("pos") ? 0 : 1;
  return indexInst(rng, { stimulus: `The scatterplot shows ${scTopicWords(t)} for 10 data points.`, question: `Which of the following best describes the trend in the scatterplot?`, options: opts, correctIndex: order.indexOf(want), figure: mkAssocFig(t, pts), P: {}, body: `${CLASS_JS}const want = cls(FIGURE.points).split('_')[0]; const kind = (o0) => { const o = o0.split(', ')[1]; return /first increases/.test(o) ? 'curve' : /stays about the same/.test(o) ? 'none' : /increase/.test(o) ? 'pos' : 'neg'; }; const hit = P.options.map(kind).map((k, i) => (k === want ? i : -1)).filter((i) => i >= 0); if (hit.length !== 1) throw new Error('일치 선지 ' + hit.length); return hit[0];`, trace: [["점들이 왼쪽에서 오른쪽으로 가며 올라가는지 내려가는지 본다.", "Look at the overall trend."], ["올라가면 증가, 내려가면 감소, 뚜렷한 방향이 없으면 변화 없음이다.", "Map the trend to a statement."]] as [string, string][], variant: "trend_direction" });
} });
push({ kind: "association_direction_strength", fig: "SC", loc: "P", lv: "medium", name: "strength", structure: "방향은 정해진 상태에서 연관의 강도(강함·보통·약함·없음)를 고름", extra: "medium: 강도만 판단", concepts: ["산점도", "상관의 강도"], spr: false, reason: MC_ONLY, gen(rng) {
  const t = rng.pick(SE_TOPICS); const dir = rng.pick(["pos", "neg"]); const c = rng.pick(["strong", "moderate", "weak"]).replace(/^/, `${dir}_`) as AClass; const pts = samplePts(rng, c); const set: AClass[] = [`${dir}_strong`, `${dir}_moderate`, `${dir}_weak`, "none"] as AClass[]; const texts = rng.shuffle(set.map((k) => claimOf(k)));
  return indexInst(rng, { stimulus: `The scatterplot shows ${scTopicWords(t)} for 10 data points.`, question: `Which of the following best describes the association shown in the scatterplot?`, options: texts, correctIndex: texts.indexOf(claimOf(c)), figure: mkAssocFig(t, pts), P: {}, body: `${CLASS_JS}${PARSE_JS}const want = cls(FIGURE.points); const hit = P.options.map(parse).map((k, i) => (k === want ? i : -1)).filter((i) => i >= 0); if (hit.length !== 1) throw new Error('일치 선지 ' + hit.length); return hit[0];`, trace: [["점들이 올라가는지 내려가는지로 방향을 확인한다(모든 선지가 같은 방향).", "The direction is the same in the options."], ["점이 한 직선 주변에 모인 정도로 강도를 정한다.", "Judge the strength."], ["강도에 맞는 서술을 고른다.", "Pick the matching statement."]] as [string, string][], variant: "strength_only" });
} });
const classRule = (cls: AClass[], correct: AClass) => cls.map((k) => (k === correct ? "correct" : `class_${k}`));
const classDiag = `${CLASS_JS}return 'class_' + cls(c.objects.find((o) => o.kind === 'scatter').points);`;
const asEm = (rng: Rng, t: (typeof SE_TOPICS)[number], correct: AClass, wrong: AClass[]) => placeChoices(rng, (() => { const pts = samplePts(rng, correct); return planeScatter(t, 20, 100, pts, ols2(pts)); })(), wrong.map((k) => ({ fig: (() => { const pts = samplePts(rng, k); return planeScatter(t, 20, 100, pts, ols2(pts)); })(), rule: `class_${k}` })));
import { ols as ols2 } from "../figure-kit";
push({ kind: "association_direction_strength", fig: "SC", loc: "C", lv: "easy", name: "none", structure: "연관이 없는(점이 무작위로 흩어진) 산점도를 고름", extra: "easy: 연관 없음 식별", concepts: ["산점도", "연관 없음"], spr: false, reason: MC_ONLY, gen(rng) {
  const t = rng.pick(SE_TOPICS); const wrong = rng.shuffle(["pos_strong", "neg_strong", "pos_moderate", "neg_moderate"] as AClass[]).slice(0, 3); const { choices, correctIndex, rules } = asEm(rng, t, "none", wrong);
  return choiceInst(rng, { stimulus: `Each scatterplot shows ${scTopicWords(t)} for 10 data points, along with a line of best fit.`, question: `Which scatterplot shows no clear association between ${lc(t.xa)} and ${lc(t.ya)}?`, choices, correctIndex, rules, P: {}, predicateJs: `${CLASS_JS}return cls(c.objects.find((o) => o.kind === 'scatter').points) === 'none';`, diagnoseJs: classDiag, trace: [["점이 하나의 직선 주변에 모였는지 본다.", "Look for clustering around a line."], ["뚜렷한 추세 없이 흩어진 그래프가 연관이 없는 그래프이다.", "The scattered graph has no association."]] as [string, string][], variant: "no_association", explainKo: "", explainEn: "" });
} });
push({ kind: "association_direction_strength", fig: "SC", loc: "C", lv: "medium", name: "negative", structure: "음의 연관(강도 무관)을 보이는 산점도를 고름", extra: "medium: 방향 판단(강도 무관) 후 양의 연관·연관 없음 제외", concepts: ["산점도", "음의 연관"], spr: false, reason: MC_ONLY, gen(rng) {
  const t = rng.pick(SE_TOPICS); const c = rng.pick(["neg_strong", "neg_moderate", "neg_weak"] as AClass[]); const wrong = ["pos_strong", "none", rng.pick(["pos_weak", "pos_moderate"] as AClass[])]; const { choices, correctIndex, rules } = asEm(rng, t, c, wrong as AClass[]);
  return choiceInst(rng, { stimulus: `Each scatterplot shows ${scTopicWords(t)} for 10 data points, along with a line of best fit.`, question: `Which scatterplot shows a negative association between ${lc(t.xa)} and ${lc(t.ya)}?`, choices, correctIndex, rules, P: {}, predicateJs: `${CLASS_JS}return cls(c.objects.find((o) => o.kind === 'scatter').points).startsWith('neg');`, diagnoseJs: classDiag, trace: [["추세선이 오른쪽 아래로 내려가는 그래프를 찾는다.", "Find graphs whose line slopes downward."], ["위로 올라가는 그래프와 방향이 뚜렷하지 않은 그래프를 지운다.", "Remove upward and directionless graphs."], ["남은 그래프가 음의 연관이다.", "The remaining graph is the negative association."]] as [string, string][], variant: "negative_association", explainKo: "", explainEn: "" });
} });

export const FIG_LEVELS: LArch[] = defs.map(mk);
export { classRule, ABCD, isInt, frac, PX };
