// nonlinear_functions.zeros_end_behavior_polynomial.FN.C — 삼차 곡선 그래프(y 눈금은 x 와 독립) 4개를 선택지로 주고, 영점·끝 모양·최고차항 계수·y 절편 조건 두 개를 모두 만족하는 그래프를 고른다.
import { GenFail, type OperatorId } from "../../../types";
import type { Rng } from "../../../rng";
import { defineItem } from "../item-kit";
import { C_LEADS, SPR_NO_PLANE_CHOICE, cInst, poolChoices, twoCond } from "../cplane-kit";
import { cubExt, cubFn, cubicFig, pickScale } from "../cubic-kit";

type S = { X: number; Y: number; sy: number; A: number; rs: [number, number, number] };
const ROOTS = (X: number) => { const out: number[] = []; for (let r = -(X - 1); r <= X - 1; r++) if (r !== 0 && Math.abs(r) !== 1 && Math.abs(r) !== 3 && Math.abs(r) !== 6) out.push(r); return out; };
const triples = (X: number): [number, number, number][] => { const p = ROOTS(X), out: [number, number, number][] = []; for (let i = 0; i < p.length; i++) for (let j = i + 1; j < p.length; j++) for (let k = j + 1; k < p.length; k++) if (p[j] - p[i] >= 2 && p[k] - p[j] >= 2) out.push([p[i], p[j], p[k]]); return out; };
const figOf = (s: S) => cubicFig(s.X, s.Y, s.sy, s.A, s.rs, null);
const yint = (s: S) => -s.A * s.rs[0] * s.rs[1] * s.rs[2];
const STAT = "const o=c.objects.find(q=>q.kind==='function'&&q.fn==='cubic'); if(!o) throw new Error('삼차함수 필요'); const [A,B,C,D]=o.params; const f=(x)=>A*x*x*x+B*x*x+C*x+D; const rs=[]; for (let x=-30;x<=30;x++) if (Math.abs(f(x))<1e-9) rs.push(x); return {A, D, rs};";
/** (Y, sy) 가 정해진 장면에서 눈금에 맞는 모든 그림(곡선만). */
function poolFor(X: number, Y: number): unknown[] { const sy = [[20, 5], [30, 5], [40, 10], [60, 10], [80, 20], [100, 20]].find((p) => p[0] === Y)![1]; const out: unknown[] = []; for (const rs of triples(X)) for (const A of [-2, -1, 1, 2]) { const e = cubExt(A, rs); if (e > Y * 1.05 || e < Y * 0.25) continue; out.push(figOf({ X, Y, sy, A, rs })); } return out; }
function okScene(rng: Rng, pred: (s: S) => boolean = () => true): S { for (let t = 0; t < 4000; t++) { const X = rng.pick([6, 8]); const ts = triples(X); const rs = rng.pick(ts); const A = rng.pick([-2, -1, 1, 2]); const sc = pickScale(cubExt(A, rs)); if (!sc) continue; const s: S = { X, Y: sc[0], sy: sc[1], A, rs }; const y0 = cubFn(A, rs)(0); if (Math.abs(y0) > s.Y * 0.95 || Math.abs(y0) < 0.12 * s.Y) continue; if (pred(s)) return s; } throw new GenFail("삼차 장면"); }
const endTxt = (up: boolean) => (up ? "increases without bound as $x$ increases" : "decreases without bound as $x$ increases");
const sg = (n: number) => (n < 0 ? `-${-n}` : `${n}`);
type B = { clause: string; P: Record<string, number>; A: string; Bj: string; rules: [string, string, string]; ok: S; tag: string; trace: [string, string][] };
const BUILD: Record<string, (rng: Rng) => B> = {
  twoZerosEnd(rng) { const s = okScene(rng); const [i, j] = rng.pick([[0, 1], [0, 2], [1, 2]]); const p = s.rs[i], q = s.rs[j]; const up = s.A > 0; return { tag: "two_zeros_end", clause: rng.pick([`has zeros at $x = ${p}$ and $x = ${q}$, and the function ${endTxt(up)}`, `the function ${endTxt(up)} and its graph crosses the $x$-axis at ${p} and at ${q}`]), P: { p, q, up: up ? 1 : 0 }, A: "s.rs.includes(P.p) && s.rs.includes(P.q)", Bj: "(s.A > 0 ? 1 : 0) === P.up", rules: ["zeros_off", "end_off", "both_off"], ok: s, trace: [[`영점 ${p}, ${q} 이고 최고차항 계수는 ${up ? "양수" : "음수"}이다.`, "Two zeros and the end behavior."]] }; },
  threeZeros(rng) { const s = okScene(rng); const up = s.A > 0; const [a, b, c] = s.rs; return { tag: "three_zeros_end", clause: rng.pick([`has zeros at $x = ${a}$, $x = ${b}$, and $x = ${c}$, and the function ${endTxt(up)}`, `the function ${endTxt(up)} and has exactly the zeros ${a}, ${b}, and ${c}`]), P: { a, b, c, up: up ? 1 : 0 }, A: "s.rs.length === 3 && s.rs[0] === P.a && s.rs[1] === P.b && s.rs[2] === P.c", Bj: "(s.A > 0 ? 1 : 0) === P.up", rules: ["zeros_off", "end_off", "both_off"], ok: s, trace: [[`세 영점 ${a}, ${b}, ${c} 이고 끝 모양은 ${up ? "위로" : "아래로"} 열린다.`, "All three zeros and the end behavior."]] }; },
  zeroYint(rng) { const s = okScene(rng, (x) => Math.abs(yint(x)) <= 99); const r = rng.pick(s.rs); const d = yint(s); return { tag: "zero_and_yint", clause: rng.pick([`has a zero at $x = ${r}$ and crosses the $y$-axis at $y = ${sg(d)}$`, `crosses the $y$-axis at $y = ${sg(d)}$ and has $x = ${r}$ as a zero`]), P: { r, d }, A: "s.rs.includes(P.r)", Bj: "s.D === P.d", rules: ["zero_off", "yint_off", "both_off"], ok: s, trace: [[`영점 ${r} 이고 y 절편은 ${d} 이다.`, "A zero and the y-intercept."]] }; },
  zeroLead(rng) { const s = okScene(rng); const r = rng.pick(s.rs); return { tag: "zero_and_leading", clause: rng.pick([`has a zero at $x = ${r}$ and a leading coefficient of ${sg(s.A)}`, `has $x = ${r}$ as a zero, and its leading coefficient is ${sg(s.A)}`]), P: { r, a: s.A }, A: "s.rs.includes(P.r)", Bj: "s.A === P.a", rules: ["zero_off", "leading_off", "both_off"], ok: s, trace: [[`영점 ${r} 이고 최고차항 계수는 ${s.A} 이다.`, "A zero and the leading coefficient."]] }; },
};
const OPS: OperatorId[] = ["repr_shift", "chain2", "compose_kind", "inverse"];
const MENU = ["twoZerosEnd", "threeZeros", "zeroYint", "zeroLead"];
const STEMS = ["Four graphs of cubic functions are shown in the $xy$-plane, all with the same axes. Note that the $y$-axis scale differs from the $x$-axis scale.", "The four graphs shown are cubic curves drawn on identical $xy$-plane axes, with different scales on the two axes.", "Each of the four graphs shown is a cubic curve in the same $xy$-plane, whose $y$-axis marks are spaced differently from its $x$-axis marks.", "Four candidate cubic curves are shown, graphed on one set of axes with different units on each axis.", "The choices shown are four cubic graphs that share the same axes; the $y$-axis scale is not the same as the $x$-axis scale."];
const QS = (c: string) => [`Which of the four graphs shown is a cubic function that ${c}?`, `Which graph shown is the graph of a cubic polynomial that ${c}?`, `Exactly one of the four cubic graphs shown ${c}. Which one is it?`, `Of the graphs shown, which cubic function ${c}?`];
const make = (rng: Rng, key: string) => { const bd = BUILD[key](rng); const c = twoCond(STAT, bd.A, bd.Bj, bd.rules); const ch = poolChoices(rng, { ok: figOf(bd.ok), pool: poolFor(bd.ok.X, bd.ok.Y), P: bd.P, ...c }); return { ch, bd, c }; };
const trail: [string, string][] = [["각 그래프에서 곡선이 x 축과 만나는 눈금과 오른쪽 끝의 방향을 읽는다.", "Read where each curve crosses the x-axis and which way its right end goes."], ["첫째 조건을 어긴 그래프를 지운다.", "Eliminate the graphs that fail the first condition."], ["둘째 조건을 어긴 그래프를 지운다.", "Eliminate the graphs that fail the second condition."], ["남은 그래프가 정답이다.", "The remaining graph is the answer."]];

export const ITEM = defineItem({
  prefix: "zebc", itemId: "nonlinear_functions.zeros_end_behavior_polynomial.FN.C",
  hard: MENU.map((key, i) => ({ op: OPS[i], sprNo: SPR_NO_PLANE_CHOICE, structure: `삼차함수 조건(${key}) 두 개를 서술로 주고 두 조건을 모두 만족하는 그래프를 4개 중에서 고름`, extra: "두 조건을 각각 따져 네 그래프를 대조해야 함(한 조건만 맞는 그래프가 함정)", concepts: ["삼차함수 그래프", "영점", "끝 모양"],
    gen(rng: Rng) { const { ch, bd, c } = make(rng, key); return cInst(rng, ch, { stimulus: `${rng.pick(C_LEADS)}${rng.pick(STEMS)}`, question: rng.pick(QS(bd.clause)), P: bd.P, ...c, variant: `cubic_${bd.tag}`, trace: [...bd.trace, ...trail] }, ["다른 그래프는 조건 하나 이상이 어긋난다.", "Each other graph violates at least one condition."]); } })),
  em: [
    { lv: "easy" as const, name: "end_only", sprNo: SPR_NO_PLANE_CHOICE, structure: "끝 모양 하나로 삼차 그래프 4개 중 고름", extra: "easy: 한 조건", concepts: ["삼차함수 그래프", "끝 모양"],
      gen(rng: Rng) { const s = okScene(rng); const up = s.A > 0; const P = { up: up ? 1 : 0 }; const pre = `const s = ((c) => { ${STAT} })(c);`; const rule = "const k = s.rs.join(','); return 'z' + k;"; const c = { predicateJs: `${pre} return (s.A > 0 ? 1 : 0) === P.up;`, diagnoseJs: `${pre} if ((s.A > 0 ? 1 : 0) === P.up) return null; ${rule}` }; const ch = poolChoices(rng, { ok: figOf(s), pool: poolFor(s.X, s.Y), P, ...c }); return cInst(rng, ch, { stimulus: `${rng.pick(C_LEADS)}${rng.pick(STEMS)}`, question: rng.pick([`Which of the four graphs shown is a cubic function that ${endTxt(up)}?`, `For which graph shown does the function ${endTxt(up)}?`, `Of the graphs shown, which cubic function ${endTxt(up)}?`, `Exactly one of the four cubic graphs shown ${endTxt(up)}. Which one is it?`, `Which cubic curve among the choices shown ${endTxt(up)}?`, `One of the four curves shown ${endTxt(up)}. Which graph is it?`]), P, ...c, variant: "cubic_end_only", trace: [[`오른쪽 끝이 ${up ? "위로" : "아래로"} 향하는 그래프를 찾는다.`, "Find the graph whose right end goes the given way."], ["나머지 그래프는 끝 모양이 달라 지운다.", "Eliminate the other end behaviors."]] }, ["끝 모양이 다른 그래프는 정답이 아니다.", "Other end behaviors are wrong."]); } },
    { lv: "medium" as const, name: "medium_two_zeros", sprNo: SPR_NO_PLANE_CHOICE, structure: "영점 두 개와 끝 모양으로 삼차 그래프 4개 중 고름", extra: "medium: 두 조건", concepts: ["삼차함수 그래프", "영점", "끝 모양"],
      gen(rng: Rng) { const { ch, bd, c } = make(rng, "twoZerosEnd"); return cInst(rng, ch, { stimulus: `${rng.pick(C_LEADS)}${rng.pick(STEMS)}`, question: rng.pick([...QS(bd.clause), `Select the cubic graph shown that ${bd.clause}.`, `One cubic graph shown ${bd.clause}. Which one is it?`]), P: bd.P, ...c, variant: "cubic_two_zeros_end_med", trace: [...bd.trace, ["조건을 어긴 그래프를 지운다.", "Eliminate the graphs that fail a condition."], ["남은 그래프가 정답이다.", "The remaining graph is the answer."]] }, ["다른 그래프는 조건 하나 이상이 어긋난다.", "Each other graph violates at least one condition."]); } },
  ],
});
