// nonlinear_functions.exponential_vs_linear_growth.FN.P — 한 그래프에 지수 곡선 f 와 직선 g 가 함께 그려져 있고, 그림 밖에서 두 함수를 비교한다.
import { GenFail } from "../../../types";
import type { Rng } from "../../../rng";
import { fmtNum } from "../../../text";
import { W } from "../../d-kit";
import { figInst, figJs } from "../../../figure-kit";
import { defineItem } from "../item-kit";
import { EXP_JS, makeExp, type ExpX } from "../pure-fn-kit";

const isI = Number.isInteger;
type EL = ExpX & { c: number; d: number; g: (x: number) => number };
/** f(곡선) + g(직선, 정수 기울기·절편, 그림 안에서 f 와 g 가 아직 만나지 않거나 한 번 만남). g 에 라벨 "g". */
function scene(rng: Rng): EL {
  for (let t = 0; t < 400; t++) {
    const e = makeExp(rng, "f"); if (e.b <= 1) continue; const d = rng.int(2, 9); const c = rng.int(1, Math.max(1, Math.floor(e.Y / 5))); const g = (x: number) => c + d * x;
    if (g(e.X) > e.Y * 0.95 || g(e.X) < e.Y * 0.2) continue; if (e.y(e.X) <= g(e.X) * 0.6) continue; if (e.y(0) >= g(0) + 1) continue; // 처음에는 g 가 위(또는 같음), 끝 근처에서 f 가 따라잡음
    const fig = JSON.parse(JSON.stringify(e.fig)); fig.objects[0].label = "f"; fig.objects.push({ id: "L1", kind: "line", through: [[0, c], [e.X, g(e.X)]], label: "g" });
    return { ...e, fig, c, d, g };
  }
  throw new GenFail("지수·직선 장면 표집 실패");
}
const G_JS = "const GL=FIGURE.objects.find(o=>o.kind==='line'); const gc=GL.through[0][1], gd=(GL.through[1][1]-GL.through[0][1])/(GL.through[1][0]-GL.through[0][0]); const g=(x)=>gc+gd*x;\n";
const intro = (rng: Rng) => rng.pick(["", "", "A student compares two functions in algebra class. ", "A graphing program plots two functions. ", "A teacher draws two curves on a grid. ", "In a practice set, two functions are shown as graphs. ", "During a lesson on growth, a class graphs two functions. "]) + rng.pick(["The graphs of the exponential function $f$ and the linear function $g$ are shown in the $xy$-plane, with three points marked on the graph of $f$.", "The figure shows the graph of an exponential function $f$ (with three marked points) and a linear function $g$ in the $xy$-plane.", "In the $xy$-plane shown, $f$ is an exponential function whose graph has three marked points, and $g$ is a linear function.", "Two functions are graphed in the $xy$-plane shown: the exponential function $f$, with three marked points, and the linear function $g$.", "The $xy$-plane shown has the graph of the linear function $g$ and the graph of the exponential function $f$, which has three marked points.", "A linear function $g$ and an exponential function $f$ are graphed together; three points on the graph of $f$ are marked."]);
const form = (rng: Rng) => rng.pick(["Here $f(x) = a \\cdot b^x$ for positive constants $a$ and $b$.", "The exponential function is $f(x) = a \\cdot b^x$, where $a$ and $b$ are positive constants.", "Let $f(x) = a \\cdot b^x$, with $a > 0$ and $b > 0$."]);
const rd = (e: EL): [string, string][] => [
  [`곡선 f 의 표시점 ${e.xs.map((x, i) => `(${x}, ${e.ys[i]})`).join(", ")} 를 읽는다.`, "Read the marked points of f."],
  [`연속한 값의 비로 b = ${fmtNum(e.b)}, a = ${e.a} 를 구한다.`, "Find b and a from the marked points of f."],
  [`직선 g 는 (0, ${e.c}) 와 (${e.X}, ${e.g(e.X)}) 를 지나므로 g(x) = ${e.d}x + ${e.c} 이다.`, "Read g from its two lattice points."],
];

export const ITEM = defineItem({
  prefix: "evlg", itemId: "nonlinear_functions.exponential_vs_linear_growth.FN.P",
  hard: [
    { op: "repr_shift", structure: "곡선 f 와 직선 g 의 식을 세워 그림 밖의 x 에서 f(x) - g(x) 를 구함", extra: "곡선은 거듭제곱, 직선은 일차식으로 각각 계산해 빼야 함(직선처럼 늘려 f 를 구하는 것이 함정) — medium 은 그림 안", concepts: ["지수 그래프", "직선 그래프", "식 세우기"],
      gen(rng) { const e = scene(rng); const x = e.X + rng.int(2, 4); const fv = e.y(x), gv = e.g(x); const ans = fv - gv; if (!isI(fv) || ans <= 0 || fv > 999) throw new GenFail("v"); return figInst(rng, { stimulus: `${intro(rng)} ${form(rng)}`, question: rng.pick([`What is the value of $f(${x}) - g(${x})$?`, `How much greater is $f(${x})$ than $g(${x})$?`, `Find $f(${x}) - g(${x})$.`]), correct: ans, wrongs: [W(fv, "step_missing", "f 의 값만 답했다."), W(gv, "step_missing", "g 의 값만 답했다."), W(Math.round(e.ys[2] + (e.ys[2] - e.ys[1]) * (x - e.xs[2])) - gv, "formula_misuse", "f 를 일정한 차로 늘려 계산했다."), W(ans + e.d, "other", "어긋났다.")].filter((w) => isI(w.v) && w.v !== ans), verificationJs: figJs({ x }, e.fig, `${EXP_JS}${G_JS}return f(P.x) - g(P.x);`), trace: [...rd(e), [`f(${x}) = ${e.a} · ${fmtNum(e.b)}^${x} = ${fv} 이다.`, "Evaluate f."], [`g(${x}) = ${e.d}(${x}) + ${e.c} = ${gv} 이므로 차는 ${ans} 이다.`, "Evaluate g and subtract."]], variant: "difference_outside" }, e.fig); } },
    { op: "chain2", structure: "0 ≤ x ≤ N 의 정수 중 f(x) > g(x) 인 x 의 개수를 셈", extra: "두 식으로 정수마다 비교해 곡선이 직선을 넘는 시점을 찾고 개수를 세야 함(그림 끝에서 멈추는 것이 함정) — medium 은 한 점 비교", concepts: ["지수 그래프", "직선 그래프", "식 비교"],
      gen(rng) { const e = scene(rng); const N = e.X + rng.int(3, 6); let n = 0; for (let x = 0; x <= N; x++) if (e.y(x) > e.g(x)) n++; if (n === 0 || n === N + 1 || e.y(N) > 5e4) throw new GenFail("n"); return figInst(rng, { stimulus: `${intro(rng)} ${form(rng)}`, question: rng.pick([`For how many integer values of $x$ with $0 \\le x \\le ${N}$ is $f(x) > g(x)$?`, `How many integers $x$ from 0 to ${N}, inclusive, satisfy $f(x) > g(x)$?`, `The inequality $f(x) > g(x)$ is true for how many integers $x$ in the interval $[0, ${N}]$?`, `Among the integers from 0 through ${N}, for how many is the exponential function $f$ greater than the linear function $g$?`]), correct: n, wrongs: [W(N + 1 - n, "sign_error", "g 가 더 큰 값의 개수를 셌다."), W(n - 1, "other", "한 칸 어긋났다."), W(n + 1, "other", "한 칸 어긋났다."), W(N + 1, "condition_ignored", "모든 정수를 셌다.")].filter((w) => isI(w.v) && w.v !== n && w.v >= 0), verificationJs: figJs({ N }, e.fig, `${EXP_JS}${G_JS}let n=0; for (let x=0;x<=P.N;x++) if (f(x)>g(x)+1e-9) n++; return n;`), trace: [...rd(e), [`f(x) = ${e.a} · ${fmtNum(e.b)}^x, g(x) = ${e.d}x + ${e.c} 이다.`, "Write both equations."], [`x = 0 부터 ${N} 까지 f(x) 와 g(x) 를 비교한다.`, "Compare at each integer."], [`f(x) > g(x) 인 정수는 ${n}개이다.`, "Count them."]], variant: "count_f_above_g" }, e.fig); } },
    { op: "compose_kind", structure: "f 와 g 의 식을 세워 그림 밖의 x 에서 f(x) + g(x) 를 구함", extra: "곡선과 직선을 각각 계산해 더해야 함(f 만 쓰는 것이 함정) — medium 은 그림 안", concepts: ["지수 그래프", "직선 그래프", "합"],
      gen(rng) { const e = scene(rng); const x = e.X + rng.int(1, 3); const fv = e.y(x), gv = e.g(x); const ans = fv + gv; if (!isI(fv) || fv > 999) throw new GenFail("v"); return figInst(rng, { stimulus: `${intro(rng)} ${form(rng)}`, question: rng.pick([`What is the value of $f(${x}) + g(${x})$?`, `Find $f(${x}) + g(${x})$.`, `What is the sum $f(${x}) + g(${x})$?`, `What is the combined value of $f$ and $g$ at $x = ${x}$?`, `If the outputs of $f$ and $g$ at $x = ${x}$ are added, what is the result?`]), correct: ans, wrongs: [W(fv, "step_missing", "f 의 값만 답했다."), W(fv - gv, "sign_error", "차를 답했다."), W(gv, "step_missing", "g 의 값만 답했다."), W(ans + e.d, "other", "어긋났다.")].filter((w) => isI(w.v) && w.v !== ans), verificationJs: figJs({ x }, e.fig, `${EXP_JS}${G_JS}return f(P.x) + g(P.x);`), trace: [...rd(e), [`f(${x}) = ${fv}, g(${x}) = ${gv} 이다.`, "Evaluate both."], [`합 = ${ans} 이다.`, "Add."]], variant: "sum_outside" }, e.fig); } },
    { op: "inverse", structure: "g(x) = Y 가 되는 x 를 구한 뒤 그 x 에서의 f 의 값을 구함", extra: "직선을 거꾸로 풀고 그 x 를 곡선 식에 넣는 2단 역방향 연쇄 — medium 은 g 만", concepts: ["지수 그래프", "직선 그래프", "역산과 대입"],
      gen(rng) { const e = scene(rng); const x0 = e.X + rng.int(1, 3); const Y = e.g(x0); const fv = e.y(x0); if (!isI(fv) || fv > 999) throw new GenFail("v"); return figInst(rng, { stimulus: `${intro(rng)} ${form(rng)}`, question: rng.pick([`If $g(x) = ${Y}$, what is the value of $f(x)$?`, `For the value of $x$ at which $g(x) = ${Y}$, what is $f(x)$?`, `At the input where $g$ equals ${Y}, what is the output of $f$?`]), correct: fv, wrongs: [W(Y, "step_missing", "Y 를 답했다."), W(x0, "step_missing", "x 를 답했다."), W(e.y(x0 - 1), "other", "한 칸 덜 갔다."), W(Math.round(fv * e.b), "other", "한 칸 더 갔다.")].filter((w) => isI(w.v) && w.v !== fv && w.v > 0), verificationJs: figJs({ Y }, e.fig, `${EXP_JS}${G_JS}return f((P.Y - gc) / gd);`), trace: [...rd(e), [`g(x) = ${e.d}x + ${e.c} = ${Y} 에서 x = ${x0} 이다.`, "Solve g(x) = Y."], [`f(${x0}) = ${e.a} · ${fmtNum(e.b)}^${x0} = ${fv} 이다.`, "Evaluate f at that x."]], variant: "f_where_g_equals" }, e.fig); } },
  ],
  em: [
    { lv: "easy", name: "g_at_integer", structure: "그림 안의 정수 x 에서 직선 g 의 값을 읽음", extra: "easy: g 읽기", concepts: ["직선 그래프"],
      gen(rng) { const e = scene(rng); const x = rng.int(1, e.X - 1); const v = e.g(x); return figInst(rng, { stimulus: `${intro(rng)} ${form(rng)}`, question: `What is the value of $g(${x})$?`, correct: v, wrongs: [W(e.y(x), "axis_misread", "f 의 값을 답했다."), W(v + e.d, "other", "한 칸 어긋났다."), W(Math.max(0, v - e.d), "other", "한 칸 어긋났다.")].filter((w) => isI(w.v) && w.v !== v && w.v >= 0), verificationJs: figJs({ x }, e.fig, `${EXP_JS}${G_JS}return g(P.x);`), trace: [[`직선 g 는 (0, ${e.c}) 와 (${e.X}, ${e.g(e.X)}) 를 지난다.`, "Read two lattice points of g."], [`g(${x}) = ${v} 이다.`, "Evaluate g."]], variant: "g_inside" }, e.fig); } },
    { lv: "medium", name: "f_minus_g_next", structure: "표시점 다음 정수 x 에서 f(x) - g(x) 를 구함", extra: "medium: 한 칸 더", concepts: ["지수 그래프", "직선 그래프"],
      gen(rng) { const e = scene(rng); const x = e.xs[2] + 1; if (x > e.X) throw new GenFail("x"); const ans = e.y(x) - e.g(x); if (!isI(ans)) throw new GenFail("v"); return figInst(rng, { stimulus: `${intro(rng)} ${form(rng)}`, question: rng.pick([`What is the value of $f(${x}) - g(${x})$?`, `How much greater is $f(${x})$ than $g(${x})$?`, `Find $f(${x}) - g(${x})$.`]), correct: ans, wrongs: [W(-ans, "sign_error", "순서를 바꿨다."), W(e.y(x), "step_missing", "f 의 값만 답했다."), W(e.g(x), "step_missing", "g 의 값만 답했다.")].filter((w) => isI(w.v) && w.v !== ans), verificationJs: figJs({ x }, e.fig, `${EXP_JS}${G_JS}return f(P.x) - g(P.x);`), trace: [...rd(e), [`f(${x}) - g(${x}) = ${ans} 이다.`, "Subtract."]], variant: "difference_next" }, e.fig); } },
  ],
});
