// percentages.compound_change.FN.P — 순수 지수 곡선 그래프(축 제목 x·y)에서 한 칸당 변화율(%)과 여러 칸에 걸친 누적 변화율을 구한다.
import { GenFail } from "../../../types";
import type { Rng } from "../../../rng";
import { fmtNum } from "../../../text";
import { W } from "../../d-kit";
import { figInst, figJs } from "../../../figure-kit";
import { defineItem } from "../item-kit";
import { pickFn } from "./_t5-kit";
import { EXP_JS, expIntro, expRead, makeExp, type ExpX } from "../pure-fn-kit";

const isI = Number.isInteger;
const RS: [number, number][] = [[3, 2], [2, 1], [1, 2], [3, 4], [3, 1], [5, 4]];
const FORM = (fn: string) => `The function is defined by $${fn}(x) = a \\cdot b^x$, where $a$ and $b$ are positive constants.`;
const grow = (e: ExpX) => e.b > 1;
const pct = (r: number) => Math.round(Math.abs(r - 1) * 100);
const dir = (e: ExpX) => (grow(e) ? "increase" : "decrease");
const mk = (rng: Rng, fn: string, o: Parameters<typeof makeExp>[2] = {}) => { const e = makeExp(rng, fn, { ratios: RS, ...o }); const p = pct(e.b); if (!isI(p) || p === 0) throw new GenFail("pct"); return e; };
const oneStep = (e: ExpX): [string, string] => [`한 칸마다 ${e.ys[1]} ÷ ${e.ys[0]} = ${fmtNum(e.b)} 배이므로 ${grow(e) ? "증가" : "감소"}율은 |${fmtNum(e.b)} - 1| × 100 = ${pct(e.b)}% 이다.`, "A factor b means a (b - 1) × 100 percent change per step."];
const pq = (rng: Rng, e: ExpX, steps: string) => rng.pick([`By what percent does $f(x)$ ${dir(e)} ${steps}?`, `Each time ${steps === "when $x$ increases by 1" ? "$x$ increases by 1" : steps.replace("when ", "")}, $f(x)$ ${dir(e)}s by what percent?`]);
void pq;

export const ITEM = defineItem({
  prefix: "ccfg", itemId: "percentages.compound_change.FN.P",
  hard: [
    { op: "repr_shift", structure: "x = 0 이 표시되지 않은 지수 곡선에서 연속한 표시점의 비로 한 칸당 변화율(%)을 구함", extra: "비 b 에서 |b - 1| × 100 으로 바꿔야 함(b 를 그대로 %로 쓰는 것이 함정) — medium 은 x = 0 이 표시됨", concepts: ["지수 그래프", "연속한 값의 비", "퍼센트 변화"],
      gen(rng) { const fn = pickFn(rng); const e = mk(rng, fn); const p = pct(e.b); return figInst(rng, { stimulus: `${expIntro(rng, fn)} ${FORM(fn)}`, question: `By what percent does $${fn}(x)$ ${dir(e)} each time $x$ increases by 1?`, correct: p, wrongs: [W(Math.round(e.b * 100), "formula_misuse", "b 를 그대로 퍼센트로 썼다."), W(Math.round(e.ys[1] - e.ys[0]), "formula_misuse", "차를 답했다."), W(grow(e) ? pct(1 / e.b) : pct(1 / e.b), "formula_misuse", "비를 거꾸로 계산했다."), W(p + 10, "other", "어긋났다."), W(Math.max(1, p - 10), "other", "어긋났다.")].filter((w) => isI(w.v) && w.v !== p && w.v > 0), verificationJs: figJs({}, e.fig, `${EXP_JS}return Math.round(Math.abs(b - 1) * 100);`), trace: [...expRead(e), [`식은 ${fn}(x) = ${e.a} · ${fmtNum(e.b)}^x 이다.`, "The equation of the curve."], oneStep(e)], variant: "percent_per_step" }, e.fig); } },
    { op: "chain2", structure: "한 칸당 비 b 를 구한 뒤 두 칸에 걸친 누적 변화율(%)을 구함", extra: "b² 를 구해 |b² - 1| × 100 으로 바꿔야 함(한 칸 변화율을 두 배로 하는 것이 함정) — medium 은 한 칸", concepts: ["지수 그래프", "누적 퍼센트 변화"],
      gen(rng) { const fn = pickFn(rng); const e = mk(rng, fn); const p2 = Math.round(Math.abs(e.b * e.b - 1) * 100); if (Math.abs(e.b * e.b * 100 - Math.round(e.b * e.b * 100)) > 1e-9) throw new GenFail("frac"); return figInst(rng, { stimulus: `${expIntro(rng, fn)} ${FORM(fn)}`, question: rng.pick([`By what percent does $${fn}(x)$ ${dir(e)} each time $x$ increases by 2?`, `When $x$ goes up by 2, $${fn}(x)$ ${dir(e)}s by what percent?`, `What is the percent ${dir(e)} in $${fn}(x)$ for every increase of 2 in $x$?`]), correct: p2, wrongs: [W(2 * pct(e.b), "formula_misuse", "한 칸 변화율을 두 배 했다."), W(pct(e.b), "step_missing", "한 칸 변화율만 답했다."), W(Math.round(e.b * e.b * 100), "formula_misuse", "b² 을 그대로 퍼센트로 썼다."), W(p2 + 5, "other", "어긋났다.")].filter((w) => isI(w.v) && w.v !== p2 && w.v > 0), verificationJs: figJs({}, e.fig, `${EXP_JS}return Math.round(Math.abs(b * b - 1) * 100);`), trace: [...expRead(e), oneStep(e), [`두 칸이면 ${fmtNum(e.b)}² = ${fmtNum(e.b * e.b)} 배이므로 변화율은 ${p2}% 이다.`, "Two steps multiply by b squared."]], variant: "percent_two_steps" }, e.fig); } },
    { op: "compose_kind", structure: "표시점 사이가 두 칸 이상 떨어진 두 점의 값으로 전체 변화율(%)을 구함", extra: "처음과 나중 값의 비로 한 번에 변화율을 구해야 함(표시된 점의 y 차를 그대로 %로 쓰는 것이 함정) — medium 은 연속한 점", concepts: ["지수 그래프", "퍼센트 변화"],
      gen(rng) { const fn = pickFn(rng); const e = mk(rng, fn); const r = e.ys[2] / e.ys[0]; const p = Math.round(Math.abs(r - 1) * 100); if (Math.abs(r * 100 - Math.round(r * 100)) > 1e-9) throw new GenFail("frac"); return figInst(rng, { stimulus: `${expIntro(rng, fn)} ${FORM(fn)}`, question: rng.pick([`By what percent ${dir(e)}s the value of $${fn}$ from $x = ${e.xs[0]}$ to $x = ${e.xs[2]}$?`, `What is the percent ${dir(e)} in $${fn}(x)$ as $x$ goes from ${e.xs[0]} to ${e.xs[2]}?`, `From $x = ${e.xs[0]}$ to $x = ${e.xs[2]}$, the value of $${fn}$ ${dir(e)}s by what percent?`]), correct: p, wrongs: [W(Math.round(Math.abs(e.ys[2] - e.ys[0])), "formula_misuse", "값의 차를 퍼센트로 썼다."), W(pct(e.b), "step_missing", "한 칸 변화율을 답했다."), W(Math.round(r * 100), "formula_misuse", "비를 그대로 퍼센트로 썼다."), W(p + 5, "other", "어긋났다.")].filter((w) => isI(w.v) && w.v !== p && w.v > 0), verificationJs: figJs({ x0: e.xs[0], x1: e.xs[2] }, e.fig, `${EXP_JS}return Math.round(Math.abs(f(P.x1) / f(P.x0) - 1) * 100);`), trace: [...expRead(e), [`${e.ys[2]} ÷ ${e.ys[0]} = ${fmtNum(r)} 배이다.`, "Compare the first and last values."], [`변화율 = |${fmtNum(r)} - 1| × 100 = ${p}% 이다.`, "Convert to a percent change."]], variant: "percent_overall" }, e.fig); } },
    { op: "inverse", structure: "같은 변화율이 계속될 때 처음 값의 몇 %가 되는지(x 칸 뒤 값 ÷ x = 0 값 × 100)를 구함", extra: "a 를 거꾸로 구한 뒤 비 b^k × 100 으로 바꿔야 함 — medium 은 한 칸", concepts: ["지수 그래프", "퍼센트", "누적 변화"],
      gen(rng) { const fn = pickFn(rng); const e = mk(rng, fn); const k = rng.int(2, 3); const ans = e.b ** k * 100; if (Math.abs(ans - Math.round(ans)) > 1e-9 || ans > 999) throw new GenFail("frac"); const A = Math.round(ans); return figInst(rng, { stimulus: `${expIntro(rng, fn)} ${FORM(fn)}`, question: `$${fn}(${k})$ is what percent of $${fn}(0)$?`, correct: A, wrongs: [W(pct(e.b) * k, "formula_misuse", "변화율에 칸 수를 곱했다."), W(Math.round(e.b * 100 * k), "formula_misuse", "b 를 퍼센트로 쓰고 칸 수를 곱했다."), W(Math.round(e.b ** (k - 1) * 100), "step_missing", "한 칸 덜 갔다."), W(A + 10, "other", "어긋났다.")].filter((w) => isI(w.v) && w.v !== A && w.v > 0), verificationJs: figJs({ k }, e.fig, `${EXP_JS}return Math.round(f(P.k) / f(0) * 100);`), trace: [...expRead(e), [`${fn}(${k}) ÷ ${fn}(0) = ${fmtNum(e.b)}^${k} = ${fmtNum(e.b ** k)} 이다.`, "The ratio is b^k."], [`퍼센트로 ${A}% 이다.`, "Convert to a percent."]], variant: "percent_of_initial" }, e.fig); } },
  ],
  em: [
    { lv: "easy", name: "origin_percent", structure: "x = 0, 1 이 표시된 곡선에서 한 칸당 변화율(%)을 구함", extra: "easy: 두 점의 비", concepts: ["지수 그래프", "퍼센트 변화"],
      gen(rng) { const fn = pickFn(rng); const e = mk(rng, fn, { startAt: 0, markOrigin: true }); const p = pct(e.b); return figInst(rng, { stimulus: `${rng.pick(["", "", "A class studies repeated percent change. ", "A student reads a growth graph. ", "A teacher compares a curve with a percent rate. "])}${expIntro(rng, fn)} ${FORM(fn)}`, question: rng.pick([`By what percent does $${fn}(x)$ ${dir(e)} each time $x$ increases by 1?`, `Each time $x$ increases by 1, by what percent does $${fn}(x)$ ${dir(e)}?`, `What is the percent by which $${fn}(x)$ ${dir(e)} for each increase of 1 in $x$?`, `For each step of 1 in $x$, $${fn}(x)$ ${dir(e)} by what percent?`, `The graph shows that $${fn}(x)$ ${dir(e)} by what percent per unit increase in $x$?`, `Per increase of 1 in $x$, what percent change does $${fn}$ show?`]), correct: p, wrongs: [W(Math.round(e.b * 100), "formula_misuse", "b 를 퍼센트로 썼다."), W(Math.round(e.ys[1] - e.ys[0]), "formula_misuse", "차를 답했다."), W(p + 10, "other", "어긋났다.")].filter((w) => isI(w.v) && w.v !== p && w.v > 0), verificationJs: figJs({}, e.fig, `${EXP_JS}return Math.round(Math.abs(b - 1) * 100);`), trace: [[`표시점 (0, ${e.ys[0]}), (1, ${e.ys[1]}) 을 읽는다.`, "Read two marked points."], oneStep(e)], variant: "percent_origin" }, e.fig); } },
    { lv: "medium", name: "factor_to_percent", structure: "표시점에서 b 를 구해 한 칸 뒤의 값이 앞의 몇 %인지 구함", extra: "medium: 비 × 100", concepts: ["지수 그래프", "퍼센트"],
      gen(rng) { const fn = pickFn(rng); const e = mk(rng, fn); const A = Math.round(e.b * 100); return figInst(rng, { stimulus: `${expIntro(rng, fn)} ${FORM(fn)}`, question: `$${fn}(x + 1)$ is what percent of $${fn}(x)$?`, correct: A, wrongs: [W(pct(e.b), "formula_misuse", "변화율을 답했다."), W(Math.round(100 / e.b), "formula_misuse", "비를 거꾸로 계산했다."), W(A + 10, "other", "어긋났다.")].filter((w) => isI(w.v) && w.v !== A && w.v > 0), verificationJs: figJs({}, e.fig, `${EXP_JS}return Math.round(b * 100);`), trace: [...expRead(e).slice(0, 2), [`비가 ${fmtNum(e.b)} 이므로 ${A}% 이다.`, "The factor times 100 is the percent."]], variant: "factor_percent" }, e.fig); } },
  ],
});
