// systems_linear.elimination_value.LN.P — 두 직선(연립방정식의 그래프)에서 해 (x, y) 의 일차결합 ax + by 의 값을 구한다(제거법 사고).
import { GenFail } from "../../../types";
import type { Rng } from "../../../rng";
import { fmtNum } from "../../../text";
import { W } from "../../d-kit";
import { figInst, figJs } from "../../../figure-kit";
import { defineItem } from "../item-kit";
import { makePureLines, PL2_JS, pl2Intro, pl2Read, type PureLines } from "../pure-fn-kit";

const isI = Number.isInteger;
const comb = (a: number, b: number) => `${a === 1 ? "" : a === -1 ? "-" : a}x ${b < 0 ? "-" : "+"} ${Math.abs(b) === 1 ? "" : Math.abs(b)}y`;
const SOL = ["The solution to the system is $(x, y)$.", "Let $(x, y)$ be the solution to the system.", "The system has exactly one solution, $(x, y)$.", "The ordered pair $(x, y)$ solves the system."];
const ask = (rng: Rng, e: string) => rng.pick([`What is the value of $${e}$?`, `Find the value of $${e}$.`, `What does $${e}$ equal at the solution?`, `Evaluate $${e}$ for the solution of the system.`]);
const coef = (rng: Rng): [number, number] => { const a = rng.pick([2, 3, 4, -2, -3, -1]); const b = rng.pick([1, 2, 3, -1, -2, 4]); return [a, b]; };
const elim = (s: PureLines, a: number, b: number): [string, string] => [`연립해 해 (${fmtNum(s.xi)}, ${fmtNum(s.yi)}) 를 얻는다(두 식을 빼서 x 를 구함).`, "Eliminate to solve the system."];
const mk = (rng: Rng, inside = false) => makePureLines(rng, { inside });

export const ITEM = defineItem({
  prefix: "sevg", itemId: "systems_linear.elimination_value.LN.P",
  hard: [
    { op: "repr_shift", structure: "그림 밖에서 만나는 두 직선으로 연립해 ax + by 의 값을 구함", extra: "해를 먼저 구한 뒤 계수를 곱해 더해야 함(x, y 를 따로 답하는 것이 함정) — medium 은 그림 안의 교점", concepts: ["연립방정식의 그래프", "제거법", "일차결합의 값"],
      gen(rng) { const s = mk(rng); const [a, b] = coef(rng); const ans = a * s.xi + b * s.yi; if (Math.abs(ans) > 200) throw new GenFail("big");
        return figInst(rng, { stimulus: `${pl2Intro(rng)} ${rng.pick(SOL)}`, question: ask(rng, comb(a, b)), correct: ans, wrongs: [W(a * s.xi, "step_missing", "x 항만 계산했다."), W(b * s.yi, "step_missing", "y 항만 계산했다."), W(a * s.xi - b * s.yi, "sign_error", "y 항의 부호를 반대로 더했다."), W(s.xi + s.yi, "formula_misuse", "계수를 곱하지 않았다."), W(ans + 1, "other", "어긋났다.")].filter((w) => isI(w.v) && w.v !== ans), verificationJs: figJs({ a, b }, s.fig, `${PL2_JS}return P.a * xi + P.b * yi;`), trace: [...pl2Read(s), elim(s, a, b), [`${a}(${fmtNum(s.xi)}) + (${b})(${fmtNum(s.yi)}) = ${ans} 이다.`, "Evaluate the combination."]], variant: "combination_outside" }, s.fig); } },
    { op: "chain2", structure: "해 (x, y) 를 구한 뒤 x - y 와 같은 부호 있는 차를 구함", extra: "순서가 있는 차이므로 부호를 지켜야 함(y - x 로 답하는 것이 함정) — medium 은 읽기", concepts: ["연립방정식의 그래프", "제거법", "해의 차"],
      gen(rng) { const s = mk(rng); const ans = s.xi - s.yi; if (ans === 0 || ans === s.xi) throw new GenFail("tie"); return figInst(rng, { stimulus: `${pl2Intro(rng)} ${rng.pick(SOL)}`, question: rng.pick(["What is the value of $x - y$?", "Find the value of $x - y$.", "What does $x - y$ equal?"]), correct: ans, wrongs: [W(-ans, "sign_error", "순서를 바꿔 y - x 를 답했다."), W(s.xi + s.yi, "sign_error", "합을 답했다."), W(s.xi, "step_missing", "x 만 답했다."), W(ans + 1, "other", "어긋났다.")].filter((w) => isI(w.v) && w.v !== ans), verificationJs: figJs({}, s.fig, `${PL2_JS}return xi - yi;`), trace: [...pl2Read(s), elim(s, 1, -1), [`x - y = ${ans} 이다.`, "Subtract."]], variant: "difference" }, s.fig); } },
    { op: "compose_kind", structure: "해를 구한 뒤 ax + by = c 가 성립하는 c 를 구함", extra: "해를 직선 ax + by = c 에 대입해 c 를 역으로 구함 — medium 은 읽기", concepts: ["연립방정식의 그래프", "제거법", "직선의 식 대입"],
      gen(rng) { const s = mk(rng); const [a, b] = coef(rng); const c = a * s.xi + b * s.yi; if (Math.abs(c) > 200 || c === 0) throw new GenFail("c"); return figInst(rng, { stimulus: `${pl2Intro(rng)} The solution to the system ${rng.pick([`lies on the line $${comb(a, b)} = c$, where $c$ is a constant.`, `satisfies the equation $${comb(a, b)} = c$ for some constant $c$.`, `is a point of the graph of $${comb(a, b)} = c$, where $c$ is a constant.`])}`, question: rng.pick(["What is the value of $c$?", "What is $c$?", "Find the constant $c$.", "What constant $c$ makes this true?", "For what value of $c$ does the solution lie on this line?"]), correct: c, wrongs: [W(a * s.xi, "step_missing", "x 항만 계산했다."), W(b * s.yi, "step_missing", "y 항만 계산했다."), W(-c, "sign_error", "부호를 바꿨다."), W(a * s.xi - b * s.yi, "sign_error", "y 항의 부호를 반대로 더했다."), W(c + 1, "other", "어긋났다.")].filter((w) => isI(w.v) && w.v !== c), verificationJs: figJs({ a, b }, s.fig, `${PL2_JS}return P.a * xi + P.b * yi;`), trace: [...pl2Read(s), elim(s, a, b), [`c = ${a}(${fmtNum(s.xi)}) + (${b})(${fmtNum(s.yi)}) = ${c} 이다.`, "Substitute into the line."]], variant: "constant_through_solution" }, s.fig); } },
    { op: "inverse", structure: "해를 구한 뒤 2x + 3y 처럼 서로 다른 두 계수쌍의 값 차(두 번 계산)를 구함", extra: "두 일차결합을 각각 계산해 빼야 함(하나만 계산하는 것이 함정) — medium 은 한 결합", concepts: ["연립방정식의 그래프", "제거법", "일차결합의 값"],
      gen(rng) { const s = mk(rng); const [a, b] = coef(rng); const [c, d] = coef(rng); if (a === c && b === d) throw new GenFail("same"); const ans = (a * s.xi + b * s.yi) - (c * s.xi + d * s.yi); if (ans === 0 || Math.abs(ans) > 300) throw new GenFail("ans"); return figInst(rng, { stimulus: `${pl2Intro(rng)} ${rng.pick(SOL)}`, question: `What is the value of $(${comb(a, b)}) - (${comb(c, d)})$?`, correct: ans, wrongs: [W(a * s.xi + b * s.yi, "step_missing", "첫 결합만 계산했다."), W(c * s.xi + d * s.yi, "step_missing", "둘째 결합만 계산했다."), W(-ans, "sign_error", "순서를 바꿨다."), W((a * s.xi + b * s.yi) + (c * s.xi + d * s.yi), "sign_error", "뺄셈을 덧셈으로 했다."), W(ans + 1, "other", "어긋났다.")].filter((w) => isI(w.v) && w.v !== ans), verificationJs: figJs({ a, b, c, d }, s.fig, `${PL2_JS}return (P.a*xi+P.b*yi)-(P.c*xi+P.d*yi);`), trace: [...pl2Read(s), elim(s, a, b), [`첫 결합 = ${a * s.xi + b * s.yi}, 둘째 결합 = ${c * s.xi + d * s.yi} 이다.`, "Evaluate both combinations."]], variant: "combination_difference" }, s.fig); } },
  ],
  em: [
    { lv: "easy", name: "read_combination", structure: "그림 안의 교점에서 ax + by 의 값을 읽어 계산", extra: "easy: 교점 읽고 계산", concepts: ["연립방정식의 그래프", "일차결합의 값"],
      gen(rng) { const s = mk(rng, true); const [a, b] = coef(rng); const ans = a * s.xi + b * s.yi; return figInst(rng, { stimulus: `${pl2Intro(rng)} ${rng.pick(SOL)}`, question: ask(rng, comb(a, b)), correct: ans, wrongs: [W(a * s.xi, "step_missing", "x 항만 계산했다."), W(b * s.yi, "step_missing", "y 항만 계산했다."), W(a * s.xi - b * s.yi, "sign_error", "y 항의 부호를 반대로 더했다."), W(ans + 1, "other", "어긋났다.")].filter((w) => w.v !== ans), verificationJs: figJs({ a, b }, s.fig, `${PL2_JS}return P.a * xi + P.b * yi;`), trace: [[`두 직선이 만나는 점 (${s.xi}, ${s.yi}) 을 읽는다.`, "Read the crossing point."], [`${a}(${s.xi}) + (${b})(${s.yi}) = ${ans} 이다.`, "Evaluate."]], variant: "combination_read" }, s.fig); } },
    { lv: "medium", name: "read_difference", structure: "그림 안의 교점에서 x - y 를 읽어 구함", extra: "medium: 부호 있는 차", concepts: ["연립방정식의 그래프", "해의 차"],
      gen(rng) { const s = mk(rng, true); const ans = s.xi - s.yi; if (ans === 0 || ans === s.xi) throw new GenFail("tie"); return figInst(rng, { stimulus: `${pl2Intro(rng)} ${rng.pick(SOL)}`, question: rng.pick(["What is the value of $x - y$?", "What is $x - y$?", "Find the value of $x - y$ for the solution of the system.", "What is the difference of the $x$- and $y$-coordinates of the solution?", "The solution $(x, y)$ of the system satisfies what value of $x - y$?", "If $(x, y)$ is the solution of the system, what is $x - y$?"]), correct: ans, wrongs: [W(-ans, "sign_error", "순서를 바꿨다."), W(s.xi + s.yi, "sign_error", "합을 답했다."), W(s.xi, "step_missing", "x 만 답했다."), W(ans + 1, "other", "어긋났다.")].filter((w) => w.v !== ans), verificationJs: figJs({}, s.fig, `${PL2_JS}return xi - yi;`), trace: [[`두 직선이 만나는 점을 찾는다.`, "Find where the lines cross."], [`교점은 (${s.xi}, ${s.yi}) 이다.`, "Read the point."], [`x - y = ${ans} 이다.`, "Subtract."]], variant: "read_difference" }, s.fig); } },
  ],
});
