// systems_linear.param_no_solution.LN.P — 그래프의 직선과 지문의 직선 kx + dy = c 로 이루어진 연립이 해가 없을(또는 무수히 많을) 때의 매개변수를 구한다.
import { GenFail } from "../../../types";
import type { Rng } from "../../../rng";
import { W } from "../../d-kit";
import { figInst, figJs } from "../../../figure-kit";
import { defineItem } from "../item-kit";
import { GL_JS, makePureLine, pureIntro, purRead } from "../pure-kit";
import { crossSafe, labelClear } from "../pure-fn-kit";

const isI = Number.isInteger;
const LEAD = ["", "", "A student is studying a system of equations in algebra class. ", "A teacher graphs one equation of a system on a grid. ", "A graphing program draws a line. "];
const intro = (rng: Rng) => rng.pick(LEAD) + pureIntro(rng);
const pl = (rng: Rng, o: { ms?: number[] } = {}) => { for (let t = 0; t < 80; t++) { const s = makePureLine(rng, o); if (crossSafe(s.b, s.R) && crossSafe(s.b / s.m, s.R) && labelClear((x) => s.m * x + s.b, s.R)) return s; } throw new GenFail("라벨"); };
const NO = (rng: Rng, eq: string) => rng.pick([`The system consisting of the line shown and the line $${eq}$, where $k$ is a constant, has no solution.`, `The line shown and the line with equation $${eq}$, where $k$ is a constant, form a system with no solution.`, `For a constant $k$, the system made of the line shown and $${eq}$ has no solution.`, `There is no point common to the line shown and the graph of $${eq}$, where $k$ is a constant.`]);
const MANY = (rng: Rng, eq: string) => rng.pick([`The system consisting of the line shown and the line $${eq}$, where $k$ and $c$ are constants, has infinitely many solutions.`, `The line shown and the graph of $${eq}$, where $k$ and $c$ are constants, are the same line.`, `For constants $k$ and $c$, the system made of the line shown and $${eq}$ has infinitely many solutions.`]);
const Kq = (rng: Rng) => rng.pick(["What is the value of $k$?", "What is $k$?", "Find the value of the constant $k$."]);
const D = [2, 3, 4, 5, 6];

export const ITEM = defineItem({
  prefix: "pnsg", itemId: "systems_linear.param_no_solution.LN.P",
  hard: [
    { op: "param_condition", structure: "그래프의 직선과 kx + dy = c 가 해가 없으려면 평행(기울기 같음) 이므로 -k/d = m 으로 k 를 구함", extra: "해가 없다 ⇔ 평행(기울기 같고 절편 다름) 으로 바꿔 표준형의 기울기 -k/d 와 맞춰야 함(부호 함정) — medium 은 기울기", concepts: ["연립방정식의 그래프", "해가 없을 조건", "표준형의 기울기"],
      gen(rng) { const s = pl(rng); const d = rng.pick(D); const k = -s.m * d; const c = rng.int(2, 30); if (c === s.b * d) throw new GenFail("c"); return figInst(rng, { stimulus: `${intro(rng)} ${NO(rng, `kx + ${d}y = ${c}`)}`, question: Kq(rng), correct: k, wrongs: [W(-k, "sign_error", "기울기 -k/d 의 부호를 놓쳤다."), W(s.m * d, "sign_error", "부호를 반대로 했다."), W(d / s.m, "condition_ignored", "수직 조건으로 계산했다."), W(s.m, "step_missing", "d 를 곱하지 않았다."), W(k + 1, "other", "어긋났다.")].filter((w) => isI(w.v) && w.v !== k), verificationJs: figJs({ d }, s.fig, `${GL_JS}return -m * P.d;`), trace: [...purRead(s), [`해가 없으려면 두 직선이 평행이어야 하므로 기울기가 같다.`, "No solution means the lines are parallel."], [`kx + ${d}y = ${c} 의 기울기는 -k/${d} 이므로 -k/${d} = ${s.m} 이다.`, "Match the slopes."], [`k = ${k} 이다.`, "Solve for k."]], variant: "k_no_solution" }, s.fig); } },
    { op: "chain2", structure: "무수히 많은 해(같은 직선)가 되도록 kx + dy = c 의 c 를 구함", extra: "기울기가 같을 뿐 아니라 절편도 같아야 하므로 k 를 먼저, 이어서 c = b d 를 구해야 함(k 만 구하는 것이 함정) — medium 은 k", concepts: ["연립방정식의 그래프", "해가 무수히 많을 조건", "표준형"],
      gen(rng) { const s = pl(rng); const d = rng.pick(D); const c = s.b * d; if (c === 0) throw new GenFail("c0"); return figInst(rng, { stimulus: `${intro(rng)} ${MANY(rng, `kx + ${d}y = c`)}`, question: rng.pick(["What is the value of $c$?", "What is $c$?", "Find the value of the constant $c$."]), correct: c, wrongs: [W(-c, "sign_error", "부호를 바꿨다."), W(s.b, "step_missing", "d 를 곱하지 않았다."), W(-s.m * d, "step_missing", "k 를 답했다."), W(c + d, "other", "어긋났다."), W(s.b / d, "formula_misuse", "d 로 나눴다.")].filter((w) => isI(w.v) && w.v !== c), verificationJs: figJs({ d }, s.fig, `${GL_JS}const b0=ys[0]-m*xs[0]; return b0 * P.d;`), trace: [...purRead(s), [`같은 직선이면 기울기와 y 절편이 모두 같다: y = ${s.m}x + (${s.b}).`, "The lines must be identical."], [`kx + ${d}y = c 를 y 로 풀면 y = (-k/${d})x + c/${d} 이다.`, "Solve the standard form for y."], [`c ÷ ${d} = ${s.b} 이므로 c = ${c} 이다.`, "Match the intercepts."]], variant: "c_infinitely_many" }, s.fig); } },
    { op: "compose_kind", structure: "y = kx + 5 꼴 직선과 그래프의 직선이 해가 없을 때의 k(= 그래프의 기울기)를 구함", extra: "해가 없다 ⇔ 기울기 같고 절편 다름 이므로 k 가 그래프의 기울기임을 알아야 함 — medium 은 기울기", concepts: ["연립방정식의 그래프", "해가 없을 조건", "기울기"],
      gen(rng) { const s = pl(rng); const t = rng.int(2, 30); if (t === s.b) throw new GenFail("t"); return figInst(rng, { stimulus: `${intro(rng)} ${NO(rng, `y = kx + ${t}`)}`, question: Kq(rng), correct: s.m, wrongs: [W(-s.m, "sign_error", "부호를 바꿨다."), W(-1 / s.m, "condition_ignored", "수직 조건으로 계산했다."), W(s.b, "formula_misuse", "절편을 답했다."), W(s.m + 1, "other", "어긋났다.")].filter((w) => isI(w.v) && w.v !== s.m), verificationJs: figJs({}, s.fig, `${GL_JS}return m;`), trace: [...purRead(s), [`해가 없으려면 평행이므로 기울기가 같다.`, "No solution means parallel lines."], [`y = kx + ${t} 의 기울기 k 가 ${s.m} 이다.`, "k is the slope."], [`k = ${s.m} 이다.`, "State k."]], variant: "k_slope_form" }, s.fig); } },
    { op: "inverse", structure: "kx + dy = c 가 그래프의 직선과 평행일 때 k 와 d 를 한꺼번에 묶은 k + d 를 구함", extra: "k 를 구한 뒤 d 를 더하는 2단 연쇄(k 만 답하는 것이 함정) — medium 은 k", concepts: ["연립방정식의 그래프", "해가 없을 조건", "표준형의 기울기"],
      gen(rng) { const s = pl(rng); const d = rng.pick(D); const k = -s.m * d; const c = rng.int(2, 30); if (c === s.b * d || k + d === k) throw new GenFail("c"); return figInst(rng, { stimulus: `${intro(rng)} ${NO(rng, `kx + ${d}y = ${c}`)}`, question: rng.pick(["What is the value of $k + " + d + "$?", "Find $k + " + d + "$."]), correct: k + d, wrongs: [W(k, "step_missing", "k 만 답했다."), W(-k + d, "sign_error", "k 의 부호를 놓쳤다."), W(-k - d, "sign_error", "부호를 바꿨다."), W(k + d + 1, "other", "어긋났다.")].filter((w) => isI(w.v) && w.v !== k + d), verificationJs: figJs({ d }, s.fig, `${GL_JS}return -m * P.d + P.d;`), trace: [...purRead(s), [`해가 없으려면 평행이다.`, "Parallel lines."], [`-k/${d} = ${s.m} 에서 k = ${k} 이다.`, "Solve for k."], [`k + ${d} = ${k + d} 이다.`, "Add d."]], variant: "k_plus_d" }, s.fig); } },
  ],
  em: [
    { lv: "easy", name: "slope_form", structure: "그래프의 기울기와 y = kx + c 가 평행이도록 k 를 읽음", extra: "easy: 기울기 읽기", concepts: ["연립방정식의 그래프", "평행"],
      gen(rng) { const s = pl(rng); const t = rng.int(2, 30); if (t === s.b) throw new GenFail("t"); return figInst(rng, { stimulus: `${intro(rng)} ${NO(rng, `y = kx + ${t}`)}`, question: Kq(rng), correct: s.m, wrongs: [W(-s.m, "sign_error", "부호를 바꿨다."), W(s.b, "formula_misuse", "절편을 답했다."), W(s.m + 1, "other", "어긋났다."), W(s.m - 1, "other", "어긋났다.")].filter((w) => w.v !== s.m), verificationJs: figJs({}, s.fig, `${GL_JS}return m;`), trace: [...purRead(s), [`평행이므로 k = ${s.m} 이다.`, "Parallel lines share the slope."]], variant: "k_easy" }, s.fig); } },
    { lv: "medium", name: "standard_form", structure: "kx + dy = c 가 평행이도록 k 를 구함(d = 2)", extra: "medium: 표준형 기울기 -k/2", concepts: ["연립방정식의 그래프", "표준형"],
      gen(rng) { const s = pl(rng, { ms: [-4, -3, -2, -1, 1, 2, 3, 4] }); const c = rng.int(2, 30); if (c === s.b * 2) throw new GenFail("c"); const k = -s.m * 2; return figInst(rng, { stimulus: `${intro(rng)} ${NO(rng, `kx + 2y = ${c}`)}`, question: Kq(rng), correct: k, wrongs: [W(-k, "sign_error", "기울기의 부호를 놓쳤다."), W(s.m, "step_missing", "2 를 곱하지 않았다."), W(k + 1, "other", "어긋났다."), W(k - 1, "other", "어긋났다.")].filter((w) => w.v !== k), verificationJs: figJs({}, s.fig, `${GL_JS}return -m * 2;`), trace: [...purRead(s), [`kx + 2y = ${c} 의 기울기는 -k/2 이다.`, "Slope of the standard form."], [`-k/2 = ${s.m} 에서 k = ${k} 이다.`, "Solve for k."]], variant: "k_standard_d2" }, s.fig); } },
  ],
});
